### ISSUE TITLE
Quarantine period is different in another document

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#100]
This document https://docs.microsoft.com/en-us/office365/securitycompliance/manage-quarantined-messages-and-files states that for spam limit is 30 days max, for malware it's 15 days (default, but no mention of max) and 7 for transport rules (also no mention of max period). The article does not mention that you can change malware and transport rule limits, so should we assume that 15 these limits are not changable?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5013ccda-a0c6-ce6c-73e7-c78187008f55
* Version Independent ID: a2233d27-d1b1-23af-776b-b860eb1f79b6
* Content: [Exchange Online Protection Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-protection-service-description/exchange-online-protection-limits#feedback)
* Content Source: [Office365-ServiceDescriptions/exchange-online-protection-service-description/exchange-online-protection-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-protection-service-description/exchange-online-protection-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@Larryngolog Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response

**Comment by SharS** [comment]
@Larryngolog Thanks for your feedback. [Manage quarantined messages and files as an administrator in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/manage-quarantined-messages-and-files) contains correct information and also contains instructions for modifying the default quarantine retention limit. Exchange Online Protection Limits will be updated to contain matching limits.
