### ISSUE TITLE
 Kiosk workers in notes section

### ISSUE THREAD

**Issue by KoenZomers** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#101]
The notes section still mentions Kiosk workers while this has been renamed to Firstline workers a while ago already

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits#feedback)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@KoenZomers Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response

**Comment by KoenZomers** [comment]
@prabita ping :) It is shown everywhere in our documentation that we call it Frontline workers these days and not kiosk workers.

**Comment by kaarins** [comment]
Thanks for reporting this. It has been fixed.
