### ISSUE TITLE
Link to Trust Center is not working

### ISSUE THREAD

**Issue by jrpool88** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#102]
on the "For more information, see the Office 365 Trust Center", the link to the Trust Center does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 650a0871-6264-958b-9010-c2798a74752f
* Version Independent ID: be651f88-49f4-b70c-0b12-11a94e77eb93
* Content: [Networking](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/networking#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/networking.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/networking.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@jrpool88 Thanks for your feedback, we are working on fixing the link.

**Comment by prabita** [comment]
Links updated, will be live in 24 hrs.
