### ISSUE TITLE
"Custom Managed Paths"

### ISSUE THREAD

**Issue by vaderj** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#103]
The link provided SPECIFICALLY says that custom managed paths do not apply to SharePoint online, so which is it?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 317e4152-691a-7ac9-8fef-2225b00b4c02
* Version Independent ID: 7178b047-40c0-f7c7-e547-954cdc920b3a
* Content: [Sites](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sites-servicedesc#feedback)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sites-servicedesc.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sites-servicedesc.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@vaderj - Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response.

**Comment by SKjerland** [comment]
@vaderj - Our SharePoint writer updated the article. Thanks!
