### ISSUE TITLE
Exchange ActiveSync file attachment limit 

### ISSUE THREAD

**Issue by CarolWangMS** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#104]
In the Message limits section, it says:
Exchange ActiveSync does not implement attachment size limits on an individual attachment basis. The total size of all attachments to an Exchange ActiveSync message must be less than the message size limit.
But in the Exchange ActiveSync limits section, it says:
Exchange ActiveSync file attachment limit The maximum size of a message file attachment that can be sent or received by an Exchange ActiveSync device.

Do we have file attachment limit applying to a single file attachment when we use Exchange ActiveSync?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#message-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@CarolWangMS Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response

**Comment by SharS** [comment]
@CarolWangMS Thanks for your feedback. I removed the contradictory limit information.
