### ISSUE TITLE
Multiple "Acess services" items with varying values

### ISSUE THREAD

**Issue by DragOncave** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#105]
https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-education#sharepoint-online-features

First three rows of the table present "Acess servicess" with the same hyperlink, while the values are different and no explanation whatsoever.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 482f1200-178f-088c-f189-ac129614cdb0
* Version Independent ID: 94ff27f4-966c-f271-1822-515c4e56a1bb
* Content: [Office 365 Education](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-education#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-education.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-education.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@DragOncave - article is updated.
