### ISSUE TITLE
Availability of sync client across licensing plans?

### ISSUE THREAD

**Issue by jformacek** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#106]
General description of O365 F1 plan says that "Desktop sync is not available", and points here for details. However, content here does not explain sync client availability.
Can you please cover eligibility of offline sync of OneDrive for Business for various license plans? (both desktop and mobile device)

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99ce1810-18cd-687b-0c8b-bfceb919225a
* Version Independent ID: 705cde78-7e58-c260-bde3-0b393747cdea
* Content: [OneDrive for Business Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/onedrive-for-business-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/onedrive-for-business-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/onedrive-for-business-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@jformacek - Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response.

**Comment by SharS** [comment]
@jformacek Anyone with OneDrive as a part of their plan can leverage the OneDrive sync client unless their IT department explicitly disables their use of it. I've updated the service description with this information.

**Comment by martinaffectoericsson** [comment]
@SharS 
Does this apply to the M365 F3 users as well? Earlier it stated: "F3 plans include 2GB OneDrive storage per user and do not include desktop sync functionality". But now that text is removed.
Thanks
