### ISSUE TITLE
EOP standalone link not working

### ISSUE THREAD

**Issue by whiggy** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#107]
"EOP standalone" link in the "Exchange Online Protection (EOP) plans" section goes to a blank page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05026887-52d6-a60f-9381-03ae5ab99779
* Version Independent ID: 4dc07d5d-ef83-0ba2-bb68-42a2ffae44b2
* Content: [Exchange Online Protection Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-protection-service-description/exchange-online-protection-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/exchange-online-protection-service-description/exchange-online-protection-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-protection-service-description/exchange-online-protection-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@whiggy Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response

**Comment by prabita** [comment]
@whiggy EOP standalon link is updated, the updated page will be live in 24 hrs.

**Comment by whiggy** [comment]
Thank you, Prabita!
