### ISSUE TITLE
Is 100,00 a typo?

### ISSUE THREAD

**Issue by bernardlam** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#108]
Looks like there may be a typo in the following sentence: "After 100,00 items are added to a list, library, or folder, permission inheritance for the list, library, or folder can't be changed."

Should it be 10,000 or 100,000 items?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@bernardlam Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response

**Comment by tomresing** [comment]
100,000. It's not a typo.

**Comment by tomresing** [comment]
Ah, the missing trailing zero. Sorry about that. Corrected!
