### ISSUE TITLE
Office Mobile for O365 BE, E1 and F1

### ISSUE THREAD

**Issue by MarkBratton** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#109]
All 3 "Office Mobile for..." rows should say 'Yes' for O365 Business Essentials, E1 and F1 and be footnoted with "Limited to devices with integrated screens 10.1” diagonally or less." per the Online Service Terms. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61b8fbc9-7314-1e82-7c85-f0f9d3c3c1fd
* Version Independent ID: 7a5944ad-e785-5711-0954-f2be068e79d1
* Content: [Office Applications Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-applications-service-description/office-applications-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/office-applications-service-description/office-applications-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-applications-service-description/office-applications-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by MarkBratton** [comment]
Status please? This is causing customer escalations.

**Comment by SKjerland** [comment]
@MarkBratton - I updated the service description. Thanks!
