### ISSUE TITLE
Broken URL

### ISSUE THREAD

**Issue by dieselVtwin** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#11]
Hi,

The "Office 365 for business roadmap" link pointing to "roadmap.office.com" returns a page that says, "We are sorry, the page you requested cannot be found.  The URL may be misspelled or the page you're looking for is no longer available."  ( https://www.microsoft.com/library/errorpages/smarterror.aspx?correlationId=iYVjFGbx80KECjc7.0.0.0 )

Regards,
Alan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc118339-bbeb-e510-7793-78054d3fc174
* Version Independent ID: e69606e1-52d7-592f-2e1a-317b4f39598b
* Content: [Service Updates](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/service-updates)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/service-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/service-updates.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by prabita** [comment]
@dieselVtwin - Thank you for your feedback; issue is fixed now.
