### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by goverlieTAFENSW** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#110]
Link in section Licencing considerations, Project Online Plans is broken. 

Link Title:  Getting Started with Project Online.
Link URL (broken): https://blogs.office.com/2014/04/18/join-the-office-365-support-webcast-april-22-getting-started-with-project-online/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69451b60-fdc1-4b81-d154-cdd38931a902
* Version Independent ID: f90ef8b6-b8ed-37d8-d5c6-da25f96a0a1d
* Content: [Project Online Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/project-online-service-description/project-online-service-description#licensing-considerations)
* Content Source: [Office365-ServiceDescriptions/project-online-service-description/project-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/project-online-service-description/project-online-service-description.md)
* Product: **office-online-server**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SKjerland** [comment]
@goverlieTAFENSW - Thanks for bringing this to our attention! I fixed the link and tested it on my end, and it works.
