### ISSUE TITLE
Modiication request for the mailbox size limit for EXO Plan1 +EOA

### ISSUE THREAD

**Issue by AkikoTsukahara** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#111]
We just got feedback from one of our customers that it looks like the following description should be updated to the correct information.
Mailbox size limit for Exchange Online Plan 1 with Exchange Online Archiving add-on license is 50GB, not 100GB.
Exchange Online Plan 1 with Exchange Online Archiving add-on license allows us to enable auto-expanding archiving for an unlimited amount of archive storage capacity, but mailbox size limit is 50GB(with unlimited amount of archive storage capacity)
So to increase the size limit to 100GB, the shared mailbox must be assigned EXO Plan 2 or E3 or E5. 

https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#feedback

2 To access a shared mailbox, a user must have an Exchange Online license, but the shared mailbox doesn’t require a separate license. Without a license, shared mailboxes are limited to 50 GB. **To increase the size limit to 100 GB, the shared mailbox must be assigned an Exchange Online Plan 2 license or an Exchange Online Plan 1 license with an Exchange Online Archiving add-on license.** This will also allow you to enable auto-expanding archiving for an unlimited amount of archive storage capacity. Similarly, if you want to place a shared mailbox on litigation hold or assign a retention policy to it, the shared mailbox must have an Exchange Online Plan 2 license or an Exchange Online Plan 1 license with an Exchange Online Archiving add-on license.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#feedback)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@AkikoTsukahara Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response

**Comment by SharS** [comment]
This service description has been updated.
