### ISSUE TITLE
Explanation of sending limits is unclear

### ISSUE THREAD

**Issue by martin-heeck** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#112]
The Explanation of sending Limits is not completely clear and leaves open questions / room for Interpretation.

Here is my understanding: 
10,000 recipients per day means the aggregrated number of different recipients contained in the To, Cc and Bcc fields for all mails sent from the corresponding account.

500 recipients means 500 different recipients contained in the To, Cc and Bcc fields of a single mail.

"Recipient Proxy address Limit"  is not defined and therefore unclear.

The "Message rate Limit" of 30 mails per Minute is clearly defined. But it is not stated what happens if the Limit is exceeded. Would sending of mails be blocked for a Minute in such a case?

Can you please clarify and update the document accordingly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#feedback)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@martin-heeck Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response

**Comment by SharS** [comment]
@martin-heeck - Thanks. I've added the requested information to the article.
