### ISSUE TITLE
GCC High AIP functionality 

### ISSUE THREAD

**Issue by cfoulon** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#113]
Any additional details on the level of integration of AIP in GCC and GCC High

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c907526-4061-94b4-f2fd-d6fca90344bb
* Version Independent ID: 82e89c18-8d6e-bbb1-f6d0-6ec091d1556e
* Content: [Office 365 GCC High and DoD](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod.md)
* Service: **o365-administration**
* GitHub Login: @danarl
* Microsoft Alias: **danarl**

**Comment by prabita** [comment]
@cfoulon Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response

**Comment by dmcwee** [comment]
For AIP details associated with GCC & GCCH refer to this link:
https://docs.microsoft.com/en-us/enterprise-mobility-security/solutions/ems-aip-premium-govt-service-description

**Comment by cfoulon** [comment]
Is this document up to date? See reference to date passed

*Note: Target date for FedRAMP Moderate compliance is H2 of calendar year
2018.

**Comment by dmcwee** [comment]
Yes the reference is up to date. That note is incorrect, AIP has received FedRAMP Moderate certification (per the link below), and has been reported to the documentation owners.
https://marketplace.fedramp.gov/#/product/azure-commercial-cloud?sort=productName&productNameSearch=microsoft

**Comment by SharS** [comment]
https://docs.microsoft.com/en-us/enterprise-mobility-security/solutions/ems-aip-premium-govt-service-description contains updated information. Closing this.

**Comment by cfoulon** [comment]
Any timelines on MCAS being available in GCC High/DoD to help ensure that
documents containing sensitive information types can be scanned and have
label being applied to the in SharePoint Online for that environment?

**Comment by dmcwee** [comment]
Nothing available on the public roadmap.
https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=Microsoft%20Cloud%20App%20Security%2CGCC%20High
