### ISSUE TITLE
Managed metadata clarification

### ISSUE THREAD

**Issue by beckettkev** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#114]
In the following statement, underneath the service limits for all plans:

Managed metadata - 200,000 terms in Term Store, 1,000 global term sets, 1,000 groups.

Does the termset and term limit include those added at the site collection level? The wording is ambiguous. If there is a different limit at the site collection level can this be detailed please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits#service-limits-for-all-plans)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@beckettkev Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response

**Comment by Vridhi-Chowdhry** [comment]
"Managed metadata - 200,000 terms in Term Store, 1,000 global term sets, 1,000 groups." - These limits do not include the site collection level term sets.
