### ISSUE TITLE
Edge is not listed in section "Secure/Multipurpose Internet Mail Extensions (S/MIME)"

### ISSUE THREAD

**Issue by GuyGroeneveld** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#117]
It is said "S/MIME is supported on Internet Explorer 9 or later. Currently, S/MIME is unsupported on Firefox, Opera, and Chrome."
Edge should be added.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57d6266c-10f7-4a96-610d-78d04311b63f
* Version Independent ID: 5445d1d2-da07-9223-b56e-225531922051
* Content: [Message Policy and Compliance](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/message-policy-and-compliance#feedback)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/message-policy-and-compliance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/message-policy-and-compliance.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@GuyGroeneveld - Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response.

**Comment by SharS** [comment]
@GuyGroeneveld Thanks for your feedback. We've added Microsoft Edge to the list of browsers.

**Comment by SharS** [comment]
@GuyGroeneveld - I've added Edge to the list of supported browsers. You should see the change online soon.
