### ISSUE TITLE
Please add a description for tenant to tenant flow

### ISSUE THREAD

**Issue by masa-narita** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#118]
Please add a description regarding mail flow between EXO tenant to another EXO tenant, something like:

> In case your recipient domain is hosted in Exchange Online with DNS MX records pointing to Exchange Online Protection, mail flow from your tenant to the recipient will not travel over the Internet. 

thank you,
Masa

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b75e1ce6-2a95-6cd3-0235-ac359b42be6b
* Version Independent ID: 028c77aa-4579-a26e-6de8-b82e99a37803
* Content: [Mail Flow](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/mail-flow#feedback)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/mail-flow.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/mail-flow.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@masa-narita - Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response.

**Comment by SharS** [comment]
@masa-narita - I've updated the article. You should see the changes online soon.
