### ISSUE TITLE
Number of simultaneous connections to SharePoint Online sites/pages?  

### ISSUE THREAD

**Issue by KoliopoulosProdromos** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#119]
Can you please confirm how many users (internal or external or both) can be connected to a single SharePoint Online/OneDrive for Business site/page at the same time?

**Comment by SharS** [comment]
@KoliopoulosProdromos Thank you for your feedback. I've contacted the product group and will update the SharePoint Online Limits page if needed.
