### ISSUE TITLE
Wrong information related to Skype for Business Server 2015 (OnPrem)

### ISSUE THREAD

**Issue by joaolloureiro** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#12]
Documentation refers to Skype for Business Online however Skype for Business Server 2015 (onPrem) is being referenced in Online documentation? Is this expected? If so info is incorrect as for Skype for Business Server scheduled meetings expire time is typically 14 days.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adfbc495-10f9-ae85-6486-6731d5942688
* Version Independent ID: d8d1bcec-612f-633c-e03d-e027972ed337
* Content: [Skype for Business Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/skype-for-business-online-service-description/skype-for-business-online-limits#bkmk_MeetingRetention_LyncOnlineLimits)
* Content Source: [Office365-ServiceDescriptions/skype-for-business-online-service-description/skype-for-business-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/skype-for-business-online-service-description/skype-for-business-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by NicholasBurkhammer** [comment]
+1 updating this documentation

**Comment by prabita** [comment]
@joaolloureiro Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response

**Comment by SharS** [comment]
@joaolloureiro Thanks for your feedback. The service description appears to contain correct information. Skype for Business Server 2015 limits are provided for comparison purposes.
