### ISSUE TITLE
Search Limitations and possibilities. 

### ISSUE THREAD

**Issue by HeineMP** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#120]
Would it be possible to get some information on the limitation and possibilities of Search in Skype for Business online and Server 2015 (OnPrem)?
As i understand it, in Skype4B Online it is only possible to search: Name (full or partial), Skype Name, Location, email address, Microsoft account.
Whereas Skype4B Server 2015 (OnPrem) opens up for more search options.
Is it possible to setup Skype4B til search for: Title, Department and so on?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adfbc495-10f9-ae85-6486-6731d5942688
* Version Independent ID: d8d1bcec-612f-633c-e03d-e027972ed337
* Content: [Skype for Business Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/skype-for-business-online-service-description/skype-for-business-online-limits#feedback)
* Content Source: [Office365-ServiceDescriptions/skype-for-business-online-service-description/skype-for-business-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/skype-for-business-online-service-description/skype-for-business-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by HeineMP** [comment]
Edit: Is it possible to setup Skype4B online to search for: Title, Department and so on?

**Comment by SharS** [comment]
@HeineMP Thanks for your feedback! I'm forwarding this to the product group, and I will update the article as necessary.
