### ISSUE TITLE
Out of date links in Training section

### ISSUE THREAD

**Issue by langjtl** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#121]
The training resources links under the Training section point to mva.microsoft.com.  There is very little content on MVA .  These links should be updated to more content rich sites.
Office 365 self-paced training courses for IT Pros
Office 365 self-paced training courses for end users
Office 365 Administrator support skills: Core Concepts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49d607e9-5a68-4c33-52a6-6ae7acd54218
* Version Independent ID: 097c9aaa-2b38-9c6f-45ab-fe837d6b04d6
* Content: [Help and Training](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/help-and-training#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/help-and-training.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/help-and-training.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@langjtl  Thanks for your feedback! I’ve reached out to the team and will update this article as needed, pending their response.

**Comment by prabita** [comment]
The page is updated with more links.
