### ISSUE TITLE
OneNote is misspelled

### ISSUE THREAD

**Issue by hkim83** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#122]
OneNote is misspelled in the hyperlink text/title in the note section. It shows as “Frequently asked Questions about OeNOte in Office 2019”. The “n” is missing in it and “o” is in caps. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61b8fbc9-7314-1e82-7c85-f0f9d3c3c1fd
* Version Independent ID: 7a5944ad-e785-5711-0954-f2be068e79d1
* Content: [Office Applications Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-applications-service-description/office-applications-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/office-applications-service-description/office-applications-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-applications-service-description/office-applications-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@hkim83 -  Thanks for your feedback! The misspelled word is fixed and the updated page will be live in 24 hrs.
