### ISSUE TITLE
ATP Licensing

### ISSUE THREAD

**Issue by CarolynBillups** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#124]
Could you include on this page the requirement for ATP licensing? Most licenses are user based, however, my understanding is that ATP licensing is based on the amount of mailboxes. To protect all of your mailboxes you need to have licensing equal to mailboxes. 50 user mailboxes + 10 shared mailboxes = 60 ATP licenses. Please clarify. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 502796e9-ca73-7123-7719-c7b5b1042b7b
* Version Independent ID: 2929af88-6d56-4de3-2b4e-4e1d0e4d97ef
* Content: [Office 365 Advanced Threat Protection Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description)
* Content Source: [Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@CarolynBillups - 
I'm sorry that you're having this issue. For Support options, see https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/support).
Also, you can review questions and answers in the Microsoft Community:
https://answers.microsoft.com/en-us/msoffice/forum/msoffice_install-mso_other/office-365-atp-licensing-for-shared-mailboxes/6a58f631-8b84-4c26-9f60-e602cff88e59
