### ISSUE TITLE
Confused due to "Distribution group limits" Description

### ISSUE THREAD

**Issue by teraco** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#125]
First section "Maximum number of distribution group members" states "The total recipient count is determined after distribution group expansion."
And third section "Maximum message size for large distribution groups." described that "the total recipient count is determined after distribution group expansion."
But second section "Limit sending messages to large distribution groups" is not described it.

As a result, "Limit sending messages to large distribution groups" is mistaken as "The total recipient count is determined after distribution group expansion." (I confirmed with Microsoft, it was not actually).

Please delete At the end of  third section description of "The total recipient count is determined after distribution group expansion."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#distribution-group-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@teraco Thank you for your feedback. I've forwarded your comments to the product group and will update the page as necessary.

**Comment by SharS** [comment]
@teraco We've made the change you requested. You should see the updated article soon.
