### ISSUE TITLE
Need to update feature table for MyAnalytics

### ISSUE THREAD

**Issue by JamesTStanley** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#126]
This should indicate partial MyAnalytics capabilities in E1 and E3 plans per https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/overview/plans-environments 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8f41cb0-4ad7-f25c-6586-fe89e8fca92d
* Version Independent ID: 9354cc15-1341-a4e1-4844-83a1f26ee149
* Content: [Office 365 Platform Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-platform-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
Thank you for your feedback. The table has been updated based on the linked article.
