### ISSUE TITLE
Threat Explorer differences between ATP P1 and ATP P2

### ISSUE THREAD

**Issue by pawp81** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#127]
IT would be great to add information to the "Feature availability across Advanced Threat Protection (ATP) plans" table about what the differences between ATP P1 and ATP P2 are in Threat Explorer. Similar to recently update article: https://docs.microsoft.com/en-us/office365/securitycompliance/threat-explorer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 502796e9-ca73-7123-7719-c7b5b1042b7b
* Version Independent ID: 2929af88-6d56-4de3-2b4e-4e1d0e4d97ef
* Content: [Office 365 Advanced Threat Protection Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description#feature-availability-across-advanced-threat-protection-atp-plans)
* Content Source: [Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
Thanks for your feedback! I've forwarded your request to the product team and will update the article if needed.

**Comment by SharS** [comment]
Added a link to [Threat Explorer (and real-time detections)](https://docs.microsoft.com/office365/securitycompliance/threat-explorer) which describes the Threat Explorer feature in Plans 1 and 2.

**Comment by pawp81** [comment]
I am sorry but this article: "[Threat Explorer (and real-time detections)](https://docs.microsoft.com/en-us/office365/securitycompliance/threat-explorer)" doesn't explain what the differences between Real-time detections (ATP P1) and Threat Explorer (ATP P2) are. This is what I have requested.

**Comment by SharS** [comment]
@pawp81 I'm following up with the product team to see if I can get additional information.

**Comment by SharS** [comment]
The linked article has been updated and will be published and available today.

**Comment by pawp81** [comment]
Can we a little bit more specific? This sentence doesn't explain what the differences are: "The real-time detections report allows you to view detections in real-time. Threat Explorer does this as well, but also allows you to view additional details for a given attack but also allows you to view additional details for a given attack"
We could mention that Threat Explorer gives additional capabilities such as:
1. All mail view
2. Search using URLs
3. Integration with MDATP and Machine tab in the message fly out
