### ISSUE TITLE
In-Cloud Archive for on-prem 2010 mailbox using 2016 Hybrid.

### ISSUE THREAD

**Issue by TymWongPSNinja** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#128]
Is it supported to configure an online archive for an on-prem 2010 mailbox when using 2016 Hybrid servers? I've been told that Hybrid Modern Auth is required to support Online Archives and 2010 doesn't support HMA so won't work, is this true?

**Comment by prabita** [comment]
@TymWongPSNinja - 
For Support options, see [Support](https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/support).

**Comment by TymWongPSNinja** [comment]
> Is it supported to configure an online archive for an on-prem 2010 mailbox when using 2016 Hybrid servers? I've been told that Hybrid Modern Auth is required to support Online Archives and 2010 doesn't support HMA so won't work, is this true?

We got this working in the end. HMA is not required for this to work. Our issue was caused by creating the retention policies via 2016 EAC whilst the mailboxes are still on 2010. Can't find this documented anywhere but if you can't get the MRM to process a 2010 mailbox try it with a retention tag and policy created via the 2010 EMC.
