### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by JasonDMorgan** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#129]
The link in the Office 365 Service Communications API section is broken and needs correcting - I'd suggest link to:  https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-service-communications-api-reference

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76358610-0b3b-49d9-6e6a-0b334b19d795
* Version Independent ID: 66466964-caa5-cded-20a6-627495521904
* Content: [Service Health and Continuity](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/service-health-and-continuity#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/service-health-and-continuity.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/service-health-and-continuity.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@JasonDMorgan - Thank you for yopur feedback. Link is working now.
