### ISSUE TITLE
MS Gov High - Account Rep

### ISSUE THREAD

**Issue by eschrader** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#13]
Hi, can you provide steps to contacting someone on GCC High Defense? There is only notes above to "Please engage your account team or preferred partner to learn more or initiate the validation process." but no one anywhere says how to get an account rep. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c907526-4061-94b4-f2fd-d6fca90344bb
* Version Independent ID: 82e89c18-8d6e-bbb1-f6d0-6ec091d1556e
* Content: [GCC High and DoD](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by AndrewLally-KTL** [comment]
If your less than 500 seats there are only 5 partners to contact. I'm not in the sales department so I've never worried about if there was a Microsoft page that listed each partner. We are an approved partner if you want to send an email with questions, alally@ktlsolutions.com

**Comment by JuanGCCHigh** [comment]
> Hi, can you provide steps to contacting someone on GCC High Defense? There is only notes above to "Please engage your account team or preferred partner to learn more or initiate the validation process." but no one anywhere says how to get an account rep.
> 
> Document Details
> ⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.
> 
> ID: 4c907526-4061-94b4-f2fd-d6fca90344bb
> Version Independent ID: 82e89c18-8d6e-bbb1-f6d0-6ec091d1556e
> Content: GCC High and DoD
> Content Source: Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod.md
> Service: o365-administration
> GitHub Login: @pebaum
> Microsoft Alias: pebaum
Hello I am a GCC High Authorized Partner. I work with many Federal Contractors today small and large under 500 users. Feel free to email me at jgarza@go-planet.com and we can set up a call to discuss the GCC High environment and sets to get into the MSFT GCC High Cloud. 

Juan Garza
Planet Technologies

**Comment by prabita** [comment]
@eschrader Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response

**Comment by prabita** [comment]
please see the following page that contains a list of what channels are available to purchase and lists specific partners they can contact.
https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/microsoft-365-government-how-to-buy
