### ISSUE TITLE
Clarify Conditional Access further 

### ISSUE THREAD

**Issue by adrianwells** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#131]
There are two rows in the main table that can benefit from more details:

* "Conditional access (based on group, location, device state, sign-in, or user risk)"
* "Conditional access"

Please provide a better description and/or link to other documentation as the rows appear to provide contradictory information ("Yes" in one column and "No" in another). Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94c91b3d-d9b1-9056-ae3e-51a255ed88ec
* Version Independent ID: b60613bc-f7b3-d1c7-4d8e-924c0f87912f
* Content: [Microsoft 365 Business Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-business-service-description)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-business-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-business-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@adrianwells - Thank you for your feedback. The columns are for different product/subscription.
Column 1 pertains to Office 365 Business Premium 
Column 2 pertains to Microsoft 365 Business
Column 3 pertains to  Enterprise Mobility + Security E3

**Comment by adrianwells** [comment]
@prabita OK. It appears the content has changed since I opened this issue so that it makes more sense now. Thank you.
