### ISSUE TITLE
SharePoint groups

### ISSUE THREAD

**Issue by alinefmr** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#132]
For Azure AD group limits, see "Azure AD service limits and restrictions": https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/directory-service-limits-restrictions as such limits can impact public and private group sites membership management. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits#feedback)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@alinefmr - Thank you for your feedback. It is not clear what needs to be changed in the document. Could you please specify what exactly needs to be changed in the article?

**Comment by alinefmr** [comment]
Hi @prabita - please see that under "Groups" (in the Azure AD document referenced) additional limits (for example, _"A maximum of 100 users can be owners of a single group"_) can also impact limits for SharePoint Groups membership. I would simply add my previous feedback as a **Note** just after **SharePoint Groups** in this document.  Hope this helps, thanks.
