### ISSUE TITLE
SPO plan/quota

### ISSUE THREAD

**Issue by sabrinahota** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#133]
Thank you very much for the whole overview. 

Could you please include which SPO plan exactly is included within which PWA plan and how much quota you receive? I assume, as SPO is provisioned with the PWA, that you receive 1TB of SPO storage + 10GB per each additional PWA plan, but it is unfortunately not clear in all PWA articles. 

Thank you so much, 
Sabrina 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69451b60-fdc1-4b81-d154-cdd38931a902
* Version Independent ID: f90ef8b6-b8ed-37d8-d5c6-da25f96a0a1d
* Content: [Project Online Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/project-online-service-description/project-online-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/project-online-service-description/project-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/project-online-service-description/project-online-service-description.md)
* Product: **office-online-server**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@sabrinahota - Thanks for your feedback! I’ve reached out to the team and will update this article as needed, pending their response.

**Comment by SharS** [comment]
@sabrinahota SharePoint Online Plan 2 is included with Project Online. For more information, see the [SharePoint Online Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-service-description) and the [SharePoint Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits) topic.
