### ISSUE TITLE
Additional 25 TB SharePoint Site

### ISSUE THREAD

**Issue by hansgafriedzal** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#134]
>For any user that reaches at least 90% capacity of their 25 TB of OneDrive storage, additional cloud storage will be provided as 25 TB SharePoint team sites to individual users. This additional storage is provided to the organization by way of credit.

Does it mean that the new site will have different URL? Will it automatically sync to the desktop client?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99ce1810-18cd-687b-0c8b-bfceb919225a
* Version Independent ID: 705cde78-7e58-c260-bde3-0b393747cdea
* Content: [OneDrive for Business Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/onedrive-for-business-service-description)
* Content Source: [Office365-ServiceDescriptions/onedrive-for-business-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/onedrive-for-business-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@hansgafriedzal - Thanks for your feedback! I’ve reached out to the team and will update this article as needed, pending their response.

**Comment by SharS** [comment]
@hansgafriedzal Here are the answers from the product team: Yes, the new site will have a different URL. The new site will not automatically sync to the desktop client unless you have the [team site automount](https://docs.microsoft.com/en-us/onedrive/use-group-policy#AutoMountTeamSites
) feature configured. If you don't have this feature enabled, you have to explicitly click sync on the new document library(ies).

**Comment by scottsa-msft** [comment]
In this statement 
For any user that reaches at least 90% capacity of their 25 TB of OneDrive storage, additional cloud storage will be provided as 25 TB SharePoint team sites to individual users. This additional storage is provided to the organization by way of credit.

The second sentence "This additional storage is provided to the organization by way of credit."  should be removed.   This makes it sound like the OneDrive storage counts against the total SharePoint storage that the customer purchased and it does not.
