### ISSUE TITLE
Search returned item limits

### ISSUE THREAD

**Issue by ericleigh007** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#135]
This one is hitting us big time in archive mailboxes.  The limit is not noted here, and should be.
If it is in FACT 250, THAT'S A woefully inadequate number.  When searching an archive, one NEEDS to be able to search the entire thing, at once, and I cannot imagine even 10 times the 250 should cause a problem for Office 365 capacity.
One thing that also might help is for the search to be done from newest to oldest messages, so the most current information is uncovered.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@ericleigh007 - Thanks for your feedback! I’ve reached out to the team and will update this article as needed, pending their response.

**Comment by SharS** [comment]
@ericleigh007 We have a dedicated topic on [content search limits](https://docs.microsoft.com/en-us/office365/securitycompliance/limits-for-content-search) and we have a dedicated topic on [in-place eDiscovery limits](https://docs.microsoft.com/en-us/Exchange/security-and-compliance/in-place-ediscovery/search-limits). Please refer to those articles for the information you requested.
