### ISSUE TITLE
Confusing and misleading Safe Links 

### ISSUE THREAD

**Issue by vboyev-MSFT** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#136]
"ATP Safe Links protection is extended to apply to URLs in Office Online (Word Online, Excel Online, PowerPoint Online, and OneNote Online) and Office 365 ProPlus on Mac."

This implies if you are *not* on O365PP on a Mac, that ATP Safelinks will not work with links in Office Documents. This gets confusing in the Safe Links section, where it says - without any qualification-

Safe Links

The ATP Safe Links feature proactively protects your users from malicious URLs in a message or in an Office document. The protection remains every time they click the link, as malicious links are dynamically blocked while good links can be accessed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 502796e9-ca73-7123-7719-c7b5b1042b7b
* Version Independent ID: 2929af88-6d56-4de3-2b4e-4e1d0e4d97ef
* Content: [Office 365 Advanced Threat Protection Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description#whats-new-in-office-365-advanced-threat-protection-atp)
* Content Source: [Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@vboyev-MSFT - Thanks for your feedback! I’ve reached out to the team and will update this article as needed, pending their response.

**Comment by SharS** [comment]
@vboyev-MSFT The article has been revised to clarify safe links.
