### ISSUE TITLE
Where does M365B SKU land on this chart with respect to storage limits?

### ISSUE THREAD

**Issue by ExR90** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#138]
M365B is not listed here, only O365 and M365 Enterprise/Government. Where does M365B land with respect to storage limits?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99ce1810-18cd-687b-0c8b-bfceb919225a
* Version Independent ID: 705cde78-7e58-c260-bde3-0b393747cdea
* Content: [OneDrive for Business Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/onedrive-for-business-service-description)
* Content Source: [Office365-ServiceDescriptions/onedrive-for-business-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/onedrive-for-business-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@ExR90 - Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response.

**Comment by SharS** [comment]
@ExR90 The service description has been updated to include the Microsoft 365 Business storage limit.
