### ISSUE TITLE
Could you update the table to include Shifts ?

### ISSUE THREAD

**Issue by acamina** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#139]
or change the stuffhub to shifts ?
thx

**Comment by prabita** [comment]
@acamina - Thank you for feedback; please specify the content page referred here for further action.

**Comment by SharS** [comment]
@acamina Please specify the service description page so that we can proceed. Thanks!

**Comment by SharS** [comment]
@acamina Thank you for your feedback. Shifts is part of Teams. Please refer to the Teams row in the table to determine Shifts availability. Staffhub will be retired in October.
