### ISSUE TITLE
The limitation for Sharing Account Number

### ISSUE THREAD

**Issue by Shelleyliu0415** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#141]
Cloud you please add the following limit in this page:

The Account Number Limit for Sharing in SharePoint Online List or Site.
The longest character limit for the Message

**Comment by prabita** [comment]
@Shelleyliu0415 - please add the page link

**Comment by SharS** [comment]
Looks like this refers to SharePoint Online Limits page.

**Comment by SharS** [comment]
@Shelleyliu0415 I need the page link to route these questions to the appropriate people. Please supply the link.

**Comment by SharS** [comment]
@Shelleyliu0415 Thanks for your feedback. Unfortunately, I can't research your issue without knowing which page you're referring to. Please supply the link.
