### ISSUE TITLE
dead link in the Deleting accounts section

### ISSUE THREAD

**Issue by MAGROULX** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#142]
There is a dead link in the Deleting accounts section.  The link for "Delete or restore users in Office 365" points to 
https://support.office.com/article/HA102816052?CorrelationId=854d7a47-0077-4b99-8920-126a6e7ced12 .  It says the information can't be found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b65730b-7010-60f8-0b50-5a6c8a4970bd
* Version Independent ID: e07b0622-0e4f-1883-b045-ca4097b3c333
* Content: [User Account Management](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/user-account-management#deleting-accounts)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/user-account-management.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/user-account-management.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@MAGROULX - link updated, will be live 24 hrs
