### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by bruceburge** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#143]
How Office 365 manages DNS records  points to (https://go.microsoft.com/fwlink/p/?LinkID=270144) which resolves to (https://support.office.com/article/HA103834284?CorrelationId=bd4401fa-71fb-483a-8638-dddcdcd84ba0) which returns 

"Sorry, the page you’re looking for can’t be found.
You may have clicked an old link or the page may have moved."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc9a7e3b-5816-e4f0-f4bc-bc9384b4732d
* Version Independent ID: 1cea0199-f381-9f3e-b2b4-387785a78aca
* Content: [Domains](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/domains#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/domains.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/domains.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@bruceburge Thanks for your feedback! Links are updated, will be live 24 hrs.
