### ISSUE TITLE
Shredded Storage

### ISSUE THREAD

**Issue by sabrinahota** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#144]
The shredded storage used to be in the overview - it is still in the service descriptions for Germany, 21Vianet, etc. 
Can you please add it again? Furthermore, could you maybe give a detailed description on the shredded storage in general? Are the deltas of all files saved, or is there any difference between office & non-office files? Thank you very much! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b12fdba4-247d-f00c-7f1c-c083787384a2
* Version Independent ID: 9198e021-3d19-3839-e394-f209142e343f
* Content: [SharePoint Online Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-service-description)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
Thanks for your feedback. I've reached out to the product group and will update the article as necessary.

**Comment by aaronlemieux** [comment]
Hi sabrinahota I've spoken with the product team on this one.  Shredded Storage was removed from this service description and they have confirmed they do not wish to add this back in.
