### ISSUE TITLE
Commercial Tenant to Government Tenant Migration

### ISSUE THREAD

**Issue by byronmc** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#145]
My customer in my Microsoft CSP is requesting to "upgrade" commercial tenant to Government Cloud Tenant. Luckily they only store data in OneDrive, Unfortunately I have not found the most efficient way to migrate OneDrive data. What are the best options to do so?

**Comment by SharS** [comment]
@byronmc - I'm sorry that you're having this issue. For Support options, see [Support](https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/support).
