### ISSUE TITLE
Subsites - 2,000 per site collection should be too high for heavy users.

### ISSUE THREAD

**Issue by kenmoritest** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#146]
Additional comment will be necessary for this number 2,000.

2,000 is too high for heavily used environment. It should be less than 1,000 at least. The smaller the better. 
There are some documentation that states not to recommend to create subsites. 
So this documentation should be coherent with those documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits#feedback)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response

**Comment by kenmoritest** [comment]
@SharS  Thank you. Waiting for your action.

**Comment by SKjerland** [comment]
@kenmoritest - Our SharePoint writer updated the article to clarify. Thanks!
