### ISSUE TITLE
Updated content is required

### ISSUE THREAD

**Issue by MarcusCKLee** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#147]
This article contains wrong info about E3 does not have DLP for Teams chat as stated in another article ( https://docs.microsoft.com/en-us/office365/securitycompliance/data-loss-prevention-policies ).

I raised a O365 ticket:15113445 earlier ( in June 2019 ) and the Microsoft engineer and I are able to create DLP policies in Teams and confirm the DLP works on Teams Desktop apps, Teams Mobile apps and Teams web app.

Please update this document to reflect that E3 have DLP for Teams chat to provide clarity to all customers.
![DLP for Teams chat and channel conversations](https://user-images.githubusercontent.com/52666120/60817468-51d8ac00-a1ce-11e9-81ad-f2b9a0963d47.png)

**Comment by SharS** [comment]
@MarcusCKLee Can you provide the topic title so that I can get this verified and fixed? Thanks!

**Comment by MarcusCKLee** [comment]
Hi Sharon,

Apologise as I was tight up with some project works.
Thanks for following up on this topic.

A paragraph in the article ( https://docs.microsoft.com/en-us/office365/securitycompliance/dlp-microsoft-teams ) stated that E3 license offers DLP for Teams and it does not require the Advanced Compliance Add-on. It provided an example of defining a DLP policy in SharePoint and OneDrive that can prevent sensitive information from being shared in Teams chat of channel conversations.

Excerpt from the article:
Example 2: Protecting sensitive information in documents. Suppose that someone attempts to share a document with guests in a Microsoft Teams channel or chat, and the document contains sensitive information. If you have a DLP policy defined to prevent this, the document won't open for those users. Note that in this case, your DLP policy must include SharePoint and OneDrive in order for protection to be in place. (This is an example of DLP for SharePoint that shows up in Microsoft Teams, and therefore requires that users are licensed for Office 365 DLP (included in Office 365 E3), but does not require users to be licensed for Office 365 Advanced Compliance.)

However its title itself does not state about E3 can offer DLP for Teams.
Header Note from the article:
Data loss prevention capabilities were recently added to Microsoft Teams chat and channel messages for users licensed for for Office 365 Advanced Compliance, which is available as a standalone option and is included in Office 365 E5 and Microsoft 365 E5 Compliance. To learn more about licensing requirements, see Microsoft 365 Tenant-Level Services Licensing Guidance.

In my opinion, this article must be clearly state about E3 does offer DLP for Teams by elaborating with more examples when defining policies for SharePoint and OneDrive that will offer DLP for Teams.

At the moment, one of my customers is reluctant to transition to Teams due to the lack of 'clear' official document from Microsoft.

We have also confirmed by defining DLP for Teams and tested with expected result: sensitive information will be blocked by the defined policies. However, the customer need a clear official document that states E3 does offer DLP for Teams from Microsoft.

Please find attached the screenshot of the customer tenant that illustrates the policies that have been defined in Teams that tested with expected result.

Looking forward to your reply.

Thanks.
[Able to enable DLP for Teams with expected result.pdf](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions/files/3413293/Able.to.enable.DLP.for.Teams.with.expected.result.pdf)

**Comment by MarcusCKLee** [comment]
Hi Sharon,

I have uploaded my comment with the requested info.

**Comment by SharS** [comment]
@MarcusCKLee - Thanks for the detailed information about DLP. I need to know which service description contains the information that needs to be corrected (i.e., which service description did the table shown above come from).

**Comment by MarcusCKLee** [comment]
Hi Sharon,

Thanks for following up, the table is excepted from :
https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center

**Comment by SharS** [comment]
@MarcusCKlee Thanks. I'll contact the product team regarding your request.

**Comment by SharS** [comment]
Here's the answer from the product team: Teams DLP is an E5 feature.
Licensing is not currently enforced and E3 customers can enable the feature; however, this may change in the future.
