### ISSUE TITLE
Office 365 Business has Shared Computer Activation

### ISSUE THREAD

**Issue by rosskoes05** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#148]
I believe Office 365 Business now has Shared Computer Activation:
https://techcommunity.microsoft.com/t5/Microsoft-365-Business-Blog/Shared-Computer-Activation-for-Office-in-Microsoft-365-Business/ba-p/472994

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61b8fbc9-7314-1e82-7c85-f0f9d3c3c1fd
* Version Independent ID: 7a5944ad-e785-5711-0954-f2be068e79d1
* Content: [Office Applications Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-applications-service-description/office-applications-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/office-applications-service-description/office-applications-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-applications-service-description/office-applications-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by justinfcoffey** [comment]
Microsoft 365 Business now has SCA rights, not Office 365 Business Premium or Business.

**Comment by rosskoes05** [comment]
Bummer.  I missed that.  Thank you.
