### ISSUE TITLE
Mailfow from feature to feature

### ISSUE THREAD

**Issue by mikesmith916** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#149]
There should be some description of where or what order different protection technologies are used against inbound email. Does Spam Filtering happen before or after Malware Detection. Does ATP process the messages after the standard security or after. When are the Mail Transport Rules referenced?

**Comment by SharS** [comment]
@mikesmith916 Thanks for your comment. Can you let me know the topic title so that I can research this? Thanks.

**Comment by SharS** [comment]
@mikesmith916 I think the information that you requested is in [What policy applies when multiple protection methods and detection scans run on your email](https://docs.microsoft.com/en-us/office365/securitycompliance/how-policies-and-protections-are-combined).
