### ISSUE TITLE
Clarification on Intune

### ISSUE THREAD

**Issue by gavsto** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#15]
I have found this service description after being told by a Team Manager at Microsoft Intune that a full Intune license is not available for Microsoft 365 for Business which does not support what I am reading here. Can this be clarified?

Here is what they said:

"As per my understanding you are getting that every feature is present in Intune is available in M365, and all the features which is not available in M365 portal can be accessed from intune portal (using M365 license)
But this seems to be misinterpreted, article and my senior engineer says that you can access all other features which is not available M365 ( Wi-Fi profiles, VPN certificates, etc.) using intune portal if you have separate Intune license ."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94c91b3d-d9b1-9056-ae3e-51a255ed88ec
* Version Independent ID: b60613bc-f7b3-d1c7-4d8e-924c0f87912f
* Content: [Microsoft 365 Business Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-business-service-description)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-business-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-business-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by prabita** [comment]
@gavsto Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response.

**Comment by SharS** [comment]
@gavsto Intune service is available in its entirety to M365 Business customers. We've updated the service description to make this more clear.
