### ISSUE TITLE
Unique permission scope

### ISSUE THREAD

**Issue by b6202lam** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#150]
This article about migration mentions that there are limits on permission scopes per site: https://docs.microsoft.com/en-us/sharepoint/dev/apis/migration-api-shared

Here's an excerpt: "Make sure not to exceed 5000 unique ACLs on a site. […]There is also a hard limit of 50,000 unique ACL's that will be enforced. If you are close to reaching the 5000 limits, we recommend that the permission model be simplified on the source before migration."

Should these per site limits be added to this article?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by timdw** [comment]
(Duplicating my comment here as it's perhaps more relevant on this page) @bernardlam I wrote a script to test the hard limit and ran it in two different tenants. The limit is (currently at least) 50,000. The script created list items and broke inheritance on them until it came up with the ServerException "You cannot break inheritance for this item because there are too many items with unique permissions in this list.".

**Comment by bernardlam** [comment]
shall we clarify that 5,000 per list is a soft limit and there's a hard limit of 50,000?

**Comment by timdw** [comment]
In the SharePoint 2016/2019 documentation [here](https://docs.microsoft.com/en-gb/SharePoint/install/software-boundaries-and-limits-0) the terms "Boundaries", "Thresholds" and "Supported limits" are used. In SharePoint online we do not have access to some settings so from an end user point of view some "Thresholds" becomes "Boundaries". This screen snip
![Central administration webapplication settings](https://social.technet.microsoft.com/Forums/getfile/151641)
from [this](https://social.technet.microsoft.com/Forums/azure/en-US/86f6c382-bb8f-4232-81b3-357e20bb6697/limitation-quotunique-permissions-limit-50000quot?forum=sharepointgeneralprevious) TechNet forum thread is an example which shows the setting for List Unique Permissions Threshold which is not accessible in SharePoint online.

**Comment by bernardlam** [comment]
right, so threshold limit cannot be exceeded. based on your test results you're able to create 50,000 unique permissions in a list, so this implies the threshold is set at 50,000. so using the terminology in the SP2016/19 documentation, 5,000 is more like the "supported limit". my suggest is to characterize it as such in the SPO limit article.

**Comment by SharS** [comment]
Thanks for your feedback. I’ve reached out to the product team and will update this article as needed, pending their response.

**Comment by anjCerbolles** [comment]
@SharS, any updates on this? Thanks.

**Comment by SKjerland** [comment]
@b6202lam @timdw - We've updated the article to clarify, based on the product team's response. Thanks!
