### ISSUE TITLE
How many document libraries per site

### ISSUE THREAD

**Issue by Damag3d** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#151]
Hello, can we add information about how many document libraries can be stored per site?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits#feedback)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
Thanks for your suggestion. I've reached out to the product group about adding this information to the topic.

**Comment by ichkoj** [comment]
That's 2 months old is the product group still on vacation?

**Comment by Damag3d** [comment]
@SharS  any updates?

**Comment by mrstevejames** [comment]
This would be really good to know, considering implementing a solution requiring 22,000 document libraries in a site collection !!

**Comment by bakerm00** [comment]
still waiting

**Comment by scara1701** [comment]
I too would like to know the limit number of document libraries per site.

**Comment by kevmaitland** [comment]
Me too

**Comment by SKjerland** [comment]
@Damag3d  @ichkoj @mrstevejames @bakerm00 @scara1701 - Our SharePoint writer updated the article to clarify. Thanks!
