### ISSUE TITLE
Access Services

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#152]
With regards to...
https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/add-ons#azure-provisioned-apps-access-services

...I don't think that's accurate anymore;

https://support.office.com/en-us/article/access-services-in-sharepoint-roadmap-497fd86b-e982-43c4-8318-81e6d3e711e8

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fb3d249-7f21-87bd-3b46-cb566cda6d95
* Version Independent ID: fb98ea7b-6f38-ad68-f3b4-47582bcdf345
* Content: [Add-ons](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/add-ons#azure-provisioned-apps-access-services)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/add-ons.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/add-ons.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
Thanks for your feedback. I've reached out to the product team and will update the document as necessary.

**Comment by SKjerland** [comment]
@anwarmahmood1 -  Our SharePoint writer updated the article. Thanks!
