### ISSUE TITLE
Azure Provisioned Apps: Access Services

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#153]
With regards to...
https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-education#sharepoint-online-features

...I don't think the "Azure Provisioned Apps: Access Services" feature is accurate anymore;

https://support.office.com/en-us/article/access-services-in-sharepoint-roadmap-497fd86b-e982-43c4-8318-81e6d3e711e8

Should it be removed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 482f1200-178f-088c-f189-ac129614cdb0
* Version Independent ID: 94ff27f4-966c-f271-1822-515c4e56a1bb
* Content: [Office 365 Education](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-education#sharepoint-online-features)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-education.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-education.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by anwarmahmood1** [comment]
better than simply removing, change the value in the cells from "Yes" to "retired", making "retired" a link to https://support.office.com/en-us/article/access-services-in-sharepoint-roadmap-497fd86b-e982-43c4-8318-81e6d3e711e8

**Comment by SharS** [comment]
Thanks for your feedback! I've reached out to the product group, and will update the page as necessary.
