### ISSUE TITLE
Enforcement of 5,000 unique security scopes per list or library

### ISSUE THREAD

**Issue by timdw** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#154]
In the two tenants I have tested the per list limit was 50,000, not 5,000. Does Microsoft plan to enforce a limit of 5,000 or does the documented limit need to be updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits#feedback)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
Thanks for your feedback! I've reached out to the product group and will update the topic as necessary.

**Comment by frankok** [comment]
Hi SharS,

What is the status on this?

**Comment by timdw** [comment]
@SharS Any news? I think this is an important question as it affects whether SharePoint is suitable for various scenarios, especially when used with PowerApps.

**Comment by Panoone** [comment]
Three months later and still waiting...

**Comment by andygjones-nz** [comment]
Any updates? I'm also keen to know the answer

**Comment by SKjerland** [comment]
@timdw @frankok @Panoone @andygjones-nz - From the SharePoint product team: "The hard (enforced) limit on unique security scopes per list or library is 50,000, but the recommended general limit is 5,000. Above 5,000, ACL size starts to matter. Although you can add scopes up to the hard limit of 50,000, Microsoft doesn’t recommend it unless you have a very specific scenario in mind."

**Comment by SKjerland** [comment]
We'll update this article to clarify the limit. Thanks, everyone, for your comments. I apologize for the delay in providing a response.
