### ISSUE TITLE
Incorrect information about Azure Information Protection P1

### ISSUE THREAD

**Issue by jhuylebroeck** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#155]
The page states: "Licensed users of Microsoft 365 F1, Microsoft 365 E3, and AIP Plan 1 can benefit from AIP Plan 1." This should read: "Licensed users of Microsoft 365 F1, Microsoft 365 Business, Microsoft 365 E3, and AIP Plan 1 can benefit from AIP Plan 1."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 Tenant-Level Services Licensing Guidance](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance#feedback)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
Thank you for your feedback! I'm forwarding this to the product group and will update the article as necessary.

**Comment by SharS** [comment]
Article has been updated with correct information.
