### ISSUE TITLE
Incorrect information about Data Loss Prevention

### ISSUE THREAD

**Issue by jhuylebroeck** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#156]
The page states: "Licensed users of Office 365 E3, Microsoft 365 E3, and Office 365 Data Loss Prevention can benefit from DLP for Exchange Online, SharePoint Online, and OneDrive for Business."
It should read: "Licensed users of Office 365 E3, Microsoft 365 Business, Microsoft 365 E3, and Office 365 Data Loss Prevention can benefit from DLP for Exchange Online, SharePoint Online, and OneDrive for Business."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 Tenant-Level Services Licensing Guidance](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
Thank you for your feedback! I'm forwarding this to the product group and will update the article as necessary.

**Comment by SharS** [comment]
The article has been updated with correct information. Thank you.
