### ISSUE TITLE
Include SharePoint 2019 in comparison table

### ISSUE THREAD

**Issue by ryanjonhealy** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#157]
Please can you include 2019 in the comparison table or perhaps reference any differences with 2016 if not a substantially different  number of features?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b12fdba4-247d-f00c-7f1c-c083787384a2
* Version Independent ID: 9198e021-3d19-3839-e394-f209142e343f
* Content: [SharePoint Online Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-service-description#feature-availability-across-office-365-plans)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@ryanjonhealy Thanks for your feedback. I'm following up with the product team and will update the article based on their input.

**Comment by SharS** [comment]
The article has been updated with correct information. Thank you.

**Comment by SharS** [comment]
Closed the wrong issue.

**Comment by SKjerland** [comment]
@ryanjonhealy - Our SharePoint writer worked with the product team to update this article and made extensive changes. Please see the various comparison tables in [Office 365 plan options](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-plan-options) instead.
