### ISSUE TITLE
Was Power Map for Excel replaced with 3D Maps?

### ISSUE THREAD

**Issue by rosskoes05** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#158]
Was Power Map for Excel replaced with 3D Maps?  And is 3D maps included in Business or Business Premium?  I am able to use it with my Business Premium License.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61b8fbc9-7314-1e82-7c85-f0f9d3c3c1fd
* Version Independent ID: 7a5944ad-e785-5711-0954-f2be068e79d1
* Content: [Office Applications Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-applications-service-description/office-applications-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/office-applications-service-description/office-applications-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-applications-service-description/office-applications-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
3D Maps is the new name for Power Map for Excel. From the [Get started with 3D Maps](https://support.office.com/en-us/article/get-started-with-3d-maps-6b56a50d-3c3e-4a9e-a527-eea62a387030?redirectSourcePath=%252fen-us%252farticle%252f3D-Maps-for-Excel-2016-c5ec20a8-f168-4c4c-aafb-0c3eb1b3c8a6&ui=en-US&rs=en-US&ad=US) article: "Power Map, our popular 3-D geospatial visualization add-in for Excel 2013, is now fully integrated into Excel. We’ve also given this feature a more descriptive name, “3D Maps". "
