### ISSUE TITLE
Limit of 100,000 items per container level

### ISSUE THREAD

**Issue by b6202lam** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#159]
"After 100,000 items are added to a list, library, or folder, permission inheritance for the list, library, or folder can't be changed." 

I believe this limit applies to the current container level only (i.e. you can still change permission inheritance as long as you group your items under subfolders containing &lt;100,000 each. however, this is not explicitly stated in the article, giving the impression that the 100,000 limit applies not just to the current level, but all sub-levels as well

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
Thanks for your feedback! I've reached out to the product group and will update the article as necessary.

**Comment by chaitusandeep** [comment]
Could you please confirm on this limitation. Is this 100,000 limit is for the complete library or does it apply at folder/subfolder level?

My question is if I add 1000 documents for all 200 folders with unique permissions, which totals to 200,000, will I be able to create a new folder and still set unique permissions to the new folder?

**Comment by mrstevejames** [comment]
Copied from above: "Unique security scopes per list or library - 5,000." So It doesn't sound like that scenario would work for you.

**Comment by SKjerland** [comment]
Our SharePoint writer said the recent update to this article addresses this. Thanks!
