### ISSUE TITLE
Feature comparison table display issue

### ISSUE THREAD

**Issue by JoeAlanis** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#16]
Depending on monitor resolution/browser display scaling, the features for SP 2016 may not display. There should be a warning near the top to let users know that there is a horizontal scroll bar near the bottom of the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b12fdba4-247d-f00c-7f1c-c083787384a2
* Version Independent ID: 9198e021-3d19-3839-e394-f209142e343f
* Content: [SharePoint Online Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-service-description#feature-availability-across-office-365-plans)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by prabita** [comment]
@JoeAlanis Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response

**Comment by kaarins** [comment]
Thanks for reporting this. Unfortunately, the table is too wide for all the columns to appear, but I added a note at the top to let people know they need to use the scrollbar at the bottom of the table to see hidden columns.
