### ISSUE TITLE
Office 365 F1 + MS Graph API

### ISSUE THREAD

**Issue by anoopt** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#160]
Hello,

Can you please let us know if MS Graph API - in particular (/me/joinedTeams) works with users who have Office 365 F1 license assigned to them? 

Happy to provide more details if needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8f41cb0-4ad7-f25c-6586-fe89e8fca92d
* Version Independent ID: 9354cc15-1341-a4e1-4844-83a1f26ee149
* Content: [Office 365 Platform Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-platform-service-description)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@anoopt Thanks for your feedback. I'll contact the product team to get an answer and update the article based on their response.

**Comment by SharS** [comment]
@anoopt I've been in touch with the product team, and they confirmed that the MS Graph API is available for users who have F1 licenses.

**Comment by anoopt** [comment]
Thank you very much for confirming Sharon!
