### ISSUE TITLE
MC173908 - Microsoft has changed the message expiration timeout from 48 to 24 hrs

### ISSUE THREAD

**Issue by stukey** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#161]
Per Office 365 Message Centre notification MC173908, Microsoft has changed the message expiration timeout from 48 to 24 hrs. This change was due to be completed by end of June 2019. I believe the message deferral limit documented on this page needs to be updated to reflect these changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5013ccda-a0c6-ce6c-73e7-c78187008f55
* Version Independent ID: a2233d27-d1b1-23af-776b-b860eb1f79b6
* Content: [Exchange Online Protection Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-protection-service-description/exchange-online-protection-limits#feedback)
* Content Source: [Office365-ServiceDescriptions/exchange-online-protection-service-description/exchange-online-protection-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-protection-service-description/exchange-online-protection-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@Stukey Thanks for your feedback! I've contacted the product group and will update the article as required based on their response.

**Comment by SharS** [comment]
@stukey I've updated the service description. You should see the change online soon.
