### ISSUE TITLE
Which ATP comes with the new Microsoft 365 Business?

### ISSUE THREAD

**Issue by jake1999** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#162]
Which ATP version comes with the new Microsoft 365 Business?

**Comment by SharS** [comment]
Thanks for your feedback! I've reached out to the product team and will update the article if appropriate after their response.

**Comment by SharS** [comment]
@jake1999 ATP Plan 1 comes with Microsoft 365 Business. I've updated the article with this information.
