### ISSUE TITLE
This page is absolutely insane!

### ISSUE THREAD

**Issue by muszyngr** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#163]
ask a simple question: What is the attachment size limit? and these fools do what Microsoft does, get paid per word I guess, cause the answer should be one number!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by xhoy** [comment]
I do not fully understand your comment. when going to: https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#message-limits (your link) there is nice table: 
````
File attachment size limit - Outlook => 150MB
File attachment size limit - OWA[6] => 35MB
File attachment size limit - Outlook for Mac => 150MB

````

Seems clear to me?

**Comment by SharS** [comment]
The topic already contains the information. Closing this.
