### ISSUE TITLE
Microsoft 365 E5/E3/F1 service description missing

### ISSUE THREAD

**Issue by xhoy** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#164]
We are currently looking in to Microsoft 365 (E5/E3/F1/business) And are unable to find a (complete) service description.

Currently there is page about Microsoft 365 business but not on E5/E3/F1.

Further there is a lot of information missing on several places see: 
* #82  => not fixed currently
* #33 => Where are the pages on Microsoft 365 E5/E3/F1? 
* #155 => not all MS 365 versions listed

Would suggest updating (most) of the docs?

With kind Regards,

Thomas

**Comment by SharS** [comment]
@xhoy - Thank you for your feedback! I've contacted the product team, and will update the service description as needed based on their response.

**Comment by xhoy** [comment]
Hello @SharS i have had contact with serveral people  at microsoft and it turns out that Microsoft 365 F1/E3/E5 is based (mostly) on several other products.

Best reference seems to be: https://github.com/AaronDinnage/Licensing

I think adding a page under https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/ [1] with a description that F1 is 'basicaly' Office 365 F1, EMS E3 - some features. That MS 365 E3 is Office 365 E3 + EMS E3 + Windows E3 etc etc....

[1] 404 since only the sub page exsist ( https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description )

**Comment by SharS** [comment]
@xhoy Thanks for your feedback. We recently published [Licensing Microsoft 365 for small and medium-sized businesses](https://docs.microsoft.com/office365/servicedescriptions/microsoft-365-service-descriptions/licensing-microsoft-365-in-smb). I believe that it has the information you're looking for.
