### ISSUE TITLE
Microsoft 365 missing in table

### ISSUE THREAD

**Issue by xhoy** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#165]
Was just wondernig about the "new" Email encryption in Office 365 and what features are included in the Microsoft 365. Its not listed!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54cc9525-7b54-4151-ac74-acae805a8f69
* Version Independent ID: 3bb6ba9b-b853-430f-6e88-13d5a20cdaea
* Content: [Exchange Online Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
Thanks for your feedback! I've forwarded your question to the product group and will update the service description if appropriate.

**Comment by SharS** [comment]
@xhoy Thanks for your feedback. Email encryption limits are listed under Message Limits in the Exchange Online Limits service description (https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#message-limits). Microsoft 365 features are documented in the Microsoft 365 Business service description (https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description)

**Comment by xhoy** [comment]
@SharS This is not correct. Microsoft 365 Enterpise (F1/E3/e5) are not listed!
