### ISSUE TITLE
Unlimited Archives

### ISSUE THREAD

**Issue by simarino** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#166]
Please clarify somewhere in our documentation that the number of AUX archives which is forming the so called 'unlimited archives' for EXO Plan 2 based mailboxes is actually 20 AUX Archives. This can't be increased at the moment. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#feedback)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by markjjo** [comment]
Closing as this is being address in a different topic
