### ISSUE TITLE
Ambiguous / equivocal description on SPO site storage limit. 

### ISSUE THREAD

**Issue by JarryShaw** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#167]
Documentation URL: https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits

1. `Max storage per site collection` says `25 TB`, and in the footnotes, `This is the storage limit for a single site collection, not the amount of storage provided for each site collection.` However, there is NO terminology definition of `site collection` through out the whole documentation nor a reference.
2. When in SharePoint admin panel, we can tell that the actually / default storage provided by Microsoft for free is 1 TB, whilst we can purchase add-on storage from Microsoft. But on this documentation, there's no additional information on this topic.

**Comment by SharS** [comment]
Thanks for your feedback! I have contacted the product group and will update the article, as necessary.

**Comment by SKjerland** [comment]
@JarryShaw - Our SharePoint writer updated the article to clarify. Thanks!
