### ISSUE TITLE
Missing details about Azure Active Directory version

### ISSUE THREAD

**Issue by xhoy** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#168]
There is a long table with features included in each plan. Under 

Azure Active Directory services  it says Yes but there are no details on what type of service is included. there a several flavours https://azure.microsoft.com/en-us/pricing/details/active-directory/

Would be nice to update the list with a more specific 'version' detail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8f41cb0-4ad7-f25c-6586-fe89e8fca92d
* Version Independent ID: 9354cc15-1341-a4e1-4844-83a1f26ee149
* Content: [Office 365 Platform Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-platform-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@xhoy Thank you for your feedback! This information has been added to the Office 365 Platform Service Description.
