### ISSUE TITLE
 Innovations in security and compliance link is broken

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#169]
Under section "Encryption at rest" there is a link to a blog " Innovations in security and compliance" but it's broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65fe30a4-d11f-29bb-5171-11e40772d740
* Version Independent ID: 7b59b04f-ea56-c839-eac7-e22d6bf0657e
* Content: [IT Professional](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/it-professional#feedback)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/it-professional.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/it-professional.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@Larryngolog Thanks for your feedback. We're fixing the link and you should see the updated content soon.
