### ISSUE TITLE
Data Residency Concerns

### ISSUE THREAD

**Issue by LTofsrud** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#17]
Under the Safe Attachments section, it would be great to know where those 'special environments' (I'm assuming these are the detonation chambers) are physically located.  Our legal department has a concern that you are taking a copy of a potentially sensitive document and putting it in a location that is outside of our Canadian data center.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 502796e9-ca73-7123-7719-c7b5b1042b7b
* Version Independent ID: 2929af88-6d56-4de3-2b4e-4e1d0e4d97ef
* Content: [Office 365 Advanced Threat Protection Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description)
* Content Source: [Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by SKjerland** [comment]
@LTofsrud - Rest assured that Microsoft does not jeopardize sensitive customer data. Copies do NOT leave your data center. The author of the article added some information that will hopefully relieve any concerns.
