### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by AlexJPawlak** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#170]
Dynamics 365 Licensing Guide link is dead (in section https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-dynamics-365-online-service-description#application-availability-across-dynamics-365-plans) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ed4ff2c-ddfd-d1d1-d2ca-b017baafd4de
* Version Independent ID: 699a5024-dcb2-4c23-f12b-5b1b3808171f
* Content: [Microsoft Dynamics 365 (online) Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-dynamics-365-online-service-description#application-availability-across-dynamics-365-plans)
* Content Source: [Office365-ServiceDescriptions/microsoft-dynamics-365-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-dynamics-365-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@AlexJPawlak Thanks for your feedback. We're fixing the link and you should see the updated content soon.
