### ISSUE TITLE
Minimum 5 users.

### ISSUE THREAD

**Issue by pminnebach** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#171]
The page states "For subscriptions with 5 or more users ... "

Does this have to be 5 users with the exact same subscription, eg 5x O365 E3?
Or can different subscriptions be mixed till the minimum of 5 users is met, eg 3x O365 E3, 1x O365 E5 and 1x OD4B plan 2?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99ce1810-18cd-687b-0c8b-bfceb919225a
* Version Independent ID: 705cde78-7e58-c260-bde3-0b393747cdea
* Content: [OneDrive for Business Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/onedrive-for-business-service-description)
* Content Source: [Office365-ServiceDescriptions/onedrive-for-business-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/onedrive-for-business-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
Thanks for your feedback. I've forwarded your question to the product team, and will update the article if necessary based on their response.

**Comment by SharS** [comment]
@pminnebach It can be any combination of qualifying plans. I've updated the article with this information.

**Comment by chelssi** [comment]
Hi,

I only have one user with a business plan. I can't get 5TB until I bought four more licenses? how is this possible if a home subscription has 6 users with a total of 6TB.

Thank you
