### ISSUE TITLE
F1 Teams users are able to create and initial meetings without any issue

### ISSUE THREAD

**Issue by XixiHuang333** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#172]
"12 InOffice 365 Enterprise F1, one-to-one audio/visual calls are supported. Meetings rights are limited to join only (no creating or initiating). "

We have tested on multiple F1 tenants.  Teams users are able to create and initial meetings without any issue. Could you please double verify this statement of document? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8f41cb0-4ad7-f25c-6586-fe89e8fca92d
* Version Independent ID: 9354cc15-1341-a4e1-4844-83a1f26ee149
* Content: [Office 365 Platform Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-platform-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@XixiHuang333 Thanks for your feedback! I've contacted the product team and will updated the article if needed, based on their response.

**Comment by SharS** [comment]
@XixiHuang333 I received the following answer: Teams users who have F1 licenses are not licensed to create and initiate meetings. This limitation is not enforced, but that may change later this year.
