### ISSUE TITLE
auto-expanding feature is also working for Exchange Online mailboxes

### ISSUE THREAD

**Issue by raducant** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#173]
In this article , there is a statement "Auto-expanding archiving is only supported in hybrid-configuration when the user's mailbox resides on Exchange Server 2016 or Exchange Server 2013 (SP1 or later). "
But if I access this docs https://docs.microsoft.com/en-us/office365/securitycompliance/unlimited-archiving , it states that When the 100 GB storage quota is reached, organizations had to contact Microsoft to request additional storage space for an archive mailbox. That's no longer the case. 
This article needs to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6177b1e-b721-39ea-25fb-0b6406cf8714
* Version Independent ID: 69864654-33a2-2669-2926-82c0433b3515
* Content: [Exchange Online Archiving Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
Thank you for your feedback. I've forwarded your question to the product team and will update the article based on their response.
