### ISSUE TITLE
Add Office 365 Message Encryption Service Guidance

### ISSUE THREAD

**Issue by jreinhardtiv4** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#174]
This is a great page, for an area that has long been not addressed. I would like to request some further guidance for the Office 365 Message Encryption service specifically. The reason is that there is no current way to restrict who gets offered the "Encrypt" template for desktop Outlook once a tenant is enabled for Rights Management. Thus, plans such as M365 F1 or other SKUs may provide access to the OME service when they are not licensed. We need some further guidance on what is the best practice for restricting users of M365 or O365 plans with licensing below E3 from using OME. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 Tenant-Level Services Licensing Guidance](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance#data-loss-prevention-for-exchange-online-sharepoint-online-and-onedrive-for-business)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
Thank you for your feedback! I've forwarded this to the product team, and will update the article as necessary.

**Comment by SharS** [comment]
@jreinhardtiv4 We've added OME information to the document. You should see it online soon.

**Comment by jreinhardtiv4** [comment]
This is good, but it doesn't added the new version of OME and the "Encrypt" button that is in Outlook. The guidance given was precisely what I did before with the legacy version of OME. It is the new version of OME that causes an issue. Thoughts?
