### ISSUE TITLE
What about G5?

### ISSUE THREAD

**Issue by hedrichm** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#175]
I see all government plans except G5 listed under "Security & Compliance Center availability for Standalone plans". Is it on par with E5?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 663a603e-482b-0a4f-55a9-229ceab11bb1
* Version Independent ID: 488b1daa-b459-c56d-11eb-59242af822b0
* Content: [Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
Thank you for your feedback! I've forwarded your question to the product team, and will update the article based on their response.

**Comment by SharS** [comment]
@hedrichm  Here's the response from the product team: 

Thank you for the question. We are in the process of adding information about Security & Compliance Center feature availability for O365 G5 in the coming weeks. Please stay tuned as we will provide more information soon.

**Comment by linebackj** [comment]
Still waiting on G5 to be added?
