### ISSUE TITLE
365 business missing services

### ISSUE THREAD

**Issue by AnyITBNE** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#176]
Office 365 Business descriptions wrong - Missing Flow, bookings, planner etc as they are makred as NO. this has the correct info here https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8f41cb0-4ad7-f25c-6586-fe89e8fca92d
* Version Independent ID: 9354cc15-1341-a4e1-4844-83a1f26ee149
* Content: [Office 365 Platform Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-platform-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@AnyITBNE Thanks for your feedback! I've contacted the product team and will revise the article based on their response.

**Comment by SharS** [comment]
@AnyITBNE I heard back from the product team, and here's their response: "Both O365 Business Premium and Microsoft 365 Business plans have Flow, Bookings, Planner but O365 Business does **not**.
