### ISSUE TITLE
SharePoint Online limits vs Best practices

### ISSUE THREAD

**Issue by pryankrohilla** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#178]

**Comment by pryankrohilla** [comment]
I like to know if there is MS official guidance on SPO limits vs Best practices. 
This article provides good overview  on SPO limits (https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits) , but I can't find any details on Best practices.  What are recommended Best practices for SPO Storage and usage ( Document management, content management, security permissions, IRM, Web Parts, Pages, Page size, etc...)

**Comment by SharS** [comment]
@pryankrohilla Thanks for your feedback! I've contacted the product team to see if they can refer you to the correct information.

**Comment by lhcole** [comment]
@pryankrohilla Thanks for your comments. Please refer to the article [Plan sites and manage users](https://support.microsoft.com/en-us/office/plan-sites-and-manage-users-95f9eb7a-4ac8-4dd5-a883-17686cbf8fff) to answer your question.
