### ISSUE TITLE
Moving from GCC to Commercial

### ISSUE THREAD

**Issue by metro-mark** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#179]
Hello, Due to some misunderstanding from legal dept, our organization is now under GCC. Is there any way to exit out of GCC and go full commercial? Who should I contact to get the process started?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e69c139-60fc-5e97-168a-12d7bf1fbd38
* Version Independent ID: bd4edf0e-4a2f-2bf7-92e6-c7e840584977
* Content: [Office 365 US Government](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md)
* Service: **o365-administration**
* GitHub Login: @danarl
* Microsoft Alias: **danarl**

**Comment by SharS** [comment]
@metro-mark Thank you for your feedback. I've contacted the product group regarding your question, and will post their response when I receive it.

**Comment by SharS** [comment]
@metro-mark Thank you for reaching out on more information on cross-cloud tenant-to-tenant migrations. Moving your organization from GCC to Commercial (and vice-versa) is a complex effort and unfortunately we do not have any step-by-step published materials to guide you through this process. We highly encourage you to reach out to [Microsoft Consulting Services](https://www.microsoft.com/en-us/enterprise/services?SilentAuth=1&activetab=pillars:primaryr11) or one of our Government partners for further assistance. For more information on which partners support our different Microsoft 365 Government environments you can refer to the list on the [How to Buy page](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/microsoft-365-government-how-to-buy).

**Comment by SharS** [comment]
@metro-mark Thank you for reaching out on more information on cross-cloud tenant-to-tenant migrations. Moving your organization from GCC to Commercial (and vice-versa) is a complex effort and unfortunately we do not have any step-by-step published materials to guide you through this process. It’s important to note once a tenant has been created and deployed with GCC licenses, it can’t be repurposed for commercial services. A new commercial tenant would need to be created, and there’s third party options for data migration and setting services. We recommend first reaching out to [Commerce support](https://support.office.com/en-us/article/talk-to-support-or-a-consultant-18948a4c-3eb1-4b30-b1bc-a4cc29eb7655)  and discuss the current status of your licensing status and enrollment options.
