### ISSUE TITLE
When is update to this document coming

### ISSUE THREAD

**Issue by DanFrumkin** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#18]
This document is a bit long in the tooth, back to September. Looking at the Roadmap site, Stream and Forms are coming in November, but Planner is later next year. Probably worth updating.

Also, I will note that Sway is included in this site as "later" but doesn't even show up on the roadmap site. Weird.

Thanks for keeping this very valuable and informative site up to date.

Dan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e69c139-60fc-5e97-168a-12d7bf1fbd38
* Version Independent ID: bd4edf0e-4a2f-2bf7-92e6-c7e840584977
* Content: [Office 365 US Government](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by heckmanz** [comment]
looking for the update on coming soon for items like Microsoft Planner to the G3 version of Office 365 Suite.  I recently received notice from Microsoft with our 365 stating the following:

Update: Microsoft Teams trial for commercial cloud customers is now available 

	Major update: General Availability rollout started 	
	Applied to: All customers 	

As we originally communicated in MC136565 in May of this year, we’re releasing a free 1-year trial of Microsoft Teams for any user of Office 365 or Azure Active Directory (AAD), even if the user is not yet licensed for the service. We heard your feedback, made some modifications and are excited to announce that this trial will be available later this week.

Admins have requested the ability to control when trials are available for their users. We have a new administrative control to manage the ability for users to claim trial apps and services within your organization. 

[How does this affect me?]
Today, if an end user does not have a valid license when attempting to use Microsoft Teams, they will see an error page prompting them to contact you to get access. 

Moving forward, users will be prompted with an option to start using Microsoft Teams. Once a user signs up for this trial, they will have access to Microsoft Teams, as well as Microsoft Planner, Flow for Office 365 (Plan 1), Office Online, PowerApps for Office 365 (Plan 1), SharePoint Online (Plan 1), and Sway.

The free trial applies to commercial Office 365 organizations where Microsoft Teams is turned on at the organization level. This trial is not currently available to Office 365 subscriptions in Education, Government, and Office 365 Germany. 

The new administrative control is available in the Office 365 admin center. Go to Services & add-ins > User owned Apps and Services. The Let users install trial apps and services option is enabled by default. Currently, the Microsoft Teams trial is the only trial in this category, but this might apply to other similar programs in the future.

If this administrative control is disabled, and an end user does not have a valid license when attempting to use Microsoft Teams, they will continue to see an error page prompting them to contact you to get access.

[What do I need to do to prepare for this change?] 
If your organization is ready to trial Microsoft Teams, there is no action you need to take. 

While the capability to sign up for the Teams trial will be turned on by-default, you can disable the ability for your users to claim trial apps and services within your organization.

1. From the Office 365 admin center, go to Services & add-ins > User owned Apps and Services.
2. Turn off Let users install trial apps and services.

Please click Additional Information to learn more about the Microsoft Teams trial.

------------------------------
I'd like to have the trial in the actual Office 365 Admin deployment and decide which users are able to access it.  We specifically are looking for Planner.

Any word on when SOON might be?

Thank you,
Zondra

**Comment by SKjerland** [comment]
@heckmanz - We can't give out dates, but for up-to-the-minutes news on Planner, check out the Planner blog: https://techcommunity.microsoft.com/t5/Planner-Blog/bg-p/PlannerBlog.

**Comment by SKjerland** [comment]
@DanFrumkin - Thanks for your comment! The article was updated on 1/8/2019. If you note any other issues with the article, please let us know by posting another comment. Thanks!
