### ISSUE TITLE
Impact of Surpassing 2000 Subsites / 10,000 Groups per Site Collection?

### ISSUE THREAD

**Issue by mferricci** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#180]
I have a site collection with more than 2200 subsites and more than 13,000 groups.  

NOTE: a subsite is automatically created when a project is created in our instance of Project Online.  I just discovered this limitation.  Before I take steps to remedy the situation, I'd like to know what are the impacts of violating these limits?  

More specifically, what will the impact be to the end user experience?  
- Just general performance issues? 
- Or might it present itself where users would get an "access denied" error message to a site they definitely have permission to access?  
- I'm hearing reports of the later and am suspecting they might be related.

**Comment by SharS** [comment]
@mferricci Thanks for your feedback! I've forwarded your questions to the product team, and will update the topic as necessary based on their response.

**Comment by SharS** [comment]
@mferricci Here's the response I received from the product team: The more subwebs a site has, the more it risks issues with performance. Support for issues will be unavailable until the site is brought back to the supported size.
