### ISSUE TITLE
SP Designer - F1 Kiosk

### ISSUE THREAD

**Issue by Marweis** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#182]
F1 Kiosk license most likely will not work with SP Designer, same as Office clients, and InfoPath. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b12fdba4-247d-f00c-7f1c-c083787384a2
* Version Independent ID: 9198e021-3d19-3839-e394-f209142e343f
* Content: [SharePoint Online Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@Marweis Thanks for your feedback! I'm forwarding this to the product group and will update the service description based on their feedback.

**Comment by SharS** [comment]
@Marweis I confirmed with the product team that SP Designer will not work with an F1 license. Thanks!
