### ISSUE TITLE
Should read: Non-GCC High Tenant C

### ISSUE THREAD

**Issue by scottyv** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#183]
Under "Other Examples:" the 2nd bullet point says:
"Non-GCC tenant C can share with GCC High tenant A or B, and A or B users sign in using one-time passcodes."

It should say:
"Non-GCC High tenant C can share with GCC High tenant A or B, and A or B users sign in using one-time passcodes".

Since the 3rd bullet point says:
"GCC High tenant A or B can share with Non-GCC High tenant C, and C users sign in using one-time passcodes.".

**Comment by SharS** [comment]
@scottyv Thanks for your feedback! I'll follow up with the product team and update the topic (depending on their approval).
