### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by markgort86** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#184]
The link after "New Office 365 admin tools" is broken. This hyperlink is visible twice on the page. The correct one could be the following page: 
https://www.microsoft.com/en-us/microsoft-365/blog/2014/07/29/new-office-365-admin-tools/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76358610-0b3b-49d9-6e6a-0b334b19d795
* Version Independent ID: 66466964-caa5-cded-20a6-627495521904
* Content: [Service Health and Continuity](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/service-health-and-continuity#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/service-health-and-continuity.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/service-health-and-continuity.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@markgort86 Thanks for your feedback! I've corrected the links and submitted the topic for publication.

**Comment by markgort86** [comment]
@SharS you're welcome! Thanks
