### ISSUE TITLE
Repeated plans in O365 ATP

### ISSUE THREAD

**Issue by AndySanchezVM** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#185]
In the section "Which users benefit from the service?" under Office 365 Advanced Threat Protection, the Microsoft 365 E5/A5/G5 plans are listed twice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 Tenant-Level Services Licensing Guidance](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@AndySanchezVM Thanks for your feedback! The topic lists Microsoft 365 35/A5/G5 and Microsoft 365 E5/A5/G5 Security, which is a different license.

**Comment by AndySanchezVM** [comment]
I understand they are 2 plans, but it should read like this:

Licensed users of Office 365 E5/A5/G5, Microsoft 365 E3/A3/G3, Microsoft 365 E5/A5/G5 Security, Microsoft 365 Business, and Office 365 ATP Plans 1 and 2 can benefit from ATP.
