### ISSUE TITLE
Ink Editor is not supported in Word for the Web

### ISSUE THREAD

**Issue by DanParish** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#186]
In the Word for the Web section ([link](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-online-service-description/word-online)) Ink Editor is mentioned as a feature. That is not available in Word for the Web and so that section should be removed.

**Comment by SharS** [comment]
@DanParish Thanks for your feedback! I've contacted the product team and will update the document as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi Dan!  Sorry for the delay on this, but we've updated the service description to reflect this.  I'll be closing this.
