### ISSUE TITLE
File upload limits

### ISSUE THREAD

**Issue by CaseyRoot** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#187]
Just to confirm - the file upload limit on SharePoint Online and OneDrive is 15 GB - is that correct?  I am asking because I read somewhere else it was 10 GB.  Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits?redirectSourcePath=%252fen-us%252farticle%252fSharePoint-Online-software-boundaries-and-limits-8f34ff47-b749-408b-abc0-b605e1f6d498)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@CaseyRoot Thanks for your feedback! I'll contact the product team to get you an answer, and depending on their response, update the service description.

**Comment by SharS** [comment]
@CaseyRoot I confirmed with the product team that 15 GB is the correct limit. 10 is obsolete.
