### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Hiyatei** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#188]
Link for Privacy section "For specific steps Enterprise, Business, Government, and Education admins can take to configure Office 365 privacy settings, see Advanced Privacy Options for Administrators." is broken. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3f9b0e1-31b0-1497-10fe-cc8284b42d22
* Version Independent ID: 8d5fa25c-b311-b072-8207-532ccc9109af
* Content: [Privacy, Security, and Transparency](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/privacy-security-and-transparency#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/privacy-security-and-transparency.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/privacy-security-and-transparency.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@Hiyatei Thanks for your feedback. I've contacted the product team about a replacement link, and will update the article based on their feedback.

**Comment by SharS** [comment]
@Hiyatei I tested the link and it's now fixed.
