### ISSUE TITLE
Transport rule limits

### ISSUE THREAD

**Issue by ohicur12** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#189]
While the transport rule limits are very clearly outlined, how do you confirm what the current size is of all transport rules. Also, what happens when you exceed the limit? Does the last rule that exceeded the limit simply not work or save correctly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#feedback)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@ohicur12 Thanks for your feedback. I've checked with the product team, and received this answer: We don’t have a built in mechanism to determine size of all transport rules, and we do not enforce any limits in the system relating to *total* size of rules. Our limits are published [here](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#journal-transport-and-inbox-rule-limits-across-office-365-options).
