### ISSUE TITLE
Broken Note Tag

### ISSUE THREAD

**Issue by Weishaupt** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#19]
Under the heading of Exchange Online Archiving plans the Note which mentiones which plans already include EOA doesn't render corrently.

![grafik](https://user-images.githubusercontent.com/2642714/48414234-6dc4a480-e74a-11e8-86e0-afe1d5ef3760.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6177b1e-b721-39ea-25fb-0b6406cf8714
* Version Independent ID: 69864654-33a2-2669-2926-82c0433b3515
* Content: [Exchange Online Archiving Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description)
* Content Source: [Office365-ServiceDescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by SKjerland** [comment]
@Weishaupt -Thanks for bringing this to our attention. I fixed the formatting of the note.
