### ISSUE TITLE
What do you actually mean by "including 5,000 items per team site"?

### ISSUE THREAD

**Issue by chanmmn** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#190]
What do you actually mean by "including 5,000 items per team site" at the sync limit pint in your article?

**Comment by SharS** [comment]
Here's the clarification (from [Restrictions and limitations when you sync SharePoint libraries to your computer through OneDrive for Business](https://support.office.com/en-us/article/14fdf1b3-61e5-49cd-a9e1-a66588505b4e): 

You can sync up to 20,000 items total across all synchronized libraries. This includes OneDrive for Business libraries, Team Site libraries, or both. This includes folders and files. Separately from the overall sync limit, there are limits to the number of items that can be synchronized for each library type.
•	You can sync up to 20,000 items in a OneDrive for Business library. This includes folders and files.
•	You can sync up to 5,000 items in a SharePoint library. This includes folders and files. These are libraries that you find on various SharePoint sites, such as team sites and community sites, libraries that other people created, or that you created from your Sites page. You can sync multiple SharePoint libraries. Any team sites that you sync will also count against the overall 20,000 item limit across all synchronized libraries.

Note that these limits are for the previous sync client (groove.exe). I'm adding this information to the service description.
