### ISSUE TITLE
Soft-deleted mailbox period

### ISSUE THREAD

**Issue by RSEEGATZ** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#193]
How long stays a deleted mailbox in the state "soft-deleted". 
Can this period be customized?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#retention-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@RSEEGATZ Thanks for your feedback! I've forwarded your questions to the product team, and I'll update the topic if necessary based on their feedback.

**Comment by SharS** [comment]
@RSEEGATZ Please refer to [Delete or restore user mailboxes in Exchange Online](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/delete-or-restore-mailboxes). Retention period is 30 days unless there is a hold on the account, in which case it's indefinite. This is not customizable.
