### ISSUE TITLE
Response time vs Initial response time.

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#194]
"Initial response time is based on the severity levels described above and the type of Office 365 subscription. The response time objectives are described in the following table."

What is the response time for replies after the initial response? Are they different for the different support plans and severity levels?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4bab1e0-b326-22fd-d1b8-23780e0720d3
* Version Independent ID: bf81479e-1ed7-d465-a72b-bb425c757411
* Content: [Support](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/support)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/support.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/support.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@jonwbstr Thanks for your feedback! I've forwarded your questions to the product team and I'll update the service description if necessary based on their feedback.

**Comment by SharS** [comment]
@jonwebstr The answer I received was “Once Support defines the scope with the customer, we set expectations around the next status update. To my knowledge there is nothing in the Premier contracts other than initial response that would indicate timelines around follow ups.”
