### ISSUE TITLE
Modern

### ISSUE THREAD

**Issue by BeVoK** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#195]
No mention of Modern Pages, Modern Sites, Modern Lists and Libraries.
This says Hub sites not supported in SP Online, but it is now supported

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b12fdba4-247d-f00c-7f1c-c083787384a2
* Version Independent ID: 9198e021-3d19-3839-e394-f209142e343f
* Content: [SharePoint Online Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@BeVok Thanks for your feedback! I've contacted the product team, and I will update the service description if necessary, based on their response.

**Comment by SKjerland** [comment]
@BeVoK - Our SharePoint writer updated the article. Thanks!
