### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by Raffatronic** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#196]
The whole page is outdated, Dynamics 365 Plan 1 or 2 do not exist anymore. 
Dynamics 365 licensing changed dramatically in August: 
- No more plans are available

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ed4ff2c-ddfd-d1d1-d2ca-b017baafd4de
* Version Independent ID: 699a5024-dcb2-4c23-f12b-5b1b3808171f
* Content: [Microsoft Dynamics 365 (online) Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-dynamics-365-online-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/microsoft-dynamics-365-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-dynamics-365-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by RaduNegulescuMS** [comment]
Do we have any news regarding the updates on this page?

**Comment by aaronlemieux** [comment]
This page has been updated.  Thank you.
