### ISSUE TITLE
Missing Teams Service Description

### ISSUE THREAD

**Issue by scossio** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#197]
I see an issue was opened and closed in April for this but I think it's a glaring omission not to have a Teams service description linked on this page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7be38c7b-125f-fff6-ae80-741132b05ca8
* Version Independent ID: 2b28c809-3413-982b-dbfb-d2bfbcbd4723
* Content: [Office 365 Service Descriptions ](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-service-descriptions-technet-library)
* Content Source: [Office365-ServiceDescriptions/office-365-service-descriptions-technet-library.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-service-descriptions-technet-library.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
Thanks for your feedback.  I passed your request on to the Teams team for consideration.

**Comment by lhcole** [comment]
@scossio The Microsoft Teams service description is live: https://docs.microsoft.com/en-us/Office365/ServiceDescriptions/teams-service-description Thanks again for your feedback.
