### ISSUE TITLE
Question about available features

### ISSUE THREAD

**Issue by DFLiddle** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#199]
I arrived at this page from this one:

Microsoft 365 Business Frequently Asked Questions
https://docs.microsoft.com/en-us/microsoft-365/business/support/microsoft-365-business-faqs

which is linked from this section:

Does Azure Active Directory Premium P1 come with Microsoft 365 Business?
Microsoft 365 Business is built on technology from across Microsoft and while it shares some features with Azure Active Directory, it is not a full version. The security and management policies created in Microsoft 365 Business rely on some Azure functionality but does not include all features (e.g. self-service features, conditional access features, and reporting). Customers may choose to purchase Azure Active Directory Premium P1 or P2 as an add-on to Microsoft 365 Business. Please see the Microsoft 365 Business Service Description for more information.

One of the main reasons why our organization has subscriptions to Enterprise Mobility + Security E3 is that we wish to employ group naming policies as described here:

Office 365 Groups naming policy
https://docs.microsoft.com/en-us/office365/admin/create-groups/groups-naming-policy

It works as advertised and ensures that user-created groups are clearly identified. Super. What I'm interested to know is if this ability is one of those that IS or IS NOT included with Microsoft 365 Business. If it is, then I will be able to change my license array to one that is more appropriate to our needs. Thank you for your help!

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94c91b3d-d9b1-9056-ae3e-51a255ed88ec
* Version Independent ID: b60613bc-f7b3-d1c7-4d8e-924c0f87912f
* Content: [Microsoft 365 Business Service Description](https://docs.microsoft.com/en-gb/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@DFLiddle Thanks for your feedback! I've reached out to the product team, and I'll update the service description as necessary based on their response.

**Comment by SharS** [comment]
@DFLiddle Here is the response from the product team: 

Group Naming Policy is an Azure AD P1 feature and not part of Azure AD Office 365.

Microsoft 365 Business includes only the following three features from AAD P1:

- Self-service password reset for hybrid Azure
- Multi-Factor-Authentication
- Conditional Access

Microsoft 365 Business does not include Group Naming Policy.

I hope this is helpful.
