### ISSUE TITLE
Wrong Link

### ISSUE THREAD

**Issue by Weishaupt** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#20]
The link [Archive mailboxes in Exchange Online](https://go.microsoft.com/fwlink/p/?LinkId=404421) actually resolves to the Exchange EOP Overview, which is unexpected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6177b1e-b721-39ea-25fb-0b6406cf8714
* Version Independent ID: 69864654-33a2-2669-2926-82c0433b3515
* Content: [Exchange Online Archiving Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description)
* Content Source: [Office365-ServiceDescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by prabita** [comment]
@Weishaupt Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response

**Comment by prabita** [comment]
@Weishaupt updated the link, the page will be live in 24 hrs.
