### ISSUE TITLE
F1 License Archive

### ISSUE THREAD

**Issue by aizatharis** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#200]
Hello. What is the up to date storage size for Exchange Online Archive for F1 license? It says in the doc that it is not available. But when I test with my tenant, I can enable the in-place archive and the size is 100GB. In another Microsoft doc, Exchange Online Archive is available as add on for F1 license. Not sure which one is correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#mailbox-storage-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@aizatharis Thanks for your feedback! I've reached out to the product team, and I'll update the service description as necessary based on their response.

**Comment by Jopoe** [comment]
regarding O365 E1, archive storage is listed as 50GB.


E1 has EXO P1 (per this- https://docs.microsoft.com/en-us/Office365/ServiceDescriptions/opbuildpdf/TOC.pdf?branch=live) , and per this ( https://docs.microsoft.com/en-us/microsoft-365/compliance/unlimited-archiving/ ) that would make E1 have unlimited archive storage. 

can you correct this in the storage limits table above ? ( table - https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#storage-limits-across-office-365-options )

**Comment by SharS** [comment]
@Jopoe I heard back from the product team, and the service description is correct. (The licensing may not be enforced in this case.)
