### ISSUE TITLE
Reset time of 10 000 recipients per day limit 

### ISSUE THREAD

**Issue by strumpfonja** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#201]
Hi,
does anyone know when exactly 10 000 recipients per day limit reset its counter? is it in 00.00h? or any other time ?

**Comment by SharS** [comment]
@strumpfonja Thanks for your feedback! I've reached out to the product team, and I'll update the service description as necessary based on their response.

**Comment by SharS** [comment]
@strumpfonja I heard back from the product team, and the answer is that it's a rolling 24-hour window. When the limit is reached, messages can't be sent from the mailbox until the number of recipients that were sent messages in the past 24 hour drops below the limit.
