### ISSUE TITLE
Feature availability across Advanced Threat Protection (ATP) plans clarification

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#202]
Where in the Feature availibility matrix are the alert policies under the security center covered? Looking over the features described, I see a reference to the "Threat Management" section of the security center, but having trouble spotting anything related to the "Alert" section having more alert policies with P2 than P1.

The article below clearly outlines certain "default policies" which are only available with ATP P2 such as, 
"A potentially malicious URL click was detected"

Alert policies in the security and compliance center
https://docs.microsoft.com/en-us/office365/securitycompliance/alert-policies

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 502796e9-ca73-7123-7719-c7b5b1042b7b
* Version Independent ID: 2929af88-6d56-4de3-2b4e-4e1d0e4d97ef
* Content: [Office 365 Advanced Threat Protection Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description)
* Content Source: [Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by jonwbstr** [comment]
The Alert policies page makes multiple references to integration with "automated investigation and response" so I'm guessing these new Default policies, and the ability to specify thresholds are tied to that feature. When first looking over the feature matrix I didn't realize the ability to set thersholds and the default policies were only available in P2. Had to do a double take when I found them missing and dug into it further from the "alert policies" direction.

https://products.office.com/en-US/exchange/advance-threat-protection#pmg-allup-content

It would be very useful to talk about the ability to set thresholds and receive additional default policies with O365 ATP P2.

**Comment by SharS** [comment]
@jonwbstr Thanks for your feedback! I've reached out to the product team, and I'll update the service description as necessary based on their response.

**Comment by SharS** [comment]
@jonwbstr You might find the information you're looking for in this [article](https://docs.microsoft.com/en-us/office365/securitycompliance/automated-investigation-response-office).
