### ISSUE TITLE
Does M365 A5 for Education include Attack Simulator

### ISSUE THREAD

**Issue by slrattan** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#203]
Hi, Does M365 A5 for Education include Attack Simulator? M365 A5 includes Advanced Threat Protection however the A5 doesn't have a column in the features list ??
Thank you
Shannon

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 502796e9-ca73-7123-7719-c7b5b1042b7b
* Version Independent ID: 2929af88-6d56-4de3-2b4e-4e1d0e4d97ef
* Content: [Office 365 Advanced Threat Protection Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@slrattan Thanks for your feedback! I'll contact the product team to see about adding A5 to the features table.

**Comment by SharS** [comment]
@slrattan Thanks for your feedback! I've contacted the product team and will update the service description as necessary, based on their input.

**Comment by SharS** [comment]
@slrattan I heard back from the product team, and Attack Simulator is only available in E5 and ATP Plan 2.
