### ISSUE TITLE
Inconsistency on DLP Section

### ISSUE THREAD

**Issue by thewrabbit** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#204]
https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-education lists DLP as being available on all education plans A1/3/5. 

However https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance#data-loss-prevention-for-exchange-online-sharepoint-online-and-onedrive-for-business states "Licensed users of Office 365 E3/A3/G3, Microsoft 365 Business, Microsoft 365 E3/A3/G3, and Office 365 Data Loss Prevention can benefit from DLP for Exchange Online, SharePoint Online, and OneDrive for Business."  There's an inconsistency between the two documents.  Could this be clarified please?

The same inconsistency is in the [Microsoft Teams](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance#data-loss-prevention-for-teams-chat-and-channel-messages) section.

**Comment by SharS** [comment]
@thewrabbit Thanks for your feedback! I'll follow up with the product team to resolve this inconsistency.

**Comment by SharS** [comment]
@thewrabbit I've corrected the DLP reference in the DLP section. However, the Teams section is currently correct. DLP for Teams chat and channel messages is an Advanced Compliance feature that requires A5/E5/G5.
