### ISSUE TITLE
OneDrive Sync section is inncorrect

### ISSUE THREAD

**Issue by dfernandezcao** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#205]
Above it states all users of OneDrive are able to use the sync client. This isn't correct. F1 users are not able to sync their libraries using the OneDrive client. This is taken from the SharePoint service description page: 

2 Firstline workers have limited OneDrive for Business functionality. Firstline workers receive 2GB of storage and lack desktop sync capabilities. Firstline accounts do not include a OneDrive for Business Personal Site, so they do not benefit from a OneDrive for Business personal library with 1 TB or 5 TB of online storage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99ce1810-18cd-687b-0c8b-bfceb919225a
* Version Independent ID: 705cde78-7e58-c260-bde3-0b393747cdea
* Content: [OneDrive for Business Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/onedrive-for-business-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/onedrive-for-business-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/onedrive-for-business-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@dfernandezcao  Thanks for your feedback! I've contacted the product team about this issue and will update the service description based on their feedback.

**Comment by SharS** [comment]
@dfernandezcao I heard back from the product team, and the SharePoint Service Description was incorrect. It has been updated. (You should see the correction online soon.)

**Comment by spivonious** [comment]
This has not been addressed. It still states that all OneDrive for Business users can use the sync client.
