### ISSUE TITLE
Mailbox mysteriously full/ ErrorQuotaExceeded - 'Cannot save changes made to an item to store.'

### ISSUE THREAD

**Issue by projdako** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#207]
If you count the space used up for mails, you come to roughly 550MB, but the mailbox has 4.8 GB used up.

![image](https://user-images.githubusercontent.com/3427900/65272743-f5740000-db1f-11e9-921d-49fbbbf702fb.png)

We are trying to get delta states through the graph api and are getting:
'code': 'ErrorQuotaExceeded', 'message': 'Cannot save changes made to an item to store.'

We can not find any help for this. 
How can we clean the mailbox?  (Ideally through the api.)
Why is it full? (It seems to be full through the usage of the Graph Delta calls)

Thanks

**Comment by SharS** [comment]
I'm sorry that you're having this issue. For Support options, see [Support](https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/support).
