### ISSUE TITLE
Is Azure AD Password Protection included?

### ISSUE THREAD

**Issue by ziesemer** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#208]
Please clarify as to if Azure AD Password Protection for Windows Server Active Directory is included or not - given that M365 Business includes only a subset of Azure AD Premium...

See also: https://docs.microsoft.com/en-us/azure/active-directory/authentication/concept-password-ban-bad#license-requirements

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94c91b3d-d9b1-9056-ae3e-51a255ed88ec
* Version Independent ID: b60613bc-f7b3-d1c7-4d8e-924c0f87912f
* Content: [Microsoft 365 Business Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@ziesemer Thanks for your feedback! I've forwarded your question to the product team, and I'll update the article if necessary, based on their feedback.

**Comment by SharS** [comment]
@ziesemer Just heard back from the product team, and the answer is no. That feature is only available in AAD Plan 1 or 2, and neither is included in Microsoft 365 Business.

**Comment by adamehale** [comment]
I'm unsure if this will re-open the question...

Since M365 Business is now getting a full feature of P1 in it, will it now include Password Protection?
