### ISSUE TITLE
clarify sharing experience at library and site level

### ISSUE THREAD

**Issue by Marweis** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#209]
Article is great for item sharing but should address sharing at other levels.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c907526-4061-94b4-f2fd-d6fca90344bb
* Version Independent ID: 82e89c18-8d6e-bbb1-f6d0-6ec091d1556e
* Content: [Office 365 GCC High and DoD](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod.md)
* Service: **o365-administration**
* GitHub Login: @danarl
* Microsoft Alias: **danarl**

**Comment by SharS** [comment]
@Marweis Thanks for your feedback. I'll contact the product team about adding the information you suggested and update the article if necessary, based on their response.

**Comment by SharS** [comment]
@Marweis The product team commented that there isn't enough information to determine what you're looking for. Can you provide some clarification? Thanks!

**Comment by Marweis** [comment]
The article outlines GCC high can use modern sharing to share documents externally and gives example on if the share operation is to another GCC high tenant or non-GCC high tenant.  This article should also describe external sharing at the library and site level. Currently, I don’t think GCC high can share a library or a site with other tenants (unless it works only GCC to GCC).

**Comment by aaronlemieux** [comment]
Hi, I have spoken with the product team and this article currently states:  "Users in GCC-High are currently unable to share with users in Non-GCC High organizations."
