### ISSUE TITLE
Hyperlink not working

### ISSUE THREAD

**Issue by NickBazinga** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#21]
Hyperlink for "License requirements for Personal Archive and retention policies " doesn't work and it takes to a page which states ," Sorry, the page you’re looking for can’t be found."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d57bfe9-67d3-4916-4849-609fcf46068c
* Version Independent ID: f5736192-b3c7-f37b-6395-a26a1e85d7bd
* Content: [Client Features in Exchange Online Archiving](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-archiving-service-description/client-features)
* Content Source: [Office365-ServiceDescriptions/exchange-online-archiving-service-description/client-features.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-archiving-service-description/client-features.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by prabita** [comment]
@NickBazinga Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response

**Comment by MarkBratton** [comment]
Any further info on this @prabita?

**Comment by prabita** [comment]
@NickBazinga - Waiting for confirmation but think this is the information you are looking for:
https://support.office.com/en-us/article/Outlook-license-requirements-for-Exchange-features-46B6B7C5-C3CA-43E5-8424-1E2807917C99

**Comment by prabita** [comment]
Article updated and published.
