### ISSUE TITLE
Retention policies

### ISSUE THREAD

**Issue by teomonda** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#211]
How come retention policies are included with SharePoint and Exchange plan 1 but not with Business premium for instance, that does include these plans?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 663a603e-482b-0a4f-55a9-229ceab11bb1
* Version Independent ID: 488b1daa-b459-c56d-11eb-59242af822b0
* Content: [Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center?redirectedfrom=MSDN#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@teomonda Thanks for your feedback. I've reached out to the product team to get you an answer, and I'll revise the service description if necessary, based on their input.

**Comment by Mike-Crowley** [comment]
Per this link, the above table is wrong, and E3 DOES NOT include retention policies. [https://github.com/MicrosoftDocs/microsoft-365-docs/issues/537](https://github.com/MicrosoftDocs/microsoft-365-docs/issues/537)

**Comment by SharS** [comment]
@Mike-Crowley I heard back from the product team and they indicated that the Security & Compliance Center service description document is correct.

**Comment by Mike-Crowley** [comment]
Can you please sync up with the content people on the other page? obviously end-customers can't be forced to choose between two opposing Microsoft articles.

**Comment by bkeski** [comment]
Business Essentials and Business Premium does include Onedrive/sharepoint retention - I have tested it... So table is wrong. Essentials and Premium does not include email retention (litigation hold).
