### ISSUE TITLE
Specifications & Limitations

### ISSUE THREAD

**Issue by Ronsss** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#212]
We need pages with specifications and limitations for these online applications equivalent to this page:
https://docs.microsoft.com/en-us/office/troubleshoot/word/operating-parameter-limitation.

Or even just add this information to that page and include a link from this set of pages to that one.

I have seen a message from Excel online saying there is a 5 MB file size limit. Other have reported unspecified size limits in Word Online. One non MS page says Word online has 50MB limit, another says 100MB.  What does MS say for all of the online &lt;cr&gt;applets? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03c6bd97-32d7-11be-e5ff-52b37aaa638c
* Version Independent ID: 8c688d43-0be9-7e68-4d08-cbb8fa5fba11
* Content: [Word for the web](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-online-service-description/word-online#feedback)
* Content Source: [Office365-ServiceDescriptions/office-online-service-description/word-online.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-online-service-description/word-online.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@Ronsss Thanks for your feedback! I've forwarded your request to the product team, and I'll update the service description, if necessary, based on their response.

**Comment by aaronlemieux** [comment]
Hi Ronsss! Sorry for the delay on this, but we've updated the service description to reflect this. I'll be closing this.
