### ISSUE TITLE
Microsoft project Online Task API doesn't return custom fields

### ISSUE THREAD

**Issue by kmanmeet** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#213]
I am using Odata url for Micorsoft project Online using following url http://<pwa_site>/_api/ProjectData/Projects(guid'<GUID here>')/Tasks

The dataset doesn't return all the Custom fields such as flag1...flag 10 and text 1 ...text 10,  Custom fields.  Do we need to use some other URL for that? Please advise

**Comment by SharS** [comment]
I'm sorry that you're having this issue. For Support options, see [Support](https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/support).
