### ISSUE TITLE
limit on number of users

### ISSUE THREAD

**Issue by ryangugcloudca** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#215]
Is there any limit on number of users who use Sharepoint Online service of Office 360 for Education?

**Comment by SharS** [comment]
@ryangugcloudca Thanks for your feedback! I've forwarded your question to the product team, and I'll update the service description (if necessary) based on their feedback.

**Comment by SharS** [comment]
@ryangugcloudca Product team response: we don’t put caps on how many Office 365 Education licenses can be sold, so any user who qualifies for and gets an Office 365 Education license would get SharePoint as part of that license.
