### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by dariomws306** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#216]
“Resource mailboxes don't require a license. However, without a license, shared mailboxes are limited to 50 GB” should be “Resource mailboxes don't require a license. However, without a license, resource mailboxes are limited to 50 GB”

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@dariomws306 Thanks for your feedback! I've contacted the product team and I'll update the service description (if necessary) based on their feedback.

**Comment by SharS** [comment]
@dariomws306 I confirmed the change with the product team and updated the document. You should see the revision online later today.
