### ISSUE TITLE
Table Size

### ISSUE THREAD

**Issue by AlexC84** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#217]
The table is too wide for the view port provided hence the horizontal scroll bar at the bottom of the table. However, the table is also so long that you have to scroll the page down to the bottom for the horizontal scroll bar to the point that you can no longer see the table headers for reference when adjusting the horizontal scroll position.

Suggestion:
Have a horizontal scroll bar at the top and bottom and also pin the header row so it's always present when scrolling down the table

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61b8fbc9-7314-1e82-7c85-f0f9d3c3c1fd
* Version Independent ID: 7a5944ad-e785-5711-0954-f2be068e79d1
* Content: [Office Applications Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-applications-service-description/office-applications-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/office-applications-service-description/office-applications-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-applications-service-description/office-applications-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@AlexC84 Thanks for your feedback! I've forwarded your suggestion to the people responsible for the documentation format.

**Comment by SharS** [comment]
@AlexC84 I've confirmed that due to the limitations of our publishing platform, we can't add another horizontal scrolling bar at the top of the article or pin the headings row.
