### ISSUE TITLE
What version of Azure Active Directory is included?

### ISSUE THREAD

**Issue by xhoy** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#219]
Its unclear what version of Azure Active Directory is included. There seems to be reference to AAD Basic but that product is no longer listed on the Azure page. https://azure.microsoft.com/nl-nl/pricing/details/active-directory/

Is AAD free? aad 365? aad p1 or aad p2 included?

With kind regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94c91b3d-d9b1-9056-ae3e-51a255ed88ec
* Version Independent ID: b60613bc-f7b3-d1c7-4d8e-924c0f87912f
* Content: [Microsoft 365 Business Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@xhoy Thanks for your feedback. We have just published an update to this service description which should clarify this for you.
