### ISSUE TITLE
The "New Office 365 admin tools" link is broken

### ISSUE THREAD

**Issue by Lexie1919** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#220]
Right link should be https://www.microsoft.com/en-us/microsoft-365/blog/2014/07/29/new-office-365-admin-tools/  (instead of en-au, the one on the page is broken, there are 2 of them )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76358610-0b3b-49d9-6e6a-0b334b19d795
* Version Independent ID: 66466964-caa5-cded-20a6-627495521904
* Content: [Service Health and Continuity](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/service-health-and-continuity?redirectedfrom=MSDN#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/service-health-and-continuity.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/service-health-and-continuity.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@Lexie1919 Thanks for your feedback. I've checked the links and they are correct. (The links in the source don't specify a locale, so I don't know why you are linking to en-au.)
