### ISSUE TITLE
Incorrect value "File attachment size limit - OWA"

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#221]
Just tested, you can add an attachments with 100MB file size.

Please update section "File attachment size limit - OWA 6"

**Comment by SharS** [comment]
@trudolf-msft Thanks for your feedback. Which service description article contains this limit?

**Comment by trudolf-msft** [comment]
https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#message-limits
________________________________

**Comment by SharS** [comment]
@trudolf-msft Thanks. I'll forward this information to the product team and update the service description if necessary based on their response.

**Comment by SharS** [comment]
@trudolf-msft I heard back from the product team. "Local" files have a limit of 35 MB, but OneDrive files (cloud docs) can be up to 2 GB.

**Comment by trudolf-msft** [comment]
Hi Sharon,

Sorry, but this isn’t right!

When I’m attaching a 125MB file OWA brings up a popup (selected option 2) and…
[cid:image003.jpg@01D594F4.DA93FB80]

…it works (local file of 125MB size attached):
[cid:image005.jpg@01D594F4.DA93FB80]


PS C:\ > Get-MessageTrace -SenderAddress test@rud.onmicrosoft.com -StartDate 2019-11-06 -EndDate 2019-11-07 | fl
Message Trace ID  : 9d6d6617-1720-4d79-ea73-08d76302d218
Message ID        : <AM0PR03MB446589DFD23D38D57F2273BB9B790@AM0PR03MB4465.eurprd03.prod.outlook.com>
Received          : 06.11.2019 21:46:46
Sender Address    : test@rud.onmicrosoft.com
Recipient Address : test@rud.onmicrosoft.com
From IP           : 195.145.168.66
To IP             :
Subject           : Test 125MB
Status            : Delivered
Size              : 131084582

Please double-check with PG.
In case you need any details feel free to contact me.

Kind regards,
Thomas

**Comment by trudolf-msft** [comment]
@Amir Haque<mailto:mhaque@microsoft.com> maybe this changed recently?

From: Thomas Rudolf <Thomas.Rudolf@microsoft.com>
Sent: Wednesday, November 6, 2019 4:52 PM
To: MicrosoftDocs/OfficeDocs-O365ServiceDescriptions <reply@reply.github.com>; MicrosoftDocs/OfficeDocs-O365ServiceDescriptions <OfficeDocs-O365ServiceDescriptions@noreply.github.com>
Cc: Mention <mention@noreply.github.com>; Scott Landry <Scott.Landry@microsoft.com>
Subject: RE: [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions] Incorrect value "File attachment size limit - OWA" (#221)

Hi Sharon,

Sorry, but this isn't right!

When I'm attaching a 125MB file OWA brings up a popup (selected option 2) and...
[cid:image001.jpg@01D59972.6E043A70]

...it works (local file of 125MB size attached):
[cid:image002.jpg@01D59972.6E043A70]


PS C:\ > Get-MessageTrace -SenderAddress test@rud.onmicrosoft.com<mailto:test@rud.onmicrosoft.com> -StartDate 2019-11-06 -EndDate 2019-11-07 | fl
Message Trace ID  : 9d6d6617-1720-4d79-ea73-08d76302d218
Message ID        : <AM0PR03MB446589DFD23D38D57F2273BB9B790@AM0PR03MB4465.eurprd03.prod.outlook.com<mailto:AM0PR03MB446589DFD23D38D57F2273BB9B790@AM0PR03MB4465.eurprd03.prod.outlook.com>>
Received          : 06.11.2019 21:46:46
Sender Address    : test@rud.onmicrosoft.com<mailto:test@rud.onmicrosoft.com>
Recipient Address : test@rud.onmicrosoft.com<mailto:test@rud.onmicrosoft.com>
From IP           : 195.145.168.66
To IP             :
Subject           : Test 125MB
Status            : Delivered
Size              : 131084582

Please double-check with PG.
In case you need any details feel free to contact me.

Kind regards,
Thomas

**Comment by SharS** [comment]
@trudolf-msft Thanks for your response. I'll try to track this down.

**Comment by SharS** [comment]
@trudolf-msft We've resolved this issue and I've updated the article to include the correct values (112 MB). The updated article will be available online soon.
