### ISSUE TITLE
Are the statements valid for Office 365 F1?

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#222]
Are the following statements valid after license changes about PowerApps and Flow.

https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-platform-service-description

_13 In Office 365 Enterprise F1, PowerApps is limited to consumption only (no publishing or sharing).
14 In Office 365 Enterprise F1, Flow is limited to consumption only and runs are limited to 750 per user per month._

About flow, I've already confirmed that two of Flow’s plan-based limits are being removed due to MC189143.
- 15-minute maximum flow frequency 
- 750 maximum runs per user, per month   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8f41cb0-4ad7-f25c-6586-fe89e8fca92d
* Version Independent ID: 9354cc15-1341-a4e1-4844-83a1f26ee149
* Content: [Office 365 Platform Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-platform-service-description)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@kemiyaza Thanks for your feedback! I've reached out to the product team, and I'll update the article if necessary, based on their response.

**Comment by aaronlemieux** [comment]
These items have been removed from this SD.  Thank you.  I will be closing this item.
