### ISSUE TITLE
Modern authentication in Exchange Online

### ISSUE THREAD

**Issue by kkazala** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#223]
I think a paragraph in Authentication / Modern authentication section is outdated: "Modern authentication is not turned by default for Exchange Online. To learn how to turn it on, see Enable Exchange Online for modern authentication."

Comparing to https://docs.microsoft.com/en-gb/Exchange/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online, I see "Modern authentication is enabled by default in Exchange Online, Skype for Business Online and SharePoint Online."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b65730b-7010-60f8-0b50-5a6c8a4970bd
* Version Independent ID: e07b0622-0e4f-1883-b045-ca4097b3c333
* Content: [User Account Management](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/user-account-management#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/user-account-management.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/user-account-management.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@kkazala Thanks for your feedback! I confirmed the change and updated the article. You should see the revised version soon.
