### ISSUE TITLE
Flow availability

### ISSUE THREAD

**Issue by rhwood** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#224]
Per the notes for the Flow offering in this document, Flow is not available to GCC High or DOD environments, but is "coming soon".

However, per https://docs.microsoft.com/en-us/flow/us-govt, Flow is available in GCC High. Can you clarify which document is correct and update the incorrect one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e69c139-60fc-5e97-168a-12d7bf1fbd38
* Version Independent ID: bd4edf0e-4a2f-2bf7-92e6-c7e840584977
* Content: [Office 365 US Government](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md)
* Service: **o365-administration**
* GitHub Login: @danarl
* Microsoft Alias: **danarl**

**Comment by SharS** [comment]
@rhwood Thanks for your feedback! I'll contact the product team and correct the appropriate document.

**Comment by SharS** [comment]
@rhwood I've confirmed with the product team that Microsoft Flow is available in GCC High, but not DoD. You should see the updated article soon.
