### ISSUE TITLE
File size limits for workbooks

### ISSUE THREAD

**Issue by v-hyko** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#225]
It seems that the limit for the online office has recently changed from 30MB to 50MB.

Why is the technical document not updated?
Also, can I know when it changed to 50mb?

best regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0d13579-5b95-82bd-4083-1919e38c034f
* Version Independent ID: 4bc5df6e-4168-3a3e-f72b-0aa327a492e8
* Content: [Excel for the web](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-online-service-description/excel-online#feedback)
* Content Source: [Office365-ServiceDescriptions/office-online-service-description/excel-online.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-online-service-description/excel-online.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@v-hyko Thanks for your feedback! I've forwarded your question to the product team, and I'll update the document if necessary based on their response.

**Comment by smittypro** [comment]
The change was for MSIT users only. It has not released to Insiders or production. The feature PM did not know if/when this will ship to GA.

Smitty

**Comment by SharS** [comment]
@v-hyko I heard back from the product team, and this change occurred for MSIT only. It has not been released to Insiders or production.

**Comment by SharS** [comment]
@v-hyko The SharePoint limit note in the service description has been updated to reflect the 50 MB limit. You should see the change online later today.
