### ISSUE TITLE
CALs equivalent

### ISSUE THREAD

**Issue by teomonda** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#226]
we read in the article that
"Office 365 Business Essentials, Office 365 Business Premium, and Office 365 Enterprise F1 do not provide access rights for utilization with on-premises servers. To be compliant, customer must purchase or have previously purchased the appropriate CALs or upgrade to an Enterprise SKU that provides these access rights."

Which makes sense because hybrid does require Enterprise CALs only included with Exchange plan 2 or enterprise plans.
However with exchange plan 1 we have the standard CAL included, so the above statement is inaccurate, Business premium, because it includes Exchange plan 1, does include CALs, just that they only include standard CALs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54cc9525-7b54-4151-ac74-acae805a8f69
* Version Independent ID: 3bb6ba9b-b853-430f-6e88-13d5a20cdaea
* Content: [Exchange Online Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@teomonda Thanks for your feedback! I've contacted the product team for a response and will update the service description if necessary.

**Comment by SharS** [comment]
@teomonda I heard back from the product team, and they are satisfied that the existing text is accurate. Customers who have Business or Enterprise plans do not get EXO P1; they get the technical capabilities that are associated with their service plan.
