### ISSUE TITLE
Azure Information Protection and Microsoft 365 Business

### ISSUE THREAD

**Issue by adrianwells** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#227]
This document indicates AIP is not included with Microsoft 365 Business which contraindicates the information provided on this document &lt;https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description&gt; where it indicates it is included. Please review, correct and updated as needed. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61b8fbc9-7314-1e82-7c85-f0f9d3c3c1fd
* Version Independent ID: 7a5944ad-e785-5711-0954-f2be068e79d1
* Content: [Office Applications Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-applications-service-description/office-applications-service-description)
* Content Source: [Office365-ServiceDescriptions/office-applications-service-description/office-applications-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-applications-service-description/office-applications-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@adrianwells Thanks for your feedback! I've contacted the product team and will update the documents based on their response.

**Comment by SharS** [comment]
@Adrianwells Thanks for your feedback. The two documents you cite are discussing two separate products: Office 365 Business and Microsoft 365 Business. Office 365 Business does not include AIP, while Microsoft 365 Business does include it.

**Comment by adrianwells** [comment]
@SharS Thank you for the reply, however, there is a Microsoft 365 Business column (very last, far right) in the table of this document. Please review again. Thank you.

**Comment by SharS** [comment]
@adrianwells Sorry that I misunderstood your question. I'll contact the product team to sort this out.

**Comment by adrianwells** [comment]
@SharS OK. Thank you.

**Comment by SharS** [comment]
@adrianwells I've updated the Office applications service description. You should see the update online later today.

**Comment by adrianwells** [comment]
@SharS checked the document and there does appear to be a change yet for the "Information Rights Management using Azure Information Protection" row in this document's table. Is that what was updated (I do not see a PR to see what changes were made)?
