### ISSUE TITLE
Storage per user Office 365 Enterprise F1

### ISSUE THREAD

**Issue by pealmasa** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#229]
Storage per user Office 365 Enterprise F1 states: 5GB but actually its 2GB.
See:
https://www.microsoft.com/en-us/microsoft-365/business/office-365-f1?activetab=pivot%3aoverviewtab

"OneDrive for Business gives each user 2GB of personal cloud storage that can be accessed from anywhere, on any device"

**Comment by SharS** [comment]
@pealmasa Thanks for your feedback! I'm contacting the product team to resolve this discrepancy and will update the article if necessary based on their feedback.

**Comment by SharS** [comment]
@pealmasa I've corrected the service description. You should see the changes online soon.

**Comment by pealmasa** [comment]
Perfect! Thanks
