### ISSUE TITLE
URLs and URL fields

### ISSUE THREAD

**Issue by LuigiBruno** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#231]
Add information about the maximum length allowed for URLs and URL fields.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint Online limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits#feedback)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@LuigiBruno Thanks for your feedback. I've contacted the product team and will update the article, if necessary, based on their response.

**Comment by LuigiBruno** [comment]
> @LuigiBruno Thanks for your feedback. I've contacted the product team and will update the article, if necessary, based on their response.

Thank you @SharS.

**Comment by SharS** [comment]
@LuigiBruno I heard back from the product team, and the maximum length of a value stored in a URL (Hyperlink or Picture) field is 255. This information is too granular for inclusion in the service description, however. I hope that's helpful.

**Comment by LuigiBruno** [comment]
> @LuigiBruno I heard back from the product team, and the maximum length of a value stored in a URL (Hyperlink or Picture) field is 255. This information is too granular for inclusion in the service description, however. I hope that's helpful.

Thank you @SharS.
