### ISSUE TITLE
Confirm accuracy of some features?

### ISSUE THREAD

**Issue by dotnick365** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#232]
Please confirm the accuracy of the deployment status of some features. The following features are called out as being "on engineering backlog" but appear to be live within GCC Moderate environment as of November 2019:
- 	Auto application of labels
-      Labels based on sensitive data types
-      Labels and associated policies based on queries
-      File plan
-      Event-based retention
-      Disposition review

Also ... this feature list appears to be missing or does not call out:
- Data Loss Prevention - Exact Data Match
- Label Activity Explorer
- Machine learning based classifiers
- Unified Labeling / Sensitivity Labels

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98a0960a-187c-ae13-7bec-7b883ff2fe1d
* Version Independent ID: 44562132-bd35-501b-f789-befd87164a09
* Content: [Plan for Microsoft 365 compliance - GCC](https://docs.microsoft.com/en-us/Office365/ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/plan-for-m365-compliance-gcc#feedback)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/plan-for-m365-compliance-gcc.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/plan-for-m365-compliance-gcc.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@dotnick365 Thanks for your feedback! I've contacted the product team and will update the article, if necessary, based on their response.

**Comment by SharS** [comment]
@dotnick365 I'm updating the documents. You should see the revised versions online soon.
