### ISSUE TITLE
Clarification around Office ProPlus licensing

### ISSUE THREAD

**Issue by bchris999** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#233]
Can you clarify this statement please? "Office 365 ProPlus is supported on user-dedicated virtual desktop infrastructure (VDI)."
What do you mean by user-dedicated? Does this mean it's not licensed for Windows 10 multi-session OSes (as available through Azure Virtual Desktop)?
Also "Office 365 ProPlus only supports Remote Desktop Services (RDS) when purchased through a Volume Licensing Program." Does this apply to Azure Virtual Desktop too?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61b8fbc9-7314-1e82-7c85-f0f9d3c3c1fd
* Version Independent ID: 7a5944ad-e785-5711-0954-f2be068e79d1
* Content: [Office Applications Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-applications-service-description/office-applications-service-description)
* Content Source: [Office365-ServiceDescriptions/office-applications-service-description/office-applications-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-applications-service-description/office-applications-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@bchris999 Thanks for your feedback. I've contacted the product team and will update the article, if necessary, based on their response.

**Comment by SharS** [comment]
@bchris999 I heard back from the product team. They suggest that you look at the [Multitenant Hosting Rights for Windows 10 page](https://www.microsoft.com/en-us/CloudandHosting/licensing_sca.aspx) to understand the licensing requirements.
