### ISSUE TITLE
Expand upon "It does not include the entirety of Azure AD Premium P1."

### ISSUE THREAD

**Issue by adrianwells** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#234]
Please further expand this statement to help clarify what is and is not included with Microsoft 365 Business in regards to Azure AD Premium P1. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94c91b3d-d9b1-9056-ae3e-51a255ed88ec
* Version Independent ID: b60613bc-f7b3-d1c7-4d8e-924c0f87912f
* Content: [Microsoft 365 Business Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@adrianwells  Thanks for your feedback! I'll follow up with the product team to get the information, and if necessary, update the article based on their response.

**Comment by SharS** [comment]
@adrianwells I've confirmed that self-service password reset with AD write-back, Azure Multi-Factor Authentication (MFA), and Conditional Access are the only P1 features included. I've edited the service description footnote to clarify that information. You should see the updated document online soon.
