### ISSUE TITLE
Office 365 Enterprise F1 Incorrect. The Storage is 2GB and not 5GB

### ISSUE THREAD

**Issue by V-ferest** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#235]
Storage space per user: 5 GB Office 365 Enterprise F1 it's incorrect ( https://docs.microsoft.com/fi-fi/office365/servicedescriptions/onedrive-for-business-service-description )

On https://www.microsoft.com/en-us/microsoft-365/business/office-365-f1?activetab=pivot:overviewtab -> The Storage value is correct

**Comment by SharS** [comment]
@V-ferest Thanks for your feedback! I'm confirming this change with the product team, and I will update the service description as necessary based on their response.

**Comment by SharS** [comment]
@V-ferest I've corrected the service description. You should see the changes online soon.
