### ISSUE TITLE
5 GB Office 365 Enterprise F1

### ISSUE THREAD

**Issue by V-ferest** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#236]
The Storage value for Office 365 Enterprise F1 is incorrect. 
The value should be 2GB, instead of 5GB.
Customer open service request , in order to check if they should have available the 5GB

**Comment by SharS** [comment]
@V-ferest Is this a duplicate of issue #235, or are you referring to a different service description article?

**Comment by V-ferest** [comment]
Sorry. It's an duplicate

**Comment by SharS** [comment]
@v-ferest This has been fixed. You should see the updated service description online soon.
