### ISSUE TITLE
Reference to Note 17 that does not exist

### ISSUE THREAD

**Issue by miguelvidex** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#237]
Intune Mobile Application Management (MAM) for Office apps and LOB apps **17**

![image](https://user-images.githubusercontent.com/26462830/69648976-3595b880-1064-11ea-9507-8abf3fab1158.png)

**Comment by SharS** [comment]
@miguelvidex Thanks for your feedback! I've corrected the footnote reference. You should see the updated article online later today.
