### ISSUE TITLE
Company Feed

### ISSUE THREAD

**Issue by Tomroy-MSFT** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#238]
should the company feed row under site features be replaced/updated to Team News? I am trying to find if there are the same limitations for F1 users regarding Team News site features as the legacy company feed.   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b12fdba4-247d-f00c-7f1c-c083787384a2
* Version Independent ID: 9198e021-3d19-3839-e394-f209142e343f
* Content: [SharePoint Online service description](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@Tomroy-MSFT Thanks for your feedback. I've contacted the product team and will update the service description if necessary based on their response.

**Comment by SKjerland** [comment]
@Tomroy-MSFT - Our SharePoint writer updated the article. Thanks!
