### ISSUE TITLE
Remove Hybrid Auditing

### ISSUE THREAD

**Issue by tseward** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#239]
Hybrid auditing has been removed from the service and needs to be removed from the SharePoint Online Service Description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b12fdba4-247d-f00c-7f1c-c083787384a2
* Version Independent ID: 9198e021-3d19-3839-e394-f209142e343f
* Content: [SharePoint Online service description](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-service-description?source=docs)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@tseward Thanks for your feedback! I've contacted the product team and I'll update the service description if necessary based on their response.

**Comment by SharS** [comment]
@tseward I've confirmed that the setting can be removed. I've updated the service description, and you should see the changes online later today.

**Comment by SharS** [comment]
@tseward I've confirmed that Hybrid Auditing was removed. You should see the updated service description online later today.
