### ISSUE TITLE
What should be my site collections max size as per best practice?

### ISSUE THREAD

**Issue by lovethakker02** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#24]
We have a scenario where we need to migrate on premise content to office 365. But we are not sure how much content we can migrate per site collection. This post do not have any details on it. 
I have googled and found its 200 GB for on premise system. 
https://docs.microsoft.com/en-gb/SharePoint/install/software-boundaries-and-limits#ContentDB

Also, Now as you are providing 25 TB space is there any update on above limits?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by AndySanchezVM** [comment]
Are there any limitations for how many folders within folders within folders (Folderception)?

**Comment by prabita** [comment]
@lovethakker02 Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response

**Comment by kaarins** [comment]
We recommend dividing content based on units of work so that each is its own site collection, and then connecting them into hubs. With this model, you tend to have more (smaller) site collections. There are limits for the migration tool, if that's what you're looking for: https://docs.microsoft.com/en-us/sharepointmigration/sharepoint-online-and-onedrive-migration-speed. I hope this helps.
