### ISSUE TITLE
Technical support for Microsoft Teams

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#240]
The section 'Technical support' mentions Skype for Business. Please add information about Microsoft Teams too, if it's covered as like as Skype.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4bab1e0-b326-22fd-d1b8-23780e0720d3
* Version Independent ID: bf81479e-1ed7-d465-a72b-bb425c757411
* Content: [Support](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/support#feature-availability)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/support.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/support.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@GiantCrocodile Thanks for your feedback! The references to individual products in the Technical Support Categories table are meant to be examples only, not an all-inclusive list.

**Comment by GiantCrocodile** [comment]
I'm aware of this @SharS; this was meant to be more like an update suggestion for the future as Microsoft Teams becomes more and more popular and Skype is being deprecated so it's confusing in the future to see Skype as an example although Teams isn't. This may also increase the visibility of Teams to existing customers.
