### ISSUE TITLE
Clarification on ConfigMgr usage rights

### ISSUE THREAD

**Issue by flippyboy** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#242]
Since ConfigMgr is included with Intune now, could you please include information about ConfigMgr in this article?
According to David James it should be included https://twitter.com/djammmer/status/1199733453954019328. It would however be good to get a clarification on this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94c91b3d-d9b1-9056-ae3e-51a255ed88ec
* Version Independent ID: b60613bc-f7b3-d1c7-4d8e-924c0f87912f
* Content: [Microsoft 365 Business service description](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@flippyboy Thanks for your feedback! I've contacted the product team, and I'll update the service description if necessary, based on their response.

**Comment by SharS** [comment]
@flippyboy The product team got back to me and informed me that the service description is correct. Config Manager is not part of Intune. (Intune is part of Config Manager, not the other way around. The twitter comment is wrong.)
