### ISSUE TITLE
Intune Mobile Device Management (MDM) for PCs, Macs, and mobile devices

### ISSUE THREAD

**Issue by MarcLaf** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#243]
The document says that Office 365 Business Premium should have access to this feature yet it doesn't seem to work (No Access). I believe this is a mistake in the documentation.

On the following page, it says Microsoft Intune is NOT available for Office 365 Business Premium.
https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/licensing-microsoft-365-in-smb 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94c91b3d-d9b1-9056-ae3e-51a255ed88ec
* Version Independent ID: b60613bc-f7b3-d1c7-4d8e-924c0f87912f
* Content: [Microsoft 365 Business service description](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@MarcLaf Thanks for your feedback! I've contacted the product team and I'll update the service description if necessary based on their response.

**Comment by SharS** [comment]
@MarcLaf The product team confirmed that MDM isn't available in Office 365 BP. I've updated the service description, and you should see it online later today. Thanks!
