### ISSUE TITLE
Unclear requirements regarding Azure AD P2 features

### ISSUE THREAD

**Issue by technion** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#244]
Hi,

There are multiple claims online that you can legally license a single administrative user to access the tenancy-wide "risky sign in" feature, including statements from VARs and "licensing experts". I don't feel this document is explicit enough in clarifying this one way or the other. There is an argument that it is only that administrative user who "benefits" or "uses" this report, and indeed there is a paragraph that starts with "SecOps analysts and security professionals benefit ....". A firm statement on this would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 tenant-level services licensing guidance](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-tenantlevel-services-licensing-guidance)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-tenantlevel-services-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-tenantlevel-services-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@technion Thanks for your feedback. I've forwarded your request to the product team, and I'll update the document if necessary based on their response.

**Comment by SharS** [comment]
@technion I heard back from the product team and here's their response: _The sentence after the one referred to states that end users benefit by having their data monitored. Therefore, they would need to license any user whose data is monitored (in addition to the analysts using the reports)._
