### ISSUE TITLE
Supported Clients for Exchange Online

### ISSUE THREAD

**Issue by Weychris** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#246]
This content is above:
For information about which Outlook clients are supported by Exchange 2016 and Exchange Online, see "Supported clients" in Exchange 2016 system requirements.

Exchange 2016 system requirements is a link that goes here (which is now Exchange 2019):
https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/system-requirements?redirectedfrom=MSDN&view=exchserver-2019

I'm just looking for an official document from Microsoft that says which versions of Outlook are compatible with Exchange Online.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4c17dfb-bbbc-51c8-d47e-08a7ab71ccd8
* Version Independent ID: e14e441b-bbab-55e4-dcb2-ccdcdfc48582
* Content: [Clients and mobile devices](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/clients-and-mobile-devices)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/clients-and-mobile-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/clients-and-mobile-devices.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@Weychris Thanks for your feedback! I've forwarded your request to the product team, and I'll update the service description if necessary based on their response.

**Comment by SharS** [comment]
@Weychris I received the following response from the product team and I'm updating the documentation with this information:

For information about which Outlook clients are supported by Exchange 2016 and Exchange Online, see [System Requirements for Office](https://products.office.com/office-system-requirements). 

Office 365 is designed to work with the latest browsers and versions of Office. If you use older browsers and versions of Office that aren't in mainstream support:

- Microsoft won’t deliberately prevent you from connecting to the service, but the quality of your Office 365 experience may diminish over time.
- Microsoft won’t provide software updates to resolve non-security related problems.
