### ISSUE TITLE
Highlight the key differences 

### ISSUE THREAD

**Issue by jebalert** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#247]
There is a reference to differences between Office 365 commercial and GCC/DoD. Would like to see those differences outlined here; via testing and research they become apparent but having them here would save time for sure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c907526-4061-94b4-f2fd-d6fca90344bb
* Version Independent ID: 82e89c18-8d6e-bbb1-f6d0-6ec091d1556e
* Content: [Office 365 GCC High and DoD](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod#feature-nuances-based-on-compliant-cloud-architecture)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod.md)
* Service: **o365-administration**
* GitHub Login: @danarl
* Microsoft Alias: **danarl**

**Comment by SharS** [comment]
@jebalert Thanks for your feedback! I've forwarded your request to the product team, and I'll update the service description if needed based on their response.

**Comment by SharS** [comment]
Here's the response from the product team: <br><br>
For service level parity differences of US Gov cloud versus commercial offerings, customers should use our environment service description page here: [Platform (GCC, GCCH, DoD)](https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government).<br><br>
For any granular feature level differences in product capability differences customers should be referring to the US gov service description pages for those specific products, listed below:<br><br>
| Product | US Gov (GCC, GCCH, DOD) Service Descriptions |
|----|----|
|Office 365 Government Platform | [Platform (GCC, GCCH, DoD)](https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government)|
|Office Applications Service Description | [Office Apps (GCC, GCCH, DoD)](https://docs.microsoft.com/Office365/ServiceDescriptions/office-applications-service-description/office-applications-service-description#office-application-and-feature-availability-in-government-plans) |
|Outlook Mobile | [Outlook Mobile (GCC, GCCH, DoD)](https://docs.microsoft.com/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-in-the-government-cloud)|
|PowerApps | [PowerApps (GCC, GCCH, DoD)](https://docs.microsoft.com/power-platform/admin/powerapps-us-government) |
|Flow | [Flow (GCC, GCCH, DoD)](https://docs.microsoft.com/power-automate/us-govt) |
|Teams | Teams ([GCC](https://docs.microsoft.com/MicrosoftTeams/plan-for-government-gcc), [GCCH](https://docs.microsoft.com/MicrosoftTeams/plan-for-government-gcc-high), [DoD](https://docs.microsoft.com/MicrosoftTeams/plan-for-government-dod)) |
|Compliance | Compliance ([GCC](https://docs.microsoft.com/Office365/ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/plan-for-m365-compliance-gcc), [GCCH](https://docs.microsoft.com/Office365/ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/plan-for-m365-compliance-gcc-high), [DoD](https://docs.microsoft.com/Office365/ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/plan-for-m365-compliance-dod)) |
|Enterprise Mobility + Security | [EMS (GCC, GCCH, DoD](https://docs.microsoft.com/enterprise-mobility-security/solutions/ems-govt-service-description)) |
|Microsoft Defender ATP | [MDATP (GCCH)](https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-atp/commercial-gov) |

**Comment by jebalert** [comment]
This is a great reference, thanks! Recommend including this in the documentation
