### ISSUE TITLE
Further clarifications needed on the limited AAD P1 features bundled with M365 Business, compared to full AAD P1

### ISSUE THREAD

**Issue by felinepc** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#248]
This page is a good start, but we really need a more complete list of differences between Microsoft 365 Business' partial AAD P1 vs. full AAD P1. The official Microsoft AAD pricing and feature comparison page can be seen at:
https://azure.microsoft.com/en-us/pricing/details/active-directory/

On that page, it lists a lot more features not discussed here. Which of them are included, and which are not included with Microsoft 365 Business? It can be important for decision making between the different license bundles.

For example, "Advanced Group Access Management" requires AAD P1. Features like Group creation permission delegation, group naming policies and group expiration can be important for Microsoft Teams deployment. Does Microsoft 365's partial AAD P1 cover these features?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94c91b3d-d9b1-9056-ae3e-51a255ed88ec
* Version Independent ID: b60613bc-f7b3-d1c7-4d8e-924c0f87912f
* Content: [Microsoft 365 Business service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@felinepc Thanks for your feedback! As the service description states, Microsoft 365 Business includes only the following Azure AD Premium P1 features: self-service password reset with AD write-back, Azure Multi-Factor Authentication (MFA), and Conditional Access.

It doesn't include any other P1 features.

**Comment by GrahamYoung05** [comment]
Does Azure AD Premium P1 that comes with Microsoft 365 Business cover Azure Password Protection?

**Comment by JelmerBarhorst** [comment]
Azure Active Directory Premium P1 in Microsoft 365 Business



MC205739, Stay Informed, Publicatiedatum: 6 mrt. 2020


















Grote update: Aankondiging
Van toepassing op: null


We’re thrilled to announce the availability of Azure Active Directory Premium P1 for Microsoft 365 Business subscribers.
We'll be gradually rolling this out in early April and expect to complete the roll-out by the end of June.
 


How does this impact me?

 
Once this update is complete, you will see a new service plan called “Azure Active Directory Premium P1” in the list of plans included with your subscription.  
 


What do I need to do to prepare?

 
Evaluate how Azure active Directory Premium P1 may benefit your organization. Please click the Additional information link to learn more.
