### ISSUE TITLE
SP Online crawl frequencies managed by Microsoft.

### ISSUE THREAD

**Issue by mitul1986** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#249]
Why we dont have more information about crawl frequencies managed by Microsoft. when we open a MS case they say content can take upto 24 hrs to appear in serch results. How MS can keep the coustomer in dark in their documentation.

**Comment by SharS** [comment]
@mitul1986 Thanks for your feedback. I've forwarded your request to the documentation team.
