### ISSUE TITLE
Sharing  Project Web App site between GCC High and outside tenant. 

### ISSUE THREAD

**Issue by calinblouin27** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#250]
If a tenant creates a project web app site with a GCC High account can that project be shared externally to someone with an O365 account that is not GCC High?

**Comment by SharS** [comment]
@calinblouin27 Thanks for your feedback! I've contacted the product team, and I'll update the service description if necessary based on their response.

**Comment by lhcole** [comment]
@calinblouin27 The product team advises opening a support case from your tenant to ensure that your issue is tracked and managed correctly. For Support options, see [Support](https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/support).
