### ISSUE TITLE
Cross reference to Help article for Safe Link protection limitations for Office docs in the web

### ISSUE THREAD

**Issue by katiekiv** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#251]
Suggest that the note under "Safe Links" cross references this help article. Specifically for Safe Links coming to Office documents in the web, there are some cases outlined in the help article where protection could not be available.
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/how-atp-safe-links-works#how-atp-safe-links-works-with-urls-in-office-documents

**Comment by SharS** [comment]
@katiekiv Thanks for your feedback! I've forwarded your suggestion to the product team, and will update the service description if necessary based on their response.

**Comment by SharS** [comment]
@katiekiv I heard back from the product team, and I'll add the link. Thanks for your suggestion.
