### ISSUE TITLE
Streamline limits per licence type

### ISSUE THREAD

**Issue by tminchin** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#252]
hi - it would be useful if you could streamline this page to only show the restrictions/limits per licence type. For example, I have Office 365 E3 - I just want to see the limits applicable to E3 rather than way thru all possible permutations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#feedback)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@tminchin Thanks for your suggestion. The existing format is used in all service description topics, and your suggested update would result in repetition of each feature for each license. We have no plans to reformat the service descriptions at this time.
