### ISSUE TITLE
SPO and External Sharing in GCCH

### ISSUE THREAD

**Issue by amishd** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#253]
Can you confirm that all tenants in GCCH as of today has the ability to do Sharing via OTP to any tenants outside GCCH ? If not then this documentation needs to be updated to reflect that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c907526-4061-94b4-f2fd-d6fca90344bb
* Version Independent ID: 82e89c18-8d6e-bbb1-f6d0-6ec091d1556e
* Content: [Office 365 GCC High and DoD - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod.md)
* Service: **o365-administration**
* GitHub Login: @danarl
* Microsoft Alias: **danarl**

**Comment by lhcole** [comment]
@amishd Thank you for your feedback! Your comment got overlooked over the holidays. I will forward to the product team and update the documentation as necessary. Thanks for your patience.

**Comment by lhcole** [comment]
@amishd The product team has advised that the answer to your question is yes, this works. Thanks for your patience as we resolved a forked thread.
