### ISSUE TITLE
File Size Limit

### ISSUE THREAD

**Issue by win2000b** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#254]
Is the File Size Limit of SharePoint Online changing inline with the OneDrive limit to 100GB per file? as at the link : 

https://support.office.com/en-gb/article/invalid-file-names-and-file-types-in-onedrive-onedrive-for-business-and-sharepoint-64883a5d-228e-48f5-b3d2-eb39e07630fa?ui=en-US&rs=en-GB&ad=GB#individualfilesize

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by win2000b** [comment]
also announced at ignite
https://techcommunity.microsoft.com/t5/Microsoft-OneDrive-Blog/Celebrating-top-OneDrive-moments-at-Ignite-2019/ba-p/963182

We are pleased to announce Microsoft 365 supports uploads of file sizes up to 100 GB – which includes uploads of files into SharePoint, Teams and OneDrive.

**Comment by bebobebo** [comment]
This seems to be implemented for OneDrive, but not for OneDrive for Business, Teams or SharePoint.  They report that 15GB is the limit.

**Comment by jantoney** [comment]
@Bebobebo - That is correct, but not for long.
OneDrive for Business: "new 100 GB limit is rolling out now, and will be everywhere by early 2020"

It might be a bit premature to update this page though. At least until rollout is complete

**Comment by bebobebo** [comment]
@jantoney "new 100 GB limit is rolling out now, and will be everywhere by early 2020" has been added since I commented. The announcement from November and this article just stated 100GB as immediate availability without a rollout period.

**Comment by SKjerland** [comment]
@bebobebo - Our SharePoint writer worked with the product team to update this article, so all limits are currently correct as of 2/11/2020. The article will be updated again if/when limits change.
