### ISSUE TITLE
Discrepancy

### ISSUE THREAD

**Issue by bybytaren** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#255]
When I am in my tenant admin center and select Purchase services and then Compare licenses it reads that Office 365 Business Premium license does not include Stream, while this page says it does.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b5e7518-641b-6d9c-da4f-90f268949793
* Version Independent ID: bae3450b-35b4-d942-7012-7867a705150d
* Content: [Office 365 platform service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-platform-service-description)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@ Thanks for your feedback! I"ve forwarded your question to the product team, and I'll update the service description if necessary based on their response.

**Comment by lhcole** [comment]
@bybytaren The product team has advised that the service description content is accurate. Stream is included with Office 365 Business Premium license. Thanks for your patience!

**Comment by maggelopoulos** [comment]
Not sure if anyone is still watching this topic, but it seems that in some SKUs it is included, but with reduced features. For instance, in Business SKUs users cannot create Stream events.

https://docs.microsoft.com/en-us/stream/license-overview

The above info is not visible in most of the pages that concern Stream, hence the confusion.

**Comment by lhcole** [comment]
@maggelopoulos Thank you for your comments! This information is with the product team.
