### ISSUE TITLE
Maximum number of subfolders?

### ISSUE THREAD

**Issue by paf61** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#256]
"Maximum number of subfolders per mailbox folder = 10 000"

It is not clear if this limit means that any folder can have 10 000 child folders on the level below it, or it means that a root folder can have a maximum of 10 000 subfolders in the whole folder tree below it.

Are these folder limits valid for both a mailbox and the Online Archive, or are there increased limits for the Online Archive?

I ask because I came across an O365 Online Archive with 17 800 folders which was working ok, but at the same time a migration of a mailbox from on-prem Exchange to O365 failed when it had 10 600 folders.

Peter :-)
www.skov.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#feedback)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SharS** [comment]
@paf61 Thanks for your feedback! I've forwarded your question to the product team, and I'll update the article if necessary based on their response.

**Comment by aaronlemieux** [comment]
Thanks @paf61.  This has been updated.
