### ISSUE TITLE
Sharepoint Plan 1 and plan 2 

### ISSUE THREAD

**Issue by VK1991MS** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#257]
Hi Team,

This Article is about Office 365 plan option ad we can see its good article, but I found that As you guys have explained well about exchnage online plan 1 and plan 2 with yes 6,7,8,9. I am expecting same for Sharepoint plan1 and plan 2 comes under which subscription which will be quite useful and easy to compare plan with yes.

Most importantly same plan option article for Microsoft 365 business, E3, E5.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3fea44b-ae19-6168-157e-56e36c76b467
* Version Independent ID: 74e1c2f3-c8f7-16cf-0fd2-7d6007b12abb
* Content: [Office 365 plan options - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-plan-options#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-plan-options.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-plan-options.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@VK1991MS Thanks for your feedback. Is the content you're looking for in this [Office 365 platform service description](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-platform-service-description#feature-availability-across-office-365-plans
)?

**Comment by VK1991MS** [comment]
Hi Leslie,

Thank you for the response.

Not really the link you have sent, it still does not show for what I gave feedback on https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-plan-options where you have explained well for Exchange online plan and Plan 2 included in what base subscription but not for SharePoint plan 1 plan 2.

Thank you for your time.

Kind Regards,
Vaibhav Patel
________________________________

**Comment by lhcole** [comment]
@VK1991MS Thanks for your feedback! I've forwarded your question to the product team, and I'll update the article if necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @VK1991MS I've been working with the product teams on these older items, and this page has been updated.
