### ISSUE TITLE
Shared Mailboxes & O365 ATP

### ISSUE THREAD

**Issue by ruairidhlc** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#258]
There is no documentation on if shared mailboxes require licenses and if so, how that is implemented.  Any search engine queries provide sources in the form of answers.microsoft.com or Tech Commnity but this doesn't suffice for credability reasons.  Please can this be documented in the service description?

Example scenario: I have 100 O365 ATP licenses via M365 Business, each attached to a named user.  I have more than 100 mailboxes though, as there could be a number of shared mailboxes.  These do not require a license on their own.  Do they require an O365 ATP license, even if the named user accessing them is O365 ATP licensed?  If they do require licenses, how do you assign these, when licenses can only be assigned to users and not mailboxes?

Another scenario: if I increase my users to 200, where half are ATP licensed but half aren't (they just have basic O365 Exchange licenses), to be compliant, do I need to tune my ATP policies to never apply to the unlicensed users' mailboxes?  What about the shared mailboxes they access?  For example, this would prohibit safe attachment policies using the "recipient domain" applied to setting, or any use of "policies that apply to the entire organization" in safe links.

Just want to make sure we remain compliant, as it doesn't appear there is technical enforcement of applying policies beyond licenses.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 502796e9-ca73-7123-7719-c7b5b1042b7b
* Version Independent ID: 2929af88-6d56-4de3-2b4e-4e1d0e4d97ef
* Content: [Office 365 Advanced Threat Protection service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by iaasazure** [comment]
I would like to see this service description updated with this information

**Comment by lhcole** [comment]
@ruairidhlc, @iaasazure Thank you for your comments. Does [Exchange Online limits - Service description](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#mailbox-storage-limits) have any of the licensing information you're looking for here? Please also take a look at the footnotes. Let us know what additional information you might need. Thanks for your patience!

**Comment by iaasazure** [comment]
@lhcole Thanks, I can see in the EXO service description some information relating to ATP.
"Similarly, if you want to place a shared mailbox on litigation hold, the shared mailbox must have an Exchange Online Plan 2 license or an Exchange Online Plan 1 license with an Exchange Online Archiving add-on license. If you want to apply advanced features such as Office 365 Advanced Threat Protection, Advanced eDiscovery, or automatic retention polices, the shared mailbox must be licensed for those feature(s).
What is unclear about this statement is specifically, do I need an EXO licence and an ATP licence for a shared mailbox that doesn't need an exchange online licence for any other reason, for example it is less than 50GB and has no advanced exchange features required. The quote states the 'the shared mailbox must be licensed for those feature(s)' but I cannot apply a ATP licence without a minimum EXO licence.
I feel this should be mentioned in the ATP service description as well in the main body or at least foot notes as this significantly increases the cost for a roll out of ATP. For example I have an customer with 1000 users with Office 365 E3 and 200 shared mailboxes at 10GB or less with no advanced features I am covered when not using ATP. To use ATP for all mailboxes I will now need add an extra 200* EXO P1 and 1200* Office 365 ATP P1.

**Comment by lhcole** [comment]
@iaasazure Thanks for your feedback and clarifications! I've forwarded your question to the product team, and I'll update the article if necessary based on their response.

**Comment by lhcole** [comment]
@ruairidhlc Please contact support for appropriate tracking of your issue. For Support options, see [Support](https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/support). Thank you!

**Comment by vicbersong** [comment]
Additionally, i need some help with clarifying ATP licencing requirement for on-premises hosted mailbox. my client currently uses EOP but all mail are hosted in on-premises and the need to bolt-on ATP. Question is if this scenario is supported and what are the licencing requirement ?

Say i have 500 on-premises mailbox (shared and user mailboxes) and i need these protected with EOP + ATP how-many EOP/ATP licence do  need?

**Comment by lhcole** [comment]
@vicbersong Please contact support for appropriate tracking of your issue. For Support options, see [Support](https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/support). Thank you!

**Comment by isaacchua** [comment]
@lhcole this is something I need to know for my organisation too. Please give us an update here, so that everyone now and the future knows.

**Comment by lhcole** [comment]
@isaacchua Hello! The product team has been advised of your request. Please contact support for specific issues related to your organization. For Support options, see [Support](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/support). Thank you!

**Comment by aaronlemieux** [comment]
Hi @ruairidhlc, @isaacchua, @iaasazure, and @vicbersong,

I met with the product team today and they verified the following for us:

Shared mailboxes need to be licensed for Advanced Threat Protection. See the following example:
Company has 5 users in Office 365. Each has a mailbox. There is 1 shared mailbox. They need a license for:
6 seats of Exchange Online Protection (5 users + 1 shared mailbox)
6 seats of Advanced Threat Protection (5 users + 1 shared mailbox)

We are in discussions regarding any updates to this service description.

**Comment by ruairidhlc** [comment]
> 
> 
> Hi @ruairidhlc, @isaacchua, @iaasazure, and @vicbersong,
> 
> I met with the product team today and they verified the following for us:
> 
> Shared mailboxes need to be licensed for Advanced Threat Protection. See the following example:
> Company has 5 users in Office 365. Each has a mailbox. There is 1 shared mailbox. They need a license for:
> 6 seats of Exchange Online Protection (5 users + 1 shared mailbox)
> 6 seats of Advanced Threat Protection (5 users + 1 shared mailbox)
> 
> We are in discussions regarding any updates to this service description.

Hi @aaronlemieux, thank you for the update.  I was aware that shared mailboxes had to be licensed for ATP, but did not know about the EOP license requirement.  Is the EOP requirement true for shared mailboxes in tenants that do not use ATP too?

**Comment by vondrac** [comment]
Hi @aaronlemieux, can you please 

> > Hi @ruairidhlc, @isaacchua, @iaasazure, and @vicbersong,
> > I met with the product team today and they verified the following for us:
> > Shared mailboxes need to be licensed for Advanced Threat Protection. See the following example:
> > Company has 5 users in Office 365. Each has a mailbox. There is 1 shared mailbox. They need a license for:
> > 6 seats of Exchange Online Protection (5 users + 1 shared mailbox)
> > 6 seats of Advanced Threat Protection (5 users + 1 shared mailbox)
> > We are in discussions regarding any updates to this service description.
> 
> Hi @aaronlemieux, thank you for the update. I was aware that shared mailboxes had to be licensed for ATP, but did not know about the EOP license requirement. Is the EOP requirement true for shared mailboxes in tenants that do not use ATP too?

@aaronlemieux, can you please reply to this? Much appreciated.

**Comment by aaronlemieux** [comment]
Hi @vondrac and @ruairidhlc.   I've been following up with the product team on this. There may be a delay on this due to Ignite going on, but I'll be continuing to chase this down later this week.

**Comment by chwilfing** [comment]
Any news about? I've the same questions with customers and licensing partners are giving different answers. from - need to license to - don't say anybody. Need to have an reliably resource to redirect the customer to!

Thanks!
Christoph

**Comment by aaronlemieux** [comment]
Hi @chwilfing I've reached out to the product team again today.  Discussions on this have been continuing.

**Comment by carljohngabato** [comment]
Hi @aaronlemieux 

> Hi @ruairidhlc, @isaacchua, @iaasazure, and @vicbersong,
> 
> I met with the product team today and they verified the following for us:
> 
> Shared mailboxes need to be licensed for Advanced Threat Protection. See the following example:
> Company has 5 users in Office 365. Each has a mailbox. There is 1 shared mailbox. They need a license for:
> 6 seats of Exchange Online Protection (5 users + 1 shared mailbox)
> 6 seats of Advanced Threat Protection (5 users + 1 shared mailbox)
> 
> We are in discussions regarding any updates to this service description.

What if there are multiple shared mailboxes and only a few of them will need EOP?

There are different business cases that would require some SMB to be protected and some do not.

It's makes more sense if EOP license can be assigned to an SMB, instead of assigning and Exchange Online license.

**Comment by JaredJJohnston** [comment]
Please can someone respond? @aaronlemieux 
There are still major unanswered questions here and the documentation and service descriptions for Exchange and Defender (ATP) do not answer these properly. We need to know definitively what is needed for Shared mailboxes to be able to use ATP legally and technically?
1. Are Exchange Plan 1/Plan 2 licenses required on the shared mailbox?
2. Are EOP licenses required? (and must they be assigned?)
3. Are ATP (Defender) licenses required? (and must they be assigned?)

Thanks

**Comment by aaronlemieux** [comment]
Hi @JaredJJohnston.  I have been in communication with the product group and am still working to get verbiage updates from the appropriate stakeholders.

**Comment by aaronlemieux** [comment]
Hi @JaredJJohnston I've spoken with the product team and they have provided the following information, which should be available through [Support](https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/support).

- Buy and assign licenses to all user mailboxes protected by the service (EXO plan or an EOP standalone license if you’re protecting an Exchange Server mailbox with EOP).

- Do not buy or assign licenses to shared  mailboxes, unless you use it with advanced features (increase the size limit to 100 GB, enable auto-expanding archiving, place a shared mailbox on litigation hold).

- For Microsoft Defender for Office 365 (ATP is the old name for this product), as well as for Advanced eDiscovery, or automatic retention policies, the shared mailbox must be licensed for those features for both user and shared mailboxes, online or on-premises. Once the licenses are purchased, MDO features are “unlocked” depending on a license type and ready to apply to the entire organization: there’s no need for explicit assignment per mailbox. In other words, licensing for these features is purchased to be compliant.

**Comment by adamehale** [comment]
@aaronlemieuxatmicrosoft 
Thank you for that information. 
I have a few questions for follow-up if you would be so kind.
1. For Microsoft Defender for Office 365, does all policies apply to all users.  There are several MS Docs that talk about safe links applying to licensed users. 
  I mention this because I found this document(https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#microsoft-defender-for-office-365) and the 4th point down talks about licensing for specific users.  I just want to ensure that all users have full protection provided by MDO even if I am not applying individual licenses to each user(a huge time save BTW!). 
2. Is there a location outside of here that has it documented that all mailboxes, licensed and basic shared, require a MDO license to stay in compliance? I work for a MSP that support lawyers, and if I simply tell them they need to buy a bunch more licenses, I am goin to need written support.

Thank you.

**Comment by ChrisAtMAF** [comment]
@adamehale Just investigating this for myself today. If you're looking for documentation that shared mailboxes need an MDO license to be in compliance, how about Note 2 below.

I think you don't have to license them, but you then would be unable to apply any of the advanced Defender features to them.

https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#mailbox-storage-limits

'To access a shared mailbox, a user must have an Exchange Online license, but the shared mailbox doesn't require a separate license... If you want to apply advanced features such as Microsoft Defender for Office 365, Advanced eDiscovery, or automatic retention policies, the shared mailbox must be licensed for those feature(s).'
