### ISSUE TITLE
Outlook (rest) API Connection Missing

### ISSUE THREAD

**Issue by chwilfing** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#259]
I do see information about EWS Access but I'm missing explicit information about Outlook Rest API access. We do want to connect to an F1 license mailbox and unsure if this will be possible.

BG Christoph

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2f622a7-32c1-2c35-2df9-ddf1bc74c74d
* Version Independent ID: e37d85d2-8b81-0c64-b7d0-1e8c01b303db
* Content: [Exchange Online service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description?redirectedfrom=MSDN#feedback)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@chwilfing Thanks for your feedback! I've forwarded your request to the product team and will make changes to the content if necessary. Thanks for your patience.

**Comment by aaronlemieux** [comment]
Hi @chwilfing REST API 2.0 is being deprecated.  As such, the team has decided to leave this service description as is.  Thank you.
