### ISSUE TITLE
Flow and PowerApps SKUs

### ISSUE THREAD

**Issue by nimojg-microsoft** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#26]
Can you clarify the Flow and PowerApps SKUs please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8328da3-5093-09b6-9b9b-b92d13625219
* Version Independent ID: f2171de5-bfa5-65d1-4615-30db23349b40
* Content: [Microsoft 365 Education](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by nimojg-microsoft** [comment]
Is anyone going to update this?

**Comment by prabita** [comment]
@nimojg-microsoft -  I’ve reached out to the product team and will update this article as needed, pending their response. If you can specify the exact change to be made, I can make the change.
