### ISSUE TITLE
Minburn Technology Group

### ISSUE THREAD

**Issue by gwturner** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#262]
Minburn Technology Group needs to be added to the list of "LSPs GCC and GCC High (+500 seats)".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86dc9aff-0190-52d9-2ab0-4f236d862739
* Version Independent ID: f6cbf527-2a7d-edd6-49b9-ca70ba43b9d6
* Content: [Microsoft 365 Government how to buy - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/microsoft-365-government-how-to-buy?source=docs#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/microsoft-365-government-how-to-buy.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/microsoft-365-government-how-to-buy.md)
* Service: **o365-administration**
* GitHub Login: @danarl
* Microsoft Alias: **danarl**

**Comment by lhcole** [comment]
@gwturner Thanks for your feedback! We don't update blog posts and our content guideline is to use the name of the blog post in the link. While misleading, the information is still correct. Thanks for your patience.

**Comment by gwturner** [comment]
I don’t understand the response. Can you please clarify why the blog post would not be updated to reflect the accurate information?

Sent from my iPhone

On Feb 5, 2020, at 2:03 PM, Leslie H Cole <notifications@github.com> wrote:

﻿

@gwturner<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgwturner&data=02%7C01%7C%7Cda0d3c8c27eb4490e6c608d7aa6e269d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637165262376455567&sdata=7Z%2FtPMfEkW0p5fZdj1ZNA9ffZHTgiyEavVFfT%2FHC7uQ%3D&reserved=0> Thanks for your feedback! We don't update blog posts and our content guideline is to use the name of the blog post in the link. While misleading, the information is still correct. Thanks for your patience.

**Comment by lhcole** [comment]
@gwturner Thanks for your feedback! I've forwarded your question to the product team, and I'll update the article if necessary based on their response.
