### ISSUE TITLE
New Admin Tools - Are not New

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#263]
the link to new admin tools points to a page that is over 5 years old. It would be helpful to revise  this text so that it is not misleading. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76358610-0b3b-49d9-6e6a-0b334b19d795
* Version Independent ID: 66466964-caa5-cded-20a6-627495521904
* Content: [Service health and continuity - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/service-health-and-continuity#notification-policy)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/service-health-and-continuity.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/service-health-and-continuity.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@DeanGross Thanks for your feedback! We don't update blog posts and our content guideline is to link to the exact title of the post. Though misleading, the content is correct. Thanks for your patience.

**Comment by lhcole** [comment]
@gwturner Sorry that I wasn't clearer. The content is accurate so there is no change to be made. Thanks.
