### ISSUE TITLE
Exchange Admin Center Maximum message size changed to 35Mb for very long time but docs didn't update.

### ISSUE THREAD

**Issue by justinianho** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#264]
Please check notes: 1 The default maximum message size for Office 365 mailboxes is 25 MB. .....  25Mb is wrong

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#feedback)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@justinianho Thanks for your feedback! I've forwarded your question to the product team, and I'll update the article if necessary based on their response.
