### ISSUE TITLE
File Size Limit from File Explorer

### ISSUE THREAD

**Issue by oliviadudley** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#265]
Attempting to view a PDF file (54.6 MB) stored on SPO, results in the error message that "the file exceeds the limit allowed". However, when viewing the file in the web interface there is no issue. If we can find where this limit is set, then we can request that our IT department make changes (if possible). Currently, we are looking for a way to view/upload/download files larger than 50 MB. Any help would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits#feedback)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@oliviadudley I'm sorry that you're having this issue. For Support options, see [Support](https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/support).
