### ISSUE TITLE
Long term audit retention?

### ISSUE THREAD

**Issue by dotnick365** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#266]
This feature is not addressed for GCCH, can the article be updated to reflect the availability of the long term audit retention for Adv. Compliance/G5 customers in GCCH?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6a73833-f8b4-c9d2-d516-5b9fc62ce5a3
* Version Independent ID: 82ba6e0c-4da4-5d3d-1d35-032d63aac1e6
* Content: [Plan for Microsoft 365 compliance - GCC High - Service Descriptions](https://docs.microsoft.com/en-us/Office365/ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/plan-for-m365-compliance-gcc-high)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/plan-for-m365-compliance-gcc-high.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/plan-for-m365-compliance-gcc-high.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@dotnick365 Thanks for your feedback! I've forwarded your question to the product team, and I'll update the article if necessary based on their response.

**Comment by lhcole** [comment]
@dotnick365 The product team has responded that Advanced Audit will be available in GCC or GCC High sometime during the second half of 2020 and the service description will be updated as appropriate at that time. Thank you!
