### ISSUE TITLE
Moving and copying across site collections – 100 GB per operation. The web browser must remain open.

### ISSUE THREAD

**Issue by RichardFransen** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#267]
I was not aware of these limitations, and performed extensive testing transferring files and folders from ODB to SPO. The scenario's tested included: 1) Transfer 150GB in one run; 2) Transfer 10,000 files divided over 2,500 folders; 3) Execute the scenarios 1 and 2 with the browser closed; 4) Execute the scenarios 1 and 2 with the user logging off. In total over 1TB was migrated using both 'Copy to' and 'Move to'.

All tests executed flawlessly ! :-)

I would like to understand the stated limitations of :
- 100 GB per operation. 
- The web browser must remain open.

I also would like to get guidance about the maximum :
- number of users simultaneously executing Copy to / Move to jobs in the same tenant
- amount of content that can be Copied / Moved by all users within a tenant

Background on these questions: our organization (80.000+ users) considers to use Copy to / Move to for transferring large volumes of files (500 TB) from ODB to SPO.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits#feedback)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@RichardFransen Support can help answer and track questions specific to your production environment. For Support options, see [Support](https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/support). Thank you!
