### ISSUE TITLE
Backup and Recovery

### ISSUE THREAD

**Issue by cfl81** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#268]
Please, let me know where I can read about backup and recovery process for Project for the web and Project Online in Microsoft Project service description.
Thanks a lot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b614c3a-5070-9595-2cb2-d2ec4fb68cb7
* Version Independent ID: f73e4cf9-fe59-e6f4-7638-2bddf97a069e
* Content: [Microsoft Project service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/project-online-service-description/project-online-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/project-online-service-description/project-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/project-online-service-description/project-online-service-description.md)
* Product: **office-online-server**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@cfl81 Thanks for your feedback! I've forwarded your question to the product team, and I'll get back to you with their response.

**Comment by lhcole** [comment]
@cfl81 Thanks for your comments. Please refer to this [service description](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance) for the backup and recovery process.
