### ISSUE TITLE
Shared Mailboxes as a means of email archival

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#269]
Archive note #7 states "only emails stored in the shared mailbox are those sent to or from it, as the shared mailbox. " in the context of disallowing shared mailboxes to be used as what would otherwise be called journal mailboxes. In previous versions of shared mailbox documentation, the wording was stronger, stating that customers could not convert former user mailboxes to "shared" as a means to get around paying for an ongoing license (for that, they were to use inactive mailboxes). 

However, since then, other documentation such as 

https://docs.microsoft.com/en-us/office365/admin/email/convert-user-mailbox-to-shared-mailbox?view=o365-worldwide#use-the-exchange-admin-center-to-convert-a-mailbox
and
https://docs.microsoft.com/en-us/office365/admin/add-users/remove-former-employee?view=o365-worldwide

say to do just that. Can you clarify here that shared mailboxes can be used as long-term archives?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#mailbox-storage-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@Mike-Crowley Thanks for your feedback! I've forwarded your question to the product team, and I'll update the article if necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi Mike, I've spoken with the product team and they do not feel the service description should be updated.
