### ISSUE TITLE
Microsoft Teams missing from "Office Apps and Feature Availability in Gov plans" section

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#270]
https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government?source=docs#office-application-and-feature-availability-in-government-plans

We need to have a Microsoft Teams section that explains what features are not available to GCC/GCC High/DOD customers just like we have for the rest of the Office suite. A realistic view of what works/does not work is not available in any of our public documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3ab3187-c403-8fb1-6ee7-56818777fdad
* Version Independent ID: f6b28482-bf80-436e-cb8f-facb974c24ec
* Content: [Office 365 US Government - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government?source=docs#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md)
* Service: **o365-administration**
* GitHub Login: @danarl
* Microsoft Alias: **danarl**

**Comment by lhcole** [comment]
@npherson Thanks for your feedback! I've forwarded your request to the product team and will update the content as per their instructions.

**Comment by lhcole** [comment]
@npherson The product team has responded and asked me to direct you to our Microsoft Teams Doc pages by environment here: Teams ([GCC](https://docs.microsoft.com/en-us/MicrosoftTeams/plan-for-government-gcc), [GCCH](https://docs.microsoft.com/en-us/MicrosoftTeams/plan-for-government-gcc-high), [DoD](https://docs.microsoft.com/en-us/MicrosoftTeams/plan-for-government-dod)). Thank you for your patience.

**Comment by lhcole** [comment]
Adding @aaron lemieux (Insight Global Inc)<mailto:v-aalemi@microsoft.com> who is working on the Service Descriptions now.

**Comment by aaronlemieux** [comment]
Hi @npherson.  Can you create a new request for this?   I'll be happy to track this and get work going on it immediately once you do.

**Comment by npherson** [comment]
Will do, @aaronlemieux. ^^^
