### ISSUE TITLE
Please provide clarify on the sync limits with the current versions of OneDrive for business

### ISSUE THREAD

**Issue by speers-cbx** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#271]
My read on this article, informs me that the SPO Sync Limit via Onedrive for business is 5K.

Clearly this is not a hard limit. Is this a guideline?

The article contains some odd wording. Are we talking about the current version of Onedrive? What about Web Dav calls? Please clarify this article providing clarity on the sync limits with the current versions of OneDrive for business when syncing to SPO 365.

**Comment by lhcole** [comment]
@speers-cbx Thanks for your feedback! I've forwarded your question to the product team, and I'll update the article if necessary based on their response.

**Comment by SKjerland** [comment]
@speers-cbx - Our SharePoint writer updated the article to clarify. Thanks!
