### ISSUE TITLE
Update Defender Name & Student Use Benefit

### ISSUE THREAD

**Issue by lysmyers** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#272]
Please update in multiple locations on this page, the reference to Windows Defender ATP. The product is now called Microsoft Defender ATP.  
Also - please add footnote calling out that the Student Use Benefit of A5 EXCLUDES Microsoft Defender ATP.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8328da3-5093-09b6-9b9b-b92d13625219
* Version Independent ID: f2171de5-bfa5-65d1-4615-30db23349b40
* Content: [Microsoft 365 Education - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@lysmyers Thanks for your feedback. Please review the changes and let me know if I can help further.
