### ISSUE TITLE
What is the upper limit exchange online unlimited archiving ? Previously it was 1 TB

### ISSUE THREAD

**Issue by Mohkam** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#273]
What is the upper limit exchange online unlimited archiving ? 
Previously it was 1TB.  I am unable find any official reference on this.
tried asking here but thread was closed without answering the query. https://github.com/MicrosoftDocs/microsoft-365-docs/issues/1191  
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c55dc71-81ed-864b-ac3f-63ce84688070
* Version Independent ID: 578c9a02-045e-4bf9-6384-d70560c332f0
* Content: [Exchange Online Archiving service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description#unlimited-archive-storage-quota)
* Content Source: [Office365-ServiceDescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@Mohkam Thanks for your feedback and patience! I've forwarded your question to the product team, and I'll update the article if necessary based on their response.
