### ISSUE TITLE
Link to "Data Governance" is incorrect. It links to DLP now. 

### ISSUE THREAD

**Issue by dennisxu2019** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#274]
Link to "Data Governance" is incorrect. It links to DLP now. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 663a603e-482b-0a4f-55a9-229ceab11bb1
* Version Independent ID: 488b1daa-b459-c56d-11eb-59242af822b0
* Content: [Office 365 Security & Compliance Center - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@dennisxu2019 Thanks for your feedback. Can you give us a little more information about which link needs to change and where the new link should go? Thanks again.

**Comment by lhcole** [comment]
@dennisxu2019 Thanks again for your feedback. I've received updates from the product team and will incorporate them into the article as requested.
