### ISSUE TITLE
Security Score Coming Soon to DoD

### ISSUE THREAD

**Issue by fergshell2000** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#276]
On 2/9/2020 Security Center says Yes with a 14, 9, 15 annotation. I am mainly interested is DoD
14 Available at https://securescore.office.com. Requires admin permissions. For more information, see Introducing the Office 365 Secure Score.  Question: What does this mean?
9 Not yet available in GCC High, but coming soon. Question: Where does one go to monitor and determine when is "Coming Soon" for GCC high?
15 Not yet available in DoD environment, but coming soon. Question: Where does one go to find out monitor and determine when is "Coming Soon" for DoD?
Also, will Security center GCC/High and DoD have limited capability/features?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3ab3187-c403-8fb1-6ee7-56818777fdad
* Version Independent ID: f6b28482-bf80-436e-cb8f-facb974c24ec
* Content: [Office 365 US Government - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md)
* Service: **o365-administration**
* GitHub Login: @danarl
* Microsoft Alias: **danarl**

**Comment by lhcole** [comment]
@fergshell2000 Thanks for your feedback! I've forwarded your question to the product team, and I'll update the article if necessary based on their response.

**Comment by lhcole** [comment]
@fergshell2000 Thanks for your feedback! I've forwarded your question to the product team, and I'll update the article if necessary based on their response.

**Comment by lhcole** [comment]
@fergshell2000 Thanks for your query on secure score. For more information on which roles in the tenant have access to which information please review the documentation on the following link: https://docs.microsoft.com/en-us/microsoft-365/security/mtp/microsoft-secure-score

Please note that we don’t list future product dates in our service descriptions. Coming soon is the reference that it will be coming to the environment. Once dates are available for a specific product they’ll be posted to the Microsoft 365 roadmap at www.microsoft365.com/roadmap

For specific information is available in DoD for our security and compliance center please reference the following page: https://docs.microsoft.com/en-us/Office365/ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/plan-for-m365-compliance-dod
