### ISSUE TITLE
Where is Stream?

### ISSUE THREAD

**Issue by emilylait** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#277]
Stream isn't mentioned in here. Can it be mentioned (i know it's considered part of the o365 platform, but would be good to have it separately mentioned), it is heavily used in EDU, particularly in classrooms for lecture recording and live streaming. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8328da3-5093-09b6-9b9b-b92d13625219
* Version Independent ID: f2171de5-bfa5-65d1-4615-30db23349b40
* Content: [Microsoft 365 Education - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@emilylait Thanks for your feedback! I've forwarded your question to the product team, and I'll update the article if necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @emilylait This SD has been updated to include this.
