### ISSUE TITLE
O365 Extra File Storage add-on applicable also for Business subscription

### ISSUE THREAD

**Issue by teomonda** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#278]
I think that the note 
3 If you have an Office 365 subscription and an Office 365 Extra File Storage add-on, the storage amounts are added.
should also be added as reference to the column with the Business subscription as the add-on is compatible with those as well as per:
https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/add-storage-space?view=o365-worldwide .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits#feedback)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@teomonda Thanks for your feedback! I've forwarded your question to the product team, and I'll update the article if necessary based on their response.

**Comment by teomonda** [comment]
Hello Leslie,
I see this one was closed however the article has not been changed to reflect the note 3 also for business subscriptions.
What were you able to find out from the Product Team?

**Comment by lhcole** [comment]
@teomonda The language has been removed. Thanks!

**Comment by teomonda** [comment]
Hello Leslie, I think i have not explained this properly as to me the article seems unchanged.
What i was complaining about is that reference 3 is missing from the Business subscriptions, indicating as if the add-on would not be available for such subscriptions. Which is false according to: https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/add-storage-space?view=o365-worldwide
I attached a screenshot, maybe it makes more sense like this.

![Annotation 2020-04-24 100701](https://user-images.githubusercontent.com/43137999/80184505-61b56580-8613-11ea-9ed0-4e9ae2fbbe43.jpg)

**Comment by lhcole** [comment]
@teomonda Thanks for clarifying. I'll query the product team again.
