### ISSUE TITLE
Add M365 subscription plans

### ISSUE THREAD

**Issue by ThomasKur** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#279]
In the "Office 365 Advanced Threat Protection (ATP) availability" the M365 plans are completely missed. It would be great to see if we are able to add it for example to am M365 F1 subscription.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 502796e9-ca73-7123-7719-c7b5b1042b7b
* Version Independent ID: 2929af88-6d56-4de3-2b4e-4e1d0e4d97ef
* Content: [Office 365 Advanced Threat Protection service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@ThomasKur Thanks for your feedback! I've forwarded your question to the product team, and I'll update the article if necessary based on their response.
