### ISSUE TITLE
Comparison of plans

### ISSUE THREAD

**Issue by DashRalti** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#280]
I was hoping I could still find a comparison chart of which features are available in the standalone and Office 365/M365 plans. 

Examples: 
SharePoint Online, SharePoint Server, Office 365 plan comparison across SP Features.
 
What features are available to Plan 2/Office365 E5/Microsoft365 E5 which are not available to F1 users?
 
Can an F1 user create a SharePoint Site? A Team? Can they connect a Team to a Group?

Some additional items in which I can't find any delineation with F1 users in the current SPO Service Description under the current per-feature breakout:   Quick Edit
   SharePoint Admin Recycle Bin
   Data Library Connection
   BCS with External Content Types
   Filter Search
   PowerPivot for Excel
   Search Web Parts
   SharePoint Admin Center

**Comment by lhcole** [comment]
@DashRalti Thanks for your feedback! I've forwarded your request to the product team, and I'll update the document if necessary, based on their response.

**Comment by lhcole** [comment]
@DashRalti Hello! The product team has advised that the information you are looking for is here: https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits
