### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by nwipfli** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#281]
There is an error 404 for the link under "Transparent operations from Office 365".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be031f7b-abd5-5192-9803-0bed8c4a6991
* Version Independent ID: 9bb96c02-da2a-b96d-75ff-c89ca729a104
* Content: [Service Level Agreement - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/service-level-agreement)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/service-level-agreement.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/service-level-agreement.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@nwipfli Are you able to access this link: https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/service-health-and-continuity ? I can't repro the 404. Thanks for your assistance.
