### ISSUE TITLE
Planner in F1 plan

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#282]
Hi! According to this post https://techcommunity.microsoft.com/t5/planner-blog/planner-is-coming-to-all-f1-commercial-plans-and-government/ba-p/835468 planner should be included in F1 plans starting October/November 2019. This table has "no" for planner in F1 plan.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b5e7518-641b-6d9c-da4f-90f268949793
* Version Independent ID: bae3450b-35b4-d942-7012-7867a705150d
* Content: [Office 365 platform service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-platform-service-description)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@Larryngolog Thanks for your feedback! I've forwarded your request to the product team, and I'll update the document if necessary, based on their response.

**Comment by christomayr** [comment]
I second this, also the compare-all-microsoft-365 page on ms.com lists Planner as included in F1. https://www.microsoft.com/en-us/microsoft-365/compare-all-microsoft-365-plans

**Comment by lhcole** [comment]
@Larryngolog @christomayr The product team has advised that Planner is included in F1 offer. Updating the service description as necessary. Thank you.

**Comment by teomonda** [comment]
Meeting creation for Office 365 F3 plan.
Hello, i read above that "12 InOffice 365 Enterprise F3, one-to-one audio/visual calls are supported. Meetings rights are limited to join only (no creating or initiating)." 
However in a new trial i created i can also create meetings. Can you double check the validity of this item?

**Comment by lhcole** [comment]
@teomonda Would you mind submitting a different GitHub issue with this question? This request is closed. Thank you!
