### ISSUE TITLE
Firstline users access

### ISSUE THREAD

**Issue by teomonda** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#283]
Could you please add updated info on firstline users access?
The phrase "Firstline workers won't see SharePoint navigation menus, so firstline workers have to navigate to SharePoint sites directly by URL." is false, i can see the SharePoint and Onedrive tiles on an F1 tenant, i can create new sites... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b30190b2-6a2d-8380-2ad8-700094acd6fe
* Version Independent ID: 774e7cff-1bb0-1024-e2af-2bec354a3b0b
* Content: [SharePoint service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-service-description)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@teomonda Thanks for your feedback! I've forwarded your request to the product team, and I'll update the document if necessary, based on their response.

**Comment by teomonda** [comment]
Hello Leslie, any news from the product team regarding this?

**Comment by lhcole** [comment]
@teomonda No response yet but the product team can take up to a couple of weeks to confirm. Thanks for your patience.

**Comment by kaarins** [comment]
@teomonda Thank you for pointing this out. You are correct and this line has been removed.
