### ISSUE TITLE
Microsoft Forms for F1?  Yes or No?

### ISSUE THREAD

**Issue by scottyv** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#284]
Under Platform Features, it says that F1 has access to Microsoft Forms, but under the Office Apps and Enterprise Value, it says that Microsoft Forms is not available for F1 users.  Which one is it?

**Comment by lhcole** [comment]
@scottyv Thanks for your feedback! I've forwarded your request to the product team, and I'll update the document if necessary, based on their response.

**Comment by lhcole** [comment]
@scottyv Hello! This article is affected by product and documentation changes that will go into effect around 3/12. Thanks for your patience.

**Comment by lhcole** [comment]
@scottyv Thanks for your patience. The product team has advised that Microsoft Forms is not available in the F1 plan but is available in both F3 plans. Let me know if we can assist further.
