### ISSUE TITLE
Sending limits across Office 365 options

### ISSUE THREAD

**Issue by mrkeiths** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#286]
The Recipient Limit of 500 should be updated to reflect info posted on the Exchange Team blog:
https://techcommunity.microsoft.com/t5/exchange-team-blog/customizable-recipient-limits-in-office-365/ba-p/1183228

Limits can now be managed in Exchange Online; the default limit can be lowered and a max value of 1000 recipients is now supported.

Thank you,
Keith

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#message-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@mrkeiths Thanks for your feedback! I am making the change to the content as you've requested.

**Comment by annferre** [comment]
Content changed to: 2 You can customize recipient limits between 1 and 1000 for existing mailboxes and for new mailboxes that will be created in the future. Edit the recipient limit on existing mailboxes individually or in bulk using the Exchange admin center and customize the default setting for new mailboxes via Remote PowerShell. For more information, see [Customizable recipient limits in Office 365](https://techcommunity.microsoft.com/t5/exchange-team-blog/customizable-recipient-limits-in-office-365/ba-p/1183228).
