### ISSUE TITLE
Customizable Recipient Limits in Office 365

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#287]
See https://techcommunity.microsoft.com/t5/exchange-team-blog/customizable-recipient-limits-in-office-365/ba-p/1183228

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#message-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@trudolf-msft Thanks for the link. Do you have a specific question I can help you with or direct to the product team if necessary?

**Comment by trudolf-msft** [comment]
Hi,

No further questions. Just the wish to add this information to the existing article.

Kind regards,
Thomas
________________________________

**Comment by cabtilx** [comment]
The below is incorrect. From experience the restriction is always lifted at midnight UTC. So if sending to 10,000 recipients at 23:00 you will only be blocked for 1 hour. 

After the recipient rate limit is reached, messages can't be sent from the mailbox until the number of recipients that were sent messages in the past 24 hours drops below the limit. For example, a user sends an email message to 5000 recipients at 09:00 AM, then sends another message to 2500 recipients at 10:00 AM, and then sends another message to 2500 recipients at 11:00 AM, hitting the limit of 10,000 messages. The user won't be able to send messages again until 09:00 AM the next day.

**Comment by aaronlemieux** [comment]
Thank you for your input!  This has been added to this service description.
