### ISSUE TITLE
Folder replication

### ISSUE THREAD

**Issue by Lewis-Barry** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#289]
It would be good to see something here that states what happens to a user's inbox folder structure when they enable online archive with automatic archive defaults. I.e when it is enabled with the default retention tags, the structure is replicated in the online archive mailbox. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e0ba987-5e52-0e0d-f9f8-d6da3feaa53c
* Version Independent ID: 5763ce54-2c7c-8956-f44e-c946d0c9a5c4
* Content: [Archive features in Exchange Online Archiving - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-archiving-service-description/archive-features)
* Content Source: [Office365-ServiceDescriptions/exchange-online-archiving-service-description/archive-features.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-archiving-service-description/archive-features.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@Lewis-Barry Thanks for your feedback! I have forwarded your question to the product team, and I'll update the article if necessary based on their response.

**Comment by 3novsan** [comment]
Any update on this request.

**Comment by lhcole** [comment]
@3novsan Sorry, no. I have made a note of your inquiry.

**Comment by aaronlemieux** [comment]
This has been resolved and updated.
