### ISSUE TITLE
per user/per device

### ISSUE THREAD

**Issue by nimojg-microsoft** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#29]
There needs to be clarity here on A1 being per device vs. A3 and A5 being per user. In addition there should be clarity here on the Student Use Benefit and A3 and A5 qualifying for them (along with which agreements etc.). Please make this documentation a one-stop shop!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8328da3-5093-09b6-9b9b-b92d13625219
* Version Independent ID: f2171de5-bfa5-65d1-4615-30db23349b40
* Content: [Microsoft 365 Education](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by SeanDeasyMM** [comment]
You may be confusing Microsoft 365 A1 and Office 365 A1 here, where O365A1 (referenced on this page) is per user.

**Comment by prabita** [comment]
@nimojg-microsoft Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response

**Comment by rsoakford** [comment]
@prabita, I would like to second that it would be helpful to have clarity on Student Use Benefit as mentioned by @nimojg-microsoft

**Comment by aaronlemieux** [comment]
This is being addressed with issue #388.
