### ISSUE TITLE
incorrect or misleading statement 

### ISSUE THREAD

**Issue by scottsa-msft** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#290]
In this statement
For any user that reaches at least 90% capacity of their 25 TB of OneDrive storage, additional cloud storage will be provided as 25 TB SharePoint team sites to individual users. This additional storage is provided to the organization by way of credit.

The second sentence "This additional storage is provided to the organization by way of credit." should be removed. This makes it sound like the OneDrive storage counts against the total SharePoint storage that the customer purchased and it does not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99ce1810-18cd-687b-0c8b-bfceb919225a
* Version Independent ID: 705cde78-7e58-c260-bde3-0b393747cdea
* Content: [OneDrive service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/onedrive-for-business-service-description#storage-space-per-user)
* Content Source: [Office365-ServiceDescriptions/onedrive-for-business-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/onedrive-for-business-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@scottsa-msft Thanks for your feedback. I will remove the sentence as per your request.
