### ISSUE TITLE
Discrepancy in Feature availability across ATP plans

### ISSUE THREAD

**Issue by aglasson** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#291]
This page lists "Safe Links in Teams" as not part of ATP Plan 1 but the [product pricing page](https://products.office.com/en-au/exchange/advance-threat-protection#coreui-contentrichblock) lists it as included in ATP Plan 1.

Example of this page:
![image](https://user-images.githubusercontent.com/11340849/75620679-71966780-5bd7-11ea-9cd7-3961a25979a2.png)

Example of the product pricing page listing different information:
![image](https://user-images.githubusercontent.com/11340849/75620680-7824df00-5bd7-11ea-9b72-c9d7dabf98b7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 502796e9-ca73-7123-7719-c7b5b1042b7b
* Version Independent ID: 2929af88-6d56-4de3-2b4e-4e1d0e4d97ef
* Content: [Office 365 Advanced Threat Protection service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@aglasson Thank you for your comments. I have forwarded your request to the product team and will update the content if necessary.

**Comment by tnashc** [comment]
This is an important discrepancy, please update on which one is the correct feature list.

**Comment by Jared-Harrington-Gibbs** [comment]
Yeah, this is a huge discrepancy. 
This could be the difference between passing and failing compliance testing for some businesses.

**Comment by lhcole** [comment]
@aglasson @Jared-Harrington-Gibbs Thank you for your comments. The product team has advised that the feature is in preview at this time and will be released shortly. The service description will be updated when the feature is generally available. For more information, see the [Microsoft 365 roadmap entry](https://www.microsoft.com/en-us/microsoft-365/roadmap?rtc=1&filters=&searchterms=34298).
