### ISSUE TITLE
URL 404

### ISSUE THREAD

**Issue by dizzy721** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#293]
https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-service-descriptions#security-and-compliance-features

This URL for "SharePoint service description" under IT admin, security, and compliance features 404s. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99ce1810-18cd-687b-0c8b-bfceb919225a
* Version Independent ID: 705cde78-7e58-c260-bde3-0b393747cdea
* Content: [OneDrive service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/onedrive-for-business-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/onedrive-for-business-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/onedrive-for-business-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@dizzy721 Hello! Thanks for your comment. Can you verify that this link does not work for you? https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-service-description#security-and-compliance-features

**Comment by dizzy721** [comment]
@lhcole The link you provided works as expected!

**Comment by lhcole** [comment]
@dizzy721 Thank you! I'll make the necessary changes in the file.
