### ISSUE TITLE
Clarification on Enterprise State Roaming

### ISSUE THREAD

**Issue by DES-Paul** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#294]
Reading above seems to suggest that Enterprise State Roaming IS included in M365 Business - but I am see conflicting documentation around this saying that a premium AAD sub is still needed (their is no note against it in the table above to suggest that the feature is not available without it) - can we have some definitive clarification? As we are struggling to enable the functionality on a tenant with an M365 Business sub.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94c91b3d-d9b1-9056-ae3e-51a255ed88ec
* Version Independent ID: b60613bc-f7b3-d1c7-4d8e-924c0f87912f
* Content: [Microsoft 365 Business service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@DES-Paul Thanks for your query. I'm sorry that you're having this issue. For support options to assist with your issue, see [Support ](https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/support).
