### ISSUE TITLE
Office 365 Security & Compliance Center Link

### ISSUE THREAD

**Issue by cloidl** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#295]
The link to "Office 365 Security & Compliance Center" in the first paragraph, goes to a generic "Microsoft 365 help center for admins and IT pros"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 663a603e-482b-0a4f-55a9-229ceab11bb1
* Version Independent ID: 488b1daa-b459-c56d-11eb-59242af822b0
* Content: [Office 365 Security & Compliance Center - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@cloidl Thanks for your comment. I've fixed the incorrect link and the new link will go live later today.
