### ISSUE TITLE
Clarity needed on Version History and Office 365 Groups

### ISSUE THREAD

**Issue by thcross81** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#296]
Office 365 Groups and Version History is available in GCC, GCC High and DOD. Clarity is needed under the specific applications Word, Excel, and PowerPoint as the chart is stating that these functionality is not available. This is not a clear message as throughout documentation we have that co-authoring, Office 365 Groups, and version history is available (end user needs to save the document to OneDrive or SPO but version history is available). The way that is chart is currently it makes these features appear that they are not available. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3ab3187-c403-8fb1-6ee7-56818777fdad
* Version Independent ID: f6b28482-bf80-436e-cb8f-facb974c24ec
* Content: [Office 365 US Government - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md)
* Service: **o365-administration**
* GitHub Login: @danarl
* Microsoft Alias: **danarl**

**Comment by lhcole** [comment]
@thcross81 Thank you for your comments. I have forwarded your request to the product team and will update the content if necessary.

**Comment by lhcole** [comment]
@thcross81 Thank you for your query on specific feature functionality listed in the US Government service description for Office features. As we continue to evolve our products we’ve consolidated feature updates on [Office Applications Service Description](https://docs.microsoft.com/en-us/Office365/ServiceDescriptions/office-applications-service-description/office-applications-service-description). Please use this for specific feature-level detail. We’ll be referencing this page in our US Government service description. Thanks!
