### ISSUE TITLE
SfBO instead of Teams?

### ISSUE THREAD

**Issue by StPhil** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#297]
This article lays SfBO, but not Teams. As this article was updated in 2020 I'm confused by the difference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 482f1200-178f-088c-f189-ac129614cdb0
* Version Independent ID: 94ff27f4-966c-f271-1822-515c4e56a1bb
* Content: [Office 365 Education - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-education#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-education.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-education.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@StPhil Thanks for your comment. I have forwarded your request to the product team and will make updates to the article if necessary.

**Comment by aaronlemieux** [comment]
Hi @StPhil 

Microsoft Teams is now the primary client for messaging, meetings, and calling in Office 365. Starting October 1, 2018, new customers with 500 seats or less will be onboarded to Microsoft Teams and will not have access to Skype for Business Online. As of September 1, 2019, this applies to all new customers. Tenants already using Skype for Business Online can continue doing so (including provisioning new users) until they complete their transition to Microsoft Teams.
