### ISSUE TITLE
Broken Microsoft Planner Link

### ISSUE THREAD

**Issue by AndySanchezVM** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#298]
The link you listed for "To learn more, see Introducing Microsoft Planner" is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dd954d8-5874-8d25-36eb-0718ef86d585
* Version Independent ID: 001e3018-251d-dc72-c669-a21e303f21d7
* Content: [Office 365 suite features - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-suite-features)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-suite-features.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-suite-features.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@AndySanchezVM Hi. Thanks for your comment. Can you get to this link? https://www.microsoft.com/en-us/microsoft-365/blog/2015/09/22/introducing-office-365-planner/

**Comment by AndySanchezVM** [comment]
Yes this link works, will you be updating the link on this page?

**Comment by lhcole** [comment]
@AndySanchezVM Yes. Thank you.
