### ISSUE TITLE
Request for Additional Information

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#299]
Please provide additional information about any differences in the Security and Compliance Centers between GCC and Commercial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c907526-4061-94b4-f2fd-d6fca90344bb
* Version Independent ID: 82e89c18-8d6e-bbb1-f6d0-6ec091d1556e
* Content: [Office 365 GCC High and DoD - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod.md)
* Service: **o365-administration**
* GitHub Login: @danarl
* Microsoft Alias: **danarl**

**Comment by lhcole** [comment]
@DeanGross Thanks for your comment. I have forwarded your request to the product team and will update the article if necessary.

**Comment by lhcole** [comment]
@DeanGross Thank you for your question. For compliance feature functionality please see our compliance teams service description for [Microsoft Compliance in GCC](https://docs.microsoft.com/en-us/Office365/ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/plan-for-m365-compliance-gcc ). If you have additional questions about features not listed on that page, please comment in the Feedback section at the bottom of the page.
