### ISSUE TITLE
 links in the sections Phonetic name matching through Refiners are broken. 

### ISSUE THREAD

**Issue by pebaum** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#30]
links in the sections Phonetic name matching through Refiners are broken. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f721a17-dd47-081a-f057-15312f6ebe34
* Version Independent ID: 15517fbe-70c9-8625-35d1-283e9c6d3f88
* Content: [Search](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/search#phonetic-name-matching)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/search.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/search.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by prabita** [comment]
Links updated
