### ISSUE TITLE
Slide Sorter View section is out of date.

### ISSUE THREAD

**Issue by Beschorr** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#301]
Hi Shari! Slide Sorter view is now available on PowerPoint for the web. Can we update that section of this article to reflect it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b97aca7-f949-2398-ef4d-b322c13ddf72
* Version Independent ID: 560b58c2-0778-9cab-c267-61a3dea9e61f
* Content: [PowerPoint for the web - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-online-service-description/powerpoint-online?source=docs)
* Content Source: [Office365-ServiceDescriptions/office-online-service-description/powerpoint-online.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-online-service-description/powerpoint-online.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@Beschorr Thanks for your update. I've made the changes to the article as requested.
