### ISSUE TITLE
A DLP add-on is available that can be added to any SKU that has either Exchange or SharePoint/OneDrive.

### ISSUE THREAD

**Issue by BSiefferman** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#302]
Number 9 under the table states "9 A DLP add-on is available that can be added to any SKU that has either Exchange or SharePoint/OneDrive." Is there any documentation on this add-on license? I've looked in my demo tenant and I don't see this add-on license there. I can't find any documentation on this add-on either. Any help is greatly appreciated! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 663a603e-482b-0a4f-55a9-229ceab11bb1
* Version Independent ID: 488b1daa-b459-c56d-11eb-59242af822b0
* Content: [Office 365 Security & Compliance Center - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@BSiefferman Thank you for your comment! I have forwarded your request to the product team and I'll respond with their response or update the documentation if necessary.

**Comment by lhcole** [comment]
@BSiefferman Thanks for your query! The offer is Office 365 Data Loss Prevention and is available through Web Direct, CSP, and VL.
