### ISSUE TITLE
Incorrect sending limits example

### ISSUE THREAD

**Issue by msbeane443** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#303]
In the note just above the section on sending limits across standalone options, the second message is reportedly sent to 21000 recipients... for the math to work for the example it would have to be sent to 2500 recipients.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#receiving-and-sending-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@msbeane443 Thanks for your comment. I've forwarded your change request to the product team and will update the article if necessary.
