### ISSUE TITLE
Delve

### ISSUE THREAD

**Issue by jebalert** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#304]
Are there plans to bring Delve to DoD/GCC High?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c907526-4061-94b4-f2fd-d6fca90344bb
* Version Independent ID: 82e89c18-8d6e-bbb1-f6d0-6ec091d1556e
* Content: [Office 365 GCC High and DoD - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod.md)
* Service: **o365-administration**
* GitHub Login: @danarl
* Microsoft Alias: **danarl**

**Comment by lhcole** [comment]
@jebalert Thanks for your comment. I have forwarded your request to the product team and will get back to you with their response.

**Comment by lhcole** [comment]
@jebalert As mentioned in footnote 17 in the chart, Delve will not be supported in the GCC High and DoD environments. Thank you for your query.
