### ISSUE TITLE
Meeting creation for Office 365 F3 plan.

### ISSUE THREAD

**Issue by teomonda** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#306]
Hello, i read above that "12 InOffice 365 Enterprise F3, one-to-one audio/visual calls are supported. Meetings rights are limited to join only (no creating or initiating)."
However in a new trial i created i can also create meetings. Can you double check the validity of this item?
)(i incorrectly commented on a previous feedback on F1/F3)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b5e7518-641b-6d9c-da4f-90f268949793
* Version Independent ID: bae3450b-35b4-d942-7012-7867a705150d
* Content: [Office 365 platform service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-platform-service-description)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@teomonda Thank you for opening this new issue. I've forwarded your request to the product team and will make changes to the article as required.

**Comment by lhcole** [comment]
@teomonda The footnote is incorrect and has been removed from the service description. Thanks again for your comments.
