### ISSUE TITLE
Some of the language about Windows 10 Pro Upgrades is unclear

### ISSUE THREAD

**Issue by PsychoData** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#308]
There are several places around M365 Business and Windows 10 Upgrade rights that are unclear
 
Mostly they have language that can be slightly cherry-picked to seem to mean you could upgrade from any version of Windows 7, 8, or 8.1 to 10 Pro. IE, That you would be able to upgrade from Windows 7 Home to 10 Pro, for example, even though this is not the way that the service actually functions. 

Some people who I have talked with said that is how the M365 Business Upgrades to Windows 10 Pro worked during the Beta, but that no longer is the case. 

With the upcoming renaming of other O365 Business licenses to M365 Business, this just becomes even more important to be clear about. 

---

In the [M365 Business Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description)
in the **Windows 10 Pro management** section, there is a portion that says 
"If you have devices that are licensed for Windows 7 and 8.1 Professional, Microsoft 365 Business provides an upgrade to Windows 10 Pro.10"

and at the footnote, there is "If you have devices that are licensed for Windows 7 and 8.1 Professional, Microsoft 365 Business provides an upgrade to Windows 10 Pro"

I have had many people (including myself) confused by this. Could we add some language to clarify that this can only upgrade Pro versions of Windows, and not Home versions as well?

Perhaps something like "If you have devices that are licensed for Windows 7 and 8.1 Professional, Microsoft 365 Business provides an upgrade to Windows 10 Pro. This license will not cover upgrading a Windows 7 or 8.1 Home edition to Windows 10 Pro." 

Additionally, on one of the [Comparison/Feature pages for M365 Business](https://www.microsoft.com/en-us/microsoft-365/business)  there is a FAQ "What should customers and partners know before running Microsoft 365 Business in their organization?" that is even more general and needs to get fixed. 

> Customers who wish to run Microsoft 365 Business in their organization must be running Windows 7, 8.1, or 10 Pro* on their current desktops. Current Windows 10 Pro PCs should be running Creators Update if they have not already done so.
> *Windows 10 Pro upgrade rights are included with the Microsoft 365 Business preview if the target machines are presently running Windows 7, 8, or 8.1.

Which is also incorrect, and even more reason that someone might thing you could upgrade from ANY edition of 7, 8, or 8.1

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94c91b3d-d9b1-9056-ae3e-51a255ed88ec
* Version Independent ID: b60613bc-f7b3-d1c7-4d8e-924c0f87912f
* Content: [Microsoft 365 Business service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@PsychoData Thanks for your comments! I have forwarded your request to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @PsychoData I've spoken with the product team and we've updated this service description based on your feedback.  Thanks!
