### ISSUE TITLE
Microsoft 365 Business missing from PDF

### ISSUE THREAD

**Issue by ingepepe** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#309]
In the Detailed Microsoft 365 Compliance Licensing Comparison (PDF), the "Microsoft 365 Business" license is not showing for any column... is it that the "Microsoft 365 Business Premium" has an extra word?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 licensing guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@ingepepe Thanks for your comments. I've forwarded your query to the product team and will update the article if necessary based on their response.

**Comment by lhcole** [comment]
@ingepepe The product team replied that Microsoft 365 Business Premium is the new name effective 4/21. For more information, see [this blog post](https://www.microsoft.com/en-us/microsoft-365/blog/2020/03/30/new-microsoft-365-offerings-small-and-medium-sized-businesses/). Thank you!
