### ISSUE TITLE
MFA Clarity

### ISSUE THREAD

**Issue by umayrsufi** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#31]
Clarify that Microsoft 365 Business offers Office 365 MFA as part of the plan, but does not offer full azure MFA without addition of AADP1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94c91b3d-d9b1-9056-ae3e-51a255ed88ec
* Version Independent ID: b60613bc-f7b3-d1c7-4d8e-924c0f87912f
* Content: [Microsoft 365 Business Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-business-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-business-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-business-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by prabita** [comment]
@umayrsufi Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response.

**Comment by prabita** [comment]
Service description updated to reflect that it now includes Azure MFA.
