### ISSUE TITLE
M365 + P1 feature?

### ISSUE THREAD

**Issue by adamehale** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#310]
Since M365 Business is now getting a full feature of P1 in it, will it now include Password Protection?

There is a closed question asking the same thing, however the answer is from 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94c91b3d-d9b1-9056-ae3e-51a255ed88ec
* Version Independent ID: b60613bc-f7b3-d1c7-4d8e-924c0f87912f
* Content: [Microsoft 365 Business service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@adamehale Thanks for your comments. I have forwarded your request to the product team and will update the article if necessary based on their response.

**Comment by lhcole** [comment]
@adamehale The product team has responded that this is a name change only. For more information, see [this blog post](https://www.microsoft.com/en-us/microsoft-365/blog/2020/03/30/new-microsoft-365-offerings-small-and-medium-sized-businesses/). Thanks again for your comments.

**Comment by adamehale** [comment]
@lhcole, Thank you for the reply, however that is not what I was asking.
In the post saying that M365BP will soon have the features of Azure P1 licencing in it, I was attempting to confirm that Password Protection would now be included in the M365BP license?

**Comment by lhcole** [comment]
@adamehale Thanks for clarifying. I have forwarded your request to the product team and I will make the changes if the service description needs an update.

**Comment by lhcole** [comment]
@adamehale The feature is in preview at this time and will be released shortly. The service description will be updated when the feature is GA. For more information, you can track the issue at [Microsoft 365 Roadmap](https://www.microsoft.com/en-us/microsoft-365/roadmap?rtc=1&filters=&searchterms=34298).

**Comment by lhcole** [comment]
@adamehale Password Protection is now included in the Microsoft 365 Business Premium license for new customers and will be rolled out for existing customers. Thanks again for your comments.
