### ISSUE TITLE
Seems like this needs to be updated for the recent name changes?

### ISSUE THREAD

**Issue by bretthill-o365** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#311]
?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1bface7-95b2-72b8-43b7-d3bd43b27d0c
* Version Independent ID: ac6756e4-bf78-278c-f8a1-89c182bf545d
* Content: [Licensing Microsoft 365 for small and medium-sized businesses - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/licensing-microsoft-365-in-smb#feedback)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/licensing-microsoft-365-in-smb.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/licensing-microsoft-365-in-smb.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@bretthill-o365 Name changes are effective 4/21 as per [this blog post](https://www.microsoft.com/en-us/microsoft-365/blog/2020/03/30/new-microsoft-365-offerings-small-and-medium-sized-businesses/). Thanks for your comments.

**Comment by JudgeDreddKLC** [comment]
@bretthill-o365 Office 365 Business Premium is being renamed to Microsoft 365 Business Standard. Did you guys not get the memo?

https://www.microsoft.com/en-us/microsoft-365/blog/2020/03/30/new-microsoft-365-offerings-small-and-medium-sized-businesses/
