### ISSUE TITLE
how many shared mailboxes can be added to mailbox account?

### ISSUE THREAD

**Issue by juanelodelpiero** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#312]
I want to add 200 shared mailboxes to a mailbox account plan E3, there are a limit to do this?

**Comment by lhcole** [comment]
@juanelodelpiero Thanks for your comments. For Support options, see [Support](https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/support).
