### ISSUE TITLE
Please add some information about data encryption at rest and in transit

### ISSUE THREAD

**Issue by TrutzS** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#313]
Currently it is not directly clear how data encryption is handled, especially as two base products "SharePoint Online" and "Power Platform: CDS" are affected. Please add a chapter detailing it or linking to relevant information for the base products.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b614c3a-5070-9595-2cb2-d2ec4fb68cb7
* Version Independent ID: f73e4cf9-fe59-e6f4-7638-2bddf97a069e
* Content: [Microsoft Project service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/project-online-service-description/project-online-service-description#service-considerations)
* Content Source: [Office365-ServiceDescriptions/project-online-service-description/project-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/project-online-service-description/project-online-service-description.md)
* Product: **office-online-server**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@TrutzS Thank you for your comments. I have forwarded your content request to the product team and will update the article if necessary based on their reply.

**Comment by aaronlemieux** [comment]
Hi @TrutzS This has been completed.
