### ISSUE TITLE
Maximum Total Tasks limit

### ISSUE THREAD

**Issue by omerbinabdulaziz** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#314]
I read that maximum tasks for "Project for the web" is limited to 500.  This seems to be a huge limitation. Project tasks grow with time. Even when these are completed, you need the tasks to remain there for analysis purposes.  So 500 tasks per project seems to be a huge limitation.  It should be increased. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b614c3a-5070-9595-2cb2-d2ec4fb68cb7
* Version Independent ID: f73e4cf9-fe59-e6f4-7638-2bddf97a069e
* Content: [Microsoft Project service description - Service Descriptions](https://docs.microsoft.com/en-us/Office365/ServiceDescriptions/project-online-service-description/project-online-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/project-online-service-description/project-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/project-online-service-description/project-online-service-description.md)
* Product: **office-online-server**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@omerbinabdulaziz Thank you for your comments. A good place to submit your ideas for feature updates is on the [Office 365 feedback and suggestions site](https://office365.uservoice.com/).
