### ISSUE TITLE
Live events for small Business

### ISSUE THREAD

**Issue by teomonda** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#315]
the table above lists that small business users have live events.
whereas in the link referenced in the live events section:
https://docs.microsoft.com/en-us/stream/license-overview
live events in teams are absent for Business subscribers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9035b5a9-1f84-54be-89ae-c3a0e53891f8
* Version Independent ID: cff57f08-ca51-2266-6189-1ce8181b942e
* Content: [Microsoft Teams service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/teams-service-description#feature-category-reference)
* Content Source: [Office365-ServiceDescriptions/teams-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/teams-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@teomonda Thanks for your comments. I have forwarded your request to the product team and will update the article if necessary based on the response.

**Comment by Ajbutkus51** [comment]
Is there any update on this conflicting information? My small business is looking to utilize live events for hosting informational webinars, and the information above indicates we should be able to do that with Microsoft 365 Business Standard.

**Comment by Ajbutkus51** [comment]
Any update?

**Comment by lhcole** [comment]
@Ajbutkus51 No. I have made a note of your inquiry.

**Comment by lhcole** [comment]
@teomonda @Ajbutkus51 I have confirmed that none of the Microsoft 365 Business packages (small business) include Live Events. Thanks for your patience.
