### ISSUE TITLE
Microsoft Bookings availability in GCC

### ISSUE THREAD

**Issue by tmsquared** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#316]
I see that Microsoft Bookings is not available in GCC. I haven't found it in the Roadmap. Is there a plan for it to available in the near future? WE are working on a solution for a State client to book online meetings to handle Unemployment Claims. This has become a high visibility project due to COVID-19, a significant increase in claims and closing of in-person centers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3ab3187-c403-8fb1-6ee7-56818777fdad
* Version Independent ID: f6b28482-bf80-436e-cb8f-facb974c24ec
* Content: [Office 365 US Government - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md)
* Service: **o365-administration**
* GitHub Login: @danarl
* Microsoft Alias: **danarl**

**Comment by lhcole** [comment]
@tmsquared Thanks for your comments! I've forwarded your request to the product team for follow up and will let you know how they respond.

**Comment by lhcole** [comment]
@tmsquared The product team has responded as follows: "We have no plans at this time to make Bookings available in the GCC environment; however, we are exploring this for future expansion." Thanks again for reaching out.
