### ISSUE TITLE
Broken link to  PDF for license differences

### ISSUE THREAD

**Issue by blevinscm** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#317]
https://github.com/MicrosoftDocs/microsoft-365-docs/raw/public/microsoft-365/downloads/Office%20365%20ATP%20Plan%20Comparison%20-%20March%202020.pdf  (404 response)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 502796e9-ca73-7123-7719-c7b5b1042b7b
* Version Independent ID: 2929af88-6d56-4de3-2b4e-4e1d0e4d97ef
* Content: [Office 365 Advanced Threat Protection service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SKjerland** [comment]
@denisebmsft - Didn't you recently update this article? Can you please fix this link? Thanks!

**Comment by SKjerland** [comment]
@blevinscm -The link has been fixed. Thanks for bringing it to our attention!
