### ISSUE TITLE
footnote 3 is no longer accurate.  Private Channels is available in GCC

### ISSUE THREAD

**Issue by rstraker** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#318]
Private channels are now available in GCC footnote 3 needs to be update
Apps are available in GCC, footnote 4 needs to be updated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9035b5a9-1f84-54be-89ae-c3a0e53891f8
* Version Independent ID: cff57f08-ca51-2266-6189-1ce8181b942e
* Content: [Microsoft Teams service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/teams-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/teams-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/teams-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@rstraker Thanks for your comments. I've forwarded your query to the product team and will make the update to the article based on their response.

**Comment by rstraker** [comment]
Thank you Leslie

**Comment by aaronlemieux** [comment]
This has been resolved.  I will be closing this item.
