### ISSUE TITLE
Excel link not working

### ISSUE THREAD

**Issue by dipinn26592** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#319]
To see the options for licensing your users to benefit from Microsoft 365 compliance features as of April 1, 2020, download the Detailed Microsoft 365 Compliance Licensing Comparison. (PDF) | (Excel)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 licensing guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#feedback)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@dipinn26592 Thanks for your comments. I've forwarded your query to the product team and will make the update to the article based on their response.

**Comment by KCCross** [comment]
Fixed!
https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/pull/584
