### ISSUE TITLE
Inconsistency with Distribution group limits

### ISSUE THREAD

**Issue by masamig** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#32]
In [Distribution group limits across Office 365 options] section, "Maximum number of distribution group members" is defined as 100,000 members across all subscriptions. However, underneath of it, it also has the feature called "Maximum message size for distribution groups with 100,000 or more members" where distribution group with more than 100,000 members should not exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#feedback)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by SKjerland** [comment]
@masamig - If I understand you correctly, you're saying it should not say "or more" because the max is 100,000. Is that correct? The "or more" is actually there to cover Active Directory scenarios, which have higher limits. Please refer to footnote 1 below the "Distribution group limits across Office 365 options" table. Thanks!

**Comment by masamig** [comment]
@SKjerland  - Thank you for looking into this. Your understanding is correct, but the footnote 1 says "If you are using Azure Active Directory DirSync, the maximum number of distribution group members that you can synchronize from your on-premises Active Directory to Azure Active Directory is **15,000**. If you are using Azure AD Connect, that number is **50,000**." which is below 100,000. So "or more" still does not make sense to me...

**Comment by SKjerland** [comment]
@masamig - Sorry about that--you're correct. I'll reopen the issue and we'll take care of it. Thanks!

**Comment by masamig** [comment]
@SKjerland - Any updates on this? Thank you!

**Comment by SKjerland** [comment]
@masamig - This has been fixed and should be live shortly.

**Comment by masamig** [comment]
@SKjerland - Thank you for fixing this. I see that "or more" is removed but it created another conflict... The one above says "Maximum message size for distribution groups with 5,000 to **100,000** members" so if the limitation for groups with 100,000 is 5MB, that need to be changed as well, e.g. 99,999.

**Comment by SKjerland** [comment]
@masamig - This has been fixed and should be live shortly.
