### ISSUE TITLE
M365 business AAD P1

### ISSUE THREAD

**Issue by WoutVergauwen** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#320]
Azure AD: Cloud App Discovery, Azure AD Connect Health, SSO for more than 10 apps: should this not be yes now for M365 business?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1bface7-95b2-72b8-43b7-d3bd43b27d0c
* Version Independent ID: ac6756e4-bf78-278c-f8a1-89c182bf545d
* Content: [Licensing Microsoft 365 for small and medium-sized businesses - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/licensing-microsoft-365-in-smb)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/licensing-microsoft-365-in-smb.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/licensing-microsoft-365-in-smb.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@WoutVergauwen Thanks for your comments. I've forwarded your request to the product team and will update this article based on their response.
