### ISSUE TITLE
no Power Automate for Office 365 Business ?

### ISSUE THREAD

**Issue by Marijnsomers** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#321]
all other licenses have Power Automate, except for Business ? Doesnt sound right.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b5e7518-641b-6d9c-da4f-90f268949793
* Version Independent ID: bae3450b-35b4-d942-7012-7867a705150d
* Content: [Office 365 platform service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-platform-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@Marijnsomers Thanks for your comments. I have forwarded your query to the product team and will update the article based on their response.

**Comment by lhcole** [comment]
@Marijnsomers As per the product team, Office 365 Business is not a suite like other plans and is just the just the Office apps so it won't include SKU value features. Thanks for your query!
