### ISSUE TITLE
MS teams limitations per licence

### ISSUE THREAD

**Issue by tomashpetr** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#322]
Multiple microsoft official help pages reffer to this page as description of MS teams service limitations per specific licence..  I see no such information here.  Only somewhere else was a mention that "CORE teams features are available across all licences". No specification what are the CORE features and what the other.. 

Especially cooperation via scheduled meetings, audio conferences, etc. are of the question. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b5e7518-641b-6d9c-da4f-90f268949793
* Version Independent ID: bae3450b-35b4-d942-7012-7867a705150d
* Content: [Office 365 platform service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-platform-service-description?redirectedfrom=MSDN#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@tomashpetr Thanks for your comments. I have forwarded your query to the product team and will update the article if necessary based on their response.

**Comment by lhcole** [comment]
@tomashpetr For more information, please refer to the [Teams service description](https://docs.microsoft.com/office365/servicedescriptions/teams-service-description), and don't hesitate to get back in touch if you have further questions.
