### ISSUE TITLE
Sending Recipients Limit to 1000 still impacted by Mailbox Plan being lower

### ISSUE THREAD

**Issue by davidjcarr** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#323]
What is the point of having a limit of 1000 recipients if the EXO mailbox can be in a plan with a 500 recipient limit? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits?redirectedfrom=MSDN#feedback)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@davidjcarr Thank you for your comments. I have forwarded your query to the product team and will update the article if necessary based on their response.

**Comment by JeremyTBradshaw** [comment]
@lhcole @davidjcarr - while we're at it, might as well mention that the new base number is 400, not 500.  This change seems to have gone unannounced.
