### ISSUE TITLE
MS teams limitations per licence

### ISSUE THREAD

**Issue by tomashpetr** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#324]
Multiple microsoft official help pages reffer to this page as description of MS teams service limitations per specific licence.. I see no such information here. Only somewhere else was a mention that "CORE teams features are available across all licences". No specification what are the CORE features and what the other..

Especially cooperation via scheduled meetings, audio conferences, etc. are of the question.

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: 9035b5a9-1f84-54be-89ae-c3a0e53891f8
* Version Independent ID: cff57f08-ca51-2266-6189-1ce8181b942e
* Content: [Microsoft Teams service description - Service Descriptions](https://docs.microsoft.com/cs-cz/office365/servicedescriptions/teams-service-description)
* Content Source: [Office365-ServiceDescriptions/teams-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/teams-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by tomashpetr** [comment]
btw there is new F3 plan not covered on this page
Microsoft 365 F1 (New): will be rolled out later this year (April 1, 2020) and will provide the foundation of a secure and connected experience for Firstline Workers. It will include products like Microsoft Teams, SharePoint, Yammer, Stream, and Enterprise Security + Management. This plan will cost $4 per user, per month.

Microsoft 365 F3 (Updated): is in market today and will be renamed from “Microsoft 365 F1” to “Microsoft 365 F3” on April 1, 2020. It includes all the features in our new firstline plan, plus additional capabilities to enhance worker productivity and innovation. This plan costs $10 per user, per month.

see
https://www.microsoft.com/en-us/licensing/news/m365-firstline-workers

**Comment by SKjerland** [comment]
@tomashpetr - Thanks for your feedback! This article has been updated to reflect new plan names.
