### ISSUE TITLE
Delegate Access

### ISSUE THREAD

**Issue by martinfeehan8** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#325]
Is it correct that delegate access is available on Exchange Online Plan 1 but not available on Plan 2?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2f622a7-32c1-2c35-2df9-ddf1bc74c74d
* Version Independent ID: e37d85d2-8b81-0c64-b7d0-1e8c01b303db
* Content: [Exchange Online service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@martinfeehan8 Thanks for your question. I have forwarded your query to the product team and will update the content if necessary based on their response.

**Comment by KevinNSTA** [comment]
This looks like it is just a typo in the Markdown, causing the three items "Yes  | Yes | No" to be split as two Items "Yes|Yes | No" 
![image](https://user-images.githubusercontent.com/60158736/80632098-ba766b00-8a24-11ea-8088-50e24f857818.png)
