### ISSUE TITLE
Apps, Bots, & Connectors Features

### ISSUE THREAD

**Issue by jmccormick28** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#326]
Apps, Bots, & Connectors is YES across the board.

Does that YES only mean that the Apps, Bots, & Connectors features are available in all plans?

Or does it mean that the same Apps, Bots, and Connectors are available in all plans?

For example, does the GCC High Teams have the same apps available as the Small Business Teams?

If not, how do I find out which apps, bots, and connectors are available under each plan? (especially the GCC High plan).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9035b5a9-1f84-54be-89ae-c3a0e53891f8
* Version Independent ID: cff57f08-ca51-2266-6189-1ce8181b942e
* Content: [Microsoft Teams service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/teams-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/teams-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/teams-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@jmccormick28 Thanks for your comments. I have forwarded your query to the Product Team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @jmccormick28 1st party apps, bots and connectors are available in all plans, 3rd party apps are not available in GCC, GCC - High and DOD, 3rd party connectors and bots are available in GCC, not in GCC - High or DOD. There is not a list of which apps, bots and connectors are available.
