### ISSUE TITLE
Long Term Audit Retention?

### ISSUE THREAD

**Issue by dotnick365** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#329]
Can you clarify or add the availability/status of Long Term Audit Log retention (storing logs for 1 year for G5/E5 customers) for GCC environment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98a0960a-187c-ae13-7bec-7b883ff2fe1d
* Version Independent ID: 44562132-bd35-501b-f789-befd87164a09
* Content: [Plan for Microsoft 365 compliance - GCC - Service Descriptions](https://docs.microsoft.com/en-us/Office365/ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/plan-for-m365-compliance-gcc)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/plan-for-m365-compliance-gcc.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/plan-for-m365-compliance-gcc.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@dotnick365 Thanks for your comments. I have forwarded your query to the product team and will update the article if necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @dotnick365 Thank you for your patience.  This has been updated.
