### ISSUE TITLE
Long Term Audit Log Retention?

### ISSUE THREAD

**Issue by dotnick365** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#330]
Can you clarify or add the availability/status of Long Term Audit Log retention (storing logs for 1 year for G5/E5 customers) for GCC High environment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6a73833-f8b4-c9d2-d516-5b9fc62ce5a3
* Version Independent ID: 82ba6e0c-4da4-5d3d-1d35-032d63aac1e6
* Content: [Plan for Microsoft 365 compliance - GCC High - Service Descriptions](https://docs.microsoft.com/en-us/Office365/ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/plan-for-m365-compliance-gcc-high)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/plan-for-m365-compliance-gcc-high.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/plan-for-m365-compliance-gcc-high.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@dotnick365 Thanks again for your comments. I have forwarded your request to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @dotnick365 This has been updated in the service description.  Thank you.
