### ISSUE TITLE
Long Term Audit Log Retention?

### ISSUE THREAD

**Issue by dotnick365** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#331]
Can you clarify or add the availability/status of Long Term Audit Log retention (storing logs for 1 year for G5/E5 customers) for DOD/IL5 environment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50f94fe0-7e29-6338-aa87-34e8c9ba9096
* Version Independent ID: 550eb3fc-6cf4-744c-148f-383760193a50
* Content: [Plan for Microsoft 365 compliance - DoD deployments - Service Descriptions](https://docs.microsoft.com/en-us/Office365/ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/plan-for-m365-compliance-dod)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/plan-for-m365-compliance-dod.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/plan-for-m365-compliance-dod.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by aaronlemieux** [comment]
Hi @dotnick365 This has been updated in the service description.  Thank you.
