### ISSUE TITLE
"Outlook for iOS and Android" is missing in the the table of "Feature availability across Exchange Online standalone plans"

### ISSUE THREAD

**Issue by csjn** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#332]
"Outlook for iOS and Android" is missing in the the table of "Feature availability across Exchange Online standalone plans": https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description#feature-availability-across-exchange-online-standalone-plans

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2f622a7-32c1-2c35-2df9-ddf1bc74c74d
* Version Independent ID: e37d85d2-8b81-0c64-b7d0-1e8c01b303db
* Content: [Exchange Online service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@csjn Thanks for your comments. I have forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @csjn This has been completed and I am closing this item.

**Comment by csjn** [comment]
@aaronlemieux when do the changes get published? The latest version is from yestersday (August 31st), but does not contain "Outlook for iOS and Android" in the the table "Feature availability across Exchange Online standalone plans".

**Comment by aaronlemieux** [comment]
Hi @csjn Please allow 72 hours for this change to appear.
