### ISSUE TITLE
Incorrect restriction time (24 hours)

### ISSUE THREAD

**Issue by cabtilx** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#333]
The below is incorrect. From experience the restriction is always lifted at midnight UTC. So if sending to 10,000 recipients at 23:00 you will only be blocked for 1 hour.

After the recipient rate limit is reached, messages can't be sent from the mailbox until the number of recipients that were sent messages in the past 24 hours drops below the limit. For example, a user sends an email message to 5000 recipients at 09:00 AM, then sends another message to 2500 recipients at 10:00 AM, and then sends another message to 2500 recipients at 11:00 AM, hitting the limit of 10,000 messages. The user won't be able to send messages again until 09:00 AM the next day.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@cabtilx Thank you for your comments. I have forwarded your request to the product team and will update the content as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @cabtilx I've been speaking with the product team on this.  The service description currently lists the correct content, per our product team.  If you are experiencing what you stated, please open a support ticket.  For Support options, please see [Support](https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/support).

**Comment by cabtilx** [comment]
It was via a support ticket which I experienced this. Your support guys just read these documents and quote 24 hours. I'm telling you, that's now how your code works.

If your product team don't want to validate this behaviour that's fine. Hopefully people will see these comments and find the correct information.
