### ISSUE TITLE
Microsoft Teams client?

### ISSUE THREAD

**Issue by JonesMikael** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#334]
Is the Microsoft Teams client not a part of the Office applications service?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce6699a7-fdd4-a51b-3fdf-9e5ae3ab8cb4
* Version Independent ID: bd7aca02-e040-476f-4b64-1e5f02e90200
* Content: [Office applications - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-applications-service-description/office-applications)
* Content Source: [Office365-ServiceDescriptions/office-applications-service-description/office-applications.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-applications-service-description/office-applications.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@JonesMikael Thank you for your comments. I have forwarded your query to the product team and will update the content as necessary based on their response.

**Comment by lhcole** [comment]
@JonesMikael Thanks for your comments. I have forwarded your query to the product team and will update the content if necessary or supply you with an answer as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @JonesMikael This has been completed.
