### ISSUE TITLE
Office 365 Cloud App Security license typo

### ISSUE THREAD

**Issue by Sherd21** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#335]
Office 365 Cloud App Security marked as E3 but everywhere else (including Excel/PDF download at the top of the page) it's E5.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 663a603e-482b-0a4f-55a9-229ceab11bb1
* Version Independent ID: 488b1daa-b459-c56d-11eb-59242af822b0
* Content: [Security & Compliance Center - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center#security--compliance-center-availability-for-business-and-enterprise-plans)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@Sherd21 Thanks for reaching out. I have forwarded your query to the product team and will update the content as necessary based on their response.
