### ISSUE TITLE
Rebranded product names

### ISSUE THREAD

**Issue by jokruege** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#336]
The product names need to reflect the rebanding to M365 that happened on April 21. It is very confusing to customers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b5e7518-641b-6d9c-da4f-90f268949793
* Version Independent ID: bae3450b-35b4-d942-7012-7867a705150d
* Content: [Microsoft 365 and Office 365 platform service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-platform-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@jokruege Thanks for reaching out. The changes are live at the article link.
