### ISSUE TITLE
A3 and A5 include School Data Sync (Plan 2)

### ISSUE THREAD

**Issue by rsoakford** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#337]
As I understand from https://docs.microsoft.com/en-us/schooldatasync/create-users-for-k12-and-hed#prerequisites-for-sds there is a distinction between School Data Sync (Plan 1) or School Data Sync (Plan 2).

I believe School Data Sync (Plan 2) is included in plans A3 and A5 - can someone please confirm and update this document as necessary?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8328da3-5093-09b6-9b9b-b92d13625219
* Version Independent ID: f2171de5-bfa5-65d1-4615-30db23349b40
* Content: [Microsoft 365 Education - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@rsoakford Thanks for your comments. I have forwarded your query to the product team and will update the content as necessary based on their response.

**Comment by lhcole** [comment]
@rsoakford Hello. I am advised that School Data Sync is available across all plans and therefore the Microsoft Education service description is correct. See also [Get Office 365 free for your entire school](https://www.microsoft.com/en-us/microsoft-365/academic/compare-office-365-education-plans?activetab=tab:primaryr2). Thanks again for reaching out.
