### ISSUE TITLE
Download limits from SharePoint?

### ISSUE THREAD

**Issue by HandyAndyOnGitHub** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#338]
If I share a Folder containing 9000 files to an external company, sure they can individually browse all files, but when they attempt to download them all, only 200 files are download.  Aside from the fact that that's a ridiculously low number, would you please add this limitation to the documentation on this page.   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@HandyAndyOnGitHub Thanks for your comments. I have forwarded your request to the product team and will update the content as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @HandyAndyOnGitHub I've taken over this item and spoken with our product group.  There is no limit on the number of files from the store or the platform.  Thank you.
