### ISSUE TITLE
Update needed for Office 2019

### ISSUE THREAD

**Issue by mconwell** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#34]
If possible can this document be updated to include Office 2019? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61b8fbc9-7314-1e82-7c85-f0f9d3c3c1fd
* Version Independent ID: 7a5944ad-e785-5711-0954-f2be068e79d1
* Content: [Office Applications Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-applications-service-description/office-applications-service-description)
* Content Source: [Office365-ServiceDescriptions/office-applications-service-description/office-applications-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-applications-service-description/office-applications-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by prabita** [comment]
@mconwell - Thanks for your feedback, document is updated.
