### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by SvenBell** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#340]
Document state E3 no voicemail yet E3 has Exchange Online P2 and voicemail works

This is a great document, however, when do we get up to date version Microsoft Phone System equivalent?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 739a04a1-c23a-a39d-ceab-0829fb67dcb4
* Version Independent ID: 88842e84-ed6b-de2f-d3e2-865d86e71818
* Content: [Skype for Business Online service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/skype-for-business-online-service-description/skype-for-business-online-service-description)
* Content Source: [Office365-ServiceDescriptions/skype-for-business-online-service-description/skype-for-business-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/skype-for-business-online-service-description/skype-for-business-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@SvenBell Thanks for your comments. I have forwarded your query to the product team and will update the content as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @SvenBell This has been updated.  Thank you.
