### ISSUE TITLE
Mailbox retention

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#341]
Please add a note that soft-deleted mailboxes retain 30 days in the database (or are recoverable during this period).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#retention-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@trudolf-msft I added the note that you requested [here](https://review.docs.microsoft.com/en-us/Office365/ServiceDescriptions/exchange-online-service-description/exchange-online-limits?branch=pr-en-us-621#retention-limits).
