### ISSUE TITLE
Business Premium Missing

### ISSUE THREAD

**Issue by mosoccer** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#342]
It seems Business Premium is missing in the grids.  It would be really useful to have to compare Business Premium against Business Standard as well as the Enterprise licenses.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b5e7518-641b-6d9c-da4f-90f268949793
* Version Independent ID: bae3450b-35b4-d942-7012-7867a705150d
* Content: [Microsoft 365 and Office 365 platform service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-platform-service-description?redirectedfrom=MSDN#office-365-plans)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@mosoccer Thanks for your comments. I have forwarded your request to the product team and will update the content as necessary based on their response.

**Comment by garye686** [comment]
Further down the document there is a section on called [Microsoft 365 Business Premium service description](https://docs.microsoft.com/en-gb/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description). In it there is the statement: -
> Microsoft 365 Business Premium includes essentially all the features available in Microsoft 365 Business Standard along with additional Microsoft security features.
I'd agree it should be in this list for clarity but for high-level referencing it helps.

**Comment by aaronlemieux** [comment]
Hi, I've spoken with the product team and they are aware of this item.  This page is going to be undergoing a major revamp soon, so this table will no longer be relevant.  Thank you, I will be closing this item.
