### ISSUE TITLE
Need to add much more Education comparison

### ISSUE THREAD

**Issue by mfrymanciber** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#343]
You mention the Education products up top, and then leave them off the rest of the comparison completely.  Yet this is essential information to compare and contract all products.  If not on this page, then link to where they are all compared, even the not-for-profit options and whatever else there may be.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3fea44b-ae19-6168-157e-56e36c76b467
* Version Independent ID: 74e1c2f3-c8f7-16cf-0fd2-7d6007b12abb
* Content: [Office 365 plan options - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-plan-options#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-plan-options.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-plan-options.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@mfrymanciber Thanks for your comments. Does this link help? Please see the [Office 365 Education service description](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-education).
