### ISSUE TITLE
Permanently deleting trash in a full, outdated Hotmail acct!

### ISSUE THREAD

**Issue by cyrusromeo** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#344]
I have had a stand-alone Hotmail account (now known as Outlook) since the mid-90s. A few years ago, all of the contents of my folders disappeared... No warning. Last week, I was unable to send if reply to emails, due to "full trash". 
I have looked up tutorials on permanently deleting spam and trash folders but they are all for newer and office accounts.
Does anyone know of a resource or away to permanently delete my trash and Spam folders.
I am able 2 permanently delete trash on my smartphone and I will see a message reading there is no trash... Yet shortly thereafter it repopulates as I've only deleted 20 or so and that only bought me about a week (of doing this every day) of limping long to send and reply to emails.
Any direction or help would be greatly appreciated... Clearly I am not a techie!!
richardson.christa@gmail.com

**Comment by lhcole** [comment]
@cyrusromeo Sorry you're having issues. For support with your issue, please go to https://support.microsoft.com/en-us/contactus/. Thanks!
