### ISSUE TITLE
Navigation suggestion

### ISSUE THREAD

**Issue by stethom** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#346]
When I need to revise the Service Description with the latest What's New updates, I need to size the browser window so that it and Word are both fully visible, so that I can quickly produce a document detailing the needed changes. Unfortunately, this page hides the in-article shortcuts when I size the browser window below a certain width (not sure exactly how wide, but narrow enough to prevent side-by-side positioning). The TOC has no resize handle, so I can't reclaim the space. If Edge provided a horizontal scroll bar at the bottom I could enable side-by-side by scrolling toward the in-article shortcuts, but it doesn't. Basically, I can't have this side-by-side experience. This only adds a little bit of time and clicking to each feature update, but the annoyance is cumulative. 

Could you please add a resize handle to the TOC? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0d13579-5b95-82bd-4083-1919e38c034f
* Version Independent ID: 4bc5df6e-4168-3a3e-f72b-0aa327a492e8
* Content: [Excel for the web - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-online-service-description/excel-online#feedback)
* Content Source: [Office365-ServiceDescriptions/office-online-service-description/excel-online.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-online-service-description/excel-online.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@stethom Thanks Steven!
