### ISSUE TITLE
Possible restrictions with older devices/ OS/ and tools on GCC High

### ISSUE THREAD

**Issue by drewberrymore** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#347]
Hello,

Maybe I've missed this in the plethora of documentation regarding GCC High but I think it needs noting. 
Are there any current migration restrictions with the following items:
Older devices: iPhones/Androids; PC machines/Apple Macintosh
Operating Systems: Windows 7/8/8.1 / Apple MacOS 10.6 - 10.15
Software/Tools: Specific programs/tools used/or allowed in the current commercial environment that are specifically disallowed on GCC High

If further explanation is needed, I'll be happy to go into further detail.
Thanks for the help.

**Comment by lhcole** [comment]
@drewberrymore Thanks for reaching out. The product team has suggested this resource to answer your migration questions: [Mover migration now available worldwide](https://techcommunity.microsoft.com/t5/microsoft-sharepoint-blog/mover-migration-now-available-worldwide/ba-p/1185228).

**Comment by drewberrymore** [comment]
@lhcole Thank you for the response. However, this blog is literally no help. This article is about a migration tool that doesn't even support GCC High, which I mentioned in the question. (***Mover does not yet support migration to Office 365 government clouds (GCC, GCC-High or DoD)***) Does Microsoft not provide a detailed page/article that explains what can/cannot move to the it's creation?
