### ISSUE TITLE
Shared Mailboxes, Username/Password and License requirements

### ISSUE THREAD

**Issue by JuanZQ** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#348]
Microsoft should be more specific about a Shared Mailbox using a username and password. Here in Service Description, it should state that is required a license to be assigned is those scenarios. Some customers are using this, as it is technically possible. Every mailbox using logon and not using delegated access, must have a license.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2f622a7-32c1-2c35-2df9-ddf1bc74c74d
* Version Independent ID: e37d85d2-8b81-0c64-b7d0-1e8c01b303db
* Content: [Exchange Online service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@JuanZQ Thank you for your comments. I have forwarded your request to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @JuanZQ.  We appreciate your feedback.  I've spoken with the product team and this addition is under discussion as to how they wish to proceed.  For now, we do have [documentation](https://docs.microsoft.com/en-us/microsoft-365/admin/email/about-shared-mailboxes?view=o365-worldwide) available that says that shared mailboxes should always be kept disabled.
