### ISSUE TITLE
ATP is included in Microsoft 365 Business Premium

### ISSUE THREAD

**Issue by jvaught48** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#349]
The row for "Advanced threat management" has a footnote about Office ATP, and the link goes to an ATP docs page. So it would seem that "Advanced threat management" = "Advanced Threat Protection", in which case it should show "YES" under Microsoft 365 Business Premium. It would be very helpful if these rows aligned to the actual service names, *especially* in the area of ATP since the nomenclature is already confusing - threat management, threat protection, atp, mdatp, azure atp, microsoft threat protection, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 663a603e-482b-0a4f-55a9-229ceab11bb1
* Version Independent ID: 488b1daa-b459-c56d-11eb-59242af822b0
* Content: [Security & Compliance Center - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@jvaught48 Thanks for your comments. I've forwarded your request to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @jvaught48,

Thank you for reaching out to us.  I've spoken with the product team.  This table is correct.  AIP Plan 1 is included in Business Premium, but not AIP Plan 2.  Advanced Threat Management is a feature of Advanced Threat Protection, but they are not the same.  Advanced Threat Management is included in AIP 2, therefore it is not part of Business Premium.  I'll be closing out this ticket.
