### ISSUE TITLE
Inbox rule or individual transport rule is now support on F1 license.

### ISSUE THREAD

**Issue by OlegKP** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#35]
Inbox rule or individual transport rule is now support on F1 license.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#journal-transport-and-inbox-rule-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by OlegKP** [comment]
Inbox rule or individual transport rule is not support on F1 license.

**Comment by prabita** [comment]
@OlegKP Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response

**Comment by SharS** [comment]
@OlegKP Thanks for your feedback. The F1 information has been added to the article.
