### ISSUE TITLE
Microsoft Search should be added to the Microsoft 365 suite features section

### ISSUE THREAD

**Issue by dawholl** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#350]
List is incomplete, doesn't include Microsoft Search

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b5e7518-641b-6d9c-da4f-90f268949793
* Version Independent ID: bae3450b-35b4-d942-7012-7867a705150d
* Content: [Microsoft 365 and Office 365 platform service description - Service Descriptions](https://docs.microsoft.com/en-ca/office365/servicedescriptions/office-365-platform-service-description/office-365-platform-service-description#feature-availability-across-plans)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@dawholl Thanks for your comments. I've forwarded your request to the product team and will update the article as necessary based on their response.

**Comment by lhcole** [comment]
@dawholl @dawholl Thanks for your patience. The response from the product team is that for now Microsoft Search is not included in any of the service descriptions so as not to drive a wedge between Microsoft Search and MSB to the extent customers remained confused as to what Microsoft Search is – most assume now that it’s Bing.
