### ISSUE TITLE
list is incomplete, doesn't include Microsoft Search

### ISSUE THREAD

**Issue by dawholl** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#351]
please add Microsoft Search to this list. For more info about Microsoft Search, https://docs.microsoft.com/en-us/microsoftsearch/

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dd954d8-5874-8d25-36eb-0718ef86d585
* Version Independent ID: 001e3018-251d-dc72-c669-a21e303f21d7
* Content: [Microsoft 365 suite features - Service Descriptions](https://docs.microsoft.com/en-ca/office365/servicedescriptions/office-365-platform-service-description/office-365-suite-features)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-suite-features.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-suite-features.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@dawholl Thanks for reaching out. I've forwarded your comments to the product team and will update the article as necessary based on their response.

**Comment by lhcole** [comment]
@dawholl Thanks for your patience. The response from the product team is that for now Microsoft Search is not included in any of the service descriptions so as not to drive a wedge between Microsoft Search and MSB to the extent customers remained confused as to what Microsoft Search is – most assume now that it’s Bing.
