### ISSUE TITLE
Office 365 Message Encryption

### ISSUE THREAD

**Issue by carolinegibson** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#352]
Conflicting information between docs articles. The Exchange Online Service description (https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description) shows Office 365 Message Encryption (OME) as available in O365 E3 and E5. This page shows it only available in E5. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 663a603e-482b-0a4f-55a9-229ceab11bb1
* Version Independent ID: 488b1daa-b459-c56d-11eb-59242af822b0
* Content: [Security & Compliance Center - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@carolinegibson Thank you for your comments. I have forwarded your query to the product team and will update the article(s) as necessary based on their response.
