### ISSUE TITLE
O365 Message Encryption Conflicting Information 

### ISSUE THREAD

**Issue by carolinegibson** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#353]
Conflicting information between docs articles. The M365 and O365 Service Description (https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-platform-service-description) shows Office 365 Message Encryption (OME) as available in O365 E5 only. This page shows it only available in E3 and E5 as well as available as part of AIP. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2f622a7-32c1-2c35-2df9-ddf1bc74c74d
* Version Independent ID: e37d85d2-8b81-0c64-b7d0-1e8c01b303db
* Content: [Exchange Online service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by carolinegibson** [comment]
Correction... Security & Compliance Center page (https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center#feedback)

**Comment by lhcole** [comment]
@carolinegibson Thanks for reaching out. I have forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by lhcole** [comment]
@carolinegibson Hi Caroline. Can you clear up some confusion for me? Are you saying that the discrepancy is between the M365 and O365 platform service description page and the Security & Compliance Center page? I'm trying to determine where you're finding the difference. Thanks!

**Comment by carolinegibson** [comment]
Hey Leslie,

It’s the Security and Compliance page (https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center#feedback) And the  Exchange online page (https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description#feedback)

**Comment by lhcole** [comment]
@carolinegibson Then issue #352 and this issue are the same? Thanks.

**Comment by carolinegibson** [comment]
Yes, correct.

**Comment by lhcole** [comment]
@carolinegibson Thanks. I'm closing this issue and will track it in #352.
