### ISSUE TITLE
Storage quota for Recoverable Items folder in primary mailbox (on hold)

### ISSUE THREAD

**Issue by 3novsan** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#354]
If a Retention Policy has been applied from Security and Compliance Center to whole EXO Location, then would these mailboxes be considered as Mailboxes on hold?
And also would "Storage quota for Recoverable Items folder in primary mailbox (on hold)" which is 100 GB be applied for those EXO mailboxes or would it be only 30 Gigs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@3novsan Thanks for your comments. I have forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @3novsan ,

I have spoken with the product team to clarify these for you.  This service description does not need an update, according to our team.

"If a Retention Policy has been applied from Security and Compliance Center to whole EXO Location, then would these mailboxes be considered as Mailboxes on hold?"

Yes, this would be a hold, which would update the mailbox plan.

"And also would "Storage quota for Recoverable Items folder in primary mailbox (on hold)" which is 100 GB be applied for those EXO mailboxes or would it be only 30 Gigs?"

Yes, this would still be 100GB, as the mailbox plan has been updated.
