### ISSUE TITLE
Gigabytes or Gibibytes

### ISSUE THREAD

**Issue by Mindzweeper** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#355]
Does the GB in file size limit specify gigabytes (1,000,000,000) or gibibytes (2^30)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits#feedback)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@Mindzweeper Thanks for your comments. I have forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by Mindzweeper** [comment]
Thanks Leslie, I actually did some research yesterday and I was able to migrate a file with 16106127360 Bytes into a tenant with a 15 GB limit, so it appears that the limit is 15 GiB (15 x 2^30).
