### ISSUE TITLE
Confusion about licenserequirements for live events

### ISSUE THREAD

**Issue by magzzz** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#356]
This page says you get live-events with both small business and enterprise plans, but the following page says you need an enterprise-plan: https://support.office.com/en-us/article/get-started-with-microsoft-teams-live-events-d077fec2-a058-483e-9ab5-1494afda578a
I had a problem with a customer that needed live-events, but the feature was not available in his Teams-client. Assigning him Microsoft 365 E3 instead of Microsoft 365 Business Premium solved the problem, so that indicates that the info regarding this on this page is wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9035b5a9-1f84-54be-89ae-c3a0e53891f8
* Version Independent ID: cff57f08-ca51-2266-6189-1ce8181b942e
* Content: [Microsoft Teams service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/teams-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/teams-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/teams-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@magzzz Thanks for reaching out. No Small Business plans support Live Events. Your organization must have an Enterprise license to organize Live Events. This does not apply to attendees who can have a Small Business license or for that matter, no license at all to attend an event.
