### ISSUE TITLE
PCI-DSS version 1.2

### ISSUE THREAD

**Issue by pwes019** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#357]
This article states that "An independent third-party auditor determines that Microsoft Online Commerce Platform (OCP) has satisfactorily met the PCI-DSS version 1.2" But the current version of PCI-DSS is 3.2.1.  Can you please check the version number listed here is correct?  Additionally, if you are providing information about PCI Compliance, it would be useful if your "Attestation of Compliance" could be linked to this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d985a67-ac98-de0b-cfbb-4079e6efaaa6
* Version Independent ID: 64dacd15-6118-13cc-2bc4-3a573a21fa95
* Content: [Compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/compliance-servicedesc#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/compliance-servicedesc.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/compliance-servicedesc.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@pwes019 Thanks for your comments. I have forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by lhcole** [comment]
@pwes019 Thanks again for your comments. This service description is being retired. Please refer to the [Microsoft compliance offerings](https://docs.microsoft.com/en-us/microsoft-365/compliance/offering-home?view=o365-worldwide) page for the most current information.
