### ISSUE TITLE
Information Protection for Microsoft 365 "Business"

### ISSUE THREAD

**Issue by ssccaavvookk** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#358]
There are 3 levels of "Business" - Basic, Standard, and Premium. This page only lists "Business" as a beneficiary of information protection. But the comparison between standard and premium lists information protection under Premium: https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description

Can this be clarified to break out which level of M365 Business this applies to?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 licensing guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@ssccaavvookk Thanks for your comments. I have forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by lhcole** [comment]
@ssccaavvookk The change has been made to reflect Business Premium as the appropriate SKU. Thanks for reaching out.
