### ISSUE TITLE
Information Governance eligibility not consistent with other MS sites

### ISSUE THREAD

**Issue by benfletcherMS** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#360]
This page says that Information Governance is available to E1 and SharePoint Online Plan 1 users.  This is not consistent with this page which says E3 level licenses are required.  
https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#information-governance 

as well as this document - (https://docs.microsoft.com/office365/servicedescriptions/downloads/microsoft-365-compliance-licensing-comparison.xlsx).  

And lastly, the link for Information Governance in the Suite section is different to the link used in the standalone section.  This is impacting our ability to talk to customers who are now saying they only need SPO Plan 1 for these features.  Please contact me internally if you need more information.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 663a603e-482b-0a4f-55a9-229ceab11bb1
* Version Independent ID: 488b1daa-b459-c56d-11eb-59242af822b0
* Content: [Security & Compliance Center - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@benfletcherMS Thanks for your comments. I have forwarded your query to the product team and will update this article as necessary based on their response.

**Comment by lhcole** [comment]
@benfletcherMS The product team responded with changes to the section in this [service description](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#information-governance). Thanks!
