### ISSUE TITLE
Information Protection Plan 1

### ISSUE THREAD

**Issue by Orta373** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#361]
In the information protection section it states M365 E3/A3 are the skus with Azure Information Protection Plan 1 but the marketing site also shows that for M365 F3.   https://www.microsoft.com/en-us/microsoft-365/compare-microsoft-365-enterprise-plans

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 licensing guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#advanced-ediscovery)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@Orta373 Thanks for your comments. I have forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by lhcole** [comment]
@Orta373 AIP Plan 1 is now included with M365 F1 and F3 plans. Thank you.
