### ISSUE TITLE
Power Platform

### ISSUE THREAD

**Issue by variblex** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#362]
There is no specifics on Power Platforms Apps. Really wondering about power app (plan 1 or plan2)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8328da3-5093-09b6-9b9b-b92d13625219
* Version Independent ID: f2171de5-bfa5-65d1-4615-30db23349b40
* Content: [Microsoft 365 Education - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@variblex Thanks for your comments. What is your specific question, so I can forward it to the product team?

**Comment by aaronlemieux** [comment]
This has been resolved, I will be closing this item.
