### ISSUE TITLE
Resource account - assigning service license help links here

### ISSUE THREAD

**Issue by StuBeck32** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#364]
I'm having issues setting up a service phone number on a resource account, and the documentation for "more information" sends me here. I'm not sure how this page helps at all with setting this up, and instead is simply referring to what licenses are required.

I know this will likely just be closed as irrelevant, but I wasn't sure where to document the weird linking occurring on the Teams portal. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9035b5a9-1f84-54be-89ae-c3a0e53891f8
* Version Independent ID: cff57f08-ca51-2266-6189-1ce8181b942e
* Content: [Microsoft Teams service description - Service Descriptions](https://docs.microsoft.com/en-US/office365/servicedescriptions/teams-service-description)
* Content Source: [Office365-ServiceDescriptions/teams-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/teams-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@StuBeck32 Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response. Here is a link to Support options: [Support](https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/support).
