### ISSUE TITLE
Regex vs. word-matching transport rule limits

### ISSUE THREAD

**Issue by vitahall** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#365]
Hello,

Under **Journal, transport, and inbox rule limits**, the documentation says:

> * **Character limit for all regular expressions used in all transport rules** The total number of characters used by all the regular expressions in all the transport rule conditions and exceptions in the organization. You can have a few rules that use long and complex regular expressions, or you can have many rules that use simple regular expressions.

That's clear enough. However, Exchange Online itself is suggesting that this is shared with other non-regex matching rules. For example, when we edit a rule that doesn't use regex matching at all, we can get this error (see also screenshot below):

> The transport rule can't be created because you've exceeded the number of characters available for word- or pattern-matching in all your transport rules. Your transport rules are using 20743 characters, and the maximum number is 20480. Reduce the number of characters, either by removing content, such as words or regular expressions, from the conditions or exceptions, or by removing conditions or exceptions. Or delete existing transport rules that use word- or pattern-matching.

This message pretty strongly implies that the limit mentioned covers more than just regular expressions.

Can this be clarified? It seems like the Exchange Online behavior and error message are inconsistent with the documentation.

(This might be related to #189, at which time the answer was essentially "we do not enforce any limits in the system relating to _total_ size of rules", with a link back to the documentation in question. Perhaps something has changed in the meantime, or there's further clarification needed?)

Thanks very much,
Aaron

---

**Screenshot:**

<img width="758" alt="Screen Shot 2020-05-26 at 3 47 30 PM" src="https://user-images.githubusercontent.com/991605/82949446-41a5f880-9f69-11ea-9d85-f4ad3174e592.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#journal-transport-and-inbox-rule-limits-across-office-365-options)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@vitahall Thanks for your comments. I have forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @vitahall This has been completed and I am closing this request.
