### ISSUE TITLE
Inconsistency between Docs sites for Information Governance. 

### ISSUE THREAD

**Issue by benfletcherMS** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#366]
This page says that every plan gets Information Governance.  The page in the link below says E3 and up is required.  

https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#information-governance

This inconsistency is confusing to Microsoft's customers.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 663a603e-482b-0a4f-55a9-229ceab11bb1
* Version Independent ID: 488b1daa-b459-c56d-11eb-59242af822b0
* Content: [Security & Compliance Center - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@benfletcherMS Thanks for your query. I've forwarded your comments to the product team and will update the article as necessary based on their response.

**Comment by lhcole** [comment]
@benfletcherMS Thanks for your patience. The product team and replied with the following: The Excel worksheet shows the most details. Most of the Information Governance capabilities are available in E3 and E5, with only a limited, such as “import PST”, “email archiving”, and “apply non-record retention labels manually” are available to E1. We'll make updates to the service description for clarification.
