### ISSUE TITLE
Compatible M365 plans are missing

### ISSUE THREAD

**Issue by JelmerBarhorst** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#367]
[Enter feedback here]
M365 E3, E5, F1 and F3 are not listed as compatible, but they should be as the all contain Teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abdc7fbf-1f49-704b-cad5-08f15e811642
* Version Independent ID: 2a9be28e-06a1-bfff-766c-de34214e7fba
* Content: [Microsoft 365 Business Voice service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-business-voice-service-description)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-business-voice-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-business-voice-service-description.md)
* Service: **o365-administration**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by lhcole** [comment]
@JelmerBarhorst Thanks for your comments. I have forwarded them to the product team and will update the article as necessary based on their response.
