### ISSUE TITLE
No clarity on SPO DocLib Item limit and relation to List View Threshold issue.

### ISSUE THREAD

**Issue by cloudpostman** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#368]
We have been migrating lot of file server data to SharePoint Online DocLib for various clients.
Our challenge is with item limits and list view threshold issues.
Can we know how much limit should we set for items count for each library? should we keep it 20k, 50k, >100k?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@cloudpostman Thanks for your comments. I have forwarded your query to the product team and will update the article as necessary based on their comments. For Support options, see [Support](https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/support).

**Comment by lhcole** [comment]
@cloudpostman The limit definition can be found in the [official support document](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits). The max number of items per library is 30m. However, as a library is getting larger, there are other limitations/restrictions as mentioned in the document. We recommend keeping the library small, as it comes with other benefits, such as usability for users to navigate and manage documents with the library, permission manageability, and so on.
