### ISSUE TITLE
Office 365 US Government G5 missing....hopefully....

### ISSUE THREAD

**Issue by scottyv** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#369]
Looking to see if there is a typo under the table on this link: https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center#security--compliance-center-availability-for-business-and-enterprise-plans.  The Office 365 Enterprise E5 heading, does *not* include Office 365 US Government G5.  The other headers do include the corresponding Office 365 US Government label.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 663a603e-482b-0a4f-55a9-229ceab11bb1
* Version Independent ID: 488b1daa-b459-c56d-11eb-59242af822b0
* Content: [Security & Compliance Center - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@scottyv Thank you for your comments. I have forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi Scottyv, this item has been completed.  Thank you.
