### ISSUE TITLE
Request to add 'default' about Note that related to address book.

### ISSUE THREAD

**Issue by TomonoriAbe** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#37]
https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description

In Exchange Online Service Description, there is the description that may cause misunderstand.
From this, the customer may think MS doesn't support customizing adddress lists/global address lists not at all. Because customizing needs PowerShell(cmdlet).
In my understanding, the meaning of this row is whether users with plans can simply see address lists and global address list or not. It means customizing 'default' address lists and 'default' global address list is not supported.
This understanding is correct, would you update the content as following Idea?

Currently
----
18 Using a cmdlet to work with the Address List and Global Address List is not supported. 
----

Idea
----
18 Using a cmdlet to work with the default Address List and default Global Address List is not supported. 
----

**Comment by chrisda** [comment]
@TomonoriAbe, OK. Done. Fixed as you described. Closing.
