### ISSUE TITLE
Retention Policy support

### ISSUE THREAD

**Issue by douglasgaigher** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#370]
In the "Detailed Microsoft 365 Compliance Licensing Comparison" Excel Spreadsheet, the feature "Apply a basic retention policy to the entire organization, specific locations or users" is not marked as available for the licenses "Microsoft 365 Business Premium" and "Exchange Online Archiving".

Is that correct? I ask because in this page is stated bellow the tables:

"11 An Exchange Online Plan 2 or Exchange Online Archiving license is required to retain content in a user mailbox by using a retention policy."

And the license "Microsoft 365 Business Premium" does include the "Exchange Online Archiving" option.

Thanks

--

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 663a603e-482b-0a4f-55a9-229ceab11bb1
* Version Independent ID: 488b1daa-b459-c56d-11eb-59242af822b0
* Content: [Security & Compliance Center - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@douglasgaigher Thank you for your comments. I have forwarded your query to the product team and will update the article as necessary based on their response.
