### ISSUE TITLE
What about new Safe Documents feature

### ISSUE THREAD

**Issue by ArttuArstila** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#371]
Which O365 ATP Plan grants it?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 502796e9-ca73-7123-7719-c7b5b1042b7b
* Version Independent ID: 2929af88-6d56-4de3-2b4e-4e1d0e4d97ef
* Content: [Office 365 Advanced Threat Protection service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description)
* Content Source: [Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@ArttuArstila Thank you for your query. The product team has responded as follows: Safe Documents is a feature in Office 365 ATP that uses Microsoft Defender ATP to scan documents and files that are opened in Protected View. It’s available to users with M365 E5 or M365 E5 Security licenses. More information is available [here](https://docs.microsoft.com/microsoft-365/security/office-365-security/safe-docs?view=o365-worldwide).

**Comment by ArttuArstila** [comment]
Hi! Thanks for the reply. As the name states, it is a new feature of Office 365 ATP. So I think it should be mentioned on the service description page.
