### ISSUE TITLE
Multilingual user interface not available with Business subscriptions?!

### ISSUE THREAD

**Issue by teomonda** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#372]
Hello,
i see in the above tables that "multilingual user interface" does not seem to be available with Business subscriptions.
whereas here:
https://docs.microsoft.com/en-us/deployoffice/overview-deploying-languages-microsoft-365-apps
where we talk about how to deploy languages, Business is listed as well.
Am i confusing what "multilingual user interface" means here or is this incorrect?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 128805e7-b1a4-5cdf-1890-8794fa46d5d5
* Version Independent ID: 884c3ae0-9317-d37c-f94f-97aabd0e622d
* Content: [Office applications service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-applications-service-description/office-applications-service-description)
* Content Source: [Office365-ServiceDescriptions/office-applications-service-description/office-applications-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-applications-service-description/office-applications-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@teomonda Thanks for your comments. I have forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by teomonda** [comment]
hello Leslie, do you have any updates here?

**Comment by teomonda** [comment]
Hi Leslie, I am sure you do not have any updates as you would have posted here if so. Anything i can do (as a Microsoft employee) to push for getting an answer here?

**Comment by lhcole** [comment]
@teomonda Hi! Changes will go live later this morning. I am closing this issue. Thanks for your patience.
