### ISSUE TITLE
Moving and copying across sites

### ISSUE THREAD

**Issue by nswain23** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#373]
For the section 'Moving and copying across sites' it states a value of 100GB per operation.  Customers are confusing this with the 'Move to' and 'copy to' functionality in the SPO UI which has a current limit of 2GB and an advised limit of 500MB.  This article specifies the limit as https://support.microsoft.com/en-us/office/copy-files-and-folders-between-onedrive-and-sharepoint-sites-67a6323e-7fd4-4254-99a8-35613492a82f.  The code specifies the limit as 2147483648 bytes (2GB).  Please clarify this in the article and what the '100BGB per operation' refers to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits#service-limits-for-all-plans)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@nswain23 This article has been updated. Thanks for your comments!
