### ISSUE TITLE
Microsoft Bookings availability in Government Cloud?

### ISSUE THREAD

**Issue by tmsquared** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#374]
This page stills says "No" but one of my Government clients "heard" it would be available in the GCC within a month. Is there an update from the product team?

Thanks!
Tom

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3ab3187-c403-8fb1-6ee7-56818777fdad
* Version Independent ID: f6b28482-bf80-436e-cb8f-facb974c24ec
* Content: [Office 365 US Government - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md)
* Service: **o365-administration**
* GitHub Login: @danarl
* Microsoft Alias: **danarl**

**Comment by lhcole** [comment]
@tmsquared Thanks for your inquiry. The product team has responded with the following: We have no plans at this time to make Bookings available in the GCC environment; However, we are exploring this for future expansion.

**Comment by lhcole** [comment]
@tmsquared Future dates of any Microsoft 365 products can be referenced on the [Microsoft Roadmap](www.microsoft365.com/roadmap). Note the entry for [Bookings in GCC](https://www.microsoft.com/en-us/microsoft-365/roadmap?ms.url=m365comroadmap&rtc=1&filters=&searchterms=Bookings).
