### ISSUE TITLE
Exchange Online Legal Hold/Retention support for mails sent from POP/IMAP/SMTP clients

### ISSUE THREAD

**Issue by randhir47** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#376]
[Enter feedback here]

Earlier this page noted that "in-place hold and litigation hold currently do not apply to emails sent using POP or IMAP clients, or by custom applications that use the SMTP protocol."

Is it fixed now?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42f3fbc2-e112-bba6-da3d-209d286825e2
* Version Independent ID: 83309966-d50b-f608-9d43-6dcfd5e72588
* Content: [Compliance and security features in Exchange Online Archiving - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-archiving-service-description/compliance-and-security-features)
* Content Source: [Office365-ServiceDescriptions/exchange-online-archiving-service-description/compliance-and-security-features.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-archiving-service-description/compliance-and-security-features.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@randhir47 Thanks for your query. I have forwarded this to the product team and will update this article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @randhir47 

Per the below article, messages sent via authenticated SMTP are supposed to be copied to Sent Items.
[Changes in message store and throttling for concurrent connections - Exchange | Microsoft Docs](https://docs.microsoft.com/en-us/exchange/troubleshoot/send-emails/smtp-submission-improvements)
