### ISSUE TITLE
Not enough information about OATP P2

### ISSUE THREAD

**Issue by JPCortesP** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#377]
This topic should be more clear on the requirements for attack simulator. Does the P2 plan is required for users being subject of an attack simulation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 licensing guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#office-365-advanced-threat-protection)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@JPCortesP Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by JPCortesP** [comment]
> @JPCortesP Thanks for your comments. To clarify before I forward your query to the Product team. Have you taken a look at [Office 365 Advanced Threat Protection](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/office-365-atp?view=o365-worldwide)? Does the article have the specifics you're looking for?

Yes it does, kinda. The point of this article is to explain how to manage tenant-wide security/compliance licenses that enable the service for everyone even when the customer only have 1 unit. So, in the spirit of being clear, I think that this article should state whether or not a customer have to license every user with O365 ATP P2 when those users are the subject of an Attack Simulator (a functionality that is only available in P2), instead of let's say, just licensing the admin users sending those attacks. Makes sense?

**Comment by lhcole** [comment]
@JPCortesP Thanks for clarifying. I'll forward your comments to the product team and update the licensing article as necessary based on their response.

**Comment by JPCortesP** [comment]
@lhcole thank you so much! Appreciated!

**Comment by jsmsaulo** [comment]
It's important to have more clarity on tenant level licenses to avoid un-compliant scenarios, so as JPCortesP mentioned, we need clarity on the requirements and consequences of partial licensing versus using it for the whole tenant.

**Comment by lhcole** [comment]
@JPCortesP Thanks for you patience. The product team replied with the following: The licensing model requires customers to have purchased P2 licenses for all targets of phish simulation using the attack simulation tool, unless otherwise noted. We don’t do a technical enforcement of that requirement today, and we do have plans in the future to release a "teaser" scenario for all customers to do a basic phish training scenario. Agreed that the documentation should state clearly that P2 licensing is required for all targets of phish simulation.

**Comment by JPCortesP** [comment]
Thank you @lhcole. That means that the docs will be updated with this?

**Comment by lhcole** [comment]
@JPCortesP If the product team sends me a request to make the changes, I will update the article. They are aware of your request. Hope this helps.
