### ISSUE TITLE
Invalid Link

### ISSUE THREAD

**Issue by RetroPillow** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#38]
The link for Microsoft Online Services Use Rights (https://www.microsoft.com/licensing/products/products.aspx) Is invalid!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 732a76e7-16da-9d55-a6da-99ee2589970b
* Version Independent ID: c691bc62-65b4-57ec-7c90-c3731e37837d
* Content: [Product Use Rights](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/product-use-rights)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/product-use-rights.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/product-use-rights.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by SKjerland** [comment]
@RetroPillow - Thanks for bringing this to our attention. The link has been fixed.
