### ISSUE TITLE
Licensing 1 user versus Licensing Whole Tenant

### ISSUE THREAD

**Issue by jsmsaulo** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#380]
The whole documentation of this page is unclear as to the consequences of licensing 1 user and the features being available to the whole tenant versus only those licensed users to the multiple workloads. Is there audit / compliance issues with that? If so, what if the user activate it without the knowledge, like conditional access or DLP where it's easy to configure for everyone and not everyone who configures it understand licensing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 licensing guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@jsmsaulo Thanks for you comments. I have forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by lhcole** [comment]
@jsmsaulo Thanks again for your query. The product team has responded as follows: Take a look at the opening paragraphs of [Microsoft 365 licensing guidance for security & compliance](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance). The guidance is to license every user that intends to benefit from the service. We also advise customers to take the necessary efforts to comply with the license as we do not have technical enforcement.
