### ISSUE TITLE
Table Data Misaligned for EOL Plan 2: Delegate access

### ISSUE THREAD

**Issue by RyanBHernandez** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#381]
Please update table so it shows as YES.  Looking at the page, or exporting to excel shows this as NO.  
![EOL Plan 2 Delegate Access Misaligned](https://user-images.githubusercontent.com/61576363/85110590-b6591380-b245-11ea-83cf-98b8164a1d2f.PNG)

**Comment by lhcole** [comment]
@RyanBHernandez Happy to fix this. Can you send post the link here for the service description article where this table appears? Thanks.
