### ISSUE TITLE
Compliance Score

### ISSUE THREAD

**Issue by carlova** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#382]
Compliance Score is currently not available in GCC High, should that be reflected on this document?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6a73833-f8b4-c9d2-d516-5b9fc62ce5a3
* Version Independent ID: 82ba6e0c-4da4-5d3d-1d35-032d63aac1e6
* Content: [Plan for Microsoft 365 compliance - GCC High - Service Descriptions](https://docs.microsoft.com/en-us/Office365/ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/plan-for-m365-compliance-gcc-high?source=docs)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/plan-for-m365-compliance-gcc-high.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/plan-for-m365-compliance-gcc-high.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@carlova Thanks for your comments. I have forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @carlova This SD has been updated and we're closing things on our end.
