### ISSUE TITLE
License SKUs that can Apply non-record retention labels manually is incorrect

### ISSUE THREAD

**Issue by TimHayward** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#383]
In section
https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#which-licenses-provide-the-rights-for-a-user-to-benefit-from-the-service-6

the text:
Office 365 E5/A5/E3/A3/E1/A1 provides basic information governance capabilities to apply non-record retention labels manually, import PST files, and archive email.

should be:
Office 365 E5/A5/E3/F3/A3/E1/A1 provides basic information governance capabilities to apply non-record retention labels manually, import PST files, and archive email.

The detail in the Microsoft 365 Compliance Licensing Comparison. (https://docs.microsoft.com/en-us/office365/servicedescriptions/downloads/microsoft-365-compliance-licensing-comparison.xlsx) confirms the ability to Apply non-record retention labels manually is available to Microsoft 365 F3 users

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 licensing guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#which-licenses-provide-the-rights-for-a-user-to-benefit-from-the-service-6)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@TimHayward Thanks for your comments. The Information Governance section of the Microsoft 365 licensing guidance for security & compliance service description is being updated and changes will go live later today.
