### ISSUE TITLE
Conditional Access policies - 

### ISSUE THREAD

**Issue by Remi007** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#384]
[Enter feedback here]
Hello,

https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#conditional-access-policies

Now:
Which users benefit from the service?
Licensed users of Enterprise Mobility + Security E3/A3, Microsoft 365 F3/E3/A3, and Azure Active Directory Premium Plan 1 can benefit from Conditional Access policies. Licensed users of Enterprise Mobility + Security E5/A5/G5, Microsoft 365 E5/A5, Microsoft E5 Security, and Azure Active Directory Premium Plan 2 can benefit from Identity Protection (risk-based Conditional Access policies).

Should be: 
Which users benefit from the service?
Licensed users of Enterprise Mobility + Security E3/A3, Microsoft 365 F3/E3/A3/**Business Premium**, and Azure Active Directory Premium Plan 1 can benefit from Conditional Access policies. Licensed users of Enterprise Mobility + Security E5/A5/G5, Microsoft 365 E5/A5, Microsoft E5 Security, and Azure Active Directory Premium Plan 2 can benefit from Identity Protection (risk-based Conditional Access policies).

Regards
Remi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 licensing guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#feedback)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by lhcole** [comment]
@Remi007 Thanks for your comments. I have forwarded your request to the product team and will update the article as necessary based on their response.
