### ISSUE TITLE
RuleQuota 8kb seems to NOT be correct

### ISSUE THREAD

**Issue by chrislehr** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#385]
Noticed that here: https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#journal-transport-and-inbox-rule-limits-1 it stated 8kb, however we found that a mailbox migrated from on premises was 64kb and a mailbox provisioned in EXO was 256kb.

Also, we found this post here that highlights there is no reporting on size:
https://answers.microsoft.com/en-us/msoffice/forum/all/get-mailboxrule-size/bc9822c1-9b02-422e-84ff-763760cffb9e

I wrote this script - it seems to just about right at measuring the character count and assumes 1 character = 1 byte.

https://github.com/chrislehr/InboxRuleSize/tree/master

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by chrislehr** [comment]
Sorry - was not clear on the issue - the maximum single rule size is 8kb, but I dont see the max rule set size published/advertised in the SD.

**Comment by aaronlemieux** [comment]
@chrislehr Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response

**Comment by aaronlemieux** [comment]
Hi @chrislehr The SD has been updated per your request and we are closing this item.
