### ISSUE TITLE
Domain and subdomain limits

### ISSUE THREAD

**Issue by Evangeliste** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#386]
Hello

For the domain name limits to 900, can you confirm that included the subdomain ?

Thanks

**Comment by aaronlemieux** [comment]
Hi @Evangeliste,

I'd love to further address your issue and find the right answers for you.  Before I do so, can you clarify if this is the service description you are referring to, which needs updates?

[](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/domains)

**Comment by Evangeliste** [comment]
Hi @aaronlemieux 

Thanks for you for your return, Yes I confirm you.
In this article, it's explain for the top level domain name but for the sub-domain it's not very clear.

**Comment by aaronlemieux** [comment]
Hi @Evangeliste.  This update has been made for you.
