### ISSUE TITLE
Subscription not shown?

### ISSUE THREAD

**Issue by fixx-er** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#387]
[Enter feedback here]
I believe this page needs to have the new name change for subscriptions.  i.e. "Business Basic" and "Business Premium" is shown, but not "Standard"  So is it inferred because the basic and premium is stated?  Low to high?
sj
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by aaronlemieux** [comment]
Hi @fixx-er, 

Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @fixx-er We've updated this SD and are closing this issue on our end.
