### ISSUE TITLE
Consider adding a column for Student Use Benefit

### ISSUE THREAD

**Issue by born-slippy** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#388]
Please consider adding specific information relating to the Student Use Benefit licensing and which products this license receives.  For example, A3 Student Use Benefit does not include Bookings.  There is no notation that makes this clear.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8328da3-5093-09b6-9b9b-b92d13625219
* Version Independent ID: f2171de5-bfa5-65d1-4615-30db23349b40
* Content: [Microsoft 365 Education - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by aaronlemieux** [comment]
Hi @born-slippy,

Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @born-slippy.  This has been updated.

**Comment by born-slippy** [comment]
Thank you!
