### ISSUE TITLE
5000 Limit

### ISSUE THREAD

**Issue by ravick4u** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#389]
I have two doubts regarding group limits,

- Under  SharePoint groups, it says that "a user can belong to 5000 groups", does this limit is per site collection or across all site collection or across all GEO(We have multi-geo with more than one tenant)?
- What will happen if we we have a user in more then 5000 groups?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @ravick4u We've updated this service description, and are closing this issue on our end.
