### ISSUE TITLE
Data Backup - Missing information

### ISSUE THREAD

**Issue by TotallyInformation** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#39]
The section [Data Backup](https://docs.microsoft.com/en-us/office365/servicedescriptions/project-online-service-description/project-online-service-description#data-backup) refers you to the "Data Backup section in SharePoint Online Service Description". However, that section does not exist on the referred page (searching for "data backup" or "backup" on the page results in no entries).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69451b60-fdc1-4b81-d154-cdd38931a902
* Version Independent ID: f90ef8b6-b8ed-37d8-d5c6-da25f96a0a1d
* Content: [Project Online Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/project-online-service-description/project-online-service-description#data-backup)
* Content Source: [Office365-ServiceDescriptions/project-online-service-description/project-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/project-online-service-description/project-online-service-description.md)
* Product: **office-online-server**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by SKjerland** [comment]
@TotallyInformation - Thanks for bringing this to our attention. We updated this section and fixed the issue.
