### ISSUE TITLE
what is the limit for the number of Hub Sites?

### ISSUE THREAD

**Issue by sfarq** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#391]
[Enter feedback here]
You recommend not creating subsites and instead use the hub and associated site flat model instead. Question - Is there a limit to the number of hub sites? I know it originally was 50 and then increased to 100 in Sept 2018. Is it still at 100? If so, the page should say this.

Current paragraph on subsites:
"Subsites

2,000 per site (site collection). We recommend creating sites and organizing them into hubs instead of creating subsites. If you do use subsites, we recommend limiting their number (especially on heavily trafficked sites)."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by aaronlemieux** [comment]
Hi @sfarq, thank you for reaching out to us.  The information you're looking for is in the service descrption for [Planning your SharePoint hub sites](https://docs.microsoft.com/en-us/sharepoint/planning-hub-sites), which is linked from the main service description for [SharePoint service description](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-service-description)

"Your organization is limited to 2,000 hub sites. You may not need a hub site for every function and it's important to do some planning before you create hubs."

We appreciate your feedback.  If you need anything else, please don't hesitate to reach out.

**Comment by sfarq** [comment]
Hi @aaronlemieux Thanks for your response. 
I appreciate you pointing me to the Hub organisation limit of 2000. Very useful. 
But it would be even better if this "limit" was listed on the SharePoint Online Limits page. Perhaps next to the SubSites limit...
https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits?redirectedfrom=MSDN#subsites

**Comment by aaronlemieux** [comment]
Hi @sfarq We've gone ahead and added this.  Thank you.
