### ISSUE TITLE
Office Message Encryption for G1

### ISSUE THREAD

**Issue by johntchoi** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#392]
The documentation for availability of Office Message Encryption in Office 365 Government G1 says "No."  However under Office 365 Enterprise E1 (https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description?redirectedfrom=MSDN#feature-availability) it is "No" with a footnote that AIP can be purchased as a separate add-on.  Is this option available for Government G1 or only Commercial?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3ab3187-c403-8fb1-6ee7-56818777fdad
* Version Independent ID: f6b28482-bf80-436e-cb8f-facb974c24ec
* Content: [Office 365 US Government - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government#platform-features)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md)
* Service: **o365-administration**
* GitHub Login: @danarl
* Microsoft Alias: **danarl**

**Comment by aaronlemieux** [comment]
Hi @johntchoi.  Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @johntchoi.  I've spoken at length with our product team about this.  Here is what they have to say:

Office Message Encryption is available for G1 by purchasing AIP P1.  AIP P1 is available for Gov customers.
