### ISSUE TITLE
Azure AD Premium P1 now fully available for Microsoft 365 Business Premium

### ISSUE THREAD

**Issue by ChrisAtMAF** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#393]
According to recent updates here:
https://techcommunity.microsoft.com/t5/small-and-medium-business-blog/azure-active-directory-premium-p1-is-coming-to-microsoft-365/ba-p/1275496

'We have completed the rollout of Azure AD Premium P1 to all Microsoft 365 Business Premium customers and this should be available to both existing and new subscribers. '

This needs reflecting in a number of places in this article, including:

'Identity and access management
Full Azure AD Premium P1 is rolling out soon to Microsoft 365 Business Premium customers. For more information, check out this blog post.8'

Plus consider removing these footnotes which are now irrelevant:

'8 Microsoft 365 Business Premium includes the following Azure AD Premium P1 features: self-service password reset with AD write-back, Azure Multi-Factor Authentication (MFA), and Conditional Access. It does not include the entirety of Azure AD Premium P1.'

'11 Full Azure AD Premium P1 is rolling out soon to Microsoft 365 Business Premium customers. For more information, check out this blog post.'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94c91b3d-d9b1-9056-ae3e-51a255ed88ec
* Version Independent ID: b60613bc-f7b3-d1c7-4d8e-924c0f87912f
* Content: [Microsoft 365 Business Premium service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @ChrisAtMAF We've updated this SD and are closing things on our end.
