### ISSUE TITLE
EMS E3 column and Note 11 changes

### ISSUE THREAD

**Issue by markoshea1212** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#394]
In the Identity and access management, Device and application management sections EMS E3 is one of the comparison items. It seems to me that it would make more sense to change that to M365 E3, and you wouldn't even need to change any of the items in the column because they would all still be a Yes anyway because it includes EMS E3.

For note 11 - I think this is safe to update, AADP P1 should be part of all tenants by now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94c91b3d-d9b1-9056-ae3e-51a255ed88ec
* Version Independent ID: b60613bc-f7b3-d1c7-4d8e-924c0f87912f
* Content: [Microsoft 365 Business Premium service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @markoshea1212 We've updated this SD and are closing this issue on our end.
