### ISSUE TITLE
Private channels are in GCC today

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#396]
"Private channels are not available in GCC clouds at this time. " is incorrect.  O365 GCC has private channels today.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9035b5a9-1f84-54be-89ae-c3a0e53891f8
* Version Independent ID: cff57f08-ca51-2266-6189-1ce8181b942e
* Content: [Microsoft Teams service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/teams-service-description)
* Content Source: [Office365-ServiceDescriptions/teams-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/teams-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @npherson We've updated this SD and are closing this issue on our end.

**Comment by npherson** [comment]
While the narrative was removed, the chart still indicates that Private Channels are not available in GCC...

**Comment by aaronlemieux** [comment]
Thank you @npherson We'll get this updated as well.

**Comment by aaronlemieux** [comment]
Hi @npherson.  This has been updated.
