### ISSUE TITLE
Unless I am mistaken, there is NO reference to Microsoft 365 Business Premium in this document.  I expected to find it here.

### ISSUE THREAD

**Issue by jah1subs** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#397]
[Unless I am mistaken, there is NO reference to Microsoft 365 Business Premium in this document.  I expected to find it here.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 licensing guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @vtrscho
* Microsoft Alias: **v-trscho**

**Comment by aaronlemieux** [comment]
Hi @jah1subs,

Thank you for reaching out to us.  The references to Microsoft 365 Business Premium are the in the .pdf file that is linked from the service description.  It lists all features included in this license.  You can access the link from the service description, or, for your convenience, I have included it [here](https://opdhsblobprod04.blob.core.windows.net/contents/e0993bf6e82e4fa8ac18b48839521869/2ce5e803079c3427c011efbce08b900a?sv=2018-03-28&sr=b&si=ReadPolicy&sig=irRNtOtHGyShE7I6n8Y%2B%2BtliuPQgBdnZk8yRnxLtbqg%3D&st=2020-07-23T18%3A02%3A25Z&se=2020-07-24T18%3A12%3A25Z).
