### ISSUE TITLE
GCC Purchase Direct from Microsoft

### ISSUE THREAD

**Issue by davetools** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#398]
For a small government organization that already has a Microsoft 365 active tenant, is it possible to renew and have our account direct with Microsoft instead of through a partner vendor?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86dc9aff-0190-52d9-2ab0-4f236d862739
* Version Independent ID: f6cbf527-2a7d-edd6-49b9-ca70ba43b9d6
* Content: [Microsoft 365 Government how to buy - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/microsoft-365-government-how-to-buy)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/microsoft-365-government-how-to-buy.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/microsoft-365-government-how-to-buy.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
I'm sorry that you're having this issue. For Support options, please see [[Support](https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/support)]().
