### ISSUE TITLE
Please add some information about not being able to disable the antimalware scan

### ISSUE THREAD

**Issue by ArendvanDijk** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#399]
Hi there,

Please add that the antimalware scan is not disableable, I am now having a discussion with the customer who would like to see this on docs.microsoft.com.

Thnx.

Regards,
Arend

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa81c393-be6f-402a-5a40-fd7bdf2eac83
* Version Independent ID: 056d6537-d3d3-9828-d4a4-11e7aec12503
* Content: [Anti-spam and anti-malware protection\[EOP\] - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-protection-service-description/anti-spam-and-anti-malware-protection-eop)
* Content Source: [Office365-ServiceDescriptions/exchange-online-protection-service-description/anti-spam-and-anti-malware-protection-eop.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-protection-service-description/anti-spam-and-anti-malware-protection-eop.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by chrisda** [comment]
@aaronlemieux, go ahead and update the topic. Anti-malware scanning can't be disabled.

**Comment by aaronlemieux** [comment]
Hi @ArendvanDijk This service description has been updated per your request.  I'm going to close this item.  Thank you!
