### ISSUE TITLE
Remove Access Services

### ISSUE THREAD

**Issue by vettekerry** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#4]
Access Services should be removed from the Developer SPO Service Description

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b30190b2-6a2d-8380-2ad8-700094acd6fe
* Version Independent ID: 774e7cff-1bb0-1024-e2af-2bec354a3b0b
* Content: [Developer](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/developer)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/developer.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/developer.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by prabita** [comment]
@vettekerry - content is updated. Thank you for feedback.
