### ISSUE TITLE
MS Teams

### ISSUE THREAD

**Issue by spiddeer** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#40]
I'm missing Teams service description 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7be38c7b-125f-fff6-ae80-741132b05ca8
* Version Independent ID: 2b28c809-3413-982b-dbfb-d2bfbcbd4723
* Content: [Office 365 Service Descriptions ](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-service-descriptions-technet-library)
* Content Source: [Office365-ServiceDescriptions/office-365-service-descriptions-technet-library.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-service-descriptions-technet-library.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by SKjerland** [comment]
@spiddeer  - Thanks for your feedback. We currently do not have a service description article written for Teams. I passed your request on to the appropriate team for consideration.
