### ISSUE TITLE
Teams Feature Limitations are not clearly documented for GCC High. 

### ISSUE THREAD

**Issue by scapero** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#400]
Teams Feature Limitations are not clearly documented for GCC High. 
The list in this document only mentions a few of the many features which are currently blocked "by design" in GCC High. Opening a ticket with support does not help as they don't seem to have access to more than this list either. 
Please provide a clear and complete list of feature limitations in GCC High which are expected?
thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9035b5a9-1f84-54be-89ae-c3a0e53891f8
* Version Independent ID: cff57f08-ca51-2266-6189-1ce8181b942e
* Content: [Microsoft Teams service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/teams-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/teams-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/teams-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @scapero.  The Teams service description is being completely reworked.  We'll let you know when this is completed.

**Comment by aaronlemieux** [comment]
Hi @scapero I've spoken with the product group and they have stated that what is currently listed in this service description is what is available at this time.
