### ISSUE TITLE
Office 365 add-on DLP

### ISSUE THREAD

**Issue by barreiros86** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#402]
[Enter feedback here]
hi,

i work in Microsoft (v-andrba@microsoft.com) and I was checking information for one partner about the DLP add-on for Microsoft 365 products.
In the page says is not available for Microsoft 365 Business Basic but in the internal documentation it says is possible.

can you change the information in this page and make the DLP add-on available for M365 Business basic?

regards 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 663a603e-482b-0a4f-55a9-229ceab11bb1
* Version Independent ID: 488b1daa-b459-c56d-11eb-59242af822b0
* Content: [Security & Compliance Center - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @barreiros86!  Thanks for passing us this information.  If you look at the footnote for that very issue (footnote 9) it states the following:  "Requires Office 365 data loss prevention add-on."
