### ISSUE TITLE
Possible missing link in note

### ISSUE THREAD

**Issue by jgrisham** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#403]
The text of the following note appears to imply it should have a hyperlink:

>  _If a mailbox was migrated to Exchange Online, the inbox rule limit might be set to the value that is lower than the default EXO value. If that is the case, the value can be increased by following this._

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Hi @jgrisham Thanks for catching this!  This line was recently added and it looks like the link got omitted.  I'll have our team add it right away.

**Comment by jgrisham** [comment]
Thanks, @aaronlemieux!

Issue resolved and closed.
