### ISSUE TITLE
THANK YOU!!!

### ISSUE THREAD

**Issue by contecc** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#404]
Mission Critical Content!!! Thank You!! My biggest frustration with Docs has been the inability to differentiate all the government information from the commercial information.  This article clearly separates the 2, allowing me to focus on analysis of impact to my customers versus just collecting data.  I am so grateful.

Chris Conte
Senior Consultant
Microsoft Federal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5408a406-02e7-bf26-e330-be25ea409aa6
* Version Independent ID: 3ed59637-9e20-85a7-83e1-e70cd61f635e
* Content: [SharePoint for US government environments - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/sharepoint)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/sharepoint.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/sharepoint.md)
* Service: **o365-administration**
* GitHub Login: @kaarins
* Microsoft Alias: **mkashman**

**Comment by aaronlemieux** [comment]
Hi @contecc We're very happy to hear that this is helping you.  We love hearing from our customers! If you have suggestions for how we can improve, please visit the [Microsoft Office 365 feedback and suggestions site](https://office365.uservoice.com/) and share them with us.
