### ISSUE TITLE
OneDrive sync statement ambiguous...

### ISSUE THREAD

**Issue by ickthwart** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#405]
[Enter feedback here]
This statement is ambiguous: "New OneDrive sync app - For optimum performance, we recommend storing no more than 300,000 files across all synced document libraries, even if you're using Files On-Demand or choosing only some folders within the libraries to sync."
Does this limit apply per user or per organization? 
I'm hoping it's per-user, as 300,000 files for an entire organization is very low.
This page is targeted at IT professionals, not end-users (most other limits on this page are from an organization, site or library point of view) so either way, this statement needs to be amended and clarified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits#limits-by-plan)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @ickthwart.  This is being updated.  Please give it 48 hours to get through our publishing pipeline to go live.  I'll be closing this.
