### ISSUE TITLE
Whiteboard incorrectly listed as available

### ISSUE THREAD

**Issue by SOM-Scott** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#408]
The pages lists Whiteboard for GCC is available, however I can't find the option or any other documentation about it for GCC and speaking with our Microsoft Rep it is not available yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3ab3187-c403-8fb1-6ee7-56818777fdad
* Version Independent ID: f6b28482-bf80-436e-cb8f-facb974c24ec
* Content: [Office 365 US Government - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government#office-application-availability-and-enterprise-value)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Hi @SOM-Scott Microsoft Whiteboard in government clouds is currently only available on Hub clients, and not on the desktop.  This information is listed in the service description attached.  Thank you!
