### ISSUE TITLE
Manual sensitivity labels

### ISSUE THREAD

**Issue by petrybr** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#409]
In the table presented in this link, it says "Yes" for "Manual sensititivity labels" for "Office 365 Enterprise E1, Office 365 US Government G1".

But in the "Detailed Microsoft 365 Compliance Licensing Comparison" there is no sensitivity label for O365 E1. https://docs.microsoft.com/en-us/office365/servicedescriptions/downloads/microsoft-365-compliance-licensing-comparison.pdf

which one is rigth?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 663a603e-482b-0a4f-55a9-229ceab11bb1
* Version Independent ID: 488b1daa-b459-c56d-11eb-59242af822b0
* Content: [Security & Compliance Center - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @petrybr We've updated this service description.  Thank you.
