### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by alisalih1** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#41]
"Use DLP in SharePoint Online to identify sensitive data stored on sites." link is broken. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65fe30a4-d11f-29bb-5171-11e40772d740
* Version Independent ID: 7b59b04f-ea56-c839-eac7-e22d6bf0657e
* Content: [IT Professional](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/it-professional#data-loss-prevention)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/it-professional.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/it-professional.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by prabita** [comment]
@alisalih1 Thank you for your feedback; issue is fixed and will be live in 24 hrs
