### ISSUE TITLE
manual sensitivity labeling

### ISSUE THREAD

**Issue by petrybr** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#410]
In section "Information Protection", in "Which licenses provide the rights for a user to benefit from the service?" it says:

"Microsoft 365 E5/A5/G5/E3/A3/G3/F1/F3/Business Premium, Enterprise Mobility + Security F3/E3/E5, **Office 365** E5/A5/E3/A3/**F3**, AIP Plan 1, and AIP Plan 2 provide the rights for a user to benefit from manual sensitivity labeling."

But in the Microsoft 365 Compliance Licensing Comparison file, https://opdhsblobprod04.blob.core.windows.net/contents/e0993bf6e82e4fa8ac18b48839521869/2ce5e803079c3427c011efbce08b900a?sv=2018-03-28&sr=b&si=ReadPolicy&sig=PYbs5Tpy%2FjtoHFZlHk6vO8fXQBCKg0nQJzfkU7DBgh8%3D&st=2020-08-12T23%3A59%3A12Z&se=2020-08-14T00%3A09%3A12Z there is no mention that Office 365 F3 has this feature

Which one is right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 licensing guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @vtrscho
* Microsoft Alias: **v-trscho**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @petrybr This request has been completed and the changes have gone live.
