### ISSUE TITLE
ATP Plan 1 vs 2 ("Office 365 Advanced Threat Protection (ATP) availability" section)

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#411]
In the section "Office 365 Advanced Threat Protection (ATP) availability", it is not made clear which ATP plan is included with the ATP-including O365/M365 plans. I just states this:

> ATP is included in Office 365 Enterprise E5, Office 365 Education A5, and Microsoft 365 Business Premium.

I would submit a PR to update this myself, but the "Edit" button isn't on the page.  Can you please change the above quoted line to instead be the following:

> Office 365 ATP Plan 2 is included in Office 365 E5, Office 365 A5, and Microsoft 365 E5.  Office 365 ATP Plan 1 is included in Microsoft 365 Business Premium.

This information is sourced from the other docs article: https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/office-365-atp?view=o365-worldwide#office-365-atp-plan-1-and-plan-2

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 502796e9-ca73-7123-7719-c7b5b1042b7b
* Version Independent ID: 2929af88-6d56-4de3-2b4e-4e1d0e4d97ef
* Content: [Office 365 Advanced Threat Protection service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description#office-365-advanced-threat-protection-atp-availability)
* Content Source: [Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @JeremyTBradshaw This has been completed and I am closing this item out.
