### ISSUE TITLE
LInks for Microsoft Security and Compliance Center

### ISSUE THREAD

**Issue by jonb2501** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#412]
When you discuss a web site, please include the link for the site.
The article was good but now I have to google the actual URL.
I shouldn't have to do that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 663a603e-482b-0a4f-55a9-229ceab11bb1
* Version Independent ID: 488b1daa-b459-c56d-11eb-59242af822b0
* Content: [Security & Compliance Center - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Hi @jonb2501.  Can you specify which site is being discussed?  I'd be happy to ensure we get the appropriate links added.

**Comment by aaronlemieux** [comment]
Hi @jonb2501 As we have not heard back in 2 weeks I will be closing this item.  You are more than welcome to submit a new request regarding this going forward, and we will be happy to look into it if you do.
