### ISSUE TITLE
Unique permissions for items in a list or library

### ISSUE THREAD

**Issue by LaPhi** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#414]
_Unique permissions for items in a list or library
The supported limit is 50,000 uniquely permissioned items, but the recommended general limit is 5,000. Making changes to more than 5,000 uniquely permissioned items at a time takes longer. For large lists, design to have as few unique permissions as possible.

Another limit is 5,000 role assignments per uniquely permissioned item._

From my understanding the customer has to create a support ticket to change the limit to 50 000. If this is true, please can you insert this information? If this is false please can you include the information that no action is needed?

BR Lars

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @LaPhi We have spoken with the product team.  Fistly, role permissions are completely different from the other limits above.  As stated in your opening paragraph, 50,000 is the limit, 5,000 is the recommendation.  No ticket is needed to increase the limit to 50,000.  We will be keeping the Service Description as is.  Thank you for bringing this to our attention.

**Comment by aaronlemieux** [comment]
This update is now live.
