### ISSUE TITLE
Outlook vesions out of date

### ISSUE THREAD

**Issue by ickthwart** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#416]
This statement is a bit out of date...
Exchange Online Archiving supports Outlook 2013, Outlook 2010, and Outlook 2007

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d57bfe9-67d3-4916-4849-609fcf46068c
* Version Independent ID: f5736192-b3c7-f37b-6395-a26a1e85d7bd
* Content: [Client features in Exchange Online Archiving - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-archiving-service-description/client-features)
* Content Source: [Office365-ServiceDescriptions/exchange-online-archiving-service-description/client-features.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-archiving-service-description/client-features.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @ickthwart.  We have made the appropriate changes to this service description based on your feedback.  I will be closing this item.
