### ISSUE TITLE
Where is the truth for licencing?

### ISSUE THREAD

**Issue by coupalm** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#417]
There are multiple locations for licencing information and they're not saying the same things...
For instance, if you look at the following link below, all Business plan do not include Yammer.

https://www.microsoft.com/en-ca/microsoft-365/business/compare-all-microsoft-365-business-products?&activetab=tab:primaryr2

However in your page, it says it is... and is it Yammer Basic in Business Licence? This should be clarify.

Also, there is no reference to Business Premium.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3fea44b-ae19-6168-157e-56e36c76b467
* Version Independent ID: 74e1c2f3-c8f7-16cf-0fd2-7d6007b12abb
* Content: [Office 365 plan options - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-plan-options#office-365-service-families-and-plans)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-plan-options.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-plan-options.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @coupalm.  I've spoken with the product team and verified that Yammer Enterprise is included in M365 Business Basic, Standard, and Premium.  We will be working on adding M365 Business Premium to this page soon.
