### ISSUE TITLE
Why all business licences include "Information Governance"

### ISSUE THREAD

**Issue by coupalm** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#418]
I don't understand why all Business licence include "Information governance"*1. What does it includes? And the reference no1 says you need E3 or E5 so why say "Yes" to all Business licences?

Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 663a603e-482b-0a4f-55a9-229ceab11bb1
* Version Independent ID: 488b1daa-b459-c56d-11eb-59242af822b0
* Content: [Security & Compliance Center - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center#security--compliance-center-availability-for-business-and-enterprise-plans)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Thank you @coupalm .  We have made the appropriate changes.  Please allow 72 hours for the page to populate with the correct ifnormation.
