### ISSUE TITLE
Cannot move the items. Unknown Error

### ISSUE THREAD

**Issue by RameshSeervi** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#419]
Hi Team,

Getting the below error: 
Cannot move the items. Unknown error. 

When trying to move email with **attachment** from Outlook. But can move the same email to an online Archive from web outlook without any error. 

Created a new Profile/OST - still same. 
Reinstall O365 - still same. 

Please help. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e0ba987-5e52-0e0d-f9f8-d6da3feaa53c
* Version Independent ID: 5763ce54-2c7c-8956-f44e-c946d0c9a5c4
* Content: [Archive features in Exchange Online Archiving - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-archiving-service-description/archive-features)
* Content Source: [Office365-ServiceDescriptions/exchange-online-archiving-service-description/archive-features.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-archiving-service-description/archive-features.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Hi @RameshSeervi,

I'm sorry that you're having this issue. For Support options, please see [[Support](https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/support)]
