### ISSUE TITLE
Missing limit

### ISSUE THREAD

**Issue by masamig** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#42]
Message rate limit (SMTP client submission only) is missing in "Sending limits across standalone options"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by MarkGerlow** [comment]
Could you please update, and or confirm this?

**Comment by prabita** [comment]
@masamig Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response

**Comment by SharS** [comment]
Thanks. I've updated the article.
