### ISSUE TITLE
Migration: Mover.io. Currently available only to customers in North America.

### ISSUE THREAD

**Issue by teomonda** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#420]
Mover is now available worldwide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b30190b2-6a2d-8380-2ad8-700094acd6fe
* Version Independent ID: 774e7cff-1bb0-1024-e2af-2bec354a3b0b
* Content: [SharePoint service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-service-description)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @teomonda.  We have updated the article per your request.  I'm closing this item out.
