### ISSUE TITLE
OST vs Note 2.

### ISSUE THREAD

**Issue by fjuhasz** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#421]
[Enter feedback here]
Hi,

The second note says:
"...AIP Plan 1 is included in Microsoft 365 Business Premium."
I have checked in the Online Services Term (OST) Engish version and it says in the "Attachment 2 – Subscription License Suites" that Azure Info Protection Premium Plan 1 is not included in the M365 BP subscription.

Does the "Premium" word make any difference? 
Is there any way to reflect the difference if exist in both documents (here and in the OST)?

Thanks in advance!

BR,
Ferenc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94c91b3d-d9b1-9056-ae3e-51a255ed88ec
* Version Independent ID: b60613bc-f7b3-d1c7-4d8e-924c0f87912f
* Content: [Microsoft 365 Business Premium service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @fjuhasz.  I've spoken with the product team.   AIP Plan 1 (and O365 ATP) are included in Microsoft 365 Business Premium.  This service description is correct.  They have agreed the OST needs to be updated and are now working on it.  As this GitHub is for service descriptions, I'll be closing this item.  Thank you!
