### ISSUE TITLE
ATP Licensing should clarify license assignment requirements

### ISSUE THREAD

**Issue by jhardwick-nxio** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#422]
Do only licensed actual users need licenses?  What about Shared/Resource or Group Mailboxes?  

The only references I can find refer to forum posts and no official documentation as an example: https://techcommunity.microsoft.com/t5/office-365/atp-licenses-for-shared-mailboxes/m-p/790370

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 502796e9-ca73-7123-7719-c7b5b1042b7b
* Version Independent ID: 2929af88-6d56-4de3-2b4e-4e1d0e4d97ef
* Content: [Office 365 Advanced Threat Protection service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description)
* Content Source: [Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @jhardwick-nxio 

I met with the product team today and they verified the following for us.

Shared mailboxes need to be licensed for Advanced Threat Protection. See the following example:
Company has 5 users in Office 365. Each has a mailbox. There is 1 shared mailbox. They need a license for:
6 seats of Exchange Online Protection (5 users + 1 shared mailbox)
6 seats of Advanced Threat Protection (5 users + 1 shared mailbox)

**Comment by jhardwick-nxio** [comment]
Can we get this -- and yes it can be that simple into the documentation, please.  I can't find anything in writing from MS other than comments and forums that simply says these are the scenarios in which ATP licenses are required.

**Comment by jhardwick-nxio** [comment]
> Shared mailboxes need to be licensed for Advanced Threat Protection. See the following example:
> Company has 5 users in Office 365. Each has a mailbox. There is 1 shared mailbox. They need a license for:
> 6 seats of Exchange Online Protection (5 users + 1 shared mailbox)
> 6 seats of Advanced Threat Protection (5 users + 1 shared mailbox)

@aaronlemieux - I'm confused where EOP came from... I assumed this was the correct license set:

Company has 5 users with Office 365 E3 and 1 Shared Mailbox.  They need the following licenses:
5 licenses of Office 365 E3 (5 users + 1 shared mailbox that doesn't require an Exchange license)
6 licenses of Advanced Threat Protection P1 (5 users + 1 shared mailbox)
