### ISSUE TITLE
Footnote 25 is missing a line break in front of it

### ISSUE THREAD

**Issue by csjn** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#423]
at the end of footnote 24 / and the beginning of footnote 25 the line break is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2f622a7-32c1-2c35-2df9-ddf1bc74c74d
* Version Independent ID: e37d85d2-8b81-0c64-b7d0-1e8c01b303db
* Content: [Exchange Online service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description#feature-availability-across-exchange-online-standalone-plans)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Hi @csjn Thanks for your comments. I've verified this change needs to occur and we are processing it now.  I will update this thread when the changes are published.

**Comment by aaronlemieux** [comment]
Hi @csjn This has been completed.  Please allow 72 hours for the changes to appear.
