### ISSUE TITLE
Licensing requirements and scope unclear for advanced eDiscovery

### ISSUE THREAD

**Issue by bmilbauer** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#424]
If I have 10 investigators and 100 people being investigated in advanced eDiscovery with a 1000 user tenant, do I need 10 licenses, 100, or 1000 licenses?

Microsoft 365 Enterprise E5 eDiscovery and Audit is the license I'm planning on buying.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 licensing guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#advanced-ediscovery)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @vtrscho
* Microsoft Alias: **v-trscho**

**Comment by aaronlemieux** [comment]
Hi @bmilbauer 

Thank you for reaching out to us on this.  This appears to be a support question, not an update to the service description in question. For Support options, please see [Support](https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/support).
