### ISSUE TITLE
clarify sync limits

### ISSUE THREAD

**Issue by fselkirk** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#425]
Because the sync limits for the old client are more extensive, it is easy for customers to miss the much higher limits on the client they are probably using. Also, the 2016 client is still being called "New", which also leads to people not realizing it's the one they are using. Please consider these changes: 

Sync

Current OneDrive sync app (OneDrive.exe)- For optimum performance, we recommend storing no more than 300,000 files per user across all synced document libraries, even if you're using Files On-Demand or choosing only some folders within the libraries to sync.

Previous OneDrive for Business sync app (Groove.exe - used with older on-premise SharePoint environments) -You can sync up to 20,000 items total across all synced libraries. This includes OneDrive libraries, team site libraries, or both. Separately from the overall sync limit, there are limits to the number of items that can be synced for each library type:

You can sync up to 20,000 items in a OneDrive library. This includes folders and files.
You can sync up to 5,000 items in a SharePoint library. This includes folders and files. These are (etc.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @fselkirk.  We've updated this service description for you.  Thank you.
