### ISSUE TITLE
Requested name updates

### ISSUE THREAD

**Issue by kasiak-msft** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#426]
Please update "Windows Defender Antivirus" to "Microsoft Defender Antivirus".

In addition, under the "Advanced Security" category, Advanced Threat Protection is not a product that exists. Please reach out to me and my team to verify the correct product details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8328da3-5093-09b6-9b9b-b92d13625219
* Version Independent ID: f2171de5-bfa5-65d1-4615-30db23349b40
* Content: [Microsoft 365 Education - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education?source=docs#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.  I have attempted to look you up within Microsoft's global address list, but I did not find a kasiak.  Please provide me with your alias and I will be happy to reach out to you.

**Comment by kasiak-msft** [comment]
Hello,

You’ve got the right alias – I got this email at kasiak@microsoft.com<mailto:kasiak@microsoft.com>


Kasia Kaplinska
Sr. Product Marketing Manager
Microsoft Defender ATP
kasia.kaplinska@microsoft.com<mailto:kasia.kaplinska@microsoft.com>
Mobile: 603-265-0920

**Comment by aaronlemieux** [comment]
Hi @kasiak-msft.  We have completed these changes and verified they have gone live.
