### ISSUE TITLE
Safe Documents Availability Update

### ISSUE THREAD

**Issue by kshi-docs** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#427]
Hey folks,

Hoping to update the Safe Documents section of https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description#safe-documents

Currently it states that:

> Word, Excel, PowerPoint, and Visio on Windows, as well as Office apps on iOS and Android devices
> 
> Microsoft Teams channels and chats

Safe Documents is currently only supported for **Word, Excel, and PowerPoint on Windows**. Could you please help update this section to reflect this? 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 502796e9-ca73-7123-7719-c7b5b1042b7b
* Version Independent ID: 2929af88-6d56-4de3-2b4e-4e1d0e4d97ef
* Content: [Office 365 Advanced Threat Protection service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description#safe-documents)
* Content Source: [Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @kshi-docs We've updated this service description for you.
