### ISSUE TITLE
Public Folder mailbox

### ISSUE THREAD

**Issue by yacooob** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#428]
Not clear if Public Folder mailbox requires a license.
For shared mailboxes or resource mailboxes it is clearly stated that those mailboxes don't require license. What about Public Folder mailboxes?
Thanks in advance for explanation.

yacoob

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @yacooob. I have spoken with the product team.  Public folder mailboxes do not require licenses under any conditions.
