### ISSUE TITLE
Conflicting support statements for education customers.

### ISSUE THREAD

**Issue by brshus** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#43]
There are conflicting statements for education customers on this site and office.com - see here and please fix to align statements: On the O365 SD (https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/support#technical-support) it states Office 365 for Education receives the following support:
•SevA: 24x7 / 1 hour response
•SevB: Business hours / no response commitment
•SevC: Business hours / no response commitment
•Footnote to state Education is considered a Business plan effectively changing SevB and SevC availability from Business hours to 24/7 (but nothing regarding a response commitment)

On the Office 365 support page (https://products.office.com/en-us/business/office-365-for-business-support-options) it describes Office 365 for Education support as follows:
•Footnote that Office 365 Education customers follow Enterprise support features which are described as follows:
• SevA: 24x7 / 1 hour response
• SevB: 24x7 / next day response
• SevC: 24x7 / no response commitment

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4bab1e0-b326-22fd-d1b8-23780e0720d3
* Version Independent ID: bf81479e-1ed7-d465-a72b-bb425c757411
* Content: [Support](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/support#technical-support)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/support.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/support.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by prabita** [comment]
Updated and added link
