### ISSUE TITLE
Follow-up on last request..

### ISSUE THREAD

**Issue by jhardwick-nxio** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#430]
@aaronlemieux answered my request last time (on 9/2/2020 with an example.. and I asked for clarification and details to be formally included in the documentation instead of just comments in a forum or on this document, etc. to be provided.

If we need to have a clarifying conversation with someone on the product team directly I'm open to that.  I need something that I can point clients to that explicitly defines what the licensing requirements are.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 502796e9-ca73-7123-7719-c7b5b1042b7b
* Version Independent ID: 2929af88-6d56-4de3-2b4e-4e1d0e4d97ef
* Content: [Office 365 Advanced Threat Protection service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description)
* Content Source: [Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Hi @jhardwick-nxio.  I've been following up with the product team on this.  There may be a delay on this due to Ignite going on, but I'll be continuing to chase this down later this week.

**Comment by jhardwick-nxio** [comment]
@aaronlemieux  any update?

**Comment by aaronlemieux** [comment]
Hi @jhardwick-nxio With Ignite over I have reached out to the product team and am seeing what can be done, as they had initially stated they did not want the documentation updated, per item [422](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions/issues/422) ( [https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions/issues/422](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions/issues/422) ).

**Comment by jhardwick-nxio** [comment]
As a partner I’m fine if you can have them reach out directly to give me something in writing explaining the requirement and I can give specific scenarios as clarification.  It’s difficult being the partner in competitive situations arguing for things to be licensed correctly when MS seems to purposely want to avoid licensing clarification.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by aaronlemieux** [comment]
Hi @jhardwick-nxio.  Do you have a place I can provide them to contact you at?

**Comment by jhardwick-nxio** [comment]
I’d prefer to avoid my direct email in GitHub.  Is there a good way to give it to you privately?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by aaronlemieux** [comment]
I do not.  If you can provide your email here I can delete your comment that includes it.

**Comment by jhardwick-nxio** [comment]
@aaronlemieux , I saw your MS alias on your GitHub profile and shot you an email.

**Comment by jhardwick-nxio** [comment]
@aaronlemieux, following up - my email is jhardwick@nxio.net but I also had emailed you directly.

**Comment by aaronlemieux** [comment]
Hi, the team has requested the documentation not be updated.
