### ISSUE TITLE
Microsoft Teams Voice in GCC High

### ISSUE THREAD

**Issue by johntchoi** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#431]
The [feature category reference](https://docs.microsoft.com/en-us/office365/servicedescriptions/teams-service-description#feature-category-reference) indicates that Microsoft Teams Voice is available in GCC High, but other documentation implies this is not true.  Can you clarify?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9035b5a9-1f84-54be-89ae-c3a0e53891f8
* Version Independent ID: cff57f08-ca51-2266-6189-1ce8181b942e
* Content: [Microsoft Teams service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/teams-service-description)
* Content Source: [Office365-ServiceDescriptions/teams-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/teams-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @johntchoi Can you provide us with what other documentation applies this is not true?

**Comment by johntchoi** [comment]
I guess this is specific to Audio Conferencing, but : https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-with-direct-routing-for-gcch-and-dod

**Comment by aaronlemieux** [comment]
Hi @johntchoi We have updated this service description to cover this.  Thank you.
