### ISSUE TITLE
Can't see watermarks in Office for the web

### ISSUE THREAD

**Issue by BLTTEST** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#433]
Hi Teams,

The note of watermark shows "These render in the viewer, but you cannot create or edit them in Office for the web." I wonder if the viewer here indicates Office for the Web? In my test, I added the watermark to the document and uploaded it to the OneDrive. But when I used office for the web to open the document, I couldn't see any watermark. Can you confirm if this function is working as designed? Please correct me if I misunderstood the article.

Thank you for your help.

Best Regards,
Ben
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27c83859-4215-14f8-5141-6086f39f21d1
* Version Independent ID: f84d45eb-fc22-1ec2-a5d0-08358bb23ecf
* Content: [Office for the web service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-online-service-description/office-online-service-description)
* Content Source: [Office365-ServiceDescriptions/office-online-service-description/office-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-online-service-description/office-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Hi @BLTTEST Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by BLTTEST** [comment]
Hi @aaronlemieux 
Thank you for your reply and look forward to your update.
Best Regards,

**Comment by aaronlemieux** [comment]
Hi @BLTTEST Here's what I've heard back from the product team.

Support for watermark display in Word Web:
Word Viewer: Supported
Word Editor: Not Supported 

PPT and XL client apps does not have watermark feature but PPT supports adding text/image in the master slide and XL supports images in the Header to have watermark like effect.

Support for display in P and X web apps.
PPT: Supported
XL: Not Supported
