### ISSUE TITLE
O365 Video and Staffhub

### ISSUE THREAD

**Issue by tomschauer** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#434]
(1) Has Staffhub been officially deprecated and now a part of Teams (Shifts?) Should we removed Staffhub from here?

Can we add the below link? When people are looking to move to our cloud, they think they are getting Staffhub.

Microsoft StaffHub has been **retired**
https://docs.microsoft.com/en-us/microsoftteams/expand-teams-across-your-org/shifts/microsoft-staffhub-to-be-retired

(2) Has O365 Video also been officially deprecated and now Stream? Should we also remove O365 Video from here?

Can we explain the transition and the link the below article? When people look a moving to our cloud, they think O365 Video is a Suite Feature.

Office 365 Video transition to Microsoft Stream overview
https://docs.microsoft.com/en-us/stream/migrate-from-office-365

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @tomschauer Could you include the service description you're referring to that you could like these links to be added?

**Comment by aaronlemieux** [comment]
Hi, as we haven't heard back on which service description this is for, I'll be closing this item.
