### ISSUE TITLE
Missing content

### ISSUE THREAD

**Issue by JasonH-Msft** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#436]
[Enter feedback here]
This article is referred to by https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/sharepoint#security-and-compliance-features

"For info about the following features, see the Office 365 US Government service description:

Customer Lockbox
Data loss prevention (DLP)
eDiscovery (Content Search, hold, export)
Office 365 Advanced Threat Protection (ATP)
Sensitivity labels"

So these features need to be explicitly mentioned in this Service description article, but they appear to be missing or not updated.  Particularly interested in Sensitivity labels

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3ab3187-c403-8fb1-6ee7-56818777fdad
* Version Independent ID: f6b28482-bf80-436e-cb8f-facb974c24ec
* Content: [Office 365 US Government - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government?source=docs#platform-features)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @JasonH-Msft I've spoken with the product team and they would like to refer you to [Microsoft 365 licensing guidance for security & compliance](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#advanced-audit).  We are continuing to work on this item for you.

**Comment by aaronlemieux** [comment]
Hi @JasonH-Msft I've spoken with the product team and this service description has been updated per their request to remove this verbiage.
