### ISSUE TITLE
Licensing Microsoft SharePoint Server   

### ISSUE THREAD

**Issue by Alice-Pa** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#437]
Hello, 
This page is refered from "[Licensing Microsoft SharePoint Server](http://download.microsoft.com/download/3/D/4/3D42BDC2-6725-4B29-B75A-A5B04179958B/Licensing_Microsoft_SharePoint_Server_2013.pdf)" document for more information about which SharePoint features are part of the base product and which features are considered additional functionality requiring additive CALs. 
But it only provides information about SharePoint in Microsoft 365. 
Could you update it to provide the information for SharePoint Server?
Thanks, Alice    
 ---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b30190b2-6a2d-8380-2ad8-700094acd6fe
* Version Independent ID: 774e7cff-1bb0-1024-e2af-2bec354a3b0b
* Content: [SharePoint service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-service-description?redirectedfrom=MSDN)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @Alice-Pa I've spoken with the product team and tracked down the owner of that .pdf.  The service description is accurate and meant to be for SharePoint Online.  The owner of the .pdf has been notified that link is out of date and they are looking into this.  As this is not a service description issue, I'll be closing this item.
