### ISSUE TITLE
Bookings feature now available in GCC

### ISSUE THREAD

**Issue by scapero** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#438]
[M365 Roadmap - Bookings page](https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=bookings), where it does state that Microsoft Bookings was released as an M365 app to GCC G3 and G5 customers, June CY2020. 

We have received customer support issues asking why the feature is available when our documentation states it should not be there.

Please update ?

Thank you
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3ab3187-c403-8fb1-6ee7-56818777fdad
* Version Independent ID: f6b28482-bf80-436e-cb8f-facb974c24ec
* Content: [Office 365 US Government - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government?source=docs#platform-features)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @scapero I have spoken with the product team and they have verified that the service description lists the correct GCC availability for Bookings.
