### ISSUE TITLE
Footnote 3 seems incorrect

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#439]
Footnote 3 appears on the Apps, Bots, and Connectors entry, and says: "3 Microsoft OneNote is not available in DOD clouds. Applications and application publishing are not available in these clouds at this time."

It looks like two lines got merged. The first sentence references a first party integration not being in DOD (which if still true, should be a separate footnote just for DOD, not GCC and GCC-H). The second sentence isn't true in GCC as far as I'm aware, or if it is, it is some minor caveat that should be explained.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9035b5a9-1f84-54be-89ae-c3a0e53891f8
* Version Independent ID: cff57f08-ca51-2266-6189-1ce8181b942e
* Content: [Microsoft Teams service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/teams-service-description)
* Content Source: [Office365-ServiceDescriptions/teams-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/teams-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @npherson This service description has been updated based on your feedback, after speaking with the product team about this.   Thank you.
