### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by cianallner** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#44]
Please, could this useful article be maintained with updates and changes as they are made to Office 365, at least on a monthly basis? I am pretty sure there have been changes since June 2018, the last time this article was updated, as it is now January 2019 but they are not reflected in this article. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 835104aa-bd1a-fa8b-634e-19c61d3b9c4e
* Version Independent ID: 6eef1d71-c0a9-711a-20ff-f398e56865c1
* Content: [Recent service descriptions changes](https://docs.microsoft.com/en-us/office365/servicedescriptions/recent-service-descriptions-changes)
* Content Source: [Office365-ServiceDescriptions/recent-service-descriptions-changes.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/recent-service-descriptions-changes.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by SKjerland** [comment]
@cianallner - Thanks for your feedback. I'm sorry, but this is an article we are no longer maintaining.
