### ISSUE TITLE
Footnotes stop at 13, but table references higher numbers

### ISSUE THREAD

**Issue by jobbio** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#440]
[Enter feedback here]

The footnotes within the page stop at 13, but there are higher numbers referenced in the table.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8328da3-5093-09b6-9b9b-b92d13625219
* Version Independent ID: f2171de5-bfa5-65d1-4615-30db23349b40
* Content: [Microsoft 365 Education - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @jobbio I have spoken with the product team.  The superscript listed for Azure Information Protection Plan17 and Azure Information Protection Plan27 should be Azure Information Protection Plan1 7 and Azure Information Protection Plan2 7.   We will be updating this page soon.
