### ISSUE TITLE
Please include a Microsoft Teams in the "Office application and feature availability..." section

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#442]
Opening new feedback on this topic again, [per docs team request.](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions/issues/270#issuecomment-704604708).

We need to have a Microsoft Teams section that explains what features are not available to GCC/GCC High/DOD customers just like we have for the rest of the Office suite. A realistic view of what works/does not work is not available in any of our public documentation. This causes significant end-user and admin frustration as they try to make things work, troubleshoot, research, and ultimately either contact their account team or support and find out that the feature isn't supported in GCC. This is an incredibly significant customer satisfaction issue, and consumes an enormous amount of time for both customer IT and Microsoft field staff. Instead of us playing whack-a-mole with every feature, it would be great it this page could include a list of what Teams features are NOT expected to be in GCC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3ab3187-c403-8fb1-6ee7-56818777fdad
* Version Independent ID: f6b28482-bf80-436e-cb8f-facb974c24ec
* Content: [Office 365 US Government - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government?source=docs#office-application-and-feature-availability-in-government-plans)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
This service description has been changed to include this.  Thank you.

**Comment by npherson** [comment]
@aaronlemieux  - I'm not seeing this information at all on the service description... Please feel free to reach out to me directly.
