### ISSUE TITLE
Microsoft Teams Exploratory storage

### ISSUE THREAD

**Issue by McDoMonsieur** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#443]
There is something missing on this page : Microsoft Teams Exploratory add 10 GB per license to the SharePoint Storage, confirmed with Microsoft Support.
You should add because you can have 1 extra TB storage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd087ed1-2394-6098-c5ee-7faafbc4133f
* Version Independent ID: ca809b64-206c-4dfa-7c79-b0a45979e953
* Content: [Connect-SPOService (SharePointOnlinePowerShell)](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/connect-sposervice?view=sharepoint-ps)
* Content Source: [sharepoint/sharepoint-ps/sharepoint-online/Connect-SPOService.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/sharepoint/sharepoint-ps/sharepoint-online/Connect-SPOService.md)
* Service: **sharepoint-powershell**
* GitHub Login: @trent-green
* Microsoft Alias: **trgreen**

**Comment by aaronlemieux** [comment]
Hi @McDoMonsieur Can you please state which Service Description you're referring to?

**Comment by aaronlemieux** [comment]
Hi @McDoMonsieur We will be closing this ticket for now.  We will reopen it if you do provide us with the SD in question.
