### ISSUE TITLE
File sharing from commercial to GCC High/DoD

### ISSUE THREAD

**Issue by jarossmsft** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#444]
We have received several cases in support with GCC High customers wanting documentation in the service descriptions that describes if commercial is able to share with a GCC High/DoD tenant. Currently, there is verbiage about GCC High to Commercial but customers are also requesting the scenario backwards of commercial sharing to GCC High.

https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c907526-4061-94b4-f2fd-d6fca90344bb
* Version Independent ID: 82e89c18-8d6e-bbb1-f6d0-6ec091d1556e
* Content: [Office 365 GCC High and DoD - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @jarossmsft I've spoke with the product team, and they have requested to not update the SD at this time.  However, they do state that new support and updated guidance and documentation are currently in the works.
