### ISSUE TITLE
Detailed Security Description like the Compliance one?

### ISSUE THREAD

**Issue by frankbough** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#448]
The Compliance E5 detailed service description is excellent - where is the corresponding one for Security?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 licensing guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @vtrscho
* Microsoft Alias: **v-trscho**

**Comment by aaronlemieux** [comment]
Hi @frankbough Can you link to which SD you're referring to for the Compliance E5 one, so I can reference what you're looking for when I speak with the product group?
