### ISSUE TITLE
Removal of legacy items

### ISSUE THREAD

**Issue by loryanstrant** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#449]
There are a number of updates required to this page.

Depreciated products:
- StaffHub
- Office 365 Video
- Microsoft Kaizala

Missing products:
- Visio (If you're going to have Project there (which is not technically part of Microsoft/Office 365) then you should have Visio)
- Yammer
- Power BI
- Microsoft 365 Apps / Office 365 ProPlus
- Lists
- To Do
- SharePoint
- OneDrive
- Whiteboard

Wrong product name:
- Office Delve; now known as "Delve"
- PowerApps; now known as "Power Apps"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dd954d8-5874-8d25-36eb-0718ef86d585
* Version Independent ID: 001e3018-251d-dc72-c669-a21e303f21d7
* Content: [Microsoft 365 suite features - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-suite-features)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-suite-features.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-suite-features.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @loryanstrant We've worked with the product team to verify this and have updated this service description.  Thank you.
