### ISSUE TITLE
Compliance Manager OOTB and Premium Assessments in the downloadable Excel/Pdf

### ISSUE THREAD

**Issue by donnyatmsft** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#450]
Compliance Manager - since GA - has new licensing requirements for the Assessments feature (M365 E5, O365E5) which does not reflect in the downloadable PDF/Excel related to Compliance officering.
Maybe it could be useful having a new excel line for Compliance Manager Out-Of-the-Box Assessments - 4 included in M365 E5 or O365 E5 - and another line related to Compliance Manager Premium Assessments (available as an add on)

It also should be useful having a version for the PDF/Excel (i.e. Sept 2020 / Oct 2020) having also the link ling in the excel / pdf to check download the most recent version.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 licensing guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#compliance-manager)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @vtrscho
* Microsoft Alias: **v-trscho**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @donnyatmsft We've updated this service description based on this.  Thank you.
