### ISSUE TITLE
Eligibility validation link not working

### ISSUE THREAD

**Issue by SilviaEid** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#451]
Good morning,

I just wanted to let you know that the below link on this page does not work. Can it be updated and/or can you provide the correct link to the form please?

https://products.office.com/government/eligibility-validation

How do I buy Microsoft 365 Government?
Follow these steps to purchase Microsoft 365 Government licenses:

Complete and submit **the form** to validate your organization’s eligibility.
Work with the Microsoft account team or a qualified partner to place an order. Customers can purchase Microsoft 365 for US Government licenses only through select partners.

Best regards,

Silvia Eid

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86dc9aff-0190-52d9-2ab0-4f236d862739
* Version Independent ID: f6cbf527-2a7d-edd6-49b9-ca70ba43b9d6
* Content: [Microsoft 365 Government how to buy - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/microsoft-365-government-how-to-buy)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/microsoft-365-government-how-to-buy.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/microsoft-365-government-how-to-buy.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Hi @SilviaEid.  I have validated that this link does work.  Thank you.
