### ISSUE TITLE
Query feature matrix - Local numbers feature - with no call plan?

### ISSUE THREAD

**Issue by SvenBell** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#452]
Hi, please confirm.... Feature matrix suggests - Local numbers feature - with no call plan?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abdc7fbf-1f49-704b-cad5-08f15e811642
* Version Independent ID: 2a9be28e-06a1-bfff-766c-de34214e7fba
* Content: [Microsoft 365 Business Voice service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-business-voice-service-description)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-business-voice-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-business-voice-service-description.md)
* Service: **o365-administration**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @SvenBell This has been updated.  Thank you.

**Comment by SvenBell** [comment]
Thank you

**Comment by SvenBell** [comment]
Feature matrix still suggests - Local numbers feature - with no call plan?
