### ISSUE TITLE
Inconsistency for A3 licensing and Office 365 Cloud App Security entitlement

### ISSUE THREAD

**Issue by benfletcherMS** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#453]
Hello,
this page is inconsistent with the link it provides, which is further inconsistent with another link.  This is all to do with eligibility for Office 365 Cloud App Security (formerly Advanced Security Management).

1. This page says (https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#office-365-cloud-app-security) says that m365 A5 users are eligible for 365 CAS.  This is inconsistent with internal licensing guidance, but is also inconsistent with the link it provides to the Microsoft Cloud App Security Licensing Datasheet at https://www.aka.ms/mcaslicensing

2. The Link at https://www.aka.ms/mcaslicensing states that M365 A3 are entitled to Office 365 Cloud App Security.  This is inconsistent with the above page.   But it then creates a further clarity issue by saying that "This licensing plan is
available to educational institutions and includes Microsoft Cloud App Security".  This would seem to be an error, as nowhere else does it says A3 includes MCAS.  The link provided does not align. https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education 

3. At this new link, it confirms MCAS is not included with A3.  However, it creates confusion as it refers to Advanced Security Management, not Office 365 CAS.  The Advanced Security Management product was renamed a long time ago, and to refence to this product is not helpful i.e. should be updated for clarity to reflect new name.  

I look forward to these inconsistencies being resolved.  Thanks.  Ben.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 licensing guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @vtrscho
* Microsoft Alias: **v-trscho**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @benfletcherMS M365 A5 includes Microsoft Cloud App Security and O365 Cloud App Security. M365 A3 includes only O365 Cloud App Security, not Microsoft Cloud App Security.

**Comment by benfletcherMS** [comment]
Thanks Aaron.  I can see the issue relating to the first one has been resolved, adding A3 in the mix.  However, the link directly below that line links to a document which is still incorrect.  So whilst this site is correct, it points the user to a link which then contradicts this site. 

So the second issue I list is still, there as is the third whereby the link in that document refers to the Service Description which still calls it Advanced Security Management rather than Office 365 CAS.

Do I have to submit different requests to have those resolved?
