### ISSUE TITLE
Requires Update

### ISSUE THREAD

**Issue by TNwestpointtg** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#454]
Can this be updated to include comparison with Exchange 2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2f622a7-32c1-2c35-2df9-ddf1bc74c74d
* Version Independent ID: e37d85d2-8b81-0c64-b7d0-1e8c01b303db
* Content: [Exchange Online service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by annferre** [comment]
Hi there, I just wanted to let you know I'm looking into this, and, I'm hoping I'll have it resolved soon.

**Comment by annferre** [comment]
Apologies for the delay. We have added a table that includes 2019 to the Exchange Server repository: https://docs.microsoft.com/en-us/exchange/new-features/feature-availability?view=exchserver-2019
We have added a link to that page in the EXO service description page. Let me know if you still have questions.
