### ISSUE TITLE
Translation available for Word, Excel, and PowerPoint in Gov Clouds

### ISSUE THREAD

**Issue by albuss-msft** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#455]
Hi, not sure if this is the right way to get this page updated but we have released the Word, Excel, and PowerPoint Translation features in GCC and GCC-H as of August 2020. We have a couple of customers coming to this page and getting confused so it would be great if we could update the Translation aspect. 

Additionally, we are going to be releasing the feature out into the DoD environment by end of year. It is currently not out but will be soon. 

If this isn't the correct way to update this page please either email or message me on Teams with the correct procedure. 

Thanks!
Alanna Buss
<Albuss@microsoft.com>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3ab3187-c403-8fb1-6ee7-56818777fdad
* Version Independent ID: f6b28482-bf80-436e-cb8f-facb974c24ec
* Content: [Office 365 US Government - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @albuss-msft We've completed this update after speaking with the product team.  Thank you for your feedback!
