### ISSUE TITLE
O365 GCC - Now FedRAMP High instead of Moderate

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#456]
> The Office 365 GCC environment provides compliance with Federal requirements for cloud services, including FedRAMP Moderate, and requirements for criminal justice and federal tax information systems (CJI and FTI data types).

According to this blog post, O365 GCC is now certified FedRAMP High instead of Moderate: https://techcommunity.microsoft.com/t5/public-sector-blog/office-365-government-gcc-is-now-fedramp-high/ba-p/1833182

It might make sense to call this out as a recent change for a period of time versus just updating "Moderate" to "High".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3ab3187-c403-8fb1-6ee7-56818777fdad
* Version Independent ID: f6b28482-bf80-436e-cb8f-facb974c24ec
* Content: [Office 365 US Government - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Hi @npherson This has recently been updated.
