### ISSUE TITLE
O365 GCC - Now FedRAMP High instead of Moderate

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#457]
>Office 365 US Government supports the Federal Risk and Authorization Management Program (FedRAMP) accreditation at a Moderate Impact level.

According to this blog post, O365 GCC is now certified FedRAMP High instead of Moderate: https://techcommunity.microsoft.com/t5/public-sector-blog/office-365-government-gcc-is-now-fedramp-high/ba-p/1833182

It might make sense to call this out as a recent change for a period of time versus just updating "Moderate" to "High".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8787e860-9615-fd73-e89a-8a93f8e1c40b
* Version Independent ID: 8771ae61-125e-cd6f-2d21-0954bdd8ea8c
* Content: [Office 365 GCC - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/gcc)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/gcc.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/gcc.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Hi @npherson This has recently been updated.
