### ISSUE TITLE
Microsoft Fluent user interface, the ribbon

### ISSUE THREAD

**Issue by ettienevermeulen** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#458]
In the section Microsoft Fluent user interface, the ribbon
The link takes me to Video: Make the switch to Project 2013

How is this related to the Fluent UI?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c58f8b7d-de2d-4675-d004-74a2a73451eb
* Version Independent ID: 22cd53b7-c264-eae8-4c7c-21232fd9abd1
* Content: [Core functionality - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/project-online-service-description/core-functionality?source=docs)
* Content Source: [Office365-ServiceDescriptions/project-online-service-description/core-functionality.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/project-online-service-description/core-functionality.md)
* Product: **office-online-server**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi ettie, this page has been updated to eliminate this out of date content.  That video was being removed shortly, and the product team has decided to remove the reference to it and to Fluent.
