### ISSUE TITLE
ATP for SharePoint, OneDrive, and Microsoft Teams

### ISSUE THREAD

**Issue by gregmilligan** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#459]
This feature (https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/turn-on-atp-for-spo-odb-and-teams), is a tenant wide setting and can't be scoped to users or groups like Safe Attachments and Safe Links.  What's the guidance for customers when only a portion of their users are licensed for E5/A5?  Does this feature only work if the user also has a Safe Attachments policy, or it truly a global setting?  

Thanks,
Greg Milligan

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @gregmilligan, this is not a service description.  For Support options, please see [Support](https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/support).
