### ISSUE TITLE
Storage limit

### ISSUE THREAD

**Issue by Balamurugan-dot** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#460]
Customer is quite confused about the 1 TB total storage per organization and 25 TB max storage limit per site. It'd be great if you draw the line for this statement.  

Partner's ask : **Can we use exactly 25TB of each sharepoint site regardless of how many “total storage per organization TB” my organization has?**

Let's say for example, they have only one site and want to utilize the 25 TB max storage limit for that site. 

In order to do that, 

1. Do they need to add more user licenses (10 GB per user license) to increase the organization total storage to more than 1 TB? (or)
2. Do they need to purchase Office 365 Extra Storage Add-on?

It'd be great if we add more clarity on this piece.  Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
"Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @Balamurugan-dot We have all the info on the "SharePoint limits" page: [SharePoint limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits) - they automatically get 1TB + 10 GB per license purchased. They can purchase additional storage at $0.20/GB/month (link on that same page). The 25TB limit is simply a technical limit per site collection - of which they can have up to 2M site collections per tenant. So however much default storage they have from the above calculation, they can distribute it how they like across one or many site collections.
