### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by batchku** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#462]
Bad link in this section:
```
Apply conditional formatting
Use a conditional format to help you visually explore and analyze data, detect critical issues, and identify patterns and trends. **Learn more about how to use conditional formatting in Excel for the web**.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0d13579-5b95-82bd-4083-1919e38c034f
* Version Independent ID: 4bc5df6e-4168-3a3e-f72b-0aa327a492e8
* Content: [Excel for the web - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-online-service-description/excel-online?redirectedfrom=MSDN)
* Content Source: [Office365-ServiceDescriptions/office-online-service-description/excel-online.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-online-service-description/excel-online.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.
