### ISSUE TITLE
Size limit for encrypted message is not correct ?

### ISSUE THREAD

**Issue by mohanse** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#463]
[Enter feedback here]
As per this- https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#message-limits-across-standalone-options

Size limit for encrypted messages(new OME) for Exchange Online plan 2 is 150 MB.

But as per this - https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#message-limits-1

Size limit for encrypted messages(new OME) in O365 E5 Plan is 25 MB. But O365 E5 includes Exchange Online Plan 2, so technically the size limit is 150 MB ?

And as per this: https://docs.microsoft.com/en-us/microsoft-365/compliance/ome-faq?view=o365-worldwide#is-there-a-size-limit-for-messages-you-can-send-with-ome

Size limit is 30 MB

can you update documentation with the correct size limit for encrypted messages ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi mohanse, I've spoken with the team.  The SD currently lists the accurate values at https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits under "Size limit for encrypted messages (for subscribers using Office 365 Message Encryption with new capabilities)" and "Size limit for encrypted messages (for subscribers using Office 365 Message Encryption legacy version)"
