### ISSUE TITLE
Microsoft 365 Education Service Description page missing Planner

### ISSUE THREAD

**Issue by joegasper** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#464]
Can we please have Microsoft Planner added?
Planner is listed on the Microsoft 365 suite features and Office 365 Service Description pages, but it is not listed on this page (while we do have other applications like Sway or Office Lens individually listed).
(Hopefully, the Office 365 Education content can finish migrating to the Microsoft 365 Education page.)
Thank you for the consideration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8328da3-5093-09b6-9b9b-b92d13625219
* Version Independent ID: f2171de5-bfa5-65d1-4615-30db23349b40
* Content: [Microsoft 365 Education - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @joegasper This has been completed.
