### ISSUE TITLE
Missing Stream Service Description

### ISSUE THREAD

**Issue by itishnitsa** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#465]
Please add Microsoft Stream service description and limits.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f448a5a2-1307-bf89-c910-9bc03840afde
* Version Independent ID: d99ca5b3-1b4b-6af2-d3c9-dc4cd1afaac3
* Content: [Microsoft 365 and Office 365 service descriptions - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-service-descriptions-technet-library)
* Content Source: [Office365-ServiceDescriptions/office-365-service-descriptions-technet-library.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-service-descriptions-technet-library.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @itishnitsa This is now in the works to be created.
