### ISSUE TITLE
Please update hybrid availability statement for GCC/21Vianetcustomers

### ISSUE THREAD

**Issue by joshtransient** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#466]
Per [this article](https://docs.microsoft.com/en-us/archive/blogs/beyondsharepoint/announcing-hybrid-search-availability-for-office-365-us-government-communication-and-office-365-operated-by-21vianet), hybrid search is available for GCC, GCC High, and 21Vianet. However, this page says that "Hybrid SharePoint Server is not available for all government cloud customers". Can this be spelled out a little more? Which hybrid features are not available? To whom?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5408a406-02e7-bf26-e330-be25ea409aa6
* Version Independent ID: 3ed59637-9e20-85a7-83e1-e70cd61f635e
* Content: [SharePoint for US government environments - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/sharepoint)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/sharepoint.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/sharepoint.md)
* Service: **o365-administration**
* GitHub Login: @kaarins
* Microsoft Alias: **mkashman**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by annferre** [comment]
Hi there, I just wanted to let you know I'm looking into this and I'm hoping I'll have it resolved soon. Thanks!

**Comment by annferre** [comment]
Hi there, the section for [Configuring SharePoint Hybrid Configuration Wizard support for all government cloud customers](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/sharepoint#configuring-sharepoint-hybrid-configuration-wizard-support-for-all-government-cloud-customers) has been added to the service description page. Please let me know if you have questions or concerns. Thanks!
