### ISSUE TITLE
Provide SKUs / product IDs, because the naming is confusing

### ISSUE THREAD

**Issue by DMahalko** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#467]
These product names are stupidly ambiguous and it is very easy to make a mistake and order the wrong product from a Microsoft reseller.

If a customer tells a sales rep they want "Microsoft 365 Education A3", the sales rep may instead give them "Office 365 Education A3" because the sales rep may think it is the same thing, but it is definitely not.

This mistake may not be discovered until after the incorrect license fees have been paid, the wrong contract has been started, and then the IT Director doing the implementation says .... "where are these missing capabilities that I'm supposed to have with Microsoft 365 Education A3?"

So, what is the actual SKU / product ID for each of these columns?

This should be included for each column on this page, either at the very top or bottom of the columns.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8328da3-5093-09b6-9b9b-b92d13625219
* Version Independent ID: f2171de5-bfa5-65d1-4615-30db23349b40
* Content: [Microsoft 365 Education - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Hi @DMahalko We love hearing from our customers! If you have suggestions for how we can improve, please visit the [Microsoft Office 365 feedback and suggestions site](https://office365.uservoice.com/) and share them with us.  I'll forward your feedback on to our licensing team.
