### ISSUE TITLE
There is no feature comparison for apps

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#47]
There used to be table that compared Word 2016 and 2013 to word from Office 365 ProPlus. There was also simillar table for Excel and PowerPoint.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce6699a7-fdd4-a51b-3fdf-9e5ae3ab8cb4
* Version Independent ID: bd7aca02-e040-476f-4b64-1e5f02e90200
* Content: [Office Applications](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-applications-service-description/office-applications#microsoft-excel)
* Content Source: [Office365-ServiceDescriptions/office-applications-service-description/office-applications.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-applications-service-description/office-applications.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by SKjerland** [comment]
@Larryngolog - We no longer show feature comparisons for our older desktop applications. I'm sorry for any inconvenience this may cause.
