### ISSUE TITLE
Moving and copying across sites section - update limits

### ISSUE THREAD

**Issue by asdcristi** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#470]
Hello,

We've recently noticed that "You can copy up to 500 MB of files and folders at a time using the online portal. To copy larger files or files totaling more than 500 MB, use File Explorer.", however haven't seen this change in the Admin Center.

It would be helpful to update the O365 SPO Limits section below, with the new limits, or detail the limits in place in the Online Portal VS File Explorer:

"Moving and copying across sites
Copying/Moving multiple files in a single operation has three requirements:

No more than 100 GB total file size
No more than 30,000 files
Each file must be less than 2 GB"

Many thanks,
Cristian
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
"Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.
