### ISSUE TITLE
Microsoft 365 Business Premium / DLP

### ISSUE THREAD

**Issue by johntchoi** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#471]
There is conflicting information in this document regarding the availability of Office 365 DLP for Microsoft Office Business Premium.

In [this](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#how-do-users-benefit-from-the-service-18)  the following is stated "Microsoft 365 A1/E3/A3/Business, Office 365 E3/A3, and Office 365 Data Loss Prevention provide the rights for a user to benefit from Office 365 DLP for Exchange Online, SharePoint Online, and OneDrive for Business."

However in the document referenced [here](https://www.microsoft.com/download/details.aspx?id=102270) referenced from the top of this document ("To see the options for licensing your users to benefit from Microsoft 365 compliance features as of April 1, 2020, download the Detailed Microsoft 365 Compliance Licensing Comparison.") Office 365 DLP is listed as not available for Microsoft 365 Business Premium

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 licensing guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#which-licenses-provide-the-rights-for-a-user-to-benefit-from-the-service-17)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @v-smandalika
* Microsoft Alias: **v-smandalika**

**Comment by aaronlemieux** [comment]
"Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.
