### ISSUE TITLE
Updates to eligibility link and GCC trials

### ISSUE THREAD

**Issue by kerbos** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#472]
1. Update for section: **How do I buy Microsoft 365 Government?**
https://docs.microsoft.comen-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/microsoft-365-government-how-to-buy#how-do-i-buy-microsoft-365-government

Step 1 has a link to a GCC (Government Community Cloud (FedRAMP Moderate)) eligibility form. However this page also covers GCC High and DoD. After talking to the USGCCE team and they said that these should be used:

GCC - GCC eligibility from - https://www.microsoft.com/en-us/microsoft-365/government/eligibility-validation?rtc=1
GCC High/DoD - General Validation - https://azure.microsoft.com/en-us/global-infrastructure/government/request/?ReqType=General

2. Update for section: **What trials are available?**
https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/microsoft-365-government-how-to-buy#what-trials-are-available

USGCCE also stated that government contractors can now get GCC trial. So maybe this FROM:

- Office 365. A free one-month trial is available exclusively for US government organizations. This is for GCC ONLY and excludes Government Contractors.

TO:

- Office 365. A free one-month trial is available for GCC ONLY.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86dc9aff-0190-52d9-2ab0-4f236d862739
* Version Independent ID: f6cbf527-2a7d-edd6-49b9-ca70ba43b9d6
* Content: [Microsoft 365 Government how to buy - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/microsoft-365-government-how-to-buy)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/microsoft-365-government-how-to-buy.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/microsoft-365-government-how-to-buy.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @kerbos This has been completed.  Thank you.
