### ISSUE TITLE
Compliance Manager Licensing Update

### ISSUE THREAD

**Issue by computeronix** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#474]
Currently Compliance Manager section is worded is worded as: 

"Customers with Office 365 E5/A5 and Microsoft 365 E5/A5 licenses will be able to access Data Protection Baseline, GDPR, NIST 800-53, and ISO 27001 out-of-the-box assessments, as well as make use of the custom assessment feature. Premium assessments will be available for purchase to Office 365 E5/A5 and Microsoft 365 E5/A5 customers during the first half of 2021. They will be available for purchase through VL, CSP and WebDirect."

It should also be included that 
Customers with E1 and E3 licenses will be able to access the default Data Protection Baseline assessment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 licensing guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#feedback)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @v-smandalika
* Microsoft Alias: **v-smandalika**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @computeronix We've updated this service description based on this, after speaking with the product team.  Thank you.
