### ISSUE TITLE
What is "Microsoft Search integration?

### ISSUE THREAD

**Issue by tombraman** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#475]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5408a406-02e7-bf26-e330-be25ea409aa6
* Version Independent ID: 3ed59637-9e20-85a7-83e1-e70cd61f635e
* Content: [SharePoint for US government environments - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/sharepoint)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/sharepoint.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/sharepoint.md)
* Service: **o365-administration**
* GitHub Login: @kaarins
* Microsoft Alias: **mkashman**

**Comment by aaronlemieux** [comment]
Hi @tombraman I see this item doesn't have any work in the body of the text.  Please feel free to comment here or create a new item with a full detail or your request and we'll be happy to address it!.

**Comment by tombraman** [comment]
Aaron LeMieux responded to and closed this thread yesterday, making it
impossible for me to "comment here." Alas.

His note says that the "item doesn't have any work in the body of the
text"-- I hadn't added words any because the subject covered it all: "What
is 'Microsoft Search integration'?" in reference to SharePoint for US
government environments - Service Descriptions | Microsoft Docs
<https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/sharepoint>.
Visit that link, and the term "Microsoft Search integration" appears once,
under "Search features." It's unclear what that phrase means. What to
non-government tenants get that GCC tenants do not? Search integration
across all of Office 365? Search integration with Bing? Search integration
with external systems (such as APIs, networked paths, or similar?)?
Search-customization functionality within the Admin Portal? The subject was
straight and to the point: What is 'Microsoft Search integration'?

Thank you for responding. It might be worth re-opening the thread and
posting a reply, so others can see and benefit from the response.

**Comment by aaronlemieux** [comment]
Hi @tombraman No worries, you can actually comment here no problem, even with the item closed.  I'm actually the only one that manages this repository, so your response comes directly to my email.  Thank you for providing more detailed information.

I'll speak with our product team about having this updated.

**Comment by tombraman** [comment]
Thank you Aaron!

**Comment by aaronlemieux** [comment]
Hi @tombraman This has been updated and completed.  Thank you.
