### ISSUE TITLE
Project on the web,   Does it include CDS storage with the license?

### ISSUE THREAD

**Issue by scottsa-msft** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#476]
As Project on the web is replacing Project online it appears that in my customers tenant that it adds 25GB of storage to CDS/Dataverse for every Project Online license.   If this is the case we should add this as feature that is detailed in the section for Project on the web now using CDS storage as default location for storage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b614c3a-5070-9595-2cb2-d2ec4fb68cb7
* Version Independent ID: f73e4cf9-fe59-e6f4-7638-2bddf97a069e
* Content: [Microsoft Project service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/project-online-service-description/project-online-service-description?source=docs)
* Content Source: [Office365-ServiceDescriptions/project-online-service-description/project-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/project-online-service-description/project-online-service-description.md)
* Product: **office-online-server**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
The product team has requested to keep this service description as is.
