### ISSUE TITLE
EWS connectivity support for Exchange Online Kiosk

### ISSUE THREAD

**Issue by sgreenlee11** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#477]
Hello,

I've noticed that EWS connectivity support is marked as No for the Office 365 F3 license, but marked as Yes for the Exchange Online Kiosk license. This doesn't seem correct, wouldn't they be the same Exchange Online license?

Also, for EWS application support it would be helpful if a footnote could be added as to whether or not this applies to access using application impersonation.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2f622a7-32c1-2c35-2df9-ddf1bc74c74d
* Version Independent ID: e37d85d2-8b81-0c64-b7d0-1e8c01b303db
* Content: [Exchange Online service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @sgreenlee11 We have updated this service description based on your request after speaking with the product team.  Thank you.
