### ISSUE TITLE
Onedrive Storage

### ISSUE THREAD

**Issue by NeftaliRM** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#478]
[Enter feedback here]

I have noticed that under Visio plan 2 the Onedrive storage is 5GB and from Microsoft teams exploratory 2Gb and is not added in this article.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99ce1810-18cd-687b-0c8b-bfceb919225a
* Version Independent ID: 705cde78-7e58-c260-bde3-0b393747cdea
* Content: [OneDrive service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/onedrive-for-business-service-description)
* Content Source: [Office365-ServiceDescriptions/onedrive-for-business-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/onedrive-for-business-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @NeftaliRM 

Under Visio Plan 2, OD storage is 2 GB as mentioned in their [product website](https://www.microsoft.com/en-us/microsoft-365/visio/visio-plan-2?activetab=pivot:overviewtab)

For Teams its [varying among different SKUs](https://www.microsoft.com/en-us/microsoft-teams/compare-microsoft-teams-options).
