### ISSUE TITLE
Stock Images Not Supported SPO DoD

### ISSUE THREAD

**Issue by jarossmsft** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#479]
We have learned from the SharePoint Online product group (SOX Publishing) that Stock Images do not work in the DoD environment and there for is by design. This is because of the network requirements with DoD and Stock Images relying on CDN's. Please see IcM: https://portal.microsofticm.com/imp/v3/incidents/details/212250974/home. It would be nice to get this put into the service descriptions for these customers so they are aware.

Repro:
1. Open a SharePoint Online site in a GCC DoD environment
2. New > Page
3. Change Image
4. Stock Image
5. We're having trouble getting this image for you. Please select a different image, or try again later.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5408a406-02e7-bf26-e330-be25ea409aa6
* Version Independent ID: 3ed59637-9e20-85a7-83e1-e70cd61f635e
* Content: [SharePoint for US government environments - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/sharepoint)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/sharepoint.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/sharepoint.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @jarossmsft This has been completed.  Thank you.
