### ISSUE TITLE
Broken links on Search information page

### ISSUE THREAD

**Issue by garyATstp** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#48]
Many of the links on this SharePoint Online Service Description page for the Search service are broken - e.g. the links to "Managing Query Rules", "Managing query suggestions" and others

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f721a17-dd47-081a-f057-15312f6ebe34
* Version Independent ID: 15517fbe-70c9-8625-35d1-283e9c6d3f88
* Content: [Search](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/search)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/search.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/search.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by pebaum** [comment]
Thanks Gary - taking a look at this and finding new targets for these links.

**Comment by prabita** [comment]
Links are updated
