### ISSUE TITLE
Message Rate Limit and Recipient Rate Limit

### ISSUE THREAD

**Issue by FC-EricWeller** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#480]
I think there's some ambiguity of the "Recipient Rate Limit".  I opened support case #23452294 because an automated mailbox is generating a "Message Recipient Rate Limit" alert.  The mailbox sends many messages, but only sends them to ~40 internal recipients.

O365 Support advises me that the intended behavior of the "Recipient Rate Limit" is to limit the number of addressed recipients to 10,000 per day - whether those recipients are unique or not.  I think this point should be clarified in the documentation which to me seems to imply that the limit is intended to restrict the number of unique recipients.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @FC-EricWeller I've spoke with the product team and they're relayed the following:  "It doesn't matter if the recipients are unique or not - If someone sends one message to 10001 unique recipients or 10001 messages to a single recipient - either way you will hit the limit."  They have requested the SD not be updated to avoid malicious activity.

**Comment by FC-EricWeller** [comment]
Umm....well first of all, I think that "people not knowing exactly how it works" is a poor security mechanism, and second this discussion is public, so that ship has kind of sailed anyway?  

I stand by my opinion that administrators would be better served by a revision as discussed.
