### ISSUE TITLE
Exchange Online Archiving - Deleted Users' Email

### ISSUE THREAD

**Issue by EngelhardtD1** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#481]
When employees are terminated, how does one archive a user's mailbox and archive mailbox for retention purposes?

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @EngelhardtD1 You can find this in the [Remove a Former Employee](https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee?view=o365-worldwide#save-the-contents-of-a-former-employees-mailbox) documentation.  Thank you!
