### ISSUE TITLE
Office 365 DLP - Policy Tips in Office Clients

### ISSUE THREAD

**Issue by jreinhardtproarch** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#482]
I'd suggest adding information to the Office 365 data loss prevention section about policy tip notification support. The reason is that according to https://support.microsoft.com/en-us/office/outlook-license-requirements-for-exchange-features-46b6b7c5-c3ca-43e5-8424-1e2807917c99, the M365 Business Standard and M365 Apps for business plans do not support DLP policy tips. This may be suprising to some partners hoping to deploy a full scale DLP solution using M365 Business Premium if indeed M365 Business Premium also does not support this.  The other link could also be updated to explicitly indicate the support or lack thereof of DLP policy tips in M365 Business Premium but I realize this team is probably not responsible to this other link at support.microsoft.com. Maybe you can work together with the team that manages that.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 licensing guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @jreinhardtproarch The product team has requested that we not modify this documentation.  Thank you.
