### ISSUE TITLE
Microsoft Defender for Office 365 included with Exchange Server 2016?

### ISSUE THREAD

**Issue by gregmilligan** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#483]
The chart says that Microsoft Defender for Office 365 is included with Exchange Server 2016.  Can you explain what that means?  Or is a typo?  Thanks.
![image](https://user-images.githubusercontent.com/11168807/104049028-38913100-51b2-11eb-848d-491f360e24e9.png)

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @gregmilligan We've updated this after speaking with the product team.  Thank you.

**Comment by gregmilligan** [comment]
Thanks Aaron…

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
