### ISSUE TITLE
Link to Download all SLA's is broken. Error 500

### ISSUE THREAD

**Issue by Luitwieler** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#484]
[Enter feedback here]

"download the Service Level Agreement for Microsoft Online Services. " https://www.microsoftvolumelicensing.com/DocumentSearch.aspx?Mode=3&DocumentTypeId=37

Link broken.

![image](https://user-images.githubusercontent.com/10795733/104160353-44b70180-53f1-11eb-81a0-5c2f7ab3bf82.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be031f7b-abd5-5192-9803-0bed8c4a6991
* Version Independent ID: 9bb96c02-da2a-b96d-75ff-c89ca729a104
* Content: [Service Level Agreement - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/service-level-agreement)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/service-level-agreement.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/service-level-agreement.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
I'm sorry that you're having this issue. For Support options, please see [Support](https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/support).
