### ISSUE TITLE
Clarification on the Data Loss Prevention Licensing Requirements (Business Premium should be Yes)

### ISSUE THREAD

**Issue by rtrigueiro** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#485]
Under the [Security & Compliance Center availability for business and enterprise plans](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center#security--compliance-center-availability-for-business-and-enterprise-plans) section in "Data loss prevention for Exchange Online, SharePoint Online, and OneDrive for Business" is listed for Microsoft 365 Business Premium as "No", however, this seems to be incorrect. This can also be confirmed on other sources:
1. 
![image](https://user-images.githubusercontent.com/36214010/104790413-fdcd6100-578e-11eb-891b-3f4a6c9f09a3.png)
Source: https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#office-365-data-loss-prevention-for-exchange-online-sharepoint-online-and-onedrive-for-business

2. 
![image](https://user-images.githubusercontent.com/36214010/104790457-26555b00-578f-11eb-82b3-5abd7d640fa0.png)
Source: https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description

3. 
![image](https://user-images.githubusercontent.com/36214010/104790525-5a308080-578f-11eb-993e-d5d54be56283.png)
Source: https://docs.microsoft.com/en-us/microsoft-365/business/security-features?view=o365-worldwide

Please update this accordingly as this is causing confusion to partners & customers.

Additionally, I believe you should also add the DLP for Teams and DLP for Endpoint, which both require E5/A5 

-
If you want to discuss this, please reach me internally to my Microsoft alias: ritrigue 

Thank you!

Ricardo Trigueiro

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 663a603e-482b-0a4f-55a9-229ceab11bb1
* Version Independent ID: 488b1daa-b459-c56d-11eb-59242af822b0
* Content: [Security & Compliance Center - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
This has been completed.  Thank you.
