### ISSUE TITLE
Power Map and Power View avaiability in 21vianet Office 365

### ISSUE THREAD

**Issue by leapyear1969** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#487]
I see the Power Map feature is avaiable in E3 subscription in 21vianet Office. However, we cannot use that feature with 21vianet Office 365 account.

https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-operated-by-21vianet?redirectedfrom=MSDN#office-365-application-features 

Power Map for Excel | No3 | No | No | No | No | No | No | No | **[Yes]([url](url))**

Please confirm whether this feature is avaiable in 21vianet Office 365 or correct this documentation to avoid any misunderstanding from my customers. thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84a9aadf-5458-1bc2-bbbe-b44794ad18c7
* Version Independent ID: 69a00a16-8f2e-9618-18b5-079c43fd3919
* Content: [Office 365 operated by 21Vianet - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-operated-by-21vianet?redirectedfrom=MSDN#office-365-application-features)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-operated-by-21vianet.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-operated-by-21vianet.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @leapyear1969 This has been completed.
