### ISSUE TITLE
Why was this page changed?

### ISSUE THREAD

**Issue by relair** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#489]
Why was this page changed?
The limit of 50000 uniquely permissioned items is still in place (and applies to whole library not just a single list), but the information about it was removed from this page.
Is there anything changing within SharePoint (and OneDrive) with the limits I should be concerned about?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Hi @relair These changes were recently made in response to another customer's query and so as to remove any ambiguity.  Thank you.
