### ISSUE TITLE
Azure Active Directory Premium P1/P2

### ISSUE THREAD

**Issue by lesterw1** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#49]
Yjos table should reference the inclusion (or omission) of Azure ACtive Directory Premium P1 and P2. While Azure Features like Privileged Identity Management and B2B collaboration are critical (both which are part of P2).  P1 also has some relevant features. I don't suggest listing the features except as a footnote but do add a row to the tables and indicate whether "Basic", "P1", or "P2" is included. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3fea44b-ae19-6168-157e-56e36c76b467
* Version Independent ID: 74e1c2f3-c8f7-16cf-0fd2-7d6007b12abb
* Content: [Office 365 Plan Options](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-plan-options)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-plan-options.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-plan-options.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by afield1235** [comment]
Yes, this is confusing!!!!!!

**Comment by afield1235** [comment]
Does E3 include Azure p2?

**Comment by prabita** [comment]
@lesterw1 Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response.

**Comment by SharS** [comment]
@lesterw1 I added the following footnote to the Office 365 Platform Service Description page:         9. Includes the Azure Active Directory features described in the Office 365 Apps column on the [Azure Active Directory pricing page](https://azure.microsoft.com/en-us/pricing/details/active-directory/). You must add Azure Active Directory Plan 1 or Plan 2, Enterprise Mobile Security, or Microsoft 365 E3 or E5 to get the advanced Azure AD features.
