### ISSUE TITLE
No roadmap

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#490]
This line should be updated
Roadmap.office.com for some service updates

There are no updates for O365 by 21vianet on the roadmap site. This should be listed as 'No'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84a9aadf-5458-1bc2-bbbe-b44794ad18c7
* Version Independent ID: 69a00a16-8f2e-9618-18b5-079c43fd3919
* Content: [Office 365 operated by 21Vianet - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-operated-by-21vianet)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-operated-by-21vianet.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-operated-by-21vianet.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @danmyhre This has been completed.
