### ISSUE TITLE
Unclear limitations on Exchange Online tenant level

### ISSUE THREAD

**Issue by soutchilin** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#491]
Hi Team,

Especially for limitation for sending of the e-mails from a single mailbox (s. below) the documentation doesn't mentions, limitation on the whole Exchange Online service. So if many users are sending lot of e-mails still **below** their individual **Message rate limit**, I'm wondering, if the sum of all messages from all users is limited with a message rate on the Exchange Online "tenant"? 

"Message rate limit: Message rate limits determine how many messages a user can send from their Exchange Online account within a specified period of time. This limit helps prevent over consumption of system resources by a single sender. If a user submits messages at a rate that exceeds the limit via SMTP client submission, the messages will be rejected and the client will need to retry."

Kind regards,
Alexander
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#sending-limits-1)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi soultchilin.  I've spoken with the product team.  They have requested this documentation not be updated.  For Support options, please see [Support](https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/support).
