### ISSUE TITLE
Azure AD Identity Protection "Plan 1" ?

### ISSUE THREAD

**Issue by anthonynz** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#493]
Hi,

Just been redirected to this page by following the "Learn More" link on the M365 F3 product page.

https://docs.microsoft.com/en-NZ/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#azure-active-directory-identity-protection

From what I can tell, there is no such thing as Azure AD Identity Protection Plan 1, or is it alluding that a concession for M365 F3 is allowed for the consumption the Identity Protection product outside of Azure AD Premium P2?

Screen shot from the Microsoft-365 Enterprise F3 page attached:
https://www.microsoft.com/en-nz/microsoft-365/enterprise/f3
 
![M365F3_Product_Page_2021-01-28_13-06-01](https://user-images.githubusercontent.com/1064418/106073949-db185080-616f-11eb-9532-047fa2004eab.jpg)

The “Learn More” link redirects here: 
https://docs.microsoft.com/en-NZ/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#azure-active-directory-identity-protection

Which makes no mention of an Azure AD Identity Protection Plan 1 or Plan 2, and also doesn’t mention M365 F3 as an eligible SKU.

I've checked the en-us version of the page and it is the same as this page.

Can we please have clarification if M365 F3 has a concession to use Azure Identity Protection?
Also if there is a Plan1 / Plan 2 for Identity Protection 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 licensing guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
The product team has been made aware of this and will be making the appropriate updates.

**Comment by anthonynz** [comment]
Thanks Aaron, any indication from the product team of what those updates might be?

Is AAD Identity Protection an included feature in the M365 F3 product?
