### ISSUE TITLE
Timesheet Submission and Task Viewing

### ISSUE THREAD

**Issue by CaptainKirk1071** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#496]
The information on this site is confusing concerning timesheet submissions and the license required. For instance, in one part of the document under the heading Project Online, it states "Team members with Project Online Essentials or Project Plan 1 subscriptions can perform the following Project Online functions:

- Use a web-based interface
- Update tasks, issues, and risks
- Submit timesheets
- Share documents and collaborate with Microsoft Teams or Skype for Business users

Project Online Essentials does not include Project for the web. Project Plan 1 includes Project for the web."

And yet, further down in the tables, submitting timesheets is shown to only be included with Project Plan 3 and Project Plan 5.

Which license is needed for team members to view (but not edit) tasks and update and submit timesheet hours worked?

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b614c3a-5070-9595-2cb2-d2ec4fb68cb7
* Version Independent ID: f73e4cf9-fe59-e6f4-7638-2bddf97a069e
* Content: [Microsoft Project service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/project-online-service-description/project-online-service-description)
* Content Source: [Office365-ServiceDescriptions/project-online-service-description/project-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/project-online-service-description/project-online-service-description.md)
* Product: **office-online-server**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @CaptainKirk1071 This has been completed.  Thank you.
