### ISSUE TITLE
Update GCC High Eligibility form link

### ISSUE THREAD

**Issue by kerbos** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#498]
I recently asked to have step 1 of this section updated. The GCC High link should point to this General Eligibility form, not the Azure Government Trial. 
https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/microsoft-365-government-how-to-buy#how-do-i-buy-microsoft-365-government

GCC High -> redirect to this General Eligibility form https://azure.microsoft.com/en-us/global-infrastructure/government/request/?ReqType=General

I'm not sure if I provided the incorrect link in the last update request or if the authors made a decision to point to the Azure Gov Trial instead (https://azure.microsoft.com/global-infrastructure/government/request/)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86dc9aff-0190-52d9-2ab0-4f236d862739
* Version Independent ID: f6cbf527-2a7d-edd6-49b9-ca70ba43b9d6
* Content: [Microsoft 365 Government how to buy - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/microsoft-365-government-how-to-buy)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/microsoft-365-government-how-to-buy.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/microsoft-365-government-how-to-buy.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Hi @kerbos The specific link provided was provided to us by the product team.  Thank you.

**Comment by aaronlemieux** [comment]
Hi @kerbos After further review, it appears when you submitted #472 the link was not fully updated.  I'll ensure our technical writers get this updated asap.

**Comment by aaronlemieux** [comment]
Hi @kerbos This has been completed.  Thank you.
