### ISSUE TITLE
Changing No to a dash in tables

### ISSUE THREAD

**Issue by jantoney** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#499]
Hey Team, As always - Love the Docs website and the feedback mechanisms. 

Not sure if it's a policy internally, but could I make a suggestion to change "No" in your tables to a dash (-) or simply leave it blank.
I know it's a petty request, but quickly scanning through large tables, and trying to see the difference between Yes and No when looking for differences is a lot harder when it's text.

Anyway, something to have a think about.

Thanks again - Keep up the great work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1bface7-95b2-72b8-43b7-d3bd43b27d0c
* Version Independent ID: ac6756e4-bf78-278c-f8a1-89c182bf545d
* Content: [Licensing Microsoft 365 for small and medium-sized businesses - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/licensing-microsoft-365-in-smb)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/licensing-microsoft-365-in-smb.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/licensing-microsoft-365-in-smb.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thank you for the feedback @jantoney.  I'll discuss this with our leadership team.  We always strive to make our documents as intuitive as possible.  That said, using a dash can be somewhat less clear to some readers than a clear "No."  We appreciate your insight, and will consider this.
