### ISSUE TITLE
Is there a plan to create a Microsoft Teams Service description?

### ISSUE THREAD

**Issue by bmckeating** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#50]
Can you advise when a Teams service description will be published? given the growing dependency list clarification would be appreciated.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22c90a21-a9ed-ff7b-449e-9e8317d9901d
* Version Independent ID: 1ad80e5b-4faf-6c62-ab1b-987952f9dafb
* Content: [Skype for Business Online Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/skype-for-business-online-service-description/skype-for-business-online-service-description)
* Content Source: [Office365-ServiceDescriptions/skype-for-business-online-service-description/skype-for-business-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/skype-for-business-online-service-description/skype-for-business-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by prabita** [comment]
@bmckeating Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response

**Comment by SvenBell** [comment]
Yes now that Skype for Business Online Plan 2 is being retired from sale as of July 1, 2019. We need a Teams service description or link to it from this page.

**Comment by SharS** [comment]
Thanks for your feedback. We currently do not have a service description article written for Teams. I passed your request on to the appropriate team for consideration.
