### ISSUE TITLE
Copying/Moving multiple files in a single operation inside same site

### ISSUE THREAD

**Issue by dumardale** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#500]
It will be helpful to have the limitations for Copying/Moving multiple files in a single operation inside the same site. 
Users are getting "The operation has timed out" and it is not obvious it is because of the number of files selected.  ICM 224978100.

**Comment by aaronlemieux** [comment]
Hi dumardale, can you please provide the service description you're referencing, and more details?

**Comment by annferre** [comment]
I know this is an old ticket, but the content was added:
Moving and copying across sites
Copying/Moving multiple files in a single operation has three requirements:

No more than 100 GB total file size
No more than 30,000 files
Each file must be less than 15 GB
