### ISSUE TITLE
Conflicting Office 365 Education License Service Information (One Outdated Page exists with conflicting info)

### ISSUE THREAD

**Issue by computerdan** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#503]
Please differentiate the data on this page from https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education (Dated 02/12/2021) and this page with same service offering, but with slightly different information (Lit Hold has conflicting information, for example): https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-education  (Dated 11/30/2020) --- Or remove the 11/30/2020 posted data/page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8328da3-5093-09b6-9b9b-b92d13625219
* Version Independent ID: f2171de5-bfa5-65d1-4615-30db23349b40
* Content: [Microsoft 365 Education - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Hi computerdan.  These services and licenses you're referencing are different.  One is O365 and one is M365.  

The licenses in question for Litigation Holds are also listed differently, as O365 lists:  
Office 365 A1 | Office 365 A3 | Office 365 A5, 

While M365 lists:  
Office 365 Education A1 | Office 365 Education A3 | Office 365 Education A5 | Microsoft 365 Education A3 | Microsoft 365 Education A5 | Office 365 A3 Student Use Benefit | Office 365 A5 Student Use Benefit | Microsoft 365 Education A3 Student Use Benefit | Microsoft 365 Education A5 Student Use Benefit

**Comment by computerdan** [comment]
> Hi computerdan. These services and licenses you're referencing are different. One is O365 and one is M365.
> 
> The licenses in question for Litigation Holds are also listed differently, as O365 lists:
> Office 365 A1 | Office 365 A3 | Office 365 A5,
> 
> While M365 lists:
> Office 365 Education A1 | Office 365 Education A3 | Office 365 Education A5 | Microsoft 365 Education A3 | Microsoft 365 Education A5 | Office 365 A3 Student Use Benefit | Office 365 A5 Student Use Benefit | Microsoft 365 Education A3 Student Use Benefit | Microsoft 365 Education A5 Student Use Benefit

Thank you aaronlemieux,
      Perhaps more clarification is needed between the two products - I will reach out to our TAM for clarification as this information may be helpful in determining license purchases.  Fwiw, since there is a difference between M365 A1 and O365 A1, it does appear that Litigation Hold is not available for M365 A1; which may be a major determining factor for some EDU customers as I'm sure one could imagine.  

While a bit of a side-loaded topic expansion; It is nice to see Microsoft starting to provide pages for detailed licensing information.  If a SKUID-To-Product-To-"Friendly Name" Table/Hash (as in Powershell/GraphAPI-to-GUI conversion) becomes available, I'm sure it will be of use - especially if it were retrievable via GraphAPI itself (or meta, etc).  M365-to-O365 Hash/Table information included.  :) Again, Thank you for your reply and help!
-computerDan
