### ISSUE TITLE
Bring back table comparing features by plan and suite sku

### ISSUE THREAD

**Issue by fmesposito** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#504]
This documentation was updated to remove the table format that compared features available across plans and suite SKUs, I.e. to highlight the differences between SharePoint Kiosk, SharePoint P1, SharePoint P2, etc. Can this be added back, similar to the other service descriptions that make this more clear?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b30190b2-6a2d-8380-2ad8-700094acd6fe
* Version Independent ID: 774e7cff-1bb0-1024-e2af-2bec354a3b0b
* Content: [SharePoint service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-service-description)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Hi @fmesposito We're going through an initiative to standardize all our main service description and to include the feature availability table.  Thank you.
