### ISSUE TITLE
CAS is wrong. Needs updating and confirming with licensing team on what is included please.

### ISSUE THREAD

**Issue by emilylait** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#505]
[Enter feedback here]
There are 2 lines for Cloud App Security.

One line says 'Office 365 Cloud App Security' and says it is only in A5. The docs on this product state it is in A3, not A5.
The second line says "Microsoft Cloud App Security" and says it is only in SUB which makes no sense, as this is the one that should be in A5 license.

Can both cloud app security please be checked with program teams and updated?
Thank you
Em

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8328da3-5093-09b6-9b9b-b92d13625219
* Version Independent ID: f2171de5-bfa5-65d1-4615-30db23349b40
* Content: [Microsoft 365 Education - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @emilylait This has been completed.
