### ISSUE TITLE
E3 vs. E5 - Programmatically apply a Retention Label

### ISSUE THREAD

**Issue by Encodian** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#506]
Hi,

Whilst the documentation clearly outlines the available automation options (Specific conditions, trainable classifiers and events) for applying retention labels, and the M365 Compliance Licensing Comparison guide details which of these options are available for the Microsoft 365 E3 and Microsoft 365 E5 licence types.

However, we can't find documentation or guidance confirming whether utilising an API (REST API or CSOM for example) to apply a retention label programmatically is covered by a Microsoft 365 E3 licence or whether a Microsoft 365 E5 licence would be required.

This is covered in the M365 Compliance Licensing Comparison guide for sensitivity labels (Enable 3rd party integration into Microsoft Information Protection (MIP) using MIP SDK), but it's not clear for retention labels.

Can this clarity be provided, please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 licensing guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @Encodian Applying non-record retention labels using a REST API doesn’t require an E5 license. However, applying a record label or a review label using a REST API would require an E5 license.
