### ISSUE TITLE
Define "non-record retention labels"

### ISSUE THREAD

**Issue by adrianwells** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#507]
Under the "Which licenses provide the rights for a user to benefit from the service?" [section ](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#which-licenses-provide-the-rights-for-a-user-to-benefit-from-the-service-8) there is reference to "non-record retention labels". Please define these in this section and/or provide a link to define them. Not yet finding Microsoft documentation that defines this term. (For example might expect to see the term defined [here ](https://docs.microsoft.com/en-us/microsoft-365/compliance/retention?view=o365-worldwide) but it is not yet). Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 licensing guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#which-licenses-provide-the-rights-for-a-user-to-benefit-from-the-service-8)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by adrianwells** [comment]
Maybe this "Learn about records management in Microsoft 365" [document](https://docs.microsoft.com/en-us/microsoft-365/compliance/records-management?view=o365-worldwide#records) should be linked to further define "non-record retention labels"

**Comment by aaronlemieux** [comment]
Hi, this was completed.
