### ISSUE TITLE
With the announcement of the MC241870, do we need to change the file size limit to 250GB?

### ISSUE THREAD

**Issue by o365tatsuyan** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#508]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits#file-size-and-file-path-length)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Hi @o365tatsuyan This has been updated.

**Comment by o365tatsuyan** [comment]
Thank you for the update!
