### ISSUE TITLE
OneDrive on F3 License

### ISSUE THREAD

**Issue by Mikeld001** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#509]
Since F3 seems to be web-only, do you still need to install the OneDrive Sync Client?

From: https://www.microsoft.com/en-us/microsoft-365/enterprise/frontline#office-SKUChooser-0dbn8nt

Note 5 on this site: 5. Plans include 2GB OneDrive storage per user and do not include desktop sync functionality.

Or is this note out of date?

**Comment by aaronlemieux** [comment]
Hi @Mikeld001 Can you clarify which service description you're referring to?

**Comment by Mikeld001** [comment]
Here are the links:

This link was in the original post.  It compares the plans and has the note (5) at the bottom of the page.  It applies to all Frontline Worker Plans.
PDF of the page is attached.

https://www.microsoft.com/en-us/microsoft-365/enterprise/frontline#office-SKUChooser-0dbn8nt 

[M365_FrontlineWorkers_Plan_Comparison.pdf](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions/files/6167644/M365_FrontlineWorkers_Plan_Comparison.pdf)
 
![F3Plans-OneDrive](https://user-images.githubusercontent.com/80296117/111709581-3c7aa880-881e-11eb-807e-1db526db856f.jpg)

![F3Plans-OneDriveNotes](https://user-images.githubusercontent.com/80296117/111709583-3d133f00-881e-11eb-9a3e-8a5e59c5bc08.jpg)

**Comment by aaronlemieux** [comment]
Hi @Mikeld001 This is not part of the service descriptions, so I would check with Support.  For Support options, please see [Support](https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/support).
