### ISSUE TITLE
Maximum file attachment size?

### ISSUE THREAD

**Issue by jjinatlanta** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#51]
What is the maximum size of a file attachment to a list item? I can't find that anywhere and it appears to be in the 100 MB range. I'd like to see a official value on this page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by andradacolceriu** [comment]
It should be 250 MB.

**Comment by dimachernov** [comment]
I have the same question.

**Comment by ichkoj** [comment]
and i have the same question

**Comment by ichkoj** [comment]
Microsoft move your butts and update !

**Comment by prabita** [comment]
@jjinatlanta Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response

**Comment by tomresing** [comment]
The limit is 250 MB.
