### ISSUE TITLE
add abbreviations of GCC and DOD

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#511]
needed abbreviations of GCC and DOD .
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c907526-4061-94b4-f2fd-d6fca90344bb
* Version Independent ID: 82e89c18-8d6e-bbb1-f6d0-6ec091d1556e
* Content: [Office 365 GCC High and DoD - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by RAJU2529** [comment]
@e0i  and @nam31 , I could not able to edit this  article  
**https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod**

**Comment by aaronlemieux** [comment]
Hi @RAJU2529 These terms are widely used within Microsoft documentation.  As such, we will not be clarifying what these abbreviations stand for in the documentation.  However, for your reference, they stand for:
GCC:  Government Community Cloud
DoD:  Department of Defense
