### ISSUE TITLE
Term "recipient" defined in conflicting ways

### ISSUE THREAD

**Issue by Craig323** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#512]
The term "recipient" has different meanings in different sections of this doc.
In one section `recipient` is an after expansion number.
In another section `recipient` is counter before expansion.
The wording or terms could be improved to avoid the conflict.

> Distribution group limits
> Maximum number of distribution group members: The total recipient count is determined after distribution group expansion.

> Sending limits
> Recipient limit: This is the maximum number of recipients allowed in the To:, Cc:, and Bcc: fields for a single email message.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#sending-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi Craig.  I've spoken with the product team and they have requested no change to the documentation.

**Comment by Craig323** [comment]
@aaronlemieux 
Did they share any reason as to why not?
This is difficult to follow.
In one place, a "recipient" is a name in a box (to, cc, bcc).
In another it is the number of members in the DL.
This does not make sense and should be explained more clearly.
