### ISSUE TITLE
Where is Microsoft 365 Business Premium

### ISSUE THREAD

**Issue by gbos212** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#514]
I am curious why Microsoft 365 Business Premium is not listed on the platform service page to get an itemized list of all of the features included but it is included on the plans options page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b5e7518-641b-6d9c-da4f-90f268949793
* Version Independent ID: bae3450b-35b4-d942-7012-7867a705150d
* Content: [Microsoft 365 and Office 365 platform service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-platform-service-description)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Hi @gbos212 This is currently underway.  For now, business premium features are located here:  [Microsoft 365 Business Premium service description](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description)
