### ISSUE TITLE
Difference between "shared computer activation" and "Desktop virtualization"

### ISSUE THREAD

**Issue by adrianwells** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#518]
Hi. Please further explain (or link to other documents) that explain the difference between "Desktop virtualization" feature (that is called out in this document) and [shared computer activation](https://docs.microsoft.com/en-us/DeployOffice/overview-shared-computer-activation). These features seem to be the same but have different terms. Please elaborate to help provide clarity. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 128805e7-b1a4-5cdf-1890-8794fa46d5d5
* Version Independent ID: 884c3ae0-9317-d37c-f94f-97aabd0e622d
* Content: [Office applications service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-applications-service-description/office-applications-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/office-applications-service-description/office-applications-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-applications-service-description/office-applications-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @adrianwells This has been completed.  Thank you.

**Comment by adrianwells** [comment]
@aaronlemieux Hi thank you but may you please explain how this has been completed as the document seems the same (is there a PR to show what has changed)? I'd request this issue stay open until this is further explained.

**Comment by aaronlemieux** [comment]
Hi @adrianwells The product team requested that the change we make to this documentation was to add a link to the [Shared computer activation](https://docs.microsoft.com/en-us/DeployOffice/overview-shared-computer-activation) documentation.

**Comment by adrianwells** [comment]
@aaronlemieux thank you but this does not help with the original issue. Please help with features they seem to be the same but have different terms. Please elaborate to help provide clarity. Thank you.
