### ISSUE TITLE
review "Cloud App Security" row

### ISSUE THREAD

**Issue by mariuszo-at-microsoft-com** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#519]
Review "Cloud App Security" row in the light of this:
https://docs.microsoft.com/en-us/enterprise-mobility-security/solutions/ems-cloud-app-security-govt-service-description
If the MCAS is available in DoD environment (since 3/1), so should be Office CAS.  
If that is so, then references to footnote 15 should be removed from "Cloud App Security" row on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3ab3187-c403-8fb1-6ee7-56818777fdad
* Version Independent ID: f6b28482-bf80-436e-cb8f-facb974c24ec
* Content: [Office 365 US Government - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @mariuszo-at-microsoft-com This item has been completed.  Thank you.
