### ISSUE TITLE
Read access to PWA Project Center and Project Schedule PDP with Essentials?

### ISSUE THREAD

**Issue by GordSchmidt** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#52]
Can a user with the Essentials license access the PWA Project Center and the read the Project PDPs (including schedule)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69451b60-fdc1-4b81-d154-cdd38931a902
* Version Independent ID: f90ef8b6-b8ed-37d8-d5c6-da25f96a0a1d
* Content: [Project Online Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/project-online-service-description/project-online-service-description#feature-availability-across-project-online-standalone-plans)
* Content Source: [Office365-ServiceDescriptions/project-online-service-description/project-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/project-online-service-description/project-online-service-description.md)
* Product: **office-online-server**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by efrene** [comment]
Thanks for your question, and sorry for the delay in getting back to you.  I believe the answer is yes.  A Project Online Essentials license by default allows you the permissions provided to the Team Members SharePoint group, and one of these is "View Project Schedule in Project Web App ".  You can see additional permissions for the Team Members SharePoint group by seeing the table in the article titled "SharePoint Permissions Mode default permissions for Project Server 2013 SharePoint groups" (https://docs.microsoft.com/project/sharepoint-permissions-mode-default-permissions-for-project-server-2013-sharepoi). This table also applies to the SharePoint groups for Project Online.  Hope this helps.
