### ISSUE TITLE
Storage section with SharePoint Online Limits is incorrect

### ISSUE THREAD

**Issue by tommybhoy** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#520]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 482f1200-178f-088c-f189-ac129614cdb0
* Version Independent ID: 94ff27f4-966c-f271-1822-515c4e56a1bb
* Content: [Office 365 Education - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-education)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-education.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-education.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by tommybhoy** [comment]
The SharePoint online limits section is incorrect.

EDU subscriptions do not have unlimited amount of SPO storage. The specific section is within the note area. Note 1 should be removed from the article. This is the section which should be removed below:

"1 You can purchase an unlimited amount of additional SharePoint Online storage. See Add storage space for your subscription."

Only the subscriptions listed on the following articles have unlimited storage:

https://docs.microsoft.com/en-us/microsoft-365/commerce/add-storage-space?redirectSourcePath=%252farticle%252f96EA3533-DE64-4B01-839A-C560875A662C&view=o365-worldwide

As a support engineer, this is confusing customers and driving customers to call Microsoft support.

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @tommybhoy I have spoken with the product team and the service description is currently accurate and does not require any updates.
