### ISSUE TITLE
Update footnote 5

### ISSUE THREAD

**Issue by kelseywylie** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#521]
Footnote 5 should be updated now that OneNote is available in DoD clouds. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9035b5a9-1f84-54be-89ae-c3a0e53891f8
* Version Independent ID: cff57f08-ca51-2266-6189-1ce8181b942e
* Content: [Microsoft Teams service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/teams-service-description)
* Content Source: [Office365-ServiceDescriptions/teams-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/teams-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by kelseywylie** [comment]
Thank you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by aaronlemieux** [comment]
Hi @kelseywylie This has been completed.  Closed.
