### ISSUE TITLE
Windows 10 Education E3 listed twice in table

### ISSUE THREAD

**Issue by pnwnightowl** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#522]
Under the **Available Subscriptions** section and in the **Education Microsoft 365** column, you have Windows 10 Education E3 listed twice.  I believe the 2nd entry needs to be E5 instead of E3, just as it is in the **Enterprise Microsoft 365** column.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21618e67-9ca5-a44e-cfb1-aa1bd215c6f2
* Version Independent ID: 717ddea9-ff81-5fc9-823b-51ba7dee0389
* Content: [Universal Print service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/universal-print-service-description/universal-print-service-description)
* Content Source: [Office365-ServiceDescriptions/universal-print-service-description/universal-print-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/universal-print-service-description/universal-print-service-description.md)
* Service: **o365-administration**
* GitHub Login: @Benzicald
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @pnwnightowl This has been completed.  Thank you.
