### ISSUE TITLE
Should Be Unlimited

### ISSUE THREAD

**Issue by abcizdaman** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#523]
I have so much junkmail coming to both my inbox and Junk folders that it's insane.  It's at least 50 messages a day.  Most of these initiated from looking into Obamacare/Biden Healthcare.  Some from other things.  Apparently they inform many others of your email address, and then you get a barrage of emails from EVERYONE!  Either that or Outlook needs to do a better job blocking junk mail.  There are  tell tell signs, and most of them are obvious right away.  The problem is obvious for the inbox of course, but then there's some good mail that goes in your junk folder, and if you haven't looked for a few days, you have to sort through 100 or more junk mail to find it.  Also some of the email addresses/domains I put in my block list STILL come through, and they're not in my safe list or contacts list.  Outlook just sucks!  I don't have this problem with my GMail or Yahoo accounts.  I don't know if you guys are Microsoft, probably not, but they're hard to get ahold of to tell them such things.  Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5013ccda-a0c6-ce6c-73e7-c78187008f55
* Version Independent ID: a2233d27-d1b1-23af-776b-b860eb1f79b6
* Content: [Exchange Online Protection limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-protection-service-description/exchange-online-protection-limits?redirectedfrom=MSDN)
* Content Source: [Office365-ServiceDescriptions/exchange-online-protection-service-description/exchange-online-protection-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-protection-service-description/exchange-online-protection-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
I'm sorry that you're having this issue. For Support options, please see [Support](https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/support).
