### ISSUE TITLE
FTC no longer supports 50 licenses for GCC, it's now 150.

### ISSUE THREAD

**Issue by ReedL-Microsoft** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#525]
https://o365fasttrack.visualstudio.com/Program%20Management/_workitems/edit/139680?src=WorkItemMention&src-action=artifact_link

Search this document for "50 licenses", it should say "150 licenses". This change was made a year ago.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3ab3187-c403-8fb1-6ee7-56818777fdad
* Version Independent ID: f6b28482-bf80-436e-cb8f-facb974c24ec
* Content: [Office 365 US Government - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government?redirectedfrom=MSDN#fasttrack-center-onboarding-assistance)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Thank you @ReedL-Microsoft, this content has been confirmed with the product team and will be updated shortly.
