### ISSUE TITLE
Add requirement for Skype for Business License for Teams users. 

### ISSUE THREAD

**Issue by carolynblanding** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#526]
[Request to add: "If users have been migrated fully online they must have both teams and Skype for Business Online licenses for full Teams functionality, even if Skype for Business Online will not be used"]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9035b5a9-1f84-54be-89ae-c3a0e53891f8
* Version Independent ID: cff57f08-ca51-2266-6189-1ce8181b942e
* Content: [Microsoft Teams service description - Service Descriptions](https://review.docs.microsoft.com/en-us/office365/servicedescriptions/teams-service-description?source=docs&branch=main)
* Content Source: [Office365-ServiceDescriptions/teams-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/master/Office365-ServiceDescriptions/teams-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @carolynblanding This has been completed.  Thank you.
