### ISSUE TITLE
Can not create an email with attachments

### ISSUE THREAD

**Issue by mrphannguyen** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#527]
Hi, we get an issue when creating a message with attachments of only one mailbox.
Here is details:

POST https://graph.microsoft.com/v1.0/me/messages
Content-type: application/json
Body:
`{ "subject":"Did you see last night's game?", "importance":"Low", "body":{ "contentType":"HTML", "content":"They were <b>awesome</b>!" }, "toRecipients":[ { "emailAddress":{ "address":"abc@gmail.com" } } ], "singleValueExtendedProperties": [ { "id": "XXXXXXX", "value": "XXXXXXXX" } ], "attachments": [ { "@odata.type": "#microsoft.graph.fileAttachment", "name": "attachment.txt", "contentType": "text/plain", "contentBytes": "SGVsbG8gV29ybGQh" } ] }`

From our application:
It throws a generic error from Graph API: "Object reference not set to an instance of an object."

From Graph Explorer/Postman
Result:
`{ "error": { "code": "ErrorQuotaExceeded", "message": "Cannot get ID from name.", "innerError": { "date": "2021-03-30T10:26:15", "request-id": "67cd369c-2f66-45d4-8576-2b769e7d4f92", "client-request-id": "040e5cbd-434e-bc8f-e811-65b4bd0304bb" } }`

It's strange because the mailbox usage 20.64 GB‎ used, ‎41.70‎% of ‎49.5‎ GB, and enable Archive Status
And one more thing, we can create/send that message directly with the endpoint POST https://graph.microsoft.com/v1.0/me/sendMail , outlook web successfully.

Our application is working fine for all mailboxes except this one.

Could you pls help to check or track the above request-id?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
I'm sorry that you're having this issue. For Support options, please see [Support](https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/support).
