### ISSUE TITLE
Incorrect and misleading sections need to be removed. Direct customer Impact!!

### ISSUE THREAD

**Issue by randring** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#529]
[Enter feedback here]
This section is currently not relevant in Excel for the web and should be removed from the document:
Refresh existing data connections
If the data in your workbook is connected to external sources, such as databases, web pages, or analysis cubes, you can refresh that data using Excel for the web.

Currently ,Excel for the web does not support external data refresh to any of the listed data sources. The functionality is severely limited.

Second, the link https://go.microsoft.com/fwlink/p/?LinkId=282330 under "Create external data connections" links to documentation intended for on-premise environments and is also not relevant for Excel for the web.

Any questions please message me (randring).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0d13579-5b95-82bd-4083-1919e38c034f
* Version Independent ID: 4bc5df6e-4168-3a3e-f72b-0aa327a492e8
* Content: [Excel for the web - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-online-service-description/excel-online)
* Content Source: [Office365-ServiceDescriptions/office-online-service-description/excel-online.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-online-service-description/excel-online.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @randring I've spoken with the product team and they have requested this not be updated.  Thank you.

**Comment by randring** [comment]
Thanks @aaronlemieux Did they happen to say why they want to keep inaccurate information on the post? We have had several customer cases that mention these documents and every time we need to inform the customer that external refresh isnt currently supported in Excel Online. If not I can reach out directly on an internal thread and find out what their reasoning is.

**Comment by aaronlemieux** [comment]
Hi @randring After further discussion this has been updated.
