### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by dagroll** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#53]
The "Archive mailboxes in Exchange Online" link in this article redirects to an article on EOP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57d6266c-10f7-4a96-610d-78d04311b63f
* Version Independent ID: 5445d1d2-da07-9223-b56e-225531922051
* Content: [Message Policy and Compliance](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/message-policy-and-compliance)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/message-policy-and-compliance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/message-policy-and-compliance.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by prabita** [comment]
@dagroll updated and published, will be live in 24 hrs.
