### ISSUE TITLE
Exchange Online Kiosk plan

### ISSUE THREAD

**Issue by Ruud-Mens** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#530]
The [Exchange licensing faq](https://www.microsoft.com/en-us/microsoft-365/exchange/microsoft-exchange-licensing-faq-email-for-business)  and the "Feature availability across Exchange Online standalone plans" in the service description don't really match on the following two points:

1. The FAQ states the following: Certain features are disabled for Kiosk users, including **inbox rules**, public folder mailboxes, site mailboxes, **shared mailboxes**, and delegate access to other mailboxes.

   In the service description are the inbox rules listed as available.

2. Shared mailbox access is a bit unclear because an Office 365 F3 user can have access to a shared mailbox (see note 24), but there is nothing mentioned about it in the Feature availability table. And in the FAQ it's mentioned as a disabled feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2f622a7-32c1-2c35-2df9-ddf1bc74c74d
* Version Independent ID: e37d85d2-8b81-0c64-b7d0-1e8c01b303db
* Content: [Exchange Online service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description?redirectedfrom=MSDN)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @Ruud-Mens.  I've spoken with the product team.  For Kiosk users:  Inbox rules, public folder mailboxes, site mailboxes, shared mailboxes, and delegate access to other mailboxes.

The following footnote is incorrect and will be removed:
24 An F3 user cannot add delegates to their own mailbox, but they can access another mailbox (including shared mailboxes) and perform any actions that have been delegated to them.
