### ISSUE TITLE
Sharepoint Online Hybrid for GCC

### ISSUE THREAD

**Issue by jamesrpt** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#532]
Reviewing post # 466 (https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions/issues/466) it says the post will be updated once feedback is given by the team. instead it just shows as closed and that some sort of merge occurred without additional feedback.  We are considering a GCC m365 G3 and having this functionality is a point of concern.  

James

**Comment by aaronlemieux** [comment]
Hi @jamesrpt Thank you for bringing this to my attention.   This item is currently in progress still internally.  I'll be closing this item and reopening #466
