### ISSUE TITLE
Office 365 desktop setup clarification

### ISSUE THREAD

**Issue by Emraphel** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#534]
On the row where Office 365 desktop setup is listed, you have YES on G1 and F3, but according to elsewhere, Office 365 desktop is not allowed for those tiers. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b5e7518-641b-6d9c-da4f-90f268949793
* Version Independent ID: bae3450b-35b4-d942-7012-7867a705150d
* Content: [Microsoft 365 and Office 365 platform service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-platform-service-description)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by annferre** [comment]
Thank you for your comments. We have updated the [M365 Platform Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-platform-service-description) page. Let me know if you have any questions. 
![image](https://user-images.githubusercontent.com/86699727/130259827-fb44a3b8-6a32-45de-8e56-41da10a36870.png)
