### ISSUE TITLE
Mention the original publication date for limits

### ISSUE THREAD

**Issue by Aishwaryagupta59** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#535]
Can we mention the original publication date when the receiving limits were communicated through the doc and when the enforcement will begin. 

It would be easy to communicate that this is not a new change that is being introduced all of a sudden, but has been available in the document and published long back and is only being enforced now.

**Comment by aaronlemieux** [comment]
Hi Aishwaryagupta.  The publication dates for all service descriptions are listed at the top of each page just below the title.
