### ISSUE TITLE
No ability to organize live events for A1 plans

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#536]
Please include a foot note that you need A3 or A5 license to organize live events.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9035b5a9-1f84-54be-89ae-c3a0e53891f8
* Version Independent ID: cff57f08-ca51-2266-6189-1ce8181b942e
* Content: [Microsoft Teams service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/teams-service-description)
* Content Source: [Office365-ServiceDescriptions/teams-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/teams-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @Larryngolog This has been completed.

**Comment by Larryngolog** [comment]
Hi! Should I already see the changes in the article? I do not see anything about the A3/A5 requirement for Live events.

**Comment by aaronlemieux** [comment]
Hi @Larryngolog The product team requested the following line be added to the live events section:  "To learn more about planning live events, including license requirements, see [Plan for live events in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/plan-for-teams-live-events)."

**Comment by Larryngolog** [comment]
Thanks!
