### ISSUE TITLE
Update GCC eligibility link in step 1 of this document 

### ISSUE THREAD

**Issue by kerbos** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#537]
Please update the GCC eligibility link in step 1 of this document to this link: https://www.microsoft.com/en-us/microsoft-365/government/eligibility-validation

_1. Complete and submit the form for GCC or GCC-High to validate your organization’s eligibility._

Leave the GCC-High link as-is.

See approval from engineering per the email thread with Ken C.

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86dc9aff-0190-52d9-2ab0-4f236d862739
* Version Independent ID: f6cbf527-2a7d-edd6-49b9-ca70ba43b9d6
* Content: [Microsoft 365 Government how to buy - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/microsoft-365-government-how-to-buy#how-do-i-buy-microsoft-365-government)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/microsoft-365-government-how-to-buy.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/microsoft-365-government-how-to-buy.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. This work item is actively being processed now.

**Comment by aaronlemieux** [comment]
Hi @kerbos This has been completed.
