### ISSUE TITLE
Office 365 Customer Key section vague / not clear

### ISSUE THREAD

**Issue by teomonda** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#538]
The O365 Customer Key section related to the <How can the service be applied only to users in the tenant who are licensed for the service?> is not clear enough and actually quite misleading.

https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#how-can-the-service-be-applied-only-to-users-in-the-tenant-who-are-licensed-for-the-service-14

This part:
" Mailboxes and files for which you don't assign a policy will use encryption policies that are controlled and managed by Microsoft."
suggests that you can choose both the mailboxes and the files (=sites) to which you apply such policies.
This is only true for mailboxes, whereas policies for SharePoint and OneDrive are assigned per tenant.

See here:
https://docs.microsoft.com/en-us/microsoft-365/compliance/customer-key-overview?view=o365-worldwide#about-the-data-encryption-policy-dep
SharePoint Online, OneDrive for Business, and Teams files If you're using the multi-geo feature, you can create up to one DEP per geo for your organization. You can use different Customer Keys for each geo. If you're not using the multi-geo feature, **you can only create one DEP per tenant**. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 licensing guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by teomonda** [comment]
Thanks, Aaron, looking forward to hearing from you!

**Comment by aaronlemieux** [comment]
Hi @teomonda I've spoked with the product team who collaborated with the customer key engineering team.  They have requested no changes be made at this time, as customer key documentation changes are currently in the works.
