### ISSUE TITLE
Update required for GCCH and DOD Connectors feature availability

### ISSUE THREAD

**Issue by pradeepananth** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#539]
Document link: https://docs.microsoft.com/en-us/office365/servicedescriptions/teams-service-description#feature-availability
Document update required to indicate that Connectors are not supported in GCCH and DOD.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9035b5a9-1f84-54be-89ae-c3a0e53891f8
* Version Independent ID: cff57f08-ca51-2266-6189-1ce8181b942e
* Content: [Microsoft Teams service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/teams-service-description#feature-availability)
* Content Source: [Office365-ServiceDescriptions/teams-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/teams-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Hi @pradeepananth As you have already filed an internal request for this item, I'll be closing this GitHub request as a duplicate.
