### ISSUE TITLE
Government SKUs

### ISSUE THREAD

**Issue by grywalskita** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#54]
Could you provide service descriptions for G1, G3, G5 etc?  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e69c139-60fc-5e97-168a-12d7bf1fbd38
* Version Independent ID: bd4edf0e-4a2f-2bf7-92e6-c7e840584977
* Content: [Office 365 US Government](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md)
* Service: **o365-administration**
* GitHub Login: @danarl
* Microsoft Alias: **danarl**

**Comment by danarl** [comment]
Office 365 US Government service description for G1, G3, G5 is posted here: https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government
