### ISSUE TITLE
Add M365 A1 plans

### ISSUE THREAD

**Issue by jaymichaud** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#540]
This page is missing two education plans: Microsoft 365 Education A1 and Microsoft 365 Education A1 Student Use Benefit. It is important for customers to understand which capabilities are available (and which are not) at the A1 level. Would you please add these plans to the comparison grid this page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8328da3-5093-09b6-9b9b-b92d13625219
* Version Independent ID: f2171de5-bfa5-65d1-4615-30db23349b40
* Content: [Microsoft 365 Education - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by jaymichaud** [comment]
I spoke with my organization's Microsoft account representative and a Microsoft commercial executive and got clarification on these plans. There is no such plan as "Microsoft 365 Education A1"; instead, my organization was purchasing "**Office** 365 Education A1" alongside "**Microsoft** 365 Education A3". The grid on this page is _not_ missing columns, so I am closing this issue. I apologize for the confusion and any work that was generated due to this issue.

**Comment by aaronlemieux** [comment]
Thank you, @jaymichaud
