### ISSUE TITLE
Limitations on term sets 

### ISSUE THREAD

**Issue by carlmarn** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#541]
[Enter feedback here]
Under the "Managed metadata" section the following is currently written:
"1 million total terms, having a total of 2 million term labels and 1 million term properties (these limits are for global & site-level terms combined). 1,000 global term sets and 1,000 global groups."
What I however do not clearly understand is:
- How many local term sets and local term set groups are allowed (in the text above it only mentions the limitations on the global term sets)?
- If you reuse/pin a term in different term sets, are they considered as multiple terms or just one term?
- You can have 1 million terms but 2 million term labels. Are term labels here the same as "Other labels", so in average a term can have one additional "other label"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by carlmarn** [comment]
Thanks for your reply!
I am right now in the process of designing a SharePoint solution for one of the bigger municipalities in Sweden and would really need to know these limitations, so I appreciate any form of update on these questions.
Regards,
Carl


Carl Mårn
Managing Partner
+46 70 423 33 37
***@***.******@***.***>
www.linkedin.com/in/carlmarn/<http://www.linkedin.com/in/carlmarn/>

MetaShare®
Simplifies Document Management
www.metashare.com<http://www.metashare.com>

**Comment by carlmarn** [comment]
Hello again!

Do you have any update on the term store limitations? I would need to know this quite soon, as we are in the process of designing a large SharePoint infrastructure and the answer to this question will be quite important in choosing the right path.

Regards,
Carl

Carl Mårn
Managing Partner
+46 70 423 33 37
***@***.******@***.***>
www.linkedin.com/in/carlmarn/<http://www.linkedin.com/in/carlmarn/>

MetaShare®
Simplifies Document Management
www.metashare.com<http://www.metashare.com>

From: Carl Mårn
Sent: den 23 april 2021 12:52
To: MicrosoftDocs/OfficeDocs-O365ServiceDescriptions ***@***.***>
Subject: RE: [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions] Limitations on term sets (#541)

Thanks for your reply!
I am right now in the process of designing a SharePoint solution for one of the bigger municipalities in Sweden and would really need to know these limitations, so I appreciate any form of update on these questions.
Regards,
Carl


Carl Mårn
Managing Partner
+46 70 423 33 37
***@***.******@***.***>
www.linkedin.com/in/carlmarn/<http://www.linkedin.com/in/carlmarn/>

MetaShare®
Simplifies Document Management
www.metashare.com<http://www.metashare.com>

**Comment by aaronlemieux** [comment]
Hi @carlmarn I've spoken with the product team and they have requested the service description remain the same.

For Support options, please see [Support](https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/support).

**Comment by carlmarn** [comment]
Hello Aron!

Thanks for your mail. It’s up to the development team to decide what to add to the service description. I would however be very glad if you or your team could advice on the following questions:

  1.  Are local term sets and local term set groups included in SharePoint’s Term store limitations (1,000 global term sets and 1,000 global groups)?
  2.  If a term is reused/pinned in different term sets, are they considered as multiple terms or just one term? Do they add up to the limitation of 1 million terms?
  3.  You can have 1 million terms but 2 million term labels. Are term labels here the same as "Other labels", so in average a term can have one additional "other label"?

I need answers to the questions in order to do a proper implementation for a larger client.
If it is difficult to answer all the 3 questions, I would be fine with an answer to question nr 1, as there’s where the client might hit a limit.

Best regards,
Carl

Carl Mårn
Managing Partner
+46 70 423 33 37
***@***.******@***.***>
www.linkedin.com/in/carlmarn/<http://www.linkedin.com/in/carlmarn/>

MetaShare®
Simplifies Document Management
www.metashare.com<http://www.metashare.com>

**Comment by aaronlemieux** [comment]
Hi @carlmarn Unfortunately, I would not be the technical resource to provide that information.  You'll want to utilize our support options.  For Support options, please see [Support](https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/support).
