### ISSUE TITLE
Thank you.

### ISSUE THREAD

**Issue by Lucas-mn** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#542]
Since M365 includes O365 + Windows + EMS, why not categorizing services and features under these three pillars?
Also, "Management and security" is a little bit confusing and easy to get misunderstood by "Mobility and security" as in EMS. 
Obviously, there is no clue about what exactly EMS includes from this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8328da3-5093-09b6-9b9b-b92d13625219
* Version Independent ID: f2171de5-bfa5-65d1-4615-30db23349b40
* Content: [Microsoft 365 Education - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Hi @Lucas-mn Thank you for the feedback.  I'll let the product team know and discuss these suggestions with them.
