### ISSUE TITLE
Unable to get sharepoint site data using graph API[Application Permissions] - Germany deployment

### ISSUE THREAD

**Issue by sUndar-Balaji** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#544]
Permission Type - **Application Permissions**
Deployment - **Germany**
API Type - **Graph**

I'm trying to get all the sharepoint site collections using the below mentioned graph API.

https://graph.microsoft.de/v1.0/sites?search=*&$top=1000

I'm getting the **accessDenied** 403 Forbidden error. Attached the screenshot of the error message

<img width="817" alt="Screen Shot 2021-04-27 at 2 44 39 PM" src="https://user-images.githubusercontent.com/15965938/116217387-381fa480-a767-11eb-956a-a3e763bb914a.png">

I've tried the /sites endpoint as well. It's returning empty list in the response. Our tenant has **30 sites**.

https://graph.microsoft.de/v1.0/sites

<img width="821" alt="Screen Shot 2021-04-27 at 3 25 45 PM" src="https://user-images.githubusercontent.com/15965938/116223193-ea0d9f80-a76c-11eb-8f60-2558fb9f51c1.png">

Application has been registered & configured in **portal.microsoftazure.de**

Below mentioned are the scopes which are given for our Azure AD application

![azure-scope](https://user-images.githubusercontent.com/15965938/116221792-92226900-a76b-11eb-9852-c6263316df85.png)

**I'm not sure if i'm missing some App configuration or some other setting. Any leads to get the site collections using graph API would be very much helpful.**

**Comment by amol-narkhede** [comment]
I am also facing Same issue

**Comment by aaronlemieux** [comment]
I'm sorry that you're having this issue. For Support options, please see [Support](https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/support).
