### ISSUE TITLE
SharePoint upload size limit

### ISSUE THREAD

**Issue by narismadz** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#545]
Document here need to be update on upload size limit
(correct me if I'm wrong) - initial 100 GB and then 250 GB from announcement
Please check
[https://techcommunity.microsoft.com/t5/microsoft-onedrive-blog/gain-more-flexibility-with-250-gb-file-size-support-in-microsoft/ba-p/1847728](https://techcommunity.microsoft.com/t5/microsoft-onedrive-blog/gain-more-flexibility-with-250-gb-file-size-support-in-microsoft/ba-p/1847728)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @narismadz I've spoked with the product team and they state that the page is accurate.
