### ISSUE TITLE
Microsoft Forms info outdated

### ISSUE THREAD

**Issue by kelseywylie** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#547]
I believe that the Microsoft Forms section of this page needs to be updated. There are features that are now available in some of the Government Clouds that are indicated as "No" under the Forms table. For example, you are able to insert a photo now in GCC environments. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3ab3187-c403-8fb1-6ee7-56818777fdad
* Version Independent ID: f6b28482-bf80-436e-cb8f-facb974c24ec
* Content: [Office 365 US Government - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by annferre** [comment]
Hi there, I just wanted to let you know I am working on this and should have an update soon. Thanks!

**Comment by annferre** [comment]
Hi there, I just wanted to let you know the following change was made: 
![image](https://user-images.githubusercontent.com/86699727/131556664-b89c99e5-32cf-4366-8b0d-2c1b1b714a3f.png)
Let me know if you have further questions.
Thanks!
