### ISSUE TITLE
Does A1 include Teams?  

### ISSUE THREAD

**Issue by PsychoData** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#548]
This page shows "Microsoft Teams" on the [linked page](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education), and on [this page](https://docs.microsoft.com/en-us/office365/servicedescriptions/teams-service-description), but at the [Service Plan Reference](https://docs.microsoft.com/en-us/azure/active-directory/enterprise-users/licensing-service-plan-reference#:~:text=Microsoft%20365%20A1) it shows no Teams license/service. Is it just meaning "Teams Free"? I feel like that should probably be given a footnote if that is the case

![image](https://user-images.githubusercontent.com/3719116/117391237-8a766900-aebd-11eb-9bcb-f51017480302.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8328da3-5093-09b6-9b9b-b92d13625219
* Version Independent ID: f2171de5-bfa5-65d1-4615-30db23349b40
* Content: [Microsoft 365 Education - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.
