### ISSUE TITLE
Information about subscriptions is wrong!

### ISSUE THREAD

**Issue by UpsilonB** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#552]
Dear

Half way down the page under "Microsoft Project Subscriptions" its says that Plan 1 also includes Project Online. This information is incorrect.
https://docs.microsoft.com/en-us/office365/servicedescriptions/project-online-service-description/project-online-service-description#microsoft-project-subscriptions

Correct info:
https://www.microsoft.com/en-us/microsoft-365/project/compare-microsoft-project-management-software

Kind regards
Ype Bertels
ype@outlook.be

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b614c3a-5070-9595-2cb2-d2ec4fb68cb7
* Version Independent ID: f73e4cf9-fe59-e6f4-7638-2bddf97a069e
* Content: [Microsoft Project service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/project-online-service-description/project-online-service-description#microsoft-project-subscriptions)
* Content Source: [Office365-ServiceDescriptions/project-online-service-description/project-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/project-online-service-description/project-online-service-description.md)
* Product: **office-online-server**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @UpsilonB I've spoken with the product team and they have verified the service description is accurate, that Plan 1 does include Project Online. It includes Project Online Essentials.  They have been notified that the marketing page needs to be updated.

**Comment by UpsilonB** [comment]
Hi Aaron

Are they sure? Because I know that plan one contains Project for the Web.
That is a completely other product. I dont think it contains Project
Online. e.g. Project for the Web cannot open .MMP files.

Op vr 4 jun. 2021 om 00:21 schreef Aaron LeMieux ***@***.***>:
