### ISSUE TITLE
Gov Cloud Feature Table Needs Updating

### ISSUE THREAD

**Issue by kelseywylie** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#553]
The table that shows specific features and which are available in which Gov Clouds needs updating. For example, this chart shows that Dictation is not available in GCC or GCCH clouds, but it is available now. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 128805e7-b1a4-5cdf-1890-8794fa46d5d5
* Version Independent ID: 884c3ae0-9317-d37c-f94f-97aabd0e622d
* Content: [Office applications service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-applications-service-description/office-applications-service-description)
* Content Source: [Office365-ServiceDescriptions/office-applications-service-description/office-applications-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-applications-service-description/office-applications-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by annferre** [comment]
Hi there, would you by chance be referring to the [Office 365 US Government](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government#office-application-and-feature-availability-in-government-plans) page? I did reach out to the team and they are in the process of reviewing the page. I will keep you updated on progress. Thanks!

**Comment by annferre** [comment]
Hi there, I just wanted to let you know various feature updates have been made to the feature cloud table, including for dictation. Thank you again for your comments. Let me know if you have any concerns or questions. Cheers!
