### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by PaulKew** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#554]
Requirements for Microsoft Defender for Office 365
Defender for Office 365 can be used with any SMTP mail transfer agent, such as Microsoft Exchange Server. For information about the operating systems, web browsers, and languages that are supported by Defender for Office 365, see the "Supported browsers" and "Supported languages" sections in Exchange admin center in Exchange Online Protection. (https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/exchange-admin-center-in-exchange-online-protection-eop)

Link is broken
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 502796e9-ca73-7123-7719-c7b5b1042b7b
* Version Independent ID: 2929af88-6d56-4de3-2b4e-4e1d0e4d97ef
* Content: [Microsoft Defender for Office 365 service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description)
* Content Source: [Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @PaulKew This has been updated.
