### ISSUE TITLE
Manual labels in M365 BP, respectively AIP Plan 1

### ISSUE THREAD

**Issue by teomonda** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#555]
The article lists Microsoft 365 Business Premium as not including Manual sensitivity labels.
Whereas the downloadable Excel says it does...

In addition I am confused about the difference in platform support for Manual labels. 
Namely that in the downloadable table we say that Manual sensitivity labels for M365 Apps are included with Azure Information Protection P1 whereas on Office Mobile and web are not. It does list Business Premium as including them though.

Can you please double check the correctness of this info?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 663a603e-482b-0a4f-55a9-229ceab11bb1
* Version Independent ID: 488b1daa-b459-c56d-11eb-59242af822b0
* Content: [Security & Compliance Center - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center?source=docs)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Hi @teomonda The latest downloadable file has been updated.

**Comment by teomonda** [comment]
hello @aaronlemieux , Thank you for the update!
I have checked the new downloadable file, and I see now we have only a PDF, not the Excel file.
In addition to this, unless I am missing anything, Small Business plans are absent here, we only see Enterprise and Firstline plans.
The level of detail I was after is also not present in these PDF tables.

**Comment by aaronlemieux** [comment]
Hi @teomonda The current content is a temporary solution that was requested by the PMM that owns this content, until they compile the latest comprehensive content.
