### ISSUE TITLE
Broken link referenced in article

### ISSUE THREAD

**Issue by cohortswitchback** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#556]
https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/whats-new-in-office-365-atp

This link referenced in the article is broken.

![Screen Shot 2021-06-01 at 4 01 05 PM](https://user-images.githubusercontent.com/85201091/120400393-a4f00680-c2f2-11eb-8504-92330b49afd4.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 502796e9-ca73-7123-7719-c7b5b1042b7b
* Version Independent ID: 2929af88-6d56-4de3-2b4e-4e1d0e4d97ef
* Content: [Microsoft Defender for Office 365 service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description)
* Content Source: [Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @cohortswitchback This has been completed.
