### ISSUE TITLE
Microsoft 365 Government G5 Service Descriptions

### ISSUE THREAD

**Issue by adrianwells** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#558]
Hi. Where can the Microsoft 365 Government Service Descriptions be found? There is other Microsoft material [like this, "Discover the Microsoft 365 U.S. Government plan that’s right for you,"](https://www.microsoft.com/en-us/microsoft-365/government#office-ContentAreaHeadingTemplate-57hz5qu) but there does not yet appear to be Microsoft 365 Government Service Descriptions.  Additional there is [Office 365 Government service descriptions ](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government) and for the commercial space documents such as [this, "Microsoft 365 and Office 365 platform service description" ](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-platform-service-description)

Please advise. Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86dc9aff-0190-52d9-2ab0-4f236d862739
* Version Independent ID: f6cbf527-2a7d-edd6-49b9-ca70ba43b9d6
* Content: [Microsoft 365 Government how to buy - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/microsoft-365-government-how-to-buy)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/microsoft-365-government-how-to-buy.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/microsoft-365-government-how-to-buy.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Hi @adrianwells There is not currently a specific service description for M365 government.

**Comment by adrianwells** [comment]
@aaronlemieux thank you. This seems related to #559
