### ISSUE TITLE
Update title to include "platform service description"

### ISSUE THREAD

**Issue by adrianwells** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#559]
Please consider updating this document's title to make it more descriptive like "Office 365 Government platform service description". It will also make it consistent with other documents like ["Microsoft 365 and Office 365 platform service description"](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-platform-service-description)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3ab3187-c403-8fb1-6ee7-56818777fdad
* Version Independent ID: f6b28482-bf80-436e-cb8f-facb974c24ec
* Content: [Office 365 US Government - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by adrianwells** [comment]
Thank you @aaronlemieux

**Comment by annferre** [comment]
Apologies for the delay. We really appreciate your feedback. The product team is looking into all the pages, and making updates for clarity as able. In regards to changing the title of the O365 Government page, currently, only our main workloads have the “service description” listed on them. Thanks!
