### ISSUE TITLE
Differences in versions

### ISSUE THREAD

**Issue by kstario** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#56]
I cannot find the different between ATP Plan 1 and ATP Plan 2. Perhaps that should be detailed here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 502796e9-ca73-7123-7719-c7b5b1042b7b
* Version Independent ID: 2929af88-6d56-4de3-2b4e-4e1d0e4d97ef
* Content: [Office 365 Advanced Threat Protection Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description)
* Content Source: [Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by SKjerland** [comment]
@kstario - There are not separate ATP plans--ATP is automatically included in subscriptions such as Microsoft 365 Enterprise, Microsoft 365 Business, Office 365 Enterprise E5, and Office 365 Education A5. Some subscriptions, however, don't include ATP, but you can purchase ATP as an add-on. For more information, see [Office 365 Advanced Threat Protection](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description). Hope this helps!

**Comment by kstario** [comment]
I am literally looking at the Add Subscriptions page of my O365 tenant and I see ATP Plan 1 and ATP Plan 2. If there is no difference in the product offering between the two, then perhaps the customer should be guided to make the correct choice depending upon their base plan. I'm on E3, for reference. 

Office 365 Advanced Threat Protection (Plan 1)
$2.00 user/month

Modern email protection techniques such as Safe Links and Safe Attachment, complementing the defense of Exchange Online Protection to protect your mailboxes against sophisticated attacks.
Office 2016 desktop & mobile apps
Not included 

Office 365 Advanced Threat Protection (Plan 2)
$5.00 user/month

Provides rich insights on advanced threats, supports proactive defense against them, and integrates seamlessly with other Office 365 security features.
Office 2016 desktop & mobile apps
Not included
Office 365 services

**Comment by SKjerland** [comment]
@kstario - Thanks for providing that additional information! We'll see what we can do to clarify it.

**Comment by kstario** [comment]
My pleasure... Hopefully it will save someone the hour of searching I spent trying to determine the difference (still don't know).

**Comment by toddportz** [comment]
I too am curious on this.

**Comment by dsghi** [comment]
The differences are listed on this page: https://products.office.com/en-us/exchange/advance-threat-protection#pmg-allup-content

Basically:
Plan 1 - The base protection malware/phishing with safe links
Plan 2 - advanced tools for investigation/response and testing (attack simulator)

**Comment by miss-tech** [comment]
This is a recent change. I believe the product which used to be called "Threat Intelligence" has been rolled into ATP and provided as ATP Plan 2.

**Comment by brucelaing** [comment]
Additional ATP Plan 1 capabilities for existing Office Threat Intelligence (ATP Plan 2) customers

Microsoft are consolidating the capabilities in current Office 365 Advanced Threat Protection(ATP) and Office 365 Threat Intelligence products to help customers with detection, protection, investigation and remediation of threats. 

They're offering this through two SKUs: 
1. Current "Office 365 ATP" SKU becomes "Office 365 ATP Plan 1" 
2. Current "Office 365 Threat Intelligence" SKU becomes "Office 365 ATP Plan 2" 

Office 365 ATP Plan 2 includes Office 365 ATP Plan 1. So, Microsoft will be back-filling Office 365 ATP P1 capabilities to existing Office 365 Threat Intelligence customers. We've started seeing this happening and the name changes in Office 365 Licencing since the 1st Feb 2019.

**Comment by SKjerland** [comment]
The author of the article updated it to address this confusion.
