### ISSUE TITLE
Please update the upload file size of SharePoint

### ISSUE THREAD

**Issue by zakarm1** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#560]
What is the actual file upload size?  It keeps changing.  I know it's been changed to 250GB but now I heard it might be 300GB.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Hi @zakarm1 The service description is currently accurate.  You can upload 250GB files.

**Comment by mcloum** [comment]
It isnt accurate as i cannot upload more than a 15gb file. The documentation is contradicting itself. Even the tools Microsoft provide failed on files larger than 15gb when they try to upload, namel the Sharepoint migration tool and the File share migration tool.

So can we get some clarification on where the 250gb file support actually applies?
