### ISSUE TITLE
App info should link to Office 365 descriptions, not Office 2019

### ISSUE THREAD

**Issue by elisabeth-jones** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#561]
Each of the app descriptions here links to SMC articles like "What's new in Excel 2019." Excel 2019 is not the latest version of the app - Excel for Microsoft 365 is. Same for the rest of the suite. I'd remove the 2019 links, and perhaps link out to the app marketing pages instead (e.g. https://www.microsoft.com/en-us/microsoft-365/excel).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce6699a7-fdd4-a51b-3fdf-9e5ae3ab8cb4
* Version Independent ID: bd7aca02-e040-476f-4b64-1e5f02e90200
* Content: [Office applications - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-applications-service-description/office-applications#feedback)
* Content Source: [Office365-ServiceDescriptions/office-applications-service-description/office-applications.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-applications-service-description/office-applications.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @elisabeth-jones This has been completed.
