### ISSUE TITLE
GCCH Feature updates

### ISSUE THREAD

**Issue by jlabjlab** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#562]
For the section, office-application-and-feature-availability-in-government-plans

https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government#office-application-and-feature-availability-in-government-plans

Some of the references to GCCH (GCC High) are out of date, and need to be updated. 

The following features are available when the file is hosted on OneDrive, or Sharepoint Online:

- Excel
  - Version history
  - Real-time collaboration (presence, regular coauthoring, in-document chat)
- PowerPoint
  - Version history
  - Real-time collaboration (presence, regular coauthoring, in-document chat)
- Word
  - Version history
  - Contextual chat with co-authors: chat with co-authors within the document

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3ab3187-c403-8fb1-6ee7-56818777fdad
* Version Independent ID: f6b28482-bf80-436e-cb8f-facb974c24ec
* Content: [Office 365 US Government - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by annferre** [comment]
Hi there, I just wanted to let you know various updates were made to the feature table for GCCH. Thank you again for your comments. Let me know if you have any further questions or concerns. Cheers!
