### ISSUE TITLE
Adding lists and pages to Teams works in GCC High

### ISSUE THREAD

**Issue by aandrew129** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#563]
In my testing, adding SharePoint lists and pages to Teams as a tab works just fine in a GCCH tenant. Could someone confirm that with the product group and update the "Sites and content" section of the page if appropriate?

Thanks much!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5408a406-02e7-bf26-e330-be25ea409aa6
* Version Independent ID: 3ed59637-9e20-85a7-83e1-e70cd61f635e
* Content: [SharePoint for US government environments - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/sharepoint)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/sharepoint.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/sharepoint.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by annferre** [comment]
Hi there, I just wanted to let you know I'm still working on this. I was able to confirm Lists in Teams is now available as part of GCC-High (rollout in June 2021).  I'm still waiting for Pages confirmation, and I'll update the SD page once I get confirmation. Thanks!

**Comment by annferre** [comment]
Hi there,  the "Sites and content" section has been updated and reference to lists and pages not being available has been removed. Let me know if you have further questions. Thanks!
