### ISSUE TITLE
Question on MSGraph, SPO and GCC 

### ISSUE THREAD

**Issue by SanjoyanM** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#564]
This article says"
Graph functionality within SharePoint Online for GCC High is currently disabled. Any service that relies on Microsoft Graph may not currently be available"

**Customer would like to build a webpart that connects to MS Graph to Read/Write objects. Will the above prevent this? If yes, are there any plans to lift this restriction?**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5408a406-02e7-bf26-e330-be25ea409aa6
* Version Independent ID: 3ed59637-9e20-85a7-83e1-e70cd61f635e
* Content: [SharePoint for US government environments - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/sharepoint#sites-and-content)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/sharepoint.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/sharepoint.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Hi @SanjoyanM I'm sorry that you're having this issue. For this I would want to refer you to support.  For Support options, please see [Support](https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/support).
