### ISSUE TITLE
Incorrect limits in this page

### ISSUE THREAD

**Issue by marsch-bit** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#565]
The supported date range in Project for the web is 1/1/2000-12/31/2149. The current date range on this page is wrong. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b614c3a-5070-9595-2cb2-d2ec4fb68cb7
* Version Independent ID: f73e4cf9-fe59-e6f4-7638-2bddf97a069e
* Content: [Microsoft Project service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/project-online-service-description/project-online-service-description)
* Content Source: [Office365-ServiceDescriptions/project-online-service-description/project-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/project-online-service-description/project-online-service-description.md)
* Product: **office-online-server**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by annferre** [comment]
Hi @marsch-bit,
This request has been completed.
