### ISSUE TITLE
Office 365 Video is retired

### ISSUE THREAD

**Issue by egiberne** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#566]
[Enter feedback here]
Office 365 Video is retired, rigth  ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dd954d8-5874-8d25-36eb-0718ef86d585
* Version Independent ID: 001e3018-251d-dc72-c669-a21e303f21d7
* Content: [Microsoft 365 suite features - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-suite-features)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-suite-features.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-suite-features.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by annferre** [comment]
Hi there, 
Thank you for your comment. Office 365 Video has been removed from the Microsoft 365 Suite Features Service Description page.
Thanks again!

**Comment by annferre** [comment]
Office 365 Video has been removed from the Microsoft 365 Suite Features Service Description page.
