### ISSUE TITLE
What is required for data to be in the Government environment

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#567]
The section "#about-office-365-government-environments" says,
> Office 365 Government plans are monthly subscriptions and can be licensed to an unlimited number of users.

This appears to indicate the O365 Government environment is determined by the monthly subscription assigned to the user.
I've heard that the government environment is determined by the gcc tag applied at the tenant level. Data for shared mailboxes and other objects without a license are also stored in the gcc environment, right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3ab3187-c403-8fb1-6ee7-56818777fdad
* Version Independent ID: f6b28482-bf80-436e-cb8f-facb974c24ec
* Content: [Office 365 US Government - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government#about-office-365-government-environments)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by jonwbstr** [comment]
I'll add that there are licenses "for GCC" (GCC environment) and licenses "for Government" (Community Cloud environment)

I believe talking about "Government" includes CC, GCC, GCCHigh and DoD environments, which may not be the intent here.

**Comment by aaronlemieux** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by aaronlemieux** [comment]
Hi @jonwbstr We would like to assure you that where the article stated "Your organization's customer content..." these commitments apply to all content, including content stored in Exchange Online.

**Comment by jonwbstr** [comment]
Hi @aaronlemieux 

The title is "What is required for data to be in the Government environment" please help me understand where this article answers that question.

**Comment by jonwbstr** [comment]
My suggestion is to help this article clearly state not only how to be eligible for a gcc but must be done to have data in the gcc environment.

It would also be awesome if this article answered the question 'where is my data'

New it admin comes onboard and is asked is our data in gcc environment? How does that person answer the question?

Do they say, 'did you meet the criteria' and then ask 'do you have the right monthly plans?'

Or is there a better approach? Such as looking at a tenant tag and the provided table of services?

Pretend for a moment you have zero experience with gcc and only know what this article says. It's extremely hard with existing online documentation to convince someone their data is in the gcc environment.
