### ISSUE TITLE
Article title

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#57]
why is there [servicedesc] in the title? that does not look correct

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d985a67-ac98-de0b-cfbb-4079e6efaaa6
* Version Independent ID: 64dacd15-6118-13cc-2bc4-3a573a21fa95
* Content: [Compliance\[ServiceDesc\]](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/compliance-servicedesc)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/compliance-servicedesc.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/compliance-servicedesc.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by prabita** [comment]
@DeanGross - Thank you for your feedback, we have fixed the issue.
