### ISSUE TITLE
Ineligible Plans can still be upgraded to 5TB

### ISSUE THREAD

**Issue by glenrmag16** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#570]
Hi Team, 

I have a tenant that has an E5 trial and another one for M365 Bus Standard Trial.

It appears that I can upgrade the ODB storage of a test user with Bus Standard license (Ineligible Plan) up to 5TB. 

Is this a bug?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99ce1810-18cd-687b-0c8b-bfceb919225a
* Version Independent ID: 705cde78-7e58-c260-bde3-0b393747cdea
* Content: [OneDrive service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/onedrive-for-business-service-description)
* Content Source: [Office365-ServiceDescriptions/onedrive-for-business-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/onedrive-for-business-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by annferre** [comment]
Hi there, the product team provided the following information:
"OneDrive sites are initially provisioned with 1TB of storage. However, if you have 5 or more active licenses, and subscribe to a qualifying plan, that number can be increased to 5TB/user."
I hope this answers your question.
Thanks!

**Comment by annferre** [comment]
Hi again, I just wanted to know if the previous comment answered your question. If not I can reopen the ticket. Thanks!
