### ISSUE TITLE
Perhaps add a consideration to the EWS Application support for Push Notifications in GCCH/DOD?

### ISSUE THREAD

**Issue by drdenson** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#572]
Hi Team - as a support engineer in the GCCH/DoD space, we've seen some cases come through about EWS push notifications subscriptions that don't work when the outgoing webhook address is a nonAllowListed, 3rd party endpoint.  This scenario should work if A) the endpoint is something the customer owns (is their onPrem infra) and B) the customer has allowListed said endpoints.  But, given we DO NOT allowList 3rd party services, this scenario is a nonStarter.  As it stands, I don't see any caveats/considerations listed under "EWS Application support".  Can this be added please?  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ff8bcc8-4789-dc65-c108-ee0641c7c3b7
* Version Independent ID: 20fff9c3-700c-30f1-0714-535957ef40e9
* Content: [Exchange Online for US government environments - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/exchange-online-for-us-government-environments)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/exchange-online-for-us-government-environments.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/exchange-online-for-us-government-environments.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by aaronlemieuxatmicrosoft** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by annferre** [comment]
Apologies for the delay. The Engineering team would like config details if possible.
"_EWS does validate the client endpoint url while subscribing to push notifications but I am not aware of functionality related to allow list or non-allow list in EWS. Could you please provide configuration details to double check_."

**Comment by drdenson** [comment]
Hi Team - this is more about egress restrictions in the GCCH/DoD sovereign forests.  Unless customers submit a request per the following process, OUTBOUND connectivity from EXO over port 443 is DENIED/RESTRICTED.

Additional network security requirements for Office 365 GCC High and DoD - Microsoft 365 Enterprise | Microsoft Docs<https://docs.microsoft.com/en-us/microsoft-365/enterprise/additional-network-security-requirements-for-office-365-gcchigh-and-dod?view=o365-worldwide>

Additionally, we only allow egress to specific address spaces the customer can prove they own, so this precludes 3rd party services and broad IP ranges used by mobile devices.  Because of these restrictions, and the nature of how pushNotification subscriptions work (outbound calls to webhooks supplied by the client), this scenario is a nonstarter, by design.

Regards,
Dean

**Comment by annferre** [comment]
Hi there, I just wanted to let you know the caveat has been added to the service description page. Let me know if you need anything further. Thanks! 
<html>
<body>
<b style="box-sizing: border-box; color: rgb(0, 0, 0); font-family: &quot;Segoe UI VSS (Regular)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="box-sizing: border-box; margin: 0in 0in 0.0001pt; font-size: 11pt; font-family: Calibri, sans-serif;"> </p><p style="box-sizing: border-box; margin: 0in 0in 0.0001pt; font-size: 11pt; font-family: Calibri, sans-serif;"> </p>

Clients and mobile devices | GCC | GCC High | DoD
-- | -- | -- | --
EWS application support2 | Yes | Yes | Yes

<p style="box-sizing: border-box; margin: 0in 0in 0.0001pt; font-size: 11pt; font-family: Calibri, sans-serif;"> </p><br style="box-sizing: border-box;"><p style="box-sizing: border-box; margin: 0in 0in 0.0001pt; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; font-family: &quot;Segoe UI&quot;, sans-serif; color: rgb(23, 23, 23);"><span style="box-sizing: border-box; background-color: rgb(255, 255, 0);"> </span></span></p><p style="box-sizing: border-box; margin: 0in 0in 0.0001pt; font-size: 11pt; font-family: Calibri, sans-serif;"><sup style="box-sizing: border-box;"><span style="box-sizing: border-box; font-family: &quot;Segoe UI&quot;, sans-serif; color: rgb(23, 23, 23); background-color: rgb(255, 255, 0);">2</span></sup><span style="box-sizing: border-box; background-color: rgb(255, 255, 0);"><i style="box-sizing: border-box;"><span> </span>Only egress to specific address spaces the customer can prove they own are allowed, so this precludes 3rd party services and broad IP ranges used by mobile devices. </i></span></p></b>
</body>
</html>
