### ISSUE TITLE
need clarity on roadmap for security and compliance center

### ISSUE THREAD

**Issue by kabawan** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#575]
[Enter feedback here]

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/kabawan/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=Edit-Time-Data
href="file:///C:/Users/kabawan/AppData/Local/Temp/msohtmlclip1/01/clip_editdata.mso">

<link rel=themeData
href="file:///C:/Users/kabawan/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/kabawan/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link="#0563C1" vlink="#954F72" style='tab-interval:.5in;
word-wrap:break-word'>

<p class=MsoNormal>Hi,<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>I am seeing two conflicting statements about the roadmap for
the “Security and Compliance Center” (<a href="https://protection.office.com">https://protection.office.com</a>).<o:p></o:p></p>

<p class=MsoNormal>On the <a
href="https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center">Microsoft
docs site</a> it says <o:p></o:p></p>

<p class=MsoNormal style='text-indent:.5in'>“<span style='font-size:12.0pt;
font-family:"Segoe UI",sans-serif;color:#171717;background:#EFD9FD'>Currently,
many of the compliance features are still accessible through service-specific
management interfaces, such as the Exchange admin center (EAC). However, this
will change in the future as more service-independent compliance features are
added to the Security &amp; Compliance Center.</span>”</span> <o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>Whereas on the current <a
href="https://protection.office.com/">Security and Compliance Center</a> it
says <o:p></o:p></p>

<p class=MsoNormal style='text-indent:.5in'>“<span style='font-size:10.5pt;
font-family:"Segoe UI",sans-serif;color:#333333;background:white'>Designed with
accessibility and usability in mind, the&nbsp;</span></span><a
href="https://security.microsoft.com/?rfr=OfficeScc" target="_blank"
style='box-sizing: border-box;font-variant-ligatures: normal;font-variant-caps: normal;
orphans: 2;text-align:start;widows: 2;-webkit-text-stroke-width: 0px;
word-spacing:0px'><span style='font-size:10.5pt;font-family:"Segoe UI",sans-serif;
color:#0076B7;background:white'>Microsoft 365 security center</span></a><span
style='font-size:10.5pt;font-family:"Segoe UI",sans-serif;color:#333333;
background:white'><span style='font-variant-ligatures: normal;font-variant-caps: normal;
orphans: 2;text-align:start;widows: 2;-webkit-text-stroke-width: 0px;
text-decoration-thickness: initial;text-decoration-style: initial;text-decoration-color: initial;
float:none;word-spacing:0px'>,&nbsp;</span></span><a
href="https://compliance.microsoft.com/?rfr=OfficeScc" target="_blank"
style='box-sizing: border-box;font-variant-ligatures: normal;font-variant-caps: normal;
orphans: 2;text-align:start;widows: 2;-webkit-text-stroke-width: 0px;
word-spacing:0px'><span style='font-size:10.5pt;font-family:"Segoe UI",sans-serif;
color:#0076B7;background:white'>Microsoft 365 compliance center</span></a><span
style='font-size:10.5pt;font-family:"Segoe UI",sans-serif;color:#333333;
background:white'><span style='font-variant-ligatures: normal;font-variant-caps: normal;
orphans: 2;text-align:start;widows: 2;-webkit-text-stroke-width: 0px;
text-decoration-thickness: initial;text-decoration-style: initial;text-decoration-color: initial;
float:none;word-spacing:0px'>, and&nbsp;</span></span><a
href="https://admin.exchange.microsoft.com/" target="_blank" style='box-sizing: border-box;
font-variant-ligatures: normal;font-variant-caps: normal;orphans: 2;text-align:
start;widows: 2;-webkit-text-stroke-width: 0px;word-spacing:0px'><span
style='font-size:10.5pt;font-family:"Segoe UI",sans-serif;color:#0076B7;
background:white'>Exchange admin center</span></a><span style='font-size:10.5pt;
font-family:"Segoe UI",sans-serif;color:#333333;background:white'><span
style='font-variant-ligatures: normal;font-variant-caps: normal;orphans: 2;
text-align:start;widows: 2;-webkit-text-stroke-width: 0px;text-decoration-thickness: initial;
text-decoration-style: initial;text-decoration-color: initial;float:none;
word-spacing:0px'>&nbsp;include existing features and new, enhanced experiences
for unified security, compliance, and mail flow management across Microsoft 365
services. <span style='background:yellow;mso-highlight:yellow'>These new
centers will gradually replace the Office 365 Security &amp; Compliance Center
(protection.office.com).</span> You can turn on automatic redirection now in
the&nbsp;</span></span><a href="https://security.microsoft.com/?rfr=OfficeScc"
target="_blank" style='box-sizing: border-box;font-variant-ligatures: normal;
font-variant-caps: normal;orphans: 2;text-align:start;widows: 2;-webkit-text-stroke-width: 0px;
word-spacing:0px'><span style='font-size:10.5pt;font-family:"Segoe UI",sans-serif;
color:#0076B7;background:white'>security center</span></a><span
style='font-size:10.5pt;font-family:"Segoe UI",sans-serif;color:#333333;
background:white'><span style='font-variant-ligatures: normal;font-variant-caps: normal;
orphans: 2;text-align:start;widows: 2;-webkit-text-stroke-width: 0px;
text-decoration-thickness: initial;text-decoration-style: initial;text-decoration-color: initial;
float:none;word-spacing:0px'>&nbsp;or&nbsp;</span></span><a
href="https://compliance.microsoft.com/?rfr=OfficeScc" target="_blank"
style='box-sizing: border-box;font-variant-ligatures: normal;font-variant-caps: normal;
orphans: 2;text-align:start;widows: 2;-webkit-text-stroke-width: 0px;
word-spacing:0px'><span style='font-size:10.5pt;font-family:"Segoe UI",sans-serif;
color:#0076B7;background:white'>compliance center</span></a><span
style='font-size:10.5pt;font-family:"Segoe UI",sans-serif;color:#333333;
background:white'><span style='font-variant-ligatures: normal;font-variant-caps: normal;
orphans: 2;text-align:start;widows: 2;-webkit-text-stroke-width: 0px;
text-decoration-thickness: initial;text-decoration-style: initial;text-decoration-color: initial;
float:none;word-spacing:0px'>&nbsp;so admins in your organization are instantly
redirected from features in the Office 365 Security &amp; Compliance Center to
the corresponding feature in the new centers.</span>”</span><o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

Security and   Compliance Center (https://protection.office.com) | Microsoft Docs –   Security and Compliance Center
-- | --
  |  

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal><a name="_MailAutoSig"><span style='mso-fareast-font-family:
"Times New Roman";mso-fareast-theme-font:minor-fareast;mso-no-proof:yes'><o:p>&nbsp;</o:p></span></a></p>

<p class=MsoNormal><span style='mso-bookmark:_MailAutoSig'><span
style='mso-fareast-font-family:"Times New Roman";mso-fareast-theme-font:minor-fareast;
mso-no-proof:yes'>Thank You<o:p></o:p></span></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailAutoSig'><span
style='mso-fareast-font-family:"Times New Roman";mso-fareast-theme-font:minor-fareast;
mso-no-proof:yes'><o:p>&nbsp;</o:p></span></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailAutoSig'><b><span
style='font-size:12.0pt;mso-fareast-font-family:"Times New Roman";mso-fareast-theme-font:
minor-fareast;mso-no-proof:yes'>Kashif S Bawany<o:p></o:p></span></b></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailAutoSig'><span
style='mso-fareast-font-family:"Times New Roman";mso-fareast-theme-font:minor-fareast;
mso-no-proof:yes'>1-847-331-7890 | </span></span><a
href="mailto:kabawan@microsoft.com"><span style='mso-bookmark:_MailAutoSig'><span
style='mso-fareast-font-family:"Times New Roman";mso-fareast-theme-font:minor-fareast;
color:#0563C1;mso-no-proof:yes'>kabawan@microsoft.com</span></span><span
style='mso-bookmark:_MailAutoSig'></span></a><span style='mso-bookmark:_MailAutoSig'><span
style='mso-fareast-font-family:"Times New Roman";mso-fareast-theme-font:minor-fareast;
mso-no-proof:yes'><o:p></o:p></span></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailAutoSig'><span
style='mso-fareast-font-family:"Times New Roman";mso-fareast-theme-font:minor-fareast;
mso-no-proof:yes'><o:p>&nbsp;</o:p></span></span></p>

<p class=MsoNormal style='line-height:12.0pt;text-autospace:none'><span
style='mso-bookmark:_MailAutoSig'><span lang=EN style='mso-fareast-font-family:
"Times New Roman";mso-fareast-theme-font:minor-fareast;mso-ansi-language:EN;
mso-no-proof:yes'><![if !vml]><img border=0 width=121 height=35
src="file:///C:/Users/kabawan/AppData/Local/Temp/msohtmlclip1/01/clip_image003.jpg"
v:shapes="Picture_x0020_1"><![endif]></span></span><span style='mso-bookmark:
_MailAutoSig'><span style='mso-fareast-font-family:"Times New Roman";
mso-fareast-theme-font:minor-fareast;mso-no-proof:yes'><o:p></o:p></span></span></p>

<p class=MsoNormal style='line-height:12.0pt;text-autospace:none'><span
style='mso-bookmark:_MailAutoSig'><span lang=EN style='font-size:8.0pt;
mso-fareast-font-family:"Times New Roman";mso-fareast-theme-font:minor-fareast;
mso-ansi-language:EN;mso-no-proof:yes'>&nbsp;</span></span><span
style='mso-bookmark:_MailAutoSig'><span style='font-size:8.0pt;font-family:
"Segoe UI",sans-serif;mso-fareast-font-family:"Times New Roman";mso-fareast-theme-font:
minor-fareast;color:#595959;mso-no-proof:yes'>This communication may contain
privileged and confidential information. Use, disclosure, or retention of this
information is prohibited if you are not the intended recipient. </span></span><span
style='mso-bookmark:_MailAutoSig'><span style='mso-fareast-font-family:"Times New Roman";
mso-fareast-theme-font:minor-fareast;mso-no-proof:yes'><o:p></o:p></span></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailAutoSig'><span
style='font-size:8.0pt;font-family:"Segoe UI",sans-serif;mso-fareast-font-family:
"Times New Roman";mso-fareast-theme-font:minor-fareast;color:#595959;
mso-no-proof:yes'>If you have received this message in error please delete the
message from your system. Thank you.</span></span><span style='mso-bookmark:
_MailAutoSig'><span style='mso-fareast-font-family:"Times New Roman";
mso-fareast-theme-font:minor-fareast;mso-no-proof:yes'><o:p></o:p></span></span></p>

<span style='mso-bookmark:_MailAutoSig'></span>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

</body>

</html>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 663a603e-482b-0a4f-55a9-229ceab11bb1
* Version Independent ID: 488b1daa-b459-c56d-11eb-59242af822b0
* Content: [Security & Compliance Center - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by annferre** [comment]
HI there, the change has been implemented and verified live. Let me know if you have any questions. Thanks!
