### ISSUE TITLE
Firstline Workers - should be Frontline

### ISSUE THREAD

**Issue by cloudhal** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#576]
[Enter feedback here]

As title, F licenses are frontline and not firstline.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by annferre** [comment]
Hi there, just wanted to let you know the change has been implemented. Let me know if you have any questions. Thanks!
