### ISSUE TITLE
Add individual public folder size limit (25GB)

### ISSUE THREAD

**Issue by gabymuntean** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#577]
There is no limit specified for the single public folder in the organization, which should be up to 25GB in size, according to the migration document https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders?view=exchserver-2019#step-2-prepare-for-the-migration

"Before you begin the public folder migration, if any **single public folder in your organization is larger than 25 GB**, we recommend that you delete content from that folder to make it smaller. Or, we recommend that you divide the public folder's content into multiple, smaller public folders. Note that the 25 GB limit cited here only applies to the public folder and not to any child or sub-folders the folder in question may have. If neither option is feasible, we recommend that you do not move your public folders to Exchange Online. See Exchange Online Limits for more information. Note: If your current public folder quotas in Exchange Online are less than 25 GB, you can use the Set-OrganizationConfig cmdlet to increase them with the DefaultPublicFolderIssueWarningQuota and DefaultPublicFolderProhibitPostQuota parameters."

Thank you,
Gabriel
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by annferre** [comment]
Hi Gabriel, thank you for your comment. We have updated the page adding a note to the "public folders" section. Let me know if you have any more concerns. Thanks!
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/v-annhe/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=Preview
href="file:///C:/Users/v-annhe/AppData/Local/Temp/msohtmlclip1/01/clip_preview.wmf">

<link rel=themeData
href="file:///C:/Users/v-annhe/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/v-annhe/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in'>




Public folder mailboxes5 | 100 GB6 | 100 GB6 | 100 GB6 | 100 GB6 | 100 GB6 | 100 GB6
-- | -- | -- | -- | -- | -- | --
Group mailboxes | 50 GB | 50 GB | 50 GB | 50 GB | 50 GB | 50 GB



<p class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt;line-height:
normal'><b><span style='font-size:12.0pt;font-family:"Segoe UI",sans-serif;
mso-fareast-font-family:"Times New Roman";color:#171717'>&nbsp;Note<o:p></o:p></span></b></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto;
line-height:normal'><sup><span style='font-size:9.0pt;font-family:"Segoe UI",sans-serif;
mso-fareast-font-family:"Times New Roman";color:#171717;background:yellow;
mso-highlight:yellow'>5</span></sup><span style='font-size:12.0pt;font-family:
"Segoe UI",sans-serif;mso-fareast-font-family:"Times New Roman";color:#171717;
background:yellow;mso-highlight:yellow'>&nbsp;The default individual public
folder size limit is 2GB. You can change the size limit individually on each
folder or change the default size limit defined in the organization’s
configuration to make the change effective for all folders in the organization.
Note: Maximum recommended size of individual public folder is 25 GB. If an
individual public folder grows above 25 GB, it will have issues during&nbsp;<a
href="https://techcommunity.microsoft.com/t5/exchange-team-blog/how-exchange-online-automatically-cares-for-your-public-folder/ba-p/2050019"><b><span
style='color:blue'>auto-split process</span></b></a>.</span><span
style='font-size:12.0pt;font-family:"Segoe UI",sans-serif;mso-fareast-font-family:
"Times New Roman";color:#171717'><br style='mso-special-character:line-break'>
<![if !supportLineBreakNewLine]><br style='mso-special-character:line-break'>
<![endif]><o:p></o:p></span></p>


</body>

</html>
