### ISSUE TITLE
Update document to include F5 Security and compliance SKUs

### ISSUE THREAD

**Issue by Stuartryan74** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#578]
Can this document please be updated to reflect the F5 Security and Compliance SKUs that are available, we are evaluating whether these services would be appropriate for our colleagues and there seems to be limited information on this at present

Regards,

Stuart Ryan
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 licensing guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response. I'll post here as soon as I have an update. Thanks!

**Comment by annferre** [comment]
Hi there, I spoke with the product team and they said currently F5 offerings are available in GCC, GCC-H. They will be updating the page in the next week or so to reflect that. I'll post here as soon as the page has been updated. Thanks!

**Comment by annferre** [comment]
Hi there, there have been various substantial updates to the Microsoft 365 licensing guidance for security & compliance - Service Descriptions page. Please let me know if you have any further questions. Thanks!
