### ISSUE TITLE
Microsoft Defender for 365 licensing & compliance

### ISSUE THREAD

**Issue by adamehale** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#579]
I have a few questions about Microsoft Defender for 365.

For Microsoft Defender for Office 365 I understand that all users are covered without having to apply licenses to all users individually(SOO GLAD I FOUND THIS), however, do all policies apply to all users? The MS Docs that talk about safe links have mixed communication applying to MDO and licensed users; specifically this document(https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#microsoft-defender-for-office-365) and the 4th point down talks about licensing for specific users. I just want to ensure that all users have full protection provided by MDO even if I am not applying individual licenses to each user.

Secondly, is there a location that has it documented that all mailboxes, licensed and basic shared, require a MDO license to stay in compliance? I work for a MSP that support lawyers, and if I simply tell them they need to buy a bunch more licenses, I am goin to need written support.

Any assistance would be greatly appreciated.

Thank you.
Adam

**Comment by annferre** [comment]
Thanks for your comments. I've forwarded your query to the product team and will provide an update here as soon as I receive a response.  Thanks!

**Comment by annferre** [comment]
Hi there, an updated has been posted to the site that hopefully answers your questions: https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description#licensing-terms. Let me know if you still have questions or concerns.
