### ISSUE TITLE
Add Attack simulator

### ISSUE THREAD

**Issue by jamvandermeer** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#582]
[Enter feedback here] Can you add the license requirements for Attack Simulator. https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulator?view=o365-worldwide

Every user that is part of the simulation should be licensed and not only the person who simulates the attack.

The sort answer is that if a user is benefiting from a service, they must be licensed.  Attack simulator is a feature of E5 and P2 and a user benefits if someone is using the TI dashboard to intentionally monitor that user. So if they are running attack simulator any user included in that simulation would be benefitting from the service, and thus requires a license. 

Please check with mark.bratton@microsoft.com from Microsoft to validate this

thanks
Hans van der Meer
hansv@microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 licensing guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thanks for your comments. I've forwarded your request to the product team and will provide an update here as soon as I receive a response. Thanks!

**Comment by annferre** [comment]
Hi Hans, I just wanted to let you know the product team is in the process of confirming the  inclusion of licensing for this solution.  I'll keep you posted with updates.

**Comment by annferre** [comment]
Hi there, I just wanted to let you know the edits have been completed and are live: 
<img width="475" alt="image" src="https://user-images.githubusercontent.com/86699727/146420692-0b3b9be7-a7a4-4002-86a4-07128213fae9.png">
Let me know if you have further questions.
Thank you again for your comment.
