### ISSUE TITLE
Gcc high changes

### ISSUE THREAD

**Issue by leefai** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#583]
[Hi, is this information up to date? Private channels in GCC high are showing as rolling out since June on public roadmap https://www.microsoft.com/en-gb/microsoft-365/roadmap?filters=&searchterms=67199  and  Live Events rolling out July https://www.microsoft.com/en-gb/microsoft-365/roadmap?filters=&searchterms=82954  but the tables indicate "NO" for these features?]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9035b5a9-1f84-54be-89ae-c3a0e53891f8
* Version Independent ID: cff57f08-ca51-2266-6189-1ce8181b942e
* Content: [Microsoft Teams service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/teams-service-description)
* Content Source: [Office365-ServiceDescriptions/teams-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/teams-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your feedback. We are currently working on updating the pages, and we will get back to you as soon as this is completed. Thanks again!

**Comment by annferre** [comment]
Hi there, I just wanted to let you know the features have been updated for the Microsoft Teams service description page. Let me know if you have any questions. Thanks!
