### ISSUE TITLE
Missing capacity information

### ISSUE THREAD

**Issue by drf-uwa** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#585]
https://docs.microsoft.com/en-us/onedrive/set-default-storage-space states "For info about the storage available for your Microsoft 365 subscription, see the OneDrive service description." and links to this page, however this page does not outline the available storage for each offering or clearly link to information on this topic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99ce1810-18cd-687b-0c8b-bfceb919225a
* Version Independent ID: 705cde78-7e58-c260-bde3-0b393747cdea
* Content: [OneDrive service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/onedrive-for-business-service-description)
* Content Source: [Office365-ServiceDescriptions/onedrive-for-business-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/onedrive-for-business-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for your comment. I couldn't find the sentence you were referring to so in checking, the intro. sentence now reads: "For most subscription plans, the default storage space for each user's OneDrive is 1 TB. Depending on your plan and the number of licensed users, you can increase this storage up to 5 TB. For info, see the OneDrive service description."
I'll talk to the product team regarding updating the OneDrive service description page, and post the response here. Thanks!

**Comment by annferre** [comment]
Hi there, we added in the "Learn more" of the OneDrive service description page the below.
Let me know if you still have questions. Thanks again for your comment.

For most subscription plans, the default storage space for each user's OneDrive is 1 TB. Depending on your plan and the number of licensed users, you can increase this storage up to 5 TB. For info, see the Core features in Compare OneDrive cloud storage pricing and plans.
