### ISSUE TITLE
Mile IQ no longer part of M365

### ISSUE THREAD

**Issue by nCharritton** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#588]
[Enter feedback here]
The service description doc should no longer include MileIQ

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1bface7-95b2-72b8-43b7-d3bd43b27d0c
* Version Independent ID: ac6756e4-bf78-278c-f8a1-89c182bf545d
* Content: [Licensing Microsoft 365 for small and medium-sized businesses - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/licensing-microsoft-365-in-smb#feedback)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/licensing-microsoft-365-in-smb.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/licensing-microsoft-365-in-smb.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thanks for your comments. I've forwarded your request to the product team and will provide an update here as soon as I receive a response. Thanks!

**Comment by annferre** [comment]
Hi there, thank you again for your comments. Reference to Mile IQ has been removed from the service description page. Thanks again!
