### ISSUE TITLE
Add-ins *are* enabled in Word Online (right?)

### ISSUE THREAD

**Issue by stravajiaxen** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#589]
According to a comment from a [2016 thread](https://answers.microsoft.com/en-us/msoffice/forum/all/add-in-for-word-online/90bf1068-a65c-4551-b0bf-f5add9601eb5) linking [this document](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-online-service-description/word-online?redirectedfrom=MSDN), it is in fact possible to use Add-Ins on Word Online, yet the documentation says otherwise. 

Either the document should be updated to say that add-ins _are_ enabled for word online (most likely resolution of the issue) or the thread should be edited to override the Melinda Ma's statement that add-ins are enabled (surprising resolution of the issue).

I'm interested in the proper answer to this question -- Can add-ins be used in Word Online? -- as my organization is interested in developing add-ins and whether they're available in Word Online as well as on desktop is important.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03c6bd97-32d7-11be-e5ff-52b37aaa638c
* Version Independent ID: 8c688d43-0be9-7e68-4d08-cbb8fa5fba11
* Content: [Word for the web - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-online-service-description/word-online?redirectedfrom=MSDN)
* Content Source: [Office365-ServiceDescriptions/office-online-service-description/word-online.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-online-service-description/word-online.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thanks for your comments. I've forwarded your request to the product team and will provide an update here as soon as I receive a response. Thanks!

**Comment by annferre** [comment]
Hi there, apologies for the delay, but the team just got back to me and confirmed add-ins are enabled for word web. We will be updating the documentation, and I will let you know when the update goes live. Thanks again for your comment.

**Comment by annferre** [comment]
Hi again, we removed reference to add-ins not being available and the page is now live. 
![image](https://user-images.githubusercontent.com/86699727/140841422-3af704fe-2095-4633-a1c0-8e6d999bc083.png)
Let me know if you have any further question or concerns. Again, thank you for your comment.

**Comment by annferre** [comment]
Hi there, I just wanted to say thank you for your comment. The sentence referring to add-ins not being available was removed from the Office add ins section. Let me know if you have any further questions.
**Office add-ins**
You can get an add-in for Word from the Office Store. Learn how to get an add-in for Word.
