### ISSUE TITLE
"電源の BI" needs to be replaced with "Power BI"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#59]
https://docs.microsoft.com/ja-jp/office365/servicedescriptions/sharepoint-online-service-description/insights

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc178d3c-62fb-211f-aecc-c46f20b0b85c
* Version Independent ID: 01772c38-f6dd-33e2-a43a-51c947b2bcc8
* Content: [Insights](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/insights)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/insights.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/insights.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by MollyMalone** [comment]
@hyoshioka0128 Thank you for reporting this issue. However we will not fix the over-translation of Power BI at this time. It is a known issue that some of our Product names (including Power BI) are being unnecessarily translated by the machine translation tool. We are investigating a tool solution to fix these issues. At this time we can not fix each issue individually.
