### ISSUE TITLE
correct domain limition

### ISSUE THREAD

**Issue by MoahmedGebril** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#590]
the number of Domain listed in the limitation do not match the update from azure limitation.
![image](https://user-images.githubusercontent.com/89928398/131699480-0ff6dc96-bb76-43b9-a49f-20a68f9c6a09.png)
 900 Domain limit is the current in the documentation.
Azure service limits and restriction increased the number of domains, which can be added to 5000 managed domains or 2500 federated domain.
https://docs.microsoft.com/en-us/azure/active-directory/enterprise-users/directory-service-limits-restrictions
![image](https://user-images.githubusercontent.com/89928398/131699548-cc1ec6af-e8fb-4b22-8124-e47c336eed81.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc9a7e3b-5816-e4f0-f4bc-bc9384b4732d
* Version Independent ID: 1cea0199-f381-9f3e-b2b4-387785a78aca
* Content: [Domains - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/domains)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/domains.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/domains.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thanks for your comments. I've forwarded your request to the product team and will provide an update here as soon as I receive a response. Thanks!

**Comment by annferre** [comment]
Hi there, I just wanted to let you know I'm still working on getting an answer. I did find out that the 900 domains is correct, but there are specific designated tenants that have the ability to add up to 5000. But, we are trying to determine the two different limits -- Azure has one domains limit and M365 service has another. I'll get back to your as soon as I have more information. Thanks!

**Comment by annferre** [comment]
Hi there, we have an engineering RFC ticket request for confirmation regarding the limit. I'll get back to you as soon as I have something. Thanks for your comment.

**Comment by annferre** [comment]
Hi there, I just wanted to let you know we clarified the text for better understanding: "Accepted domain limit - You can add up to 900 accepted domains per tenant. Subdomains can be included in this 900-limit, or if necessary, as part of a catch-all option, match subdomains. For more information, see Manage Accepted Domains in EOP." Let me know if you still have questions. Thanks!
