### ISSUE TITLE
Microsoft 365 Business Premium inclusive of Online Archiving

### ISSUE THREAD

**Issue by directorcia** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#591]
According to - 

Microsoft 365 Business Premium Service description - https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description

3 Microsoft 365 Business Premium includes Exchange Online Archiving subscription.

but this article says:

Cloud-based archive and in-place hold as an add-on for the following plans1,2,3:
Exchange Online Plan 1
Exchange Online Kiosk
Microsoft 365 Business Basic
Microsoft 365 Business Standard
Microsoft 365 Business Premium   <<<<<<<<<<
Office 365 E1
Office 365 A1
Office 365 G1
Office 365 F3
Microsoft 365 F3

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c55dc71-81ed-864b-ac3f-63ce84688070
* Version Independent ID: 578c9a02-045e-4bf9-6384-d70560c332f0
* Content: [Exchange Online Archiving service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description)
* Content Source: [Office365-ServiceDescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thanks for your comments. I've forwarded your request to the product team and will provide an update here as soon as I receive a response. Thanks!

**Comment by annferre** [comment]
Hi there, I just want to let you know I did receive a response from the product team. They state that Exchange Online Archiving page is accurate. BP includes Exchange Plan 1 and Exchange Online Archiving is only included in Exchange Plan 2 (E3/E5). I will be requesting an update to the MS Business Premium page, and will let you know when it is updated. Thanks!

**Comment by directorcia** [comment]
@annferre I have spoken with Neha Bhaskar (Microsoft 365 SMB Product Marketing, Microsoft) nehabha@microsoft.com who has confirmed that EXO archiving IS included in M365 BP and would like to join the conversation with the Team that provided you with that answer.

**Comment by annferre** [comment]
I reached out to the commercial licensing team and confirmed the original text in the service description page was correct, and M365 business premium does have EXO Archiving included. I think the confusion on the product team's part was because it was listed as an add-on which it is but it is included. I will be correcting both pages EXO Archiving and the M365 Biz Premium page. I'll let you know when these are done.

**Comment by annferre** [comment]
Hi there, I just wanted to let you know the corrections have been posted and confirmed live. Thank you for posting this. Let me know if you have further questions. Thanks!
