### ISSUE TITLE
Invalid quota limit for A3 mailboxes?

### ISSUE THREAD

**Issue by Feandil** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#593]
The `Mailbox storage limits` for `Office 365 A3` in `Office 365 Education - Service Descriptions` (`100 GB`) diverges from what is described in https://www.microsoft.com/en-us/microsoft-365/academic/compare-office-365-education-plans?activetab=tab:primaryr2, which only mentions `Get email with 100 GB mailbox` for `Office 365 A5`, not for `Office 365 A3`.

(No idea who is correct between the two)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 482f1200-178f-088c-f189-ac129614cdb0
* Version Independent ID: 94ff27f4-966c-f271-1822-515c4e56a1bb
* Content: [Office 365 Education - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-education)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-education.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-education.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your comment. I have reached out to the product team and will follow up with an update. Thanks again!

**Comment by annferre** [comment]
Hi there, the product team responded and stated A3 mailbox quota is 100 GB because A3 comes with Exchange Plan 2. Let me know if you have any further questions. Thanks!

**Comment by Feandil** [comment]
Thanks! So this is a bit Off topic for this repository, but who should be contacted to fix https://www.microsoft.com/en-us/microsoft-365/academic/compare-office-365-education-plans?activetab=tab:primaryr2 then? 100 GB only appears for A5 there
