### ISSUE TITLE
Possible contradiction regarding Exchange Online Archiving

### ISSUE THREAD

**Issue by mbender-ith** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#595]
While https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description claims
_Microsoft 365 Business Premium includes Exchange Online Archiving subscription._
the page https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description says
_Cloud-based archive and in-place hold as an add-on for the following plans [...] Microsoft 365 Business Premium_

Please clarify, ideally on both pages, whether Exchange Online Archiving (or which parts of it) are already included in Microsoft 365 Business Premium.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94c91b3d-d9b1-9056-ae3e-51a255ed88ec
* Version Independent ID: b60613bc-f7b3-d1c7-4d8e-924c0f87912f
* Content: [Microsoft 365 Business Premium service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your comment and question. I have forwarded your question to the product team. I will update this thread as soon as I receive feedback. Thanks again!

**Comment by annferre** [comment]
Thanks again for your comment. I reached out to the product team and they said the statement is correct: Cloud-based archive and in-place hold as an add-on for the following plans1,2,3:
Microsoft 365 Business Basic
Microsoft 365 Business Standard
Microsoft 365 Business Premium <<<<<<<<<<
They will be requesting an update to the Microsoft business premium service description page. 
I will let you know when this is finalized.
Thanks!

**Comment by AaronDinnage** [comment]
@mbender-ith has rightly pointed out that the service description is confusing.
However, the Microsoft internal Offer Management Tool shows that Exchange Online Archiving **is** included in Microsoft 365 Business Premium. Can you clarify the change you are looking to make @annferre ?

**Comment by annferre** [comment]
Thanks for the note. I forwarded the information to the Exchange Online Archiving team. Thanks again!

**Comment by annferre** [comment]
Hi there, thank you again for your comment. We have addressed your concern regarding Exchange Online Archiving. For 
https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description: this has been updated to reflect Exchange Online Archiving is not included, but is available as an add-on. 
For: https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description -- this is correct. Let me know if you still have questions. Thanks!

**Comment by mbender-ith** [comment]
Frankly speaking, the changes made to https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description confuse me even more.

- On the one hand, there is the table on top wich denotes for Microsoft 365 Business Premium "Long-term archiving of Exchange Online-based mailboxes"  = YES, referring to footnote 3
- Footnote 3 reads "_Microsoft 365 Business Premium includes Exchange Plan 1 and Exchange Online Archiving is only included in Exchange Plan 2 (E3/E5). Cloud-based archive and in-place hold can be purchased as an add-on_" 

To me, this seems like a contradiction: Either it is included in M365 Business Premium (where the footnote clearly states "no"), or the table should also read "no". 

The only possible answer which I could imagine (but again, this is only speculating and would not render the current statements on that page any better) is that

- "Long Term Archiving" is only a **subset** of "Exchange Online Archiving", and while "Long Term Archiving" **is** part of Microsoft 365 Business Premium, the full "Exchange Online Archiving" is not (and must be bought separately as an add-on)

@AaronDinnage Do you have any sources or arguments for further clarification?
-

**Comment by AaronDinnage** [comment]
I agree.

I believe there is some confusion over what is and is not included. I’ve sent some further information to the team that refers to internal Microsoft resources which I can’t discuss here, but I hope that will be sufficient to resolve this. If not, I believe I have a few other ways to demonstrate that Exchange Online Archiving _is_ included in Microsoft 365 Business Premium, but they will take some effort, so we’ll see what the team say first.

Cheers,
- Aaron.

**Comment by mbender-ith** [comment]
Thanks for following up.

Frankly speaking, I am a bit puzzled why M365 Business Premium is still contained in the list entitled  "_cloud-based archive and in-place hold **as an add-on for the following plans**_"

The only possible answer I can think of is "M365 Business Premium does include Exchange Online Archiving, but it does not include In-Place hold". 

Can you confirm this is the correct interpretation?

CC @AaronDinnage
