### ISSUE TITLE
China Office 365 Video has been retired, please update the documentation

### ISSUE THREAD

**Issue by leapyear1969** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#596]
China Office 365 Video has been retired, please update below documentation.

[China Office 365 service description](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-operated-by-21vianet?redirectedfrom=MSDN#platform-features)
<html>
<body>

Office 365 Video | No | No | No | Yes | Yes | Yes2
-- | -- | -- | -- | -- | -- | --

</body>
</html>

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84a9aadf-5458-1bc2-bbbe-b44794ad18c7
* Version Independent ID: 69a00a16-8f2e-9618-18b5-079c43fd3919
* Content: [Office 365 operated by 21Vianet - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-operated-by-21vianet?redirectedfrom=MSDN#office-365-application-features)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-operated-by-21vianet.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-operated-by-21vianet.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your comment. I have forwarded your request to the product team. Thanks again!

**Comment by annferre** [comment]
Hi there, I just wanted to let you know the page has been updated to reflect that the service has been retired. Let me know if you have any further questions. Thanks again for your comment.
