### ISSUE TITLE
Add licensing guidance to service description

### ISSUE THREAD

**Issue by ggarruba** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#598]
[Enter feedback here]
Per attached email with Ryan Baker from business planning, we need to add the following text to the licensing section of this document. 

For Microsoft Defender for Office 365 Plan 1 tenants, licenses must be acquired for users or mailboxes falling under one or more of the following scenarios:
•	Any user that accesses a mailbox that benefits from Defender for Office 365 protections.
•	Shared mailboxes that benefit from Defender for Office 365 protections.  
•	If Safe Attachments protection for SharePoint, OneDrive for Business, or Teams is turned on, all users that access SharePoint, OneDrive for Business, or Teams.
•	Any user that uses Microsoft 365 Apps or Teams when Safe Links protections are enabled.
For Microsoft Defender for Office 365 Plan 2 tenants, licenses must be acquired for users or mailboxes falling under one or more of the following scenarios:
•	All Exchange Online users on the tenant. This is because Plan 2 features and capabilities protect all users in the tenant.
•	All shared mailboxes on the tenant.
•	If Safe Attachments protection for SharePoint, OneDrive for Business, or Teams is turned on, all users that access SharePoint, OneDrive for Business, or Teams.
•	Any user that uses Microsoft 365 Apps or Teams when Safe Links protections are enabled.
 
Note that Office 365 E5, Microsoft 365 E5 Security, and Microsoft 365 E5 include Microsoft Defender for Office P2 licenses, and Microsoft 365 Business Premium includes Microsoft Defender for Office 365 P1 licenses. 
[MDO Licensing.pdf](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions/files/7219187/MDO.Licensing.pdf)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 502796e9-ca73-7123-7719-c7b5b1042b7b
* Version Independent ID: 2929af88-6d56-4de3-2b4e-4e1d0e4d97ef
* Content: [Microsoft Defender for Office 365 service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description)
* Content Source: [Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi Giulian, I received your request and forwarded it to the PubOps team. Thanks!

**Comment by annferre** [comment]
Closing since updates have posted and are live. Thanks again for your comment!
