### ISSUE TITLE
Non-GCC tenant C CANNOT share with GCC High tenant A or B.

### ISSUE THREAD

**Issue by eschrader** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#6]
I noticed when I try to share a Non-GCC or GCC site with anyone in the GCC High using B2B sharing invites, I get an error saying its blocked. I cannot share with anyone @ .mil domains.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c907526-4061-94b4-f2fd-d6fca90344bb
* Version Independent ID: 82e89c18-8d6e-bbb1-f6d0-6ec091d1556e
* Content: [GCC High and DoD](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by TP73** [comment]
Where can I find documentation regarding GCC high? If one need to build VMs in azure GCC high what is the process?

**Comment by eschrader** [comment]
> Where can I find documentation regarding GCC high? If one need to build VMs in azure GCC high what is the process?

https://azuregov.microsoft.com/general

**Comment by darrenlarkins** [comment]
Did you ever resolve this?

**Comment by TP73** [comment]
Nope..

**Comment by prabita** [comment]
@eschrader Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response

**Comment by dmcwee** [comment]
B2B is not available in the GCCH environment (refer to the link below and in particular the Variations section)
https://docs.microsoft.com/en-us/azure/azure-government/documentation-government-services-securityandidentity#azure-active-directory

**Comment by SharS** [comment]
See updated article.
