### ISSUE TITLE
No discussion of missing features

### ISSUE THREAD

**Issue by WillMartin58** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#60]
My customer is a government customer and wants to use Forms for external surveys.  However, external sharing of Forms is disabled in the GCC tenant, and they have no information saying it will be enabled.  The above table shows Forms as deployed, which it is, but only for internal access.  The table needs to include information about what features are and aren't available to be of any use to my customer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e69c139-60fc-5e97-168a-12d7bf1fbd38
* Version Independent ID: bd4edf0e-4a2f-2bf7-92e6-c7e840584977
* Content: [Office 365 US Government](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md)
* Service: **o365-administration**
* GitHub Login: @danarl
* Microsoft Alias: **danarl**

**Comment by zachsaltzman** [comment]
https://support.office.com/en-us/article/Microsoft-Forms-features-for-U-S-Government-Community-Cloud-GCC-and-GCC-High-environments-5cbd407a-eef7-431e-8e3a-eb666eab4b4c

**Comment by BennietheJets** [comment]
Is there a page like this for each application? This is a useful list.

**Comment by SharS** [comment]
@WillMartin58 Thanks for your feedback. I've contacted the product team to see if we can add the requested information to the service description.

**Comment by SharS** [comment]
Response from the product team: The Office 365 US Government Service Description was built to mirror the Office 365 Platform Service Description, and it gives details about what is included within the purchase of G1, G3, G4, and F1 offerings, similar to the Office 365 Enterprise Service Description. This page is NOT intended to be a detailed list of the feature/functionality of every application/service that’s listed, as they have their own service descriptions. The Forms team has chosen a different location to make updates to their service documentation here: https://support.office.com/en-us/forms, and https://support.office.com/en-us/article/Microsoft-Forms-features-for-U-S-Government-Community-Cloud-GCC-and-GCC-High-environments-5cbd407a-eef7-431e-8e3a-eb666eab4b4c
