### ISSUE TITLE
Deployment pipeline are availabe under PBI PRem per user according FAQ.

### ISSUE THREAD

**Issue by ed7257** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#605]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86000cdb-49e5-93db-f466-19b6befdd78e
* Version Independent ID: b5524949-3534-8d95-8cde-a13518b4c51e
* Content: [Power BI service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/power-bi-service-description)
* Content Source: [Office365-ServiceDescriptions/power-bi-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/power-bi-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, I just wanted to let you know that the page has been updated to reflect the below change. Let me know if you have any further questions. Thanks again for your comment.
<html>
<body>


Feature | Power BI Pro | Power BI Premium per user | Power BI Premium per capacity
-- | -- | -- | --
Deployment pipelines for application lifecycle management | No | Yes | Yes
Multi-geo deployment management | No | No | Yes

<p style="box-sizing: border-box; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin: 0in 0in 0.0001pt; font-size: 11pt; font-family: Calibri, sans-serif;"> </p><br class="Apple-interchange-newline">
</body>
</html>
