### ISSUE TITLE
Apps, Bots, & Connectors Updated Needed

### ISSUE THREAD

**Issue by AndrewKlutz** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#607]
We need that following update made on the Apps, Bots, & Connectors line: remove the 1 on the GCC Colum, it should now just be "YES".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9035b5a9-1f84-54be-89ae-c3a0e53891f8
* Version Independent ID: cff57f08-ca51-2266-6189-1ce8181b942e
* Content: [Microsoft Teams service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/teams-service-description?form=MY01SV&OCID=MY01SV)
* Content Source: [Office365-ServiceDescriptions/teams-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/teams-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, I just wanted to let you know the page has been updated to reflect the below. Let me know if you have any further questions. Thanks again for your comment.
<html>
<body>
<b style="box-sizing: border-box; color: rgb(0, 0, 0); font-family: &quot;Segoe UI VSS (Regular)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="box-sizing: border-box; margin-right: 0in; margin-left: 0in; font-size: 11pt; font-family: Calibri, sans-serif; background: white;"><span style="box-sizing: border-box; font-size: 12pt; font-family: &quot;Segoe UI&quot;, sans-serif; color: rgb(23, 23, 23);">After:</span></p>

FEATURE AVAILABILITY
--
Feature | Small business | Enterprise plans | GCC | GCC - High | DOD | Education
Apps, Bots, & Connectors | Yes | Yes | Yes | Yes1 | Yes1 | Yes

<p style="box-sizing: border-box; margin: 0in 0in 0.0001pt; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box;"> </span></p></b><br class="Apple-interchange-newline">
</body>
</html>
