### ISSUE TITLE
DLP Licensing documentation inconsistency

### ISSUE THREAD

**Issue by rtrigueiro** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#608]
Microsoft 365 Business Premium includes DLP for files and emails, however there's some inconsistency accross the different Microsoft sources for this.

1. In the Microsoft 365 guidance for security & compliance (https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#data-loss-prevention-for-exchange-online-sharepoint-online-and-onedrive-for-business):
![image](https://user-images.githubusercontent.com/36214010/138345605-720c8cea-cf12-4a51-b794-bf9878b2ff6a.png)

It is clear that Microsoft 365 Business Premium is a licensing option for DLP for Files and Emails

2. In Security & Compliance Center Service Descriptions (https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center):
![image](https://user-images.githubusercontent.com/36214010/138345772-7770adb7-b75e-42a0-a1f9-46a866f0dcdf.png)

We also see Microsoft 365 Business Premium is "Yes", however we can see Microsoft 365 Business Standard with "Yes" which seems to be an error. as we can also confirm from the next reference.

3. The Microsoft 365 Business Premium service description (https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description):
![image](https://user-images.githubusercontent.com/36214010/138346006-f001bea7-cf29-4888-acba-c13b50de81f7.png)

It seems to confirm Business Premium is licenses DLP and Business Standard No. This is also confirmed in the next reference.

4. The Licensing Microsoft 365 for small and medium-sized businesses (https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/licensing-microsoft-365-in-smb):
![image](https://user-images.githubusercontent.com/36214010/138346206-c47d7722-1515-43e7-ad71-41f87adcc502.png)

However the Microsoft 365 compliance licensing comparison PDF (https://docs.microsoft.com/en-us/office365/servicedescriptions/downloads/microsoft-365-compliance-licensing-comparison.pdf) and Excel (https://docs.microsoft.com/en-us/office365/servicedescriptions/downloads/microsoft-365-compliance-licensing-comparison.xlsx) show that for Microsoft 365 Business Premium is not licensing DLP for files and emails:

Is it possible to confirm and update all the references to the correct licensing capabilities, which seems to be:
- Microsoft 365 Business Premium supports DLP for Emails and Files
- Microsoft 365 Business Standard dont.

I've also submitted a similar clarification request on January for DLP under Microsoft 365 Business Premium: https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions/issues/485

**Comment by annferre** [comment]
Hi again, the below change is live. Regarding the pdf and excel pages, those are no longer valid, and the links to those have been removed. Let me know if you have any further questions. Thanks again for your comment! 
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/v-annhe/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/v-annhe/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Feature | Microsoft 365 Business Basic | Microsoft 365 Business Standard | Microsoft 365 Business Premium
-- | -- | -- | --
Data loss prevention for Exchange   Online, SharePoint Online, and OneDrive for Business7,9 | No | No | Yes



</body>

</html>
