### ISSUE TITLE
Storage limit clarity for OneDrive

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#609]
Hi!

This page states the following:

_For most subscription plans, the default storage space for each user's OneDrive is 1 TB. Depending on your plan and the number of licensed users, you can increase this storage up to 5 TB._

but it also includes a link to a pdf document _For information on OneDrive storage per user, check OneDrive in the Modern Work Plan Comparison. https://go.microsoft.com/fwlink/?linkid=2139145_ and this document states that "OneDrive personal storage Unlimited 3 - 3 Microsoft will provide an initial 5 TB of OneDrive storage per user. Customers who want additional OneDrive storage can request it as needed by contacting Microsoft support. Subscriptions for fewer than five users receive 1 TB OneDrive storage per user"

So which one is correct? 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99ce1810-18cd-687b-0c8b-bfceb919225a
* Version Independent ID: 705cde78-7e58-c260-bde3-0b393747cdea
* Content: [OneDrive service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/onedrive-for-business-service-description)
* Content Source: [Office365-ServiceDescriptions/onedrive-for-business-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/onedrive-for-business-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, I just wanted to let you know the following change is being made to the Modern Work Plan Comparison Sheet: "Microsoft will provide an initial up to 5 TB of initial OneDrive storage per user based on the default quota for the tenant. Customers who want additional OneDrive storage can request it as needed by contacting Microsoft support. Subscriptions for fewer than five users received 1 TB of OneDrive storage that cannot be expanded." I'll let you know as soon as the change is live. Thanks!

**Comment by Larryngolog** [comment]
Thank you, this is great.

**Comment by annferre** [comment]
Hi there, I just wanted to let you know the change below to the Modern Work Plan Comparison sheet has been completed 
 and is live. Thanks again for your comment.
3 Microsoft will provide up to 5 TB of initial OneDrive storage per user based on the default quota for the tenant. Additional storage can be requested by contacting Microsoft support. Subscriptions for fewer than five users received 1 TB of OneDrive storage that cannot be expanded.
