### ISSUE TITLE
The Preservation Hold library link goes to the wrong content

### ISSUE THREAD

**Issue by MatthewMcD** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#61]
The link in the body of the Preservation Hold item goes to old eDiscovery Content and not to newer info on Retention Policies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b9b38cf-edb6-3240-cd8b-b97f03062611
* Version Independent ID: e39e9ad2-507e-c3f2-3024-cb10f586ad2d
* Content: [Content](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/content)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/content.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/content.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by SKjerland** [comment]
@MatthewMcD - We tested the link and it goes to the correct article on retention policies. If you're saying the article it links to needs to be updated, please log an issue on that article, not this one. Thank you!
