### ISSUE TITLE
Update with "recommended" number of communities you can be a member of

### ISSUE THREAD

**Issue by ichesa** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#610]
Hello,

I've been experiencing issues with the Yammer website not working (showing an error to retry loading the page) and, after reviewing this with support, we identified it was caused to my user being the owner of a lot of Yammer communities (around 3000).

After some communications with the Yammer engineering team, they stated that once the user goes past ~800 Yammer communities they will begin to experience considerable performance issues, and this may be the reason why I was experiencing issues with this user.

Effectively, after reducing the amount of communities to less than those 800, the Yammer website started to work again.

It would be great if some recommendation about this could be added to the documentation in order to avoid this kind of problem, or at least, to identify better this kind of issue because, I was able to prove that although it might technically be possible for a user to be a member of 7,000 Yammer communities (at least I try with 3000), this may lead to issues.

Regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b575e2e-b40c-51fc-1c48-1743d5a543c3
* Version Independent ID: 9d90111b-126b-bfcc-69ea-c97b9981ac87
* Content: [Limits in Yammer - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/yammer-service-description/yammer-limits#yammer-community-limits)
* Content Source: [Office365-ServiceDescriptions/yammer-service-description/yammer-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/yammer-service-description/yammer-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, I just wanted to let you know we have added the below note to the Limits in Yammer page. I hope this is acceptable. Thanks again for your comment. Cheers!
<img width="469" alt="image" src="https://user-images.githubusercontent.com/86699727/155762158-02c0e68c-1d1d-437b-9f38-b89378d1f400.png">
