### ISSUE TITLE
Please update Domain limit

### ISSUE THREAD

**Issue by tarekd** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#611]
[Enter feedback here]

Hi folks, Exchange Online updated their domain limit to 5,000, but customers still find this article and they think EOP has a different limit of 900 domains. Can you please update this limit after checking with engineering?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5013ccda-a0c6-ce6c-73e7-c78187008f55
* Version Independent ID: a2233d27-d1b1-23af-776b-b860eb1f79b6
* Content: [Exchange Online Protection limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-protection-service-description/exchange-online-protection-limits?source=docs)
* Content Source: [Office365-ServiceDescriptions/exchange-online-protection-service-description/exchange-online-protection-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-protection-service-description/exchange-online-protection-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, I just wanted to let you know an RFC was created for this and we are waiting for a response from Engineering. Thanks again for your comment.

**Comment by annferre** [comment]
<html>
<body>
<b style="box-sizing: border-box; color: rgb(0, 0, 0); font-family: &quot;Segoe UI VSS (Regular)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div style="box-sizing: border-box; margin: 0px 0in; font-size: 11pt; font-family: Calibri, sans-serif;"><p style="box-sizing: border-box; margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif;">The online service description has been updated to the below. Let me know if you have further questions or concerns. Thanks again for your comment.</p><p style="box-sizing: border-box; margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif;"><a href="https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fdocs.microsoft.com%2fen-us%2foffice365%2fservicedescriptions%2foffice-applications-service-description%2foffice-applications-service-description?redirectedfrom%3DMSDN&amp;data=04%7c01%7cv-annhem%40microsoft.com%7c1c0705f07ae84821b71708d9d6c638e8%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637776969138040594%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000&amp;sdata=lRoMHyPITGhpbReobdyP82Z8M5uMLsnczQeC1XP3imQ%3D&amp;reserved=0" style="box-sizing: border-box; color: var(--communication-foreground,rgba(0, 90, 158, 1)); text-decoration: underline; cursor: pointer;">Office applications service description - Service Descriptions | Microsoft Docs</a></p><p style="box-sizing: border-box; margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif;"> </p><div style="box-sizing: border-box; margin: 0px 0in; font-size: 11pt; font-family: Calibri, sans-serif;"><div style="box-sizing: border-box; margin: 0px 0in;"><p style="box-sizing: border-box; margin: 0in;"> </p>

Enterprise value | Office Professional Plus 2013 | Office Professional Plus 2016 | Office Professional Plus 2019 | Microsoft 365 Apps for enterprise | Microsoft 365 Apps for business | Microsoft 365 Business Basic | Microsoft 365 Business Standard | Microsoft 365 Business Premium | Office 365 E1 | Office 365 E3 | Office 365 E5 | Office 365 F3
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Group Policy support | Yes | Yes | Yes | Yes | Yes<sup>15</sup> | No | Yes<sup>15</sup> | Yes<sup>15</sup> | No | Yes | Yes | No

<p style="box-sizing: border-box; margin: 0in;"> </p><br style="box-sizing: border-box;"></div></div></b><br class="Apple-interchange-newline">
</body>
</html>

**Comment by annferre** [comment]
Hi Tarek, I'm closing the ticket based on our conversation, but I did want you to know the document was updated with the following note: 
![image](https://user-images.githubusercontent.com/86699727/154571988-49890b12-fcc4-4163-9576-c398d662186f.png)
