### ISSUE TITLE
Why does it say Universal Print Integration for Business Edition is not supported

### ISSUE THREAD

**Issue by johnkellyjr** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#612]
In your documentation here:

https://docs.microsoft.com/en-us/office365/servicedescriptions/windows-365-service-description/windows-365-service-description

Business Edition and Enterprise Edition features are compared.

Universal Print (UP) Integration says "No" for Business Plan and "Yes" for Enterprise Plan.

Yet, I am using a Business trial edition of Windows 365 and have set up a UP printer and used it. What does it therefore mean for UP Integration on Enterprise plan?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee88ad0f-5e92-9220-b187-885c8fa8d856
* Version Independent ID: 2bd2e669-a38d-714d-ca73-581714310ca0
* Content: [Windows 365 service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/windows-365-service-description/windows-365-service-description)
* Content Source: [Office365-ServiceDescriptions/windows-365-service-description/windows-365-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/windows-365-service-description/windows-365-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, I just wanted to let you know Universal Print support to Business will be reviewed by SME's and PMM's. I'll keep you posted as I get an update on this. Thanks again for your comment.

**Comment by annferre** [comment]
Hi there, I just wanted to let you know Universal Print is supported for Business Premium. We'll be updating the documentation accordinly. I'll let you know when that is complete. Thanks!

**Comment by johnkellyjr** [comment]
Thank you very much. I'll pass on this info to the IHV I work for.

**Comment by annferre** [comment]
Hi there, the below changes have been made to the Windows 365 page. Please reopen the ticket if you have anything further. Thanks again for your comment.!
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/v-annhe/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/v-annhe/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/v-annhe/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>


<p class=MsoNormal><span style='font-family:"Segoe UI Light",sans-serif'>Change
#1:<o:p></o:p></span></p>



Feature | Business Plan | Enterprise Plan
-- | -- | --
Universal Print (UP) Integration | Yes1 | Yes2



<p class=MsoNormal style='background:white'><sup><span style='font-size:10.5pt;
font-family:"Segoe UI",sans-serif;color:#24292F'>1</span></sup><span
style='font-size:10.5pt;font-family:"Segoe UI",sans-serif;color:#24292F'>&nbsp;</span><span
style='font-size:12.0pt;color:black'>Universal Print is part of M365 Business
Premium.</span><span style='font-size:10.5pt;font-family:"Segoe UI",sans-serif;
color:black'><o:p></o:p></span></p>

<p class=MsoNormal><sup><span style='font-size:10.5pt;font-family:"Segoe UI",sans-serif;
color:black;background:white'>2</span></sup><span style='font-size:10.5pt;
font-family:"Segoe UI",sans-serif;color:black;background:white'>&nbsp;</span><span
style='font-size:12.0pt;color:black;background:white'>Universal Print is part
of&nbsp;</span><span style='font-size:12.0pt;color:black'>Enterprise / M365
E3/A3, E5/A5 and F3.</span><o:p></o:p></p>


</body>

</html>
