### ISSUE TITLE
Sensitivity Labels

### ISSUE THREAD

**Issue by randomat123** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#613]
The docs says, as below, that you need M365 Business Premium to use AIPService Powershell.
What about M365 E5 and the other licenses that cost more than M365 Bussiness Premium?

```
For a user to benefit from the AIPService PowerShell module to administer the Azure Rights Management protection service for Azure Information Protection, the following license provides user rights:

Microsoft 365 Business Premium and Enterprise Mobility
```

**Comment by jorge-at123** [comment]
Hello @annferre, that's the link: https://docs.microsoft.com/en-us/azure/information-protection/install-powershell

**Comment by jorge-at123** [comment]
Hi @annferre, any updates?
Thank you.

**Comment by annferre** [comment]
Thanks for reaching out, but the team is swamped, and they haven't been able to get back to me. I apologize for the delay.

**Comment by annferre** [comment]
Hi there, we did get a response back and they are stating that information is incorrect: -- "any license valid for using AIP or sensitivity labels is also valid you for administering the protection service using the AIPService PS module." So, I'm working with the product team to update the information. I'll let you know as soon as the edit goes live.

**Comment by annferre** [comment]
Hi again, per the product team, I have updated the page to the below. Let me know if you have further questions. Thanks again for your comment!
For information on how a user can benefit from the [AIPService](https://docs.microsoft.com/en-us/powershell/azure/aip/overview) PowerShell module to administer the Azure Rights Management protection service for [Azure Information Protection](https://docs.microsoft.com/en-us/powershell/azure/aip/overview), see Azure Information Protection.

**Comment by annferre** [comment]
Hi there, per the product's team recommendation, I have updated the section to read the below. Let me know if you have any questions. Thanks again for your comment.
For information on how a user can benefit from the [AIPService](https://docs.microsoft.com/en-us/powershell/azure/aip/overview) PowerShell module to administer the Azure Rights Management protection service for [Azure Information Protection](https://docs.microsoft.com/en-us/powershell/azure/aip/overview), see Azure Information Protection.
