### ISSUE TITLE
The archive mailbox for business premium is 1.5TB? 

### ISSUE THREAD

**Issue by GloriaZzzz** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#614]
![image](https://user-images.githubusercontent.com/93304404/139185374-d0a8675e-2405-4e4c-bbc8-e4f6324151fd.png)
The archive mailbox for business premium is 1.5 TB?? Are you sure? As far as I know, it's 50GB.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for your comment. I have reached out to the product team and will give make changes to the page per their feedback. Thanks again!

**Comment by annferre** [comment]
Hi there, I confirmed with the product team the 1.5 TB. They confirmed that Business Premium gets Exchange Archiving service plan which ups it from 50 GB to 1.5 TB. Let me know if you have any other questions. Thanks!

**Comment by GloriaZzzz** [comment]
Hi Ann,

Thank you for your update. When I checked the Chinese version, it is still showing 50GB. Is there any difference?

Best Regards,
Gloria
Microsoft 365 Ambassador
Working Hours: Sunday - Thursday: 5:30PM  - 2:30AM EDT
If you have any feedback about my work, please do not hesitate to contact my manager Vivian at ***@***.******@***.***>

**Comment by GloriaZzzz** [comment]
Hi Ann,

Yes, I checked from my end, it's 1.5TB now. Thank you so much for your help!

Best Regards,
Gloria
Microsoft 365 Ambassador
Working Hours: Sunday - Thursday: 5:30PM  - 2:30AM EDT
If you have any feedback about my work, please do not hesitate to contact my manager Vivian at ***@***.******@***.***>
