### ISSUE TITLE
New product name

### ISSUE THREAD

**Issue by mmoioli** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#615]
Windows Virtual Desktop is now Azure Virtual Desktop as announced in this blob post
https://azure.microsoft.com/en-us/blog/azure-virtual-desktop-the-desktop-and-app-virtualization-platform-for-the-hybrid-workplace/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94c91b3d-d9b1-9056-ae3e-51a255ed88ec
* Version Independent ID: b60613bc-f7b3-d1c7-4d8e-924c0f87912f
* Content: [Microsoft 365 Business Premium service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for your comment. Can you provide the link to the document you are referring to? Thanks again for your comment.

**Comment by annferre** [comment]
Hi there, the product name has been updated on the business plan comparison sheet, and the current page is now the link to the comparison sheet. Let me know if you have any further questions. Thanks!
![image](https://user-images.githubusercontent.com/86699727/140170516-930ea7e9-33e2-4419-9edc-76b8dff93f17.png)
