### ISSUE TITLE
Which licenses for Information Protection:Sensitivity Labels allow use of Machine Learning (trainable classifier)

### ISSUE THREAD

**Issue by bholzmmc** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#616]
In the section on **Information Protection: Sensitivity labeling**, **Which licenses provide the rights for a user to benefit from the service?** topic (at https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#which-licenses-provide-the-rights-for-a-user-to-benefit-from-the-service-11   at the very end is this sentence
"Information Protection does not include rights to automatic classification based on Machine Learning (trainable classifiers)."
There does not seem to be a license in the document that does include the right to use Machine Learning (trainable classifiers) with Information Protection: Sensitivity Labels.  Documentation, presentations and announcements on Sensitivity Labels proclaim the use and benefits of using trainable classifiers (e.g. https://techcommunity.microsoft.com/t5/security-compliance-and-identity/microsoft-information-protection-announcing-enhanced-automatic/ba-p/2871144).  I understand the statement to mean that there is no license that confers a right to use trainable classifiers.  This is confusing and doesn't seem right.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by annferre** [comment]
Hi there, I spoke with the product team and they said references to trainable classifiers are included in Microsoft 365 E5/A5/G5, Microsoft 365 E5/A5/G5/F5 Compliance and F5 Security & Compliance, Microsoft 365 E5/A5/G5 Information Protection and Governance.

They are called out here: https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#information-governance
And here: https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#records-management

They also said the sentence was initially added to help clarify that ML is part of MIG and not MIP, but did they agree that it might be confusing, so we will be making a change to clarify it better. I'll let you know when that has been updated.

**Comment by bholzmmc** [comment]
Thanks your and the product team for the prompt response.

Brian

**Comment by annferre** [comment]
Hi again, we removed the below sentence from the page. Let me know if you have any other concerns. 
"Information Protection does not include rights to automatic classification based on Machine Learning (trainable classifiers)."

**Comment by bholzmmc** [comment]
Hi Ann,

Actually, I do have the concern that with the absence of any statement, individuals focused on Sensitivity Labels (Information Protection) may not be cognizant of Governance and Compliance, a customer may start utilizing Machine Learning (trainable classifiers) and incur an unintended liability.  It might be better to provide an alternative sentence along the lines of "Rights to automatic classification based on Machine Learning (trainable classifiers) is based on the Information Governance and/or Records Management service subscriptions” and include references or links to those sections."

Brian

**Comment by annferre** [comment]
Hi Brian, I'll reach out to the product team and I'll keep you posted on the response. Thanks for your comment!

**Comment by annferre** [comment]
Hi Brian, I spoke with the product team, and we're adding a note in the section to help direct users to information regarding machine learning. I'll let you know when it goes live. Thanks!

Notes:

Power BI is included with Microsoft 365 E5/A5/G5; in all other plans, Power BI must be licensed separately.
Rights to For user benefit information regarding automatic classification based on Machine Learning, (trainable classifiers) is based on please see [Information Governance](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Foffice365%2Fservicedescriptions%2Fmicrosoft-365-service-descriptions%2Fmicrosoft-365-tenantlevel-services-licensing-guidance%2Fmicrosoft-365-security-compliance-licensing-guidance%23information-governance&data=04%7C01%7Cv-annhem%40microsoft.com%7C48b339076cfb4edd8d3208d9f003f870%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637804722110570242%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=MnNja19a8g8g9vDISYOlixdtamzBeBTBBKcRHLY46K4%3D&reserved=0) and/or [Records Management](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Foffice365%2Fservicedescriptions%2Fmicrosoft-365-service-descriptions%2Fmicrosoft-365-tenantlevel-services-licensing-guidance%2Fmicrosoft-365-security-compliance-licensing-guidance%23records-management&data=04%7C01%7Cv-annhem%40microsoft.com%7C48b339076cfb4edd8d3208d9f003f870%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637804722110570242%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8cZyCeVNf2xbJtRj4ZJgxbnvhF%2F1swn6SRRUWddHdMk%3D&reserved=0) service subscriptions.
