### ISSUE TITLE
The "File size and file path length" section does not contain path length information

### ISSUE THREAD

**Issue by joerodgers** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#617]
The "File size and file path length" section makes not mention of the path length limits in SPO & OD4B.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, I reached out to the product team and they stated that 400 characters is the limit (the technical definition is that ServerRelativePath excluding the leading slash is <= 400 characters). I will work with them to add this information to the page. Thanks for your comment!

**Comment by annferre** [comment]
Hi there, I just wanted to say thank you for your comment, and wanted to let you know the following has been added to the SharePoint limits page: 
File size and file path length
250 GB - File upload limit. Applies to each individual file uploaded to Microsoft Teams Files tab, SharePoint document libraries, OneDrive folders, and Yammer conversations.

250 MB - File attached to a list item. Applies to Microsoft Lists and SharePoint lists - both based on same lists platform.

The entire decoded file path, including the file name, can't contain more than 400 characters for OneDrive, OneDrive for work or school and SharePoint in Microsoft 365. The limit applies to the combination of the folder path and file name after decoding. For more information, go to File name and path lengths.
