### ISSUE TITLE
Office 365 Enterprise F3 -does- include Microsoft Bookings

### ISSUE THREAD

**Issue by AaronDinnage** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#618]
Hi team, this page says that Bookings is not included in Office 365 Enterprise F3, however the license is available in Office 365 tenants for F3 customers. This page should be updated to indicate that Bookings is an inclusion for Office 365 F3. This is also confirmed by the Microsoft internal offer management tool and Ingestion Artefact Analytics Report.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b5e7518-641b-6d9c-da4f-90f268949793
* Version Independent ID: bae3450b-35b4-d942-7012-7867a705150d
* Content: [Microsoft 365 and Office 365 platform service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-platform-service-description#feature-availability-across-plans)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi Aaron, I will forward your request to the product team. Thanks for your comment!

**Comment by annferre** [comment]
Thank you again for your comment. You are correct. F3 is available for F3. We are in the process of updating the page and I'll let you know as soon as it's live.

**Comment by annferre** [comment]
HI there, I just wanted to let you know that you just have to toggle/scroll to the right to see the "yes." Let me know if you have further questions. Thanks!
