### ISSUE TITLE
Change URL https://securescore.office.com to https://security.microsoft.com/securescore

### ISSUE THREAD

**Issue by asdcristi** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#619]
Foornotes section for Secure Score:

"4 Available at https://securescore.office.com. Requires admin permissions. For more information, see Microsoft Secure Score."

Requires an update as that URL is not available any longer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94c91b3d-d9b1-9056-ae3e-51a255ed88ec
* Version Independent ID: b60613bc-f7b3-d1c7-4d8e-924c0f87912f
* Content: [Microsoft 365 Business Premium service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-business-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for your comment. I will forward your request to the product team and keep you updated. Thanks again!

**Comment by annferre** [comment]
Hi there, the M365 business premium page has move to [here](https://www.microsoft.com/en-us/microsoft-365/business/compare-all-microsoft-365-business-products?rtc=1). Let me know if you have anything further. Thank you for your comment!
