### ISSUE TITLE
Retention policy for ExO, SPO, Teams by "Microsoft 365 F5 Compliance" and "Microsoft 365 F5 Security and Compliance"

### ISSUE THREAD

**Issue by takeakitake** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#620]
[Enter feedback here]

Regarding "Which licenses provide the rights for a user to benefit from the service?" of "Information Governance", please include "Microsoft 365 F5 Compliance" and "Microsoft 365 F5 Security and Compliance" add-on plans to plans that can use retention policy for ExO, SPO, Teams.

About Teams retention policy, there are written "the supported minimum retention or deletion period is 30 days" for Microsoft 365 F3. But by these add-on, this is not to be limited.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#information-governance)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for adding the comment. I have forwarded your request to the product team and I'll keep you posted on their response. Thanks again!

**Comment by annferre** [comment]
Hi there, I wanted to let you know we received a response from the product team and we are in the process of updating the page. The response is as follows:
-	Basic org-wide or location-wide mailbox retention policy: Only F3 and F5 should be added
-	SharePoint or OneDrive retention policy and/or manually apply a label: Only F3 and F5 should be added
-	Teams Retention Policy: He wasn’t 100% sure. Based on the comparison chart below, I believe we should add F5 Compliance and F5 Security and Compliance add-on
-	Minimum retention or deletion period: Does not apply for F5

**Comment by annferre** [comment]
Hi there, I just wanted to let you know we are in the final stages of rewriting this whole section. I'm hoping to post it this week.

**Comment by annferre** [comment]
HI there, the rewrite is still in process, however I requested the change to be able to add the missing plans. The text now shows: 
<img width="408" alt="image" src="https://user-images.githubusercontent.com/86699727/175120357-c310c35e-807f-4e21-862f-fcad7dde4033.png">
Please reopen if you you have further questions.
