### ISSUE TITLE
license requirements incomplete

### ISSUE THREAD

**Issue by SRE93** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#621]
"For both client and service-side automatic sensitivity labeling, the following licenses provide user rights:"

Is this feature not included in the E5 Compliance Add-On? Could you please check and update this? I have a customer using this Add-On and the feature successfully.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#information-protection)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by SRE93** [comment]
Hey Microsoft @pamelaar, could you please give me an update on this?

**Comment by annferre** [comment]
Hi there, thank you for your comment. We received an update from the product team in regard to your question. They confirmed E5 is missing from the list and the following update has been requested to the S&C page.
AFTER:

Microsoft 365 E5/A5/G5
F5 and E5 Compliance
F5 Security & Compliance
Microsoft 365 E5/A5/G5 Information Protection and Governance
Office 365 E5

I will let you know when the change is live. Thanks again for your comment.

**Comment by annferre** [comment]
Thank you again for your comment. Edits have been completed and are now live. Let me know if you have further questions. 
<img width="436" alt="image" src="https://user-images.githubusercontent.com/86699727/146421728-2c3422cb-2d0d-488e-aa23-1f3d469f0eea.png">
