### ISSUE TITLE
US Citizenship for GCC High and DOD 

### ISSUE THREAD

**Issue by denpsch** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#622]
[Enter feedback here]

Under Customer Support, needs to clarify support for GCC High and DOD.  This internal document details the US Citizenship differences between engineers that work in the datacenter and support personal. Been receiving confusing statements from Federal/DOD customers and we should lay this paragraph from this document if its applicable. 

https://microsoft.sharepoint.com/:w:/r/teams/USGovCloudSupport/_layouts/15/Doc.aspx?sourcedoc=%7B5FC28466-EF4C-4DF8-980C-0B246F0EDE98%7D&file=Premier%20Cloud%20Field%20FAQ%20-%20US%20Government%20Cloud.docx&action=default&mobileredirect=true&DefaultItemOpen=1

Incidents should be submitted through approved channels (i.e., Office 365 GCC High and DoD Portal or special phone number), or else we can’t determine the customer is part of the Office 365 GCC High and DoD cloud and the promises here described are not valid.

o While datacenter personnel with access to Customer Data are screened US Citizens, support personnel have no access to the Datacenter nor to Customer Data, and therefore can only be exposed to sensitive information when provided directly by the customer.

o Office 365 GCC High and DoD offer technical support contact provided by screened US Citizens in a US Location, in order to help customers and make it easier for them to comply with data sharing standards and requirements defined by the DoD Security Requirements Guidelines (SRG) 2.1 for Impact Level 4 and Impact Level 5 data, as well as ITAR-controlled data. However, that doesn’t remove or diminish the customer responsibility in sharing controller/sensitive data with 3rd parties

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c907526-4061-94b4-f2fd-d6fca90344bb
* Version Independent ID: 82e89c18-8d6e-bbb1-f6d0-6ec091d1556e
* Content: [Office 365 GCC High and DoD - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, can you clarify the actual paragraph you would like to see changed and is the change request for the the [service description page](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod) or the [document](https://microsoft.sharepoint.com/:w:/r/teams/USGovCloudSupport/_layouts/15/Doc.aspx?sourcedoc=%7B5FC28466-EF4C-4DF8-980C-0B246F0EDE98%7D&file=Premier%20Cloud%20Field%20FAQ%20-%20US%20Government%20Cloud.docx&action=default&mobileredirect=true&DefaultItemOpen=1)?
Thanks!

**Comment by denpsch** [comment]
Hi. 

It's under the Customer Support section in the service description page: https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod 

It is not clear on customer support options we provide with GCC High and DoD. In the document section 3 describes promises are not valid unleess incidents are submitted through the portal. Since our GCC High and DoD customers rely on USNAT, this applies  only if its submitted through the portal. 

Thanks! feel free to reach me on teams or here for more details. 
dschnell

**Comment by annferre** [comment]
Closing per email conversation. Once the FAQ page is created, please request the link to be added to the page in the portal: https://aka.ms/365servicedesc
