### ISSUE TITLE
License and features spreadsheet retirement...

### ISSUE THREAD

**Issue by H2OGrrl** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#623]
The spreadsheet retirement made the page nearly useless. Have a spreadsheet to quickly compare licensing and features is invaluable. Having to search each feature, to see which license applies, is a time waster.

 Note
If you're looking for the service description comparison spreadsheet, it's been retired. The product feature availability tables on each service description page have been updated to better help you choose the version of Office 365 that suits your needs.

-LeAnne

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f448a5a2-1307-bf89-c910-9bc03840afde
* Version Independent ID: d99ca5b3-1b4b-6af2-d3c9-dc4cd1afaac3
* Content: [Microsoft 365 and Office 365 service descriptions - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-service-descriptions-technet-library)
* Content Source: [Office365-ServiceDescriptions/office-365-service-descriptions-technet-library.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-service-descriptions-technet-library.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for your comment. Can you provide more information regarding what change you would like to see? We have three comparison sheets, one for Enterprise, one for Small and Medium Business, and one for Education. Is it one of these comparison sheets you are referring to? Can you provide information as to what you would like to see in it's place? Thanks again!

**Comment by annferre** [comment]
Hi LeAnne, I'm not sure how to address your concern. The spreadsheets we now have are the following: https://aka.ms/M365BusinessPlans
https://aka.ms/M365EnterprisePlans
https://aka.ms/M365EduPlans
Can you help me determine the change you like to see?
Thanks!

**Comment by annferre** [comment]
Hi there, I'm just checking again to see if you can provide the old link to the spreadsheet you are referring to? Thanks!

**Comment by annferre** [comment]
Hi LeAnne, I'm not sure how to address your concern. The spreadsheets we now have are the following: https://aka.ms/M365BusinessPlans
https://aka.ms/M365EnterprisePlans
https://aka.ms/M365EduPlans
Let me know if this is acceptable?
Thanks!
