### ISSUE TITLE
Education the Same

### ISSUE THREAD

**Issue by leifdavisson** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#624]
Is Education the Same as Enterprise?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
HI there, I reached out to the product team, and I'll keep you posted on the response. Thanks for your comment!

**Comment by annferre** [comment]
Hi there, I did confirm with the product team that for limits for SharePoint there is no difference between enterprise, education, or government clouds. It is all the same infrastructure. Let me know if you have further questions. Thanks!
________________________________________
