### ISSUE TITLE
Conflicting Information with another page

### ISSUE THREAD

**Issue by mprentice22153** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#625]
In this page there is a link to the **Modern Work User Subscription Plan Comparison for Enterprise - 2 November 2021.pdf**
There is a corresponding document **Microsoft 365 Business Plan Comparison for SMB - 2 November 2021.pdf** for the M365 Business products.

The above mentioned M365 Business doc should also be linked to this page.

The above mentioned M365 Business doc shows M365 Business Premium actually does support Group Policy.  Can this be confirmed?

Thank you.

Matthew

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 128805e7-b1a4-5cdf-1890-8794fa46d5d5
* Version Independent ID: 884c3ae0-9317-d37c-f94f-97aabd0e622d
* Content: [Office applications service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-applications-service-description/office-applications-service-description?redirectedfrom=MSDN)
* Content Source: [Office365-ServiceDescriptions/office-applications-service-description/office-applications-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-applications-service-description/office-applications-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your comment. I have reached out to the product team and will keep you posted on the response. Thanks again!

**Comment by annferre** [comment]
<html>
<body>
<b style="box-sizing: border-box; color: rgb(0, 0, 0); font-family: &quot;Segoe UI VSS (Regular)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div style="box-sizing: border-box; margin: 0px 0in; font-size: 11pt; font-family: Calibri, sans-serif;"><p style="box-sizing: border-box; margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif;">The online service description has been updated to the below. Let me know if you have further questions or concerns. Thanks again for your comment.</p><p style="box-sizing: border-box; margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif;"><a href="https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fdocs.microsoft.com%2fen-us%2foffice365%2fservicedescriptions%2foffice-applications-service-description%2foffice-applications-service-description?redirectedfrom%3DMSDN&amp;data=04%7c01%7cv-annhem%40microsoft.com%7c1c0705f07ae84821b71708d9d6c638e8%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637776969138040594%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000&amp;sdata=lRoMHyPITGhpbReobdyP82Z8M5uMLsnczQeC1XP3imQ%3D&amp;reserved=0" style="box-sizing: border-box; color: var(--communication-foreground,rgba(0, 90, 158, 1)); text-decoration: underline; cursor: pointer;">Office applications service description - Service Descriptions | Microsoft Docs</a></p><p style="box-sizing: border-box; margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif;"> </p><div style="box-sizing: border-box; margin: 0px 0in; font-size: 11pt; font-family: Calibri, sans-serif;"><div style="box-sizing: border-box; margin: 0px 0in;"><p style="box-sizing: border-box; margin: 0in;"> </p>

Enterprise value | Office Professional Plus 2013 | Office Professional Plus 2016 | Office Professional Plus 2019 | Microsoft 365 Apps for enterprise | Microsoft 365 Apps for business | Microsoft 365 Business Basic | Microsoft 365 Business Standard | Microsoft 365 Business Premium | Office 365 E1 | Office 365 E3 | Office 365 E5 | Office 365 F3
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Group Policy support | Yes | Yes | Yes | Yes | Yes<sup>15</sup> | No | Yes<sup>15</sup> | Yes<sup>15</sup> | No | Yes | Yes | No

<p style="box-sizing: border-box; margin: 0in;"> </p><br style="box-sizing: border-box;"></div></div></b><br class="Apple-interchange-newline">
</body>
</html>

**Comment by annferre** [comment]
<html>
<body>
<b style="box-sizing: border-box; color: rgb(0, 0, 0); font-family: &quot;Segoe UI VSS (Regular)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div style="box-sizing: border-box; margin: 0px 0in; font-size: 11pt; font-family: Calibri, sans-serif;"><p style="box-sizing: border-box; margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif;">The service description page has been updated to the below. Let me know if you have further questions or concerns. Thanks again for your comment.</p><p style="box-sizing: border-box; margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif;"><a href="https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fdocs.microsoft.com%2fen-us%2foffice365%2fservicedescriptions%2foffice-applications-service-description%2foffice-applications-service-description?redirectedfrom%3DMSDN&amp;data=04%7c01%7cv-annhem%40microsoft.com%7c1c0705f07ae84821b71708d9d6c638e8%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637776969138040594%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000&amp;sdata=lRoMHyPITGhpbReobdyP82Z8M5uMLsnczQeC1XP3imQ%3D&amp;reserved=0" style="box-sizing: border-box; color: var(--communication-foreground,rgba(0, 90, 158, 1)); text-decoration: underline; cursor: pointer;">Office applications service description - Service Descriptions | Microsoft Docs</a></p><p style="box-sizing: border-box; margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif;"> </p><div style="box-sizing: border-box; margin: 0px 0in; font-size: 11pt; font-family: Calibri, sans-serif;"><div style="box-sizing: border-box; margin: 0px 0in;"><p style="box-sizing: border-box; margin: 0in;"> </p>

Enterprise value | Office Professional Plus 2013 | Office Professional Plus 2016 | Office Professional Plus 2019 | Microsoft 365 Apps for enterprise | Microsoft 365 Apps for business | Microsoft 365 Business Basic | Microsoft 365 Business Standard | Microsoft 365 Business Premium | Office 365 E1 | Office 365 E3 | Office 365 E5 | Office 365 F3
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Group Policy support | Yes | Yes | Yes | Yes | Yes<sup>15</sup> | No | Yes<sup>15</sup> | Yes<sup>15</sup> | No | Yes | Yes | No

<p style="box-sizing: border-box; margin: 0in;"> </p><br style="box-sizing: border-box;"></div></div></b><br class="Apple-interchange-newline">
</body>
</html>
