### ISSUE TITLE
Viva learning licenses nog mentioned in the license table

### ISSUE THREAD

**Issue by CasperNaudts** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#627]
Viva learning is only available in the Microsoft 365 A3 and A5 for faculty not in the student use benefits.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8328da3-5093-09b6-9b9b-b92d13625219
* Version Independent ID: f2171de5-bfa5-65d1-4615-30db23349b40
* Content: [Microsoft 365 Education - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for your comment. I have forwarded your request to the product team, and I'll keep you posted on the response. Cheers!

**Comment by annferre** [comment]
Hi there, I'm not sure what the ask is. Can you clarify? The comparison sheet reflects that Microsoft 365 A3 and A5 for faculty not in the student use benefits. Is the ask to have Viva Learning added to the Education Service Description page? Thanks!

**Comment by CasperNaudts** [comment]
Hi @annferre, We would like to see Viva learning included in the services and features tabel on the docs page. By try and error we found that viva learning never is included in any student license but would like an article to reference when we discuss this with clients. Now everyone is just guessing a bit.

**Comment by annferre** [comment]
Hi there, I just wanted to let you know we added Viva Learning to the [Microsoft 365 Education - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education) page. Let me know if you have any questions. Thanks again for your comment.
