### ISSUE TITLE
Link does not work from this page: Compare All Microsoft 365 Business Products

### ISSUE THREAD

**Issue by MagnusKanngard** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#628]
[Enter feedback here]
There is a link in this page that does not work. The link to "Compare All Microsoft 365 Business Products"
Page does not exist

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f448a5a2-1307-bf89-c910-9bc03840afde
* Version Independent ID: d99ca5b3-1b4b-6af2-d3c9-dc4cd1afaac3
* Content: [Microsoft 365 and Office 365 service descriptions - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-service-descriptions-technet-library)
* Content Source: [Office365-ServiceDescriptions/office-365-service-descriptions-technet-library.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-service-descriptions-technet-library.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for your comment. I have sent your request to the product team and will reply as soon as I receive a response. Thanks again! Cheers!

**Comment by annferre** [comment]
Hi there, I just wanted to let you know all the links and TOC have been updated. Let me know if you still have questions. Thanks again for your comment!
