### ISSUE TITLE
Microsoft Search is actually available in GCC

### ISSUE THREAD

**Issue by CBrasga** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#629]
Bullet point about "Microsoft Search is not available in GCC." is no longer true, according to Microsoft 365 Roadmap which shows Microsoft Search for GCC went GA in October 2021. ([Microsoft 365 Roadmap](https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=Microsoft%20Search%2CGCC) and [Microsoft Search for US government environments](https://docs.microsoft.com/en-us/microsoftsearch/microsoft-search-us-government-environments))

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5408a406-02e7-bf26-e330-be25ea409aa6
* Version Independent ID: 3ed59637-9e20-85a7-83e1-e70cd61f635e
* Content: [SharePoint for US government environments - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/sharepoint?source=docs)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/sharepoint.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/sharepoint.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for your comment. I have sent your request to the product team and will reply as soon as I receive a response. Thanks again! Cheers!

**Comment by annferre** [comment]
Hi there, the "Search features" section has been updated to the below, hence closing the ticket. Let me know if you have any questions. Thanks!
**Search features**
For details on availability of specific Microsoft Search features within the GCC, GCC High, and DoD environments, refer to the [following table](https://docs.microsoft.com/en-us/MicrosoftSearch/microsoft-search-us-government-environments#microsoft-search-features).
