### ISSUE TITLE
sign in

### ISSUE THREAD

**Issue by sekharDoppalapudi** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#63]
Request to update shared mailbox default sign-in behavior.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by chrisda** [comment]
@sekharDoppalapudi , can you be more specific? What does signing into a shared mailbox have to do with limits?

**Comment by chrisda** [comment]
@sekharDoppalapudi I modified the information about shared mailboxes with a link to instructions re: how to block sign-in for the associated (and active by default) user account.
