### ISSUE TITLE
PowerBI in China (21vianet)

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#630]
According to https://powerbi.microsoft.com/en-us/clouds/ Power BI is available in the China sovereign cloud (21vianet), but it is not listed on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84a9aadf-5458-1bc2-bbbe-b44794ad18c7
* Version Independent ID: 69a00a16-8f2e-9618-18b5-079c43fd3919
* Content: [Office 365 operated by 21Vianet - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-operated-by-21vianet)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-operated-by-21vianet.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-operated-by-21vianet.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your comment. I have reached out to the product team, and I'll get back to you as soon as they reply. Thanks again! Cheers!

**Comment by annferre** [comment]
Hi there, I received the following response from the product team: PowerBI Pro, PowerBI Premium Per Capacity & PowerBI Premium Per User are available under Gallatin Cloud (operated by 21Vianet), but they are available as individual products, not part of the listed bundles below. It should be “No“ in all below boxes. For more information, please see:
Microsoft Power BI – 21Vianet Blue Cloud (21vbluecloud.com)
Power BI 商业计划 – 21Vianet Blue Cloud (21vbluecloud.com)
