### ISSUE TITLE
Need update to service description for MS Bookings

### ISSUE THREAD

**Issue by gabovm** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#633]
This service descrip: https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-platform-service-description?source=docs needs to be updated to reflect that MS Bookings is available for F3 subscriptions too.

Thanks!

**Comment by annferre** [comment]
Hi Gabriel, closing the ticket due to F3 already showing "yes" for MS Bookings. Thanks!
