### ISSUE TITLE
Please update "Microsoft 365 Comparison table" file. We can not use Webinars feature in Office 365 E1 plan.

### ISSUE THREAD

**Issue by takeakitake** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#635]
[Enter feedback here]

Hello,

Please update "Microsoft 365 Comparison table" file. It is linked in upper of this page.

There are dot in [Webinars] for Office 365 E1 column. This is not correct. We can not use Webinars feature in Office 365 E1 plan.

There are 2 pages that explained licensing of this feature. There are not included Office 365 E1 in both of 2 pages. And "promotional period" for 2021 is finished.

Introducing Webinars in Microsoft Teams: Easy, professional webinars to engage customers
https://www.microsoft.com/en-us/microsoft-365/blog/2021/05/11/introducing-webinars-in-microsoft-teams-easy-professional-webinars-to-engage-customers/

1These new capabilities will be available in Microsoft 365 E3/E5, Microsoft 365 A3/A5, and Microsoft 365 Government G3/G5 plans. Microsoft 365 Business Standard and Microsoft 365 Business Premium plans will include all the features above for up to 300 attendees. And for the rest of 2021, we are offering a promotional period where all Teams users can try the features with their existing subscription. Please visit the Microsoft 365 roadmap and Microsoft Docs for additional feature details and availability.

Elevate webinar and broadcasting experiences with Microsoft Teams
https://techcommunity.microsoft.com/t5/microsoft-teams-blog/elevate-webinar-and-broadcasting-experiences-with-microsoft/ba-p/2784943

1These new capabilities will be available in Office 365 and Microsoft 365 E3/E5/A3/A5 plans. Microsoft 365 Business Standard and Microsoft 365 Business Premium plans will include all the webinar features for up to 300 attendees. And for the rest of 2021, we are offering a promotional period where all Teams users can try the features with their existing subscription including Office 365 E1, A1, and Microsoft 365 Business Basic plans. Please visit the Microsoft 365 roadmap and Microsoft Docs for additional feature details and availability.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, I confirmed with the product team, and you are correct. They'll be double-checking and then updating the pdf in the next version.  Thanks!

**Comment by annferre** [comment]
Hi there, I just wanted to let you know the comparison sheet has been updated. Please let me know if you have any further concerns. Thanks again for your comment!
<img width="923" alt="Screenshot 2022-02-04 145859" src="https://user-images.githubusercontent.com/86699727/152614675-8caf4a82-0fa8-493d-a0b9-ed034b2c772b.png">
