### ISSUE TITLE
Incorrect information mentioned for Reuse Slides

### ISSUE THREAD

**Issue by Gaurav0327** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#636]
Hi Team,
I want to report an issue here as shared by 1 of our Strategic Government Customer.
Per the article https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government

![image](https://user-images.githubusercontent.com/39978613/148970893-c9551b7c-f30a-4b8c-ad4a-b7b8e9598410.png)

As per the article, REUSE SLIDE is not supposed to work in any GCC environment, however my customer has proved on a screen share session with us that the feature works in his VDI's. For the same customer, the feature is not working in machines connected to VPN. 

Customer has raised a break-fix issue with us and requesting a fix. 
Response from the customer:
![image](https://user-images.githubusercontent.com/39978613/148971959-6208a5fa-b385-4e4e-baf5-64104abea553.png)

Request you to please suggest and confirm, if this is supported and update the article accordingly.

**Comment by annferre** [comment]
Thanks Gaurav! I forwarded your request to the product team and cc'd you on the communication. Thanks again!

**Comment by annferre** [comment]
Hi Gaurav, can you reach out to me in outlook. The product team needs help with the repro. I'm under Ann Hemmons Ferreira. Thanks!
