### ISSUE TITLE
Incorrect Basic Auditing on O365 F3

### ISSUE THREAD

**Issue by brvargas11** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#637]
In the O365 F3 license it says that it supports Basic Auditing, but it seems that is not updated correctly, in the M365 Comparisong table there is no Basic Auditing in O365F3

https://go.microsoft.com/fwlink/?linkid=2139145
thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 663a603e-482b-0a4f-55a9-229ceab11bb1
* Version Independent ID: 488b1daa-b459-c56d-11eb-59242af822b0
* Content: [Security & Compliance Center - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-securitycompliance-center.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for your comment. I have reached out to the product team and will keep you posted on response, and any necessary changes. Thanks again!

**Comment by annferre** [comment]
Hi there, I just wanted to let you know you are correct. The [Security & Compliance Center - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center#feedback) page is incorrect. We have a [new page](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance) now for Security and Compliance and the older Security & Compliance Center page has been deprecated. Let me know if you have any further concerns. Thanks again for your comment!
