### ISSUE TITLE
New section for retention / hold limits

### ISSUE THREAD

**Issue by robertoyms** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#638]
We're working to improve documentation of retention policies & hold limits (my team owns these features), could you please help adding the following section?

Holds limits
Holds include Microsoft 365 retention policies and retention label policies, eDiscovery case holds, Litigation holds, and In-Place Holds. These count towards the 10,000 per tenant maximum for compliancy policies that also include policies for DLP, information barriers, and sensitivity labels.   
Note: Exchange retention policies from messaging records management (MRM)) are excluded from this 10,000 maximum.
Maximum number of Microsoft 365 retention policies per tenant: 1,800
Maximum number of holds per mailbox: 25 is the recommended maximum before performance might be impacted; 50 is the supported limit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits?source=docs)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your comment. I have forwarded your request to the product team. I'll confirm here once the product team confirms, and the update is live.

**Comment by annferre** [comment]
Hi there, I haven't heard back from the product team, but I requested confirmation again to add the Hold Limits section. I'll keep you posted. Thanks!

**Comment by annferre** [comment]
Hi there, the "Hold Limits" section has been added to the [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits?source=docs) page. Let me know if you have any questions. Thanks!!
