### ISSUE TITLE
New section for retention policies / holds limits

### ISSUE THREAD

**Issue by robertoyms** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#639]
We're working to improve the documentation of retention policies and holds limits which my team is accountable for. Could you please consider adding the following section?

Holds limits
Holds include eDiscovery case holds and Microsoft 365 retention policies for SharePoint and OneDrive. These count towards the 10,000 per tenant maximum for compliancy policies that also include policies for DLP, information barriers, and sensitivity labels.   
Maximum number of holds supported
•	SharePoint or OneDrive: (all sites automatically included): 13
•	SharePoint or OneDrive (specific locations included or excluded): 2,600

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits#service-limits-for-all-plans)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your comment. I have forwarded your request to the product team. I'll confirm here once the product team confirms, and the update is live.

**Comment by robertoyms** [comment]
Thanks, please copy me on that conversation if needed, we're the product team for M365 retention policies.

Roberto.

**Comment by annferre** [comment]
Hi there, the Hold Limits section has been added to the [SharePoint limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits#service-limits-for-all-plans) page. Let me know you have any further questions. Thank you!
