### ISSUE TITLE
Remove frontline SKU condition "Cannot be administrators"

### ISSUE THREAD

**Issue by AaronDinnage** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#640]
The frontline license condition that users "cannot be administrators" has been removed from other online documentation, for example the product comparison page: https://www.microsoft.com/microsoft-365/compare-microsoft-365-enterprise-plans

This page needs the same update applied. I can provide Microsoft internal references for this if needed, contact me on my @microsoft.com email for further infromation as needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3fea44b-ae19-6168-157e-56e36c76b467
* Version Independent ID: 74e1c2f3-c8f7-16cf-0fd2-7d6007b12abb
* Content: [Microsoft 365 and Office 365 plan options - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-plan-options)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-plan-options.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-plan-options.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your comment. I have forwarded your request to the product team. I'll confirm here once the product team confirms, and the update is live.

**Comment by annferre** [comment]
Hi there, I just wanted to let you know the frontline license condition that users "cannot be administrators" has been removed. Let me know if you have further questions. Thanks again for your comment!
