### ISSUE TITLE
Cloud App Security has been renamed Defender for Cloud Apps.

### ISSUE THREAD

**Issue by dcurwin** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#641]
Cloud App Security has been renamed Defender for Cloud Apps.

I'm responsible for Defender for Cloud Apps documentation. Feel free to be in contact with me if you have questions about the rebrand.

Thanks,

David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3fea44b-ae19-6168-157e-56e36c76b467
* Version Independent ID: 74e1c2f3-c8f7-16cf-0fd2-7d6007b12abb
* Content: [Microsoft 365 and Office 365 plan options - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-plan-options)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-plan-options.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-plan-options.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your comment. I'll work with the product teams to update the name. I'll let you know once the edits are confirmed and live. Thanks again!

**Comment by dcurwin** [comment]
@annferre  - Any updates?

**Comment by annferre** [comment]
Hi there, I just wanted to let you know we're in the process of updating the pages. I'll let you know as soon as the edits are live. Thanks again for your comment!

**Comment by annferre** [comment]
Hi David, I just wanted to let you know all of the pages have been updated except one. I'll close out the ticket as soon as the last one is live. Thanks!

**Comment by annferre** [comment]
Hi again, I just wanted to let you know the last page is live as well. Let me know if you have any questions. Thanks again for your comment!
