### ISSUE TITLE
Connected Accounts is no longer an Exchange Online feature

### ISSUE THREAD

**Issue by rsparnaaij** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#642]
This page still lists Connected Accounts as an Exchange Online feature although it no longer is for quite some time now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2f622a7-32c1-2c35-2df9-ddf1bc74c74d
* Version Independent ID: e37d85d2-8b81-0c64-b7d0-1e8c01b303db
* Content: [Exchange Online service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your comment, I have forwarded your request to the product team and once I get confirmation, I will let you know when the edit goes live. Thanks again!

**Comment by annferre** [comment]
Thank you again for your comment. Connected Accounts as an Exchange Online feature has been removed from the page. Let me know if you have any further concerns. Thanks!
