### ISSUE TITLE
Wrong superscript reference for F3 license about POP/IMAP

### ISSUE THREAD

**Issue by myfope** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#644]
Hi,

the matrix has a wrong reference for the F3 license about POP and IMAP. It is referenced as "Yes" with a superscript to 2. But 2 references to AD RMS and is not in the context with POP and IMAP. This should be referenced to 3 as 3 states that IMAP/POP is not available within F3 what is correct.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2f622a7-32c1-2c35-2df9-ddf1bc74c74d
* Version Independent ID: e37d85d2-8b81-0c64-b7d0-1e8c01b303db
* Content: [Exchange Online service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for your comment. I have forwarded your request to the product, and I'll keep you posted on when the edit goes live. Thanks again! (note: the footnote should read: POP is supported, but IMAP is not).

**Comment by annferre** [comment]
Thank you again for your comment. The footnote has been updated. Let me know if you still have questions.
