### ISSUE TITLE
"IL4 Segmentation" is incorrect

### ISSUE THREAD

**Issue by mabranda** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#649]
[Enter feedback here]
We don't have an "IL4 segmented environment". We have IL2 (GCC) and IL4/5 (DoD). 

This is misleading and confuses our customers and our sales team. Please verify with Richard Wakeman on the proper language for this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c907526-4061-94b4-f2fd-d6fca90344bb
* Version Independent ID: 82e89c18-8d6e-bbb1-f6d0-6ec091d1556e
* Content: [Office 365 GCC High and DoD - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod?source=docs#compliance)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for your comment. I have reached out to the product team for help with this. I'll let you know as soon as I've received a response. Thanks again! Cheers!

**Comment by annferre** [comment]
Hi there, I just wanted to let you know the Compliance section has been updated to the following:
<img width="460" alt="image" src="https://user-images.githubusercontent.com/86699727/160473417-b48da032-756c-4f3f-8181-04b440a4dd43.png">

**Comment by mabranda** [comment]
Excellent. Thanks!

Mario Brandan
***@***.***
