### ISSUE TITLE
Licensing information for Adaptive Scopes

### ISSUE THREAD

**Issue by bubhat** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#650]
Can you please add licensing information for Adaptive Scopes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for your comment. I have forwarded your request to the product team, and I'll let you know as soon as I get a response. Thanks again! Cheers!

**Comment by annferre** [comment]
Hi there, I just wanted to let you know we are in process of a rewrite of this section. I'm hoping to post it this week. Thanks!

**Comment by annferre** [comment]
Hi there, the page has been updated with the below information. Please reopen if you still have questions.
The following deployment methods for retention labels require specific licensing:

Auto-apply to content that contains sensitive information
Auto-apply to content that contains specific words, phrases, or properties
Apply a default retention label to a SharePoint document library, folder, or document set
Using an adaptive policy scope in the retention label policy
The following licenses provide user rights for those deployment methods:

Microsoft 365 E5/A5/G5
Microsoft 365 E5/A5/G5/F5 Compliance and F5 Security & Compliance
Microsoft 365 E5/A5/F5/G5 Information Protection and Governance
Office 365 E5/A5/G5
