### ISSUE TITLE
Inclusion of Defender for Endpoint Plan 1

### ISSUE THREAD

**Issue by iftikhariqbal** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#651]
As per this tech community [blog](https://techcommunity.microsoft.com/t5/microsoft-defender-for-endpoint/microsoft-defender-for-endpoint-plan-1-now-generally-available/ba-p/2966231) Defender for Endpoint is now available as Plan 1 and Plan 2 and since A3 includes Defender for Endpoint Plan 1, this should be stated here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8328da3-5093-09b6-9b9b-b92d13625219
* Version Independent ID: f2171de5-bfa5-65d1-4615-30db23349b40
* Content: [Microsoft 365 Education - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, I have reached out to the product team and I'll keep you posted on the response. Thanks for your comment!

**Comment by annferre** [comment]
Hi there, I just wanted to let you know we are updating the page to the following:
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/v-annhe/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=Preview
href="file:///C:/Users/v-annhe/AppData/Local/Temp/msohtmlclip1/01/clip_preview.wmf">

<link rel=themeData
href="file:///C:/Users/v-annhe/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/v-annhe/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>


<p class=MsoNormal>After:<o:p></o:p></p>



Management and security | Office 365 Education A1 | Office 365 Education A3 | Office 365 Education A5 | Microsoft 365 Education A3 | Microsoft 365 Education A5 | Office 365 A3 Student Use Benefit | Office 365 A5 Student Use Benefit | Microsoft 365 Education A3 Student Use Benefit | Microsoft 365 Education A5 Student Use Benefit
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Microsoft   Defender for Endpoint12 Plan 1 | No | No | No | Yes | No | No | No | No | No
Microsoft   Defender for Endpoint12 Plan 2 | No | No | No | No | Yes | No | No | No | No



<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>Thanks!<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>


</body>

</html>


Thanks!

**Comment by annferre** [comment]
Hi there, I wanted to let you know the update is live. Thank again for your comment. Let me know if you have any questions. Cheers!
