### ISSUE TITLE
Teams Essentials and 1 TB per tenant for SPO

### ISSUE THREAD

**Issue by EvgenyArtemyev** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#652]
Hello team,

It would be nice to add information about Teams Essential to the last column with 1TB for SPO w/o 10 additional storage.
or it looks incoherent since in any Tenant with Teams Essentials plans only the 1TB in SPO per organization is available. 

Thank you in advance 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits?source=docs)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your comment! I have forwarded your request to the product team and I'll keep you posted on the response. Thanks again!

**Comment by annferre** [comment]
Hi there, apologies for the delay, but Teams Essential has been added. Please reopen if you have any questions. Thanks again for your comment.
