### ISSUE TITLE
300,000 files in a single OneDrive : Add Shortcut to OneDrive - does it count ?

### ISSUE THREAD

**Issue by danone1985** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#653]
Hello,

Apparently, adding shortcuts to OneDrive from SharePoint, counts against the below limitation:

"For optimum performance, we recommend storing no more than 300,000 files in a single OneDrive or team site library"

any thoughts ?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your comment. I have forwarded your request to the Product team and I'll get back to you as soon as I receive an answer. Thanks again!

**Comment by annferre** [comment]
Hi there, the product team stated that shortcuts are special files in a OneDrive and they count against any limits that file/folders participate in. They're currently looking into which documents need to be updated. Thanks again for your comment.

**Comment by annferre** [comment]
Hi there, the teams asked if you could help them understand why the concern regarding the distinctions.   How many shortcuts do you expect to have?  Usually, the expectation is for a small fraction of the 300K files you can sync. Even if you have 1000 short cuts, that still less than a 1/3 of 1% of the total number of files. Can you provide a little more information?

**Comment by HansBrender** [comment]
the engine on your Windows device will count all files form OneDrive, Odrive for Business, all SharePoint Libraries

**Comment by annferre** [comment]
Hi there, the product team provided the following information: There are two different 300K limits mentioned in that article:
•	"For optimum performance, we recommend storing no more than 300,000 files in a single OneDrive or team site library"
•	“Additionally, the same performance issues can occur if you have 300,000 items or more across all libraries you are syncing, even if you are not syncing all items in those libraries. This 300K file “soft” limit for OneDrive Sync also applies to shortcut folders. Check [Restrictions and limitations in OneDrive and SharePoint](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.microsoft.com%2Fen-us%2Foffice%2Frestrictions-and-limitations-in-onedrive-and-sharepoint-64883a5d-228e-48f5-b3d2-eb39e07630fa%3Fui%3Den-us%26rs%3Den-us%26ad%3Dus%23numberitemscanbesynced&data=04%7C01%7Cv-annhem%40microsoft.com%7C01a0191e2ed34e211e8d08d9fb9c8ddc%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637817472094600650%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gMKCLQHJ4%2Bo%2FLGVjY360%2BKsg73puK4OiH6CmrsvgS%2FM%3D&reserved=0).

**Comment by annferre** [comment]
Hi again, the verbiage from the product team is now live. Please reopen if you still have questions or concerns. Much appreciated!
<img width="457" alt="image" src="https://user-images.githubusercontent.com/86699727/177407563-836e472e-922c-4394-8b5e-bb44439cc650.png">
