### ISSUE TITLE
Bookings SKU updates needed

### ISSUE THREAD

**Issue by cobirge** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#655]
This page shows Bookings as not available in the Student Benefit SKUs, but per https://commoffertool.catalog.cp.microsoft.com/Prod/Office365/element/details/199a5c09-e0ca-4e37-8f7c-b05d533e1ea2 Bookings is available in these SKUs as well. Please update. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8328da3-5093-09b6-9b9b-b92d13625219
* Version Independent ID: f2171de5-bfa5-65d1-4615-30db23349b40
* Content: [Microsoft 365 Education - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your comment. We are in the process of updating the page. I'll let you know when the update is live. Thanks again!

**Comment by annferre** [comment]
Hi there, 
I just wanted to let you know Microsoft Bookings in the [Microsoft 365 Education - Service Descriptions] (https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education) page has been updated to the following:
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/v-annhe/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=Preview
href="file:///C:/Users/v-annhe/AppData/Local/Temp/msohtmlclip1/01/clip_preview.wmf">

<link rel=themeData
href="file:///C:/Users/v-annhe/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/v-annhe/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>




Voice video and meetings | Office 365 Education A1 | Office 365 Education A3 | Office 365 Education A5 | Microsoft 365 Education A3 | Microsoft 365 Education A5 | Office 365 A3 Student Use Benefit | Office 365 A5 Student Use Benefit | Microsoft 365 Education A3 Student Use   Benefit | Microsoft 365 Education A5 Student Use   Benefit
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Microsoft Bookings | No | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes




</body>

</html>

Let me know if you have any questions. 
Thanks!

**Comment by cobirge** [comment]
Brilliant, thank you for your help.
