### ISSUE TITLE
Wron documentation in the Microsoft Defender for Endpoint Section

### ISSUE THREAD

**Issue by wolf-365** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#656]
Hi,

the part on how to apply usage of the service for Microsoft Defender for Endpoint only to licensed users is not correct. You describe, how to limit access to the admin portal but not how you limit the usage on the user side.

The mechanism to limit usage on the user end would be to only onboard devices to the tenant, that are being used by users who are licensed for the service. Strictly speaking not even that would make sure that the service is limited to licensed users because users could exchange devices and then users who are not licensed would use an enrolled device and thus would be incompliant.

Please correct the documentation. Limiting admin access to the portal does not limit usage of the end user service.

**How can the service be applied only to users in the tenant who are licensed for the service?**
Microsoft Defender for Endpoint administrators can use role-based access control (RBAC) to create roles and groups within the security operations team to grant appropriate access to the Microsoft Defender Security Center. For more information, see [Manage portal access using role-based access control](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/rbac).
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#how-can-the-service-be-applied-only-to-users-in-the-tenant-who-are-licensed-for-the-service-20)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for your comment. I have reached out to the product team, and I'll keep you posted on their response. Cheers!

**Comment by annferre** [comment]
Hi there, if you work for Microsoft, can you reach out to me directly? Ann Hemmons Ferreira. Thanks!
