### ISSUE TITLE
Licensing requirements for Basic Audit

### ISSUE THREAD

**Issue by sasaito** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#657]
Hello,

Licensing requirements for Basic Audit is inconsistent with the docs article "Auditing solutions in Microsoft 365".

This page "Microsoft 365 and Office 365 platform service description" says as follows, but it might be updated to "No"?
Microsoft 365 and Office 365 platform service description (https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-platform-service-description) : 
Privacy, security, and transparency Basic Audit
- Microsoft 365 Business Basic Yes
- Microsoft 365 Apps for business Yes
- Microsoft 365 Business Standard Yes

Auditing solutions in Microsoft 365 (https://docs.microsoft.com/en-us/microsoft-365/compliance/auditing-solutions-overview?view=o365-worldwide&source=docs#licensing-requirementsLicensing%20requirements) :

Licensing requirements
The following sections identify the licensing requirements for Basic Audit and Advanced Audit. Basic Audit functionality is included with Advanced Auditing.

- Basic Audit
- Microsoft 365 Enterprise E3 subscription
- Microsoft 365 Business Premium
- Microsoft 365 Education A3 subscription
- Microsoft 365 Government G3 subscription
- Microsoft 365 Government G1 subscription
- Microsoft 365 Frontline F1 or F3 subscription, or F5 Security add-on
- Office 365 Enterprise E3 subscription
- Office 365 Enterprise E1 subscription
- Office 365 Education A1 subscription
- Office 365 Education A3 subscription

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b5e7518-641b-6d9c-da4f-90f268949793
* Version Independent ID: bae3450b-35b4-d942-7012-7867a705150d
* Content: [Microsoft 365 and Office 365 platform service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-platform-service-description)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for your comment. I have forwarded your request to the product and will keep you posted on the response. Thanks again!

**Comment by annferre** [comment]
Hi there, I received the below information from the product team. I'll be reaching out to the owner of the Auditing solutions in Microsoft 365 to get it updated. 
Basic Audit is in all of the M/O365 suites (including EDU, GCC, GCCH, DoD) except O365 F3. Specifically, O365 E1/G1/A1/E3/G3/A3/E5/G5/A5 and M365 F1/F3/A1/E3/G3/A3/E5/G5/A5/Business Basic/Business Standard/Business Premium. You can find the information in the following comparisons: 
[https://aka.ms/M365BusinessPlans](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2FM365BusinessPlans&data=04%7C01%7Cv-annhem%40microsoft.com%7C79c2f1a8e8ac4f886ba108d94e0fcc77%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637626652025884338%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ylaEKIXaMKzmIDDl6QBtVlkL8o6pBZkgc6ongyGpdRk%3D&reserved=0)

[https://aka.ms/M365EnterprisePlans](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2FM365EnterprisePlans&data=04%7C01%7Cv-annhem%40microsoft.com%7C79c2f1a8e8ac4f886ba108d94e0fcc77%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637626652025884338%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=de4WVBq68C4IWCQXw9j64EnYwcX6W9ubh7NgTojH%2Fwk%3D&reserved=0)

https://aka.ms/M365EduPlans

**Comment by annferre** [comment]
Hi there, I just wanted to let you know that the [Auditing solutions page](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description#features-available-to-some-plans) has been updated to reflect the following plans are covered for Basic Audit: 
Microsoft 365 Business Basic subscription
Microsoft 365 Apps for Business subscription
Microsoft 365 Enterprise E3 subscription
Microsoft 365 Business Premium
Microsoft 365 Education A3 subscription
Microsoft 365 Government G3 subscription
Microsoft 365 Government G1 subscription
Microsoft 365 Frontline F1 or F3 subscription, or F5 Security add-on
Office 365 Enterprise E3 subscription
Office 365 Enterprise E1 subscription
Office 365 Education A1 subscription
Office 365 Education A3 subscription
Let me know if you have any questions.
Thanks again for your comment.
