### ISSUE TITLE
Is shared mailbox feature available for F3+ExOK1 user? Can this F3+ExOK1 user become an admin of this shared mailbox?

### ISSUE THREAD

**Issue by Shimarisa** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#658]
[Enter feedback here]
Hi,

I am wondering if the shared mailbox can be used by F3+ExOK1 user, as one of our customers is considering to shared mailbox between F3 and E1 users. As per the docs, though the size limit exists, it seems that the customer do not need ExO license to access to the shared mailbox. 
> To access a shared mailbox, a user must have an Exchange Online license, but the shared mailbox doesn't require a separate license. 
(cited from the notes)

However, from the other source, I found the opposite statement.
https://www.microsoft.com/en-us/microsoft-365/exchange/microsoft-exchange-licensing-faq-email-for-business

> Exchange Online Kiosk is designed for users who require fewer messaging features because they do not have dedicated computers. The subscription provides 2 GB of mailbox space per user and web-based access through Outlook on the web. Certain features are disabled for Kiosk users, including inbox rules, public folder mailboxes, site mailboxes, **shared mailboxes,** and delegate access to other mailboxes. For more information, see the [Exchange Online service description](https://go.microsoft.com/fwlink/p/?LinkId=401232).

Could you confirm that the shared mailbox feature is available for ExO Kiosk users as well?
Thank you so much for your support!

Best,
Risa

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#storage-limits-across-standalone-plans)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for your comment. I forwarded your request to the product team and I'll keep you posted on their response. Thanks again!

**Comment by Shimarisa** [comment]
Hi @annferre, do you have any updates about this topic? I would like to clarify this topic by Wednesday. Thanks!

**Comment by annferre** [comment]
Hi Risa, our SME is out on vacation. I did however reach out to the Exchange team to see if anyone can help. I'll keep you posted. Thanks!

**Comment by annferre** [comment]
Hi Risa, closing the ticket per our email thread. Where the product team determined that "this is okay and is compliant with licensing." Thanks for reaching out.
