### ISSUE TITLE
Groups members limit

### ISSUE THREAD

**Issue by Justfyn** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#659]
The Azure AD Connect v2 now supports groups with 250.000 members: https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-sync-endpoint-api-v2

The exo limits should be updated to reflect that change as i see we are syncing groups into EXO with more than 100000 members:
`Maximum number of distribution group members | 100,000 members - https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#distribution-group-limits-1
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for your comment. I submitted a request to the product team and added you to the communication. Thanks again! I'll also post here when the change is live. Thanks again!

**Comment by annferre** [comment]
Hi there, I just wanted to let you know I received the below response from the team and we're in the process of updating the page. I'll let you know when the edit goes live. 
"-	We do not increase the supported DG/DL limit from 100,000; it stays there
-	The footnote should be changed to something like:

1 If you are using Azure Active Directory DirSync, the maximum number of distribution group members that you can synchronize from your on-premises Active Directory to Azure Active Directory is 15,000. If you are using [Azure AD Connect](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Factive-directory%2Fhybrid%2Fhow-to-connect-sync-endpoint-api-v2&data=04%7C01%7Cv-annhem%40microsoft.com%7Ca00ba1b107a842af868508da0d9b4a00%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637837257894753789%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HAFlnvJtWkWohYqULH6SywuBxy5RDdGXZuMH6ZgAzlE%3D&reserved=0), that number is 250,000, but the supported limit of distribution group members is still 100,000."

**Comment by annferre** [comment]
HI there, just letting you know the below change is live. Let me know if you have any questions. Thanks again for your comment.
After:


1 If you are using Azure Active Directory DirSync, the maximum number of distribution group members that you can synchronize from your on-premises Active Directory to Azure Active Directory is 15,000. If you are using [Azure AD Connect](https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fdocs.microsoft.com%2fen-us%2fazure%2factive-directory%2fhybrid%2fhow-to-connect-sync-endpoint-api-v2&data=04%7c01%7cv-annhem%40microsoft.com%7ca00ba1b107a842af868508da0d9b4a00%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637837257894753789%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000&sdata=HAFlnvJtWkWohYqULH6SywuBxy5RDdGXZuMH6ZgAzlE%3D&reserved=0), that number is 250,000, but the supported limit of distribution group members is still 100,000.
