### ISSUE TITLE
Data location for Exchange Online Archiving

### ISSUE THREAD

**Issue by mtrneny** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#66]
Can you please confirm that data stored in Exchange Online Archiving is located within the same location (data center) as Exchange online data? For our case - data is stored only in EU data centers. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e0ba987-5e52-0e0d-f9f8-d6da3feaa53c
* Version Independent ID: 5763ce54-2c7c-8956-f44e-c946d0c9a5c4
* Content: [Archive Features in Exchange Online Archiving](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-archiving-service-description/archive-features)
* Content Source: [Office365-ServiceDescriptions/exchange-online-archiving-service-description/archive-features.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-archiving-service-description/archive-features.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by prabita** [comment]
@mtrneny Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response

**Comment by SharS** [comment]
This information is in the [Archive Features in Exchange Online service description](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-archiving-service-description/archive-features): Archive mailboxes in Exchange Online Archiving are replicated to multiple database copies, in geographically dispersed Microsoft data centers, to provide data restoration capability in the event of a messaging infrastructure failure. For large-scale failures, business continuity management is initiated.

**Comment by mtrneny** [comment]
@SharS I read that but my concern is about this part "replicated to multiple database copies, in geographically dispersed Microsoft data centers". Our company is in EU and we need to comply with GDPR regulation (it is saying that our data must be stored only in EU region) so I need to have a confirmation that our data in "Archive" is stored in EU data centers only.
