### ISSUE TITLE
 Wrong licensing information - AIP

### ISSUE THREAD

**Issue by natlims18** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#660]
Hi, I was analyzing the licenses that have the Information Protection: Sensitivity labeling service included, in documentation contain the information that users of Office 365 F3 can use AIP, but in file attached Modern Work Plan Comparison the informations is different.

![image](https://user-images.githubusercontent.com/37196093/156649733-5d8125f5-8b64-4512-addb-090f90dd3e20.png)
![image](https://user-images.githubusercontent.com/37196093/156650076-e2108f68-c6fa-4b78-a7c5-90b39a778dd2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#information-protection)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc*
[Microsoft Modern Work Plan Comparison - Enterprise US ERP (1).pdf](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions/files/8181019/Microsoft.Modern.Work.Plan.Comparison.-.Enterprise.US.ERP.1.pdf)
*

**Comment by annferre** [comment]
Hi there, thank you for your comment. I reached out to the product team to confirm which is correct and based on their response I'll update the page and let you know when it goes live. Thanks again!

**Comment by annferre** [comment]
Thanks again for your comment. The page has been updated and F3 has been removed from the O365 bullet. Thanks again!
