### ISSUE TITLE
Business standard license showing  organization level 5 TB storage.  is business standard still qualifying plan for unlimited storage

### ISSUE THREAD

**Issue by robinpoulose1** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#661]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99ce1810-18cd-687b-0c8b-bfceb919225a
* Version Independent ID: 705cde78-7e58-c260-bde3-0b393747cdea
* Content: [OneDrive service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/onedrive-for-business-service-description)
* Content Source: [Office365-ServiceDescriptions/onedrive-for-business-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/onedrive-for-business-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by robinpoulose1** [comment]
![bug](https://user-images.githubusercontent.com/17806101/156855433-6ce39589-0456-49f7-b500-1ec05f2f90e2.PNG)
Attached screenshot where business standard shows 5TB storage at organizational level.  But there is no details about it in this article.

**Comment by annferre** [comment]
Hi there, apologies for the delay. I have reached out to the product team for assistance, and I'll keep you posted. Thanks!

**Comment by robinpoulose1** [comment]
> Hi there, apologies for the delay. I have reached out to the product team for assistance, and I'll keep you posted. Thanks!

Thanks !  Please do confirm if there was any loop holes which got fixed ? 
https://community.spiceworks.com/topic/1595399-how-to-increase-your-onedrive-storage-to-5tb

**Comment by robinpoulose1** [comment]
Do you have any update on this ?

**Comment by robinpoulose1** [comment]
> Hi there, apologies for the delay. I have reached out to the product team for assistance, and I'll keep you posted. Thanks!

do you have any update on this ?

**Comment by annferre** [comment]
Hi there, the product team is asking it were you able to run the diagnostic and update the settings (per the [docs webpage](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/storage/check-storage-increase-eligibility)) and after that your admin center still shows 5TB?

**Comment by annferre** [comment]
The product team stated: "the image you have shared is of the OneDrive admin center. 
Does it mean that after running the diagnostic and updating the settings ( as captured below from the docs webpage) your admin center still shows 5TB?"
![image](https://user-images.githubusercontent.com/86699727/177577485-ff268dd9-a709-43a3-a604-0aa924156c4b.png)

**Comment by annferre** [comment]
Please reopen if the image you have shared is showing 5TB after running the diagnostic and updating the settings.
