### ISSUE TITLE
Storage for small business plans are not covered 

### ISSUE THREAD

**Issue by robinpoulose1** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#662]
1 For information on OneDrive storage per user, check OneDrive in the [Modern Work Plan Comparison](https://go.microsoft.com/fwlink/?linkid=2139145).

The link does not provide details for Small business plans.  It just talk about standalone plans and Enterprise
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99ce1810-18cd-687b-0c8b-bfceb919225a
* Version Independent ID: 705cde78-7e58-c260-bde3-0b393747cdea
* Content: [OneDrive service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/onedrive-for-business-service-description?redirectedfrom=MSDN)
* Content Source: [Office365-ServiceDescriptions/onedrive-for-business-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/onedrive-for-business-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for your comment. We'll be adding the below link to the OneDrive Service Description page. I'll let you know when the link is live. Thanks again!
1 For information on OneDrive storage per user, you can check OneDrive in the [Modern Work Plan Comparison](https://go.microsoft.com/fwlink/?linkid=2139145) or the [M365 User Subscription Suites for Small and Medium-sized Businesses](https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2faka.ms%2fM365BusinessPlans&data=04%7c01%7cv-annhem%40microsoft.com%7c79c2f1a8e8ac4f886ba108d94e0fcc77%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637626652025884338%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=ylaEKIXaMKzmIDDl6QBtVlkL8o6pBZkgc6ongyGpdRk%3D&reserved=0).

**Comment by annferre** [comment]
I just wanted to let you know the update is live. Thanks again for your comment!
