### ISSUE TITLE
Vocabulary: "Record policy" and "record label" and "retention policy" and "retention label"

### ISSUE THREAD

**Issue by chuckpiot** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#663]
The chart for GCChigh regarding records management, it appears to use "record label" and "record policies" synonymously.  Is that the intent? Or is "record policy" supposed to be "retention policy"?

In compliance center, Microsoft uses "Retention Policy" for information governance and "record label" for records management. These are two separate functions and are not synonymous. MSFT Compliance Center  does not use the term "record policy" in the Information Governance or the Records Management solutions. (At least, I don't this it does!) 

![image](https://user-images.githubusercontent.com/11818421/157137591-5eb027b0-0dca-4d23-9415-2ebd7a11a83b.png)

Thanks! 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6a73833-f8b4-c9d2-d516-5b9fc62ce5a3
* Version Independent ID: 82ba6e0c-4da4-5d3d-1d35-032d63aac1e6
* Content: [Plan for Microsoft 365 compliance - GCC High - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/plan-for-m365-compliance-gcc-high)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/plan-for-m365-compliance-gcc-high.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/plan-for-m365-compliance-gcc-high.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, I just wanted to reach out to let you know that we're in the process of updating the documentation. I'll let you know when the changes are live. Thank you for your comment!
