### ISSUE TITLE
Is "Inactive mailboxes" included in M365 F3? 

### ISSUE THREAD

**Issue by olthomps** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#664]
Is "Inactive mailboxes" included in M365 F3? This contradicts the public licensing information here: 
https://go.microsoft.com/fwlink/?linkid=2139145

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2f622a7-32c1-2c35-2df9-ddf1bc74c74d
* Version Independent ID: e37d85d2-8b81-0c64-b7d0-1e8c01b303db
* Content: [Exchange Online service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description#feature-availability-across-exchange-online-standalone-plans)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your comment. I have reached out to the product team for confirmation, and I'll keep you posted on the response. and update to the page. Thanks again!

**Comment by annferre** [comment]
Hi there, we will be updating the page to the below. I'll keep you posted as to the status. Thanks again for your comment.
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/v-annhe/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=Preview
href="file:///C:/Users/v-annhe/AppData/Local/Temp/msohtmlclip1/01/clip_preview.wmf">

<link rel=themeData
href="file:///C:/Users/v-annhe/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/v-annhe/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>




Feature | Description | Microsoft 365 Business Basic, Business Standard | Microsoft 365 Business Premium | Office 365 E1 | Microsoft 365 E3/E5 & Office 365 E3/E5 | Microsoft 365 F3 & Office 365 F3 | Exchange Online Plan 2 | Exchange Online Plan 1 | Exchange Online Kiosk
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Recipients | Inactive mailboxes | No | No | No | Yes | No | Yes | No | No

**Comment by annferre** [comment]
Hi there, several edits have been made to the page including the one above. Let me know if you have any questions. Thanks again for your comment.
