### ISSUE TITLE
Add meeting invite limits

### ISSUE THREAD

**Issue by JasenHicks7** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#665]
It would be nice to see the meeting invite limits listed on this page that are in the below document.

https://support.microsoft.com/en-us/office/scheduling-meetings-with-hundreds-of-attendees-f8cce35d-673e-41a0-8aea-dc5331bb60ed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits?redirectedfrom=MSDN)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your comments. I have reached out to the product team and I'll keep you posted on response and update to the page. Thanks again!

**Comment by annferre** [comment]
Hi there, I just wanted to let you know the meeting invite limits have been added to the page. Let me know if you have any questions. Thanks again for your comment.
<img width="461" alt="image" src="https://user-images.githubusercontent.com/86699727/159071938-e6d0603c-622a-47ce-b356-e134b9fb9daa.png">
