### ISSUE TITLE
Microsoft Defender for Identity doesn't have info for Identity

### ISSUE THREAD

**Issue by coderlicious** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#666]
The Microsoft Defender for Identity section doesn't have information for Microsoft Defender for Identity. The contents look like they are just a copy+paste from Microsoft Defender for Business section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#feedback)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your comment. There are two sections for Microsoft Defender for Identity. The second one is correct. We are removing the first one and I'll you know when the edit is live. Thanks!

**Comment by annferre** [comment]
Hi there, I just wanted to let you know this has been corrected. Thanks again for your comment.
