### ISSUE TITLE
Page Head has "[ServiceDesc]" Visible

### ISSUE THREAD

**Issue by MatthewMcD** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#67]
The formatting on this page is broken. See the "[ServiceDesc]" in the title.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 317e4152-691a-7ac9-8fef-2225b00b4c02
* Version Independent ID: 7178b047-40c0-f7c7-e547-954cdc920b3a
* Content: [Sites\[ServiceDesc\]](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sites-servicedesc)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sites-servicedesc.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sites-servicedesc.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by prabita** [comment]
Fixed
