### ISSUE TITLE
Microsoft Defender for Endpoint Server confusing

### ISSUE THREAD

**Issue by rtrigueiro** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#670]
Hi team,

in this article is mentioned that for Microsoft Defender for Endpoint Server, a customer need a combined minimum of 50 licenses of Microsoft Defender for Endpoint.
Is this a combined of MDE Plan 1 and Plan 2 or is it combined from the P2 enabling licenses (Win 10/11 E5/A5, M365 E5/A5/G5, M365 E5/A5/G5/G5 Security, M365 F5 Security) ?

Also, from the MDE (server) [Product Terms](https://www.microsoft.com/licensing/terms/productoffering/MicrosoftDefenderforEndpointServer/EAEAS) it is  mentioned the following:
"Customers with a combined minimum of 50 licenses for one or more of the following may acquire Microsoft Defender for Endpoint (server) licenses (one per covered Server [OSE](https://www.microsoft.com/licensing/terms/product/Glossary/all)): Microsoft Defender for Endpoint (per user), Windows E5/A5, Microsoft 365 E5/A5 and Microsoft 365 E5 Security User SLs."

So it would ne nice to be very clear on the documentation if MDE P1 also contributes for the 50 license counting for Server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#microsoft-defender-for-endpoint)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your comment. I have reached out to the product team, and I'll get back to you as soon as I hear from them. Thanks again!

**Comment by annferre** [comment]
Hi Ricardo, at the moment we are unable to make changes to the page, however I will reopen the ticket as soon as we're able. Reach out to me if you have any questions. Thanks!

**Comment by annferre** [comment]
Reopening to address the question.

**Comment by annferre** [comment]
Hi there, this section has been rewritten. Please reopen if you have further concerns/questions. Thanks again for your comment.
