### ISSUE TITLE
This doesn't really include all the license types

### ISSUE THREAD

**Issue by mattdreher** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#671]
It shows the licensing for Office 365 E1 and E3 and Microsoft Business plans but doesn't show the licensing for Microsoft 365 E3 and E5 plan so I am not sure what sizes are included in those plans.

I am specifically referring to these plans.
https://www.microsoft.com/en-us/microsoft-365/compare-microsoft-365-enterprise-plans

If these are the same as the Office 365 E1 and E3 plans, it should at least have a note to indicate that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#storage-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, I have reached out to the product team, and I'll keep you posted on their response. Thanks for your comment!

**Comment by annferre** [comment]
Hi there, we've updated the tables to include the new columns. Please reopen if you still have questions. Thanks again for you comment.
