### ISSUE TITLE
eDiscovery Holds

### ISSUE THREAD

**Issue by Bueltmann** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#672]
[Enter feedback here]

Documentation is confusing (and potentially inaccurate).  Feature Grid shows eDiscovery Holds are available in EXO Kiosk License.  My team and I had expectation that EXO Kiosk only includes eDiscovery Searches and not Holds.  If we did add Holds to the Kiosk license it is surprising that they would not also be included in M365 F3 (which includes EXO Kiosk) or EXO P1 which should have more features than the Kiosk version---

![EXO Service Description Grid](https://user-images.githubusercontent.com/66739918/161122224-38c58b9d-0099-4668-a9cb-af412157fa4c.png)

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2f622a7-32c1-2c35-2df9-ddf1bc74c74d
* Version Independent ID: e37d85d2-8b81-0c64-b7d0-1e8c01b303db
* Content: [Exchange Online service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
HI there, I did get confirmation for the below update. I will let you know when it goes live. Thanks!
<img width="486" alt="image" src="https://user-images.githubusercontent.com/86699727/163863641-a98d6044-91ee-4f11-9ba3-519f64fc761b.png">

**Comment by annferre** [comment]
Hi there, the edit is live. Please reopen if you have any questions. Thanks again for your comment!
