### ISSUE TITLE
Exchange Online Receiving limits

### ISSUE THREAD

**Issue by riohedfield** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#673]
Hello,

Regarding the receiving limits here: 
https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#receiving-limits

I have these 2 requests, please have a look:

1. Can you please adjust the naming of the limits to not have any confusion between what's in the table and the description above it.
For example:
- In the description we have "Receiving limit" and in the table we have "Messages received".
- In the description we have "Sender-recipient pair limit" and in the table we have "Messages received from single sender".

2. Regarding the 2nd limit "Messages received from single sender", it is mentioned "33% of messages received", does that mean it should be always 33% of the 3,600 messages received last 60 mins or it's a 33% of all messages received last 60 mins regardless the total number of messages received last 60 mins whether it was 3,600 or not ? could you please adjust with more precision in the description above the table in the article as well ?

BR
Ribo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, I spoke with the product team, and I'll be updating the page to the following:
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/v-annhe/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/v-annhe/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/v-annhe/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>


<p class=MsoNormal><span style='font-family:"Segoe UI Light",sans-serif;
mso-bidi-font-family:"Times New Roman"'>After:<o:p></o:p></span></p>



Feature | Microsoft 365 Business Basic | Microsoft 365 Business Standard | Microsoft 365 Business Premium | Office 365 Enterprise E1 | Office 365 Enterprise E3 | Office 365 Enterprise E5 | Office 365 Enterprise F3
-- | -- | -- | -- | -- | -- | -- | --
Messages received Receiving limit | 3,600   messages per hour | 3,600   messages per hour | 3,600   messages per hour | 3,600   messages per hour | 3,600   messages per hour | 3600   messages per hour | 3600   messages per hour
Messages   received from single sender | 33% of messages receivedreceiving   limit | 33% of messages receivedreceiving   limit | 33% of messages receivedreceiving   limit | 33% of messages receivedreceiving   limit | 33% of messages receivedreceiving   limit | 33% of messages receivedreceiving   limit | 33% of messages receivedreceiving   limit



<p class=MsoNormal><span style='font-family:"Segoe UI Light",sans-serif;
mso-bidi-font-family:"Times New Roman"'><o:p>&nbsp;</o:p></span></p>


</body>

</html>

**Comment by annferre** [comment]
Hi there, I just wanted to let you know the change is live. Let me know if you have any questions. Thanks again for your comment.

**Comment by riohedfield** [comment]
Thank you for the adjustments made on the article, but I still think that the description for "sender-recipient pair limit" (Messages received from single sender) is misleading because the limit is simply 1188 (33% of the 3600) per hour regardless the recipient received 3600 emails during that hour or not, which is what I was thinking at the beginning.

Best regards

**Comment by annferre** [comment]
Thanks for the response. Sorry for the delay. I forwarded your request to the product team.

**Comment by annferre** [comment]
Hi there, I received the below response from the product team:
The current description says below-

 
![image](https://user-images.githubusercontent.com/86699727/194612479-081ca45a-11b5-403f-a1dc-5f38c3f9d043.png)


It is 33% of Overall receiving limit and that is clearly mentioned in the Article (screenshot above), but it is not 33% of 3600. This limit is applicable even if the hourly receiving limit has not been reached.

**Comment by annferre** [comment]
Please reopen if you have further questions
