### ISSUE TITLE
More clarity on content explorer

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#674]
referring to this sentence:
Microsoft 365 E3/A3/G3 and Office 365 E3/A3/G3 allow users to benefit from **Content Explorer data aggregation** only.
in section: 
https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#which-licenses-provide-the-rights-for-a-user-to-benefit-from-the-service-8

I can find no information anywhere on what Content Explorer **data aggregation** means. As this is the only feature available to E3 users this documentation would benefit from an explanation of exactly what that means

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, I have reached out to the product team, and I'll keep you posted on their response. Thanks for your comment!

**Comment by brsieff** [comment]
Hello are there any updates on this? I have the same question

**Comment by annferre** [comment]
Hi there, apologies for the delay. The product team responded saying "The aggregation for E3 means there is only numbers shown, as in how many document per Exchange or SharePoint etc. that contain the selected sensitive information type. But you won't be able to drill down and see the details. You just see the total number on the aggregate level."

**Comment by annferre** [comment]
Please reopen if you still have questions. Thanks again for your post.

**Comment by cabailey** [comment]
@annferre It would be helpful if this explanation was included on the page.  I also didn't know what "data aggregation" meant in practice.
