### ISSUE TITLE
Is the shared mailbox feature available for Exchange Online users of Teams Essentials (AAD Identity)?

### ISSUE THREAD

**Issue by nhonda23** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#675]
Hi,

One of our customers is considering **sharing mailboxes with Exchange Online in Teams Essentials (AAD Identity) and E1 users**, and it is stated that shared mailboxes are disabled for ExOK1 users as follows. Does Exchange Online in Teams Essentials (AAD Identity) have the same limitations as ExOK1?

https://www.microsoft.com/en-us/microsoft-365/exchange/microsoft-exchange-licensing-faq-email-for-business

>Exchange Online Kiosk is designed for users who require fewer messaging features because they do not have dedicated computers. >The subscription provides 2 GB of mailbox space per user and web-based access through Outlook on the web. Certain features are >disabled for Kiosk users, including inbox rules, public folder mailboxes, site mailboxes, **shared mailboxes**, and delegate access to other >mailboxes. For more information, see the [Exchange Online service description] (https://go.microsoft.com/fwlink/p/?LinkId=401232).``

**Comment by nhonda23** [comment]
We received a response that shared mailboxes are available in ExOK1 through the following cases.
[https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions/issues/658#issuecomment-1055757580](url)

I will change the question.
Is Exhange Online available in Teams Essentials (AAD Identity) considered the same as ExOK1?

**Comment by annferre** [comment]
Hi there, apologies for the delay. I received the following information from the product team: Teams Essentials AAD includes Exchange Online Kiosk (EXO K). There is no number after it, there is only one Exchange Online Kiosk. EXO K includes Shared Mailboxes. Please reopen the ticket if you have further questions. Thanks for your comment!
