### ISSUE TITLE
Subscriptions for fewer than five users received 1 TB of OneDrive storage that cannot be expanded.

### ISSUE THREAD

**Issue by robinpoulose1** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#677]
Please clarify  the statement or elaborate :
1. Does that means, if we have  less than 5 Subscription of E3 or E5 then we cannot expand the to 5 TB 
2. Or is this statement for SharePoint online Plan 2 standalone license, if we have less than 5 subscription we get only 1TB storage 

I have follow up question 

What if we have 2 E3 license 2 E5 License and 1 Sharepoint Online plan 2 license , in such case are we eligible for 5 TB storage since I have different set of qualifying plan or it should be same subscriptions??? 

What about the OneDrive online Plan 2 standalone license,  this is not covered anywhere in the service description article. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99ce1810-18cd-687b-0c8b-bfceb919225a
* Version Independent ID: 705cde78-7e58-c260-bde3-0b393747cdea
* Content: [OneDrive service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/onedrive-for-business-service-description)
* Content Source: [Office365-ServiceDescriptions/onedrive-for-business-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/onedrive-for-business-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, I have reached out to the product team and I'll keep you posted on response. Thanks for your comment. Cheers!

**Comment by dsghi** [comment]
It would be great to see official documentation regarding the question above. However, I can confirm a tenant with only a single OneDrive online Plan 2 license does receive the 5 TB quota for the assigned user.

**Comment by annferre** [comment]
Hi there, I still don't have an answer regarding which plans are part of the 5-user count, but I do have OneDrive plan 2 listed here.: https://learn.microsoft.com/en-us/archive/blogs/educloud/increase-onedrive-for-business-storage-to-5tb
