### ISSUE TITLE
Clarity around server licensing for MDE

### ISSUE THREAD

**Issue by Steve-MS** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#678]
We refer to licensing for Microsoft Defender for Endpoint being an add-on, but this isn't clear from a customer point of view that this isn't included.
The wording instead should be:

"Microsoft Defender for Endpoint Server is an additional cost for customers with a combined minimum of 50 licenses of Microsoft Defender for Endpoint."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#microsoft-defender-for-endpoint)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, I have reached out to the product team and I'll keep you posted on response. Thanks for your comment. Cheers!

**Comment by annferre** [comment]
Hi there, the following new text has been published. Thanks for the comment.
<img width="468" alt="image" src="https://user-images.githubusercontent.com/86699727/163439587-9eda38c3-42d9-426e-80c6-0b115726901b.png">
