### ISSUE TITLE
TechCon: The linked URL is displayed https://go.microsoft.com/fwlink/?linkid=2144147> (Office365)

### ISSUE THREAD

**Issue by cdowling1971** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#679]
**Description:** A Microsoft MVP reported an issue to the C&AI team with this article issue - please make the necessary fix, thankyou. 

<The linked URL is displayed https://go.microsoft.com/fwlink/?linkid=2144147> (Office365) 

![image](https://user-images.githubusercontent.com/29043399/162731933-1724c5c4-77bb-495c-b187-8aaa7e1a3775.png)

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b65730b-7010-60f8-0b50-5a6c8a4970bd
* Version Independent ID: e07b0622-0e4f-1883-b045-ca4097b3c333
* Content: [User account management - Service Descriptions](https://review.docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/user-account-management?branch=main)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/user-account-management.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/main/Office365-ServiceDescriptions/office-365-platform-service-description/user-account-management.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by cdowling1971** [comment]
FYI @TinaMcN

**Comment by annferre** [comment]
Hi there, thank you for your comment. I have updated the page and the change will go live today at 3:30. Thanks again!

**Comment by annferre** [comment]
Hi there, I just wanted to let you know the link has been update. Thank you for your comment. Let me know if you have anything further.
