### ISSUE TITLE
Table of Contents

### ISSUE THREAD

**Issue by jamiee4lynne** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#680]
[I love this docs page! However, I think it could be even better by slightly adjusting the table of contents. Although they seem to be in alphabetical order, the Defender solutions all have the term "Microsoft" in front of them so if one isn't paying attention to the table of contents I've seen people get lost. The information itself is fantastic I just think that might be better to organize the topics. Thanks!  ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance?source=docs#information-governance)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for your comment. I have forwarded your request to the product team. I'll keep you posted on reply. Thanks again.

**Comment by annferre** [comment]
Hi there, I just wanted to let you know that we updated the table of contents. It is now in alphabetical order assuming all products are Microsoft. Please reopen the ticket if you have anything further. Thanks again for your comment. It is greatly appreciated!

**Comment by jamiee4lynne** [comment]
You just made my day!! Small changes can make a huge difference, thank you!

Jamie L. Cohen-Gronberg
Digital Technical Specialist
Modern Work Canada
***@***.******@***.***>
[Microsoft]
