### ISSUE TITLE
Tap to find and reuse content

### ISSUE THREAD

**Issue by rramdoyal** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#681]
[Tap to find and reuse content
This feature is available for Business Premium, E3 and E5
But on the table it says Business Standard, E3 and E5
Please check and make amendment]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 128805e7-b1a4-5cdf-1890-8794fa46d5d5
* Version Independent ID: 884c3ae0-9317-d37c-f94f-97aabd0e622d
* Content: [Office applications service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-applications-service-description/office-applications-service-description?msclkid=cbc13559ba8611ec981a9e2ee8d169a0)
* Content Source: [Office365-ServiceDescriptions/office-applications-service-description/office-applications-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-applications-service-description/office-applications-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, I have reached out to the product team and I'll keep you posted on response. We are in the process of updating the page, so it might take a little time to get back to you. Thank you for your comment.

**Comment by annferre** [comment]
Hi there, the column is for Business Standard and Business Premium. The row says "yes" with a footnote that states it is for Business Premium only. Please reopen if you have further questions. Thanks again for your comment.
