### ISSUE TITLE
GCCH availability

### ISSUE THREAD

**Issue by J227668** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#683]
I have heard conflicting statements whether this is available in GCCH. Can you please add a statement to this document of whether this service is or is not available in GCCH?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 929f5194-b49a-1d9c-1777-a4d34a720068
* Version Independent ID: 44e5b986-fd93-75de-10e2-b6802f8e3e27
* Content: [Microsoft Project Online service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/project-online-service-description/microsoft-project-online-service-description)
* Content Source: [Office365-ServiceDescriptions/project-online-service-description/microsoft-project-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/project-online-service-description/microsoft-project-online-service-description.md)
* Product: **office-online-server**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for your comment. Can you confirm you are referring to Microsoft Project Online, or is it one of the features you are referring to? Thanks again!

**Comment by J227668** [comment]
Correct Microsoft Project Online. I did not see any reference stating that it WAS available in GCCH.

**Comment by annferre** [comment]
Thanks! I've reached out to the project team to see if they have information. Thanks again!

**Comment by annferre** [comment]
Hi there, I received a response from the product team: Project Online is available. Project for the web is not. Project is a separate SKU from O365 offerings. I'm working with the team on how to update the text. Thanks again for your comment.

**Comment by annferre** [comment]
Hi there, I just wanted to let you know the page has been updated to reflect the response. Please reopen if you still have questions.
