### ISSUE TITLE
Clarify basic organization-wide or location-wide mailbox retention policy license requirements for Shared Mailboxes

### ISSUE THREAD

**Issue by ma261065** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#684]
Can you please clarify basic organization-wide or location-wide mailbox retention policy license requirements for Shared Mailboxes?

As shared mailboxes by default don't require a license, it's not clear whether a customer must add a license to their shared mailboxes to make use of a basic organization-wide or location-wide mailbox retention policy that includes shared mailboxes.

The documentation does make it clear that a license is required for a shared mailbox if a customer is using "automatic retention policies", which I believe is referring to adaptive retention policies, but this is not the same as the scenario above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, I've reached out to the product team and cc'd you on the thread. Thank you for your comment.

**Comment by annferre** [comment]
Hi there, the page has been updated with the information below. Please reopen if you still have questions.

Additionally, shared mailboxes are limited to 50 GB without the need for an Exchange add-on. To increase the size limit to 100 GB, the inactive mailbox requires Exchange Online Plan 2 or Exchange Online Archiving + Exchange Online Plan 1.

**Comment by annferre** [comment]
Hi there, the page has been updated with the information below. Please reopen if you still have questions.

Additionally, shared mailboxes are limited to 50 GB without the need for an Exchange add-on. To increase the size limit to 100 GB, the inactive mailbox requires Exchange Online Plan 2 or Exchange Online Archiving + Exchange Online Plan 1.
