### ISSUE TITLE
Updated 2022 Service health and continuity numbers

### ISSUE THREAD

**Issue by DataHam** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#686]
I'm looking for the updated 2022 Service health and continuity numbers for Q1 2022

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76358610-0b3b-49d9-6e6a-0b334b19d795
* Version Independent ID: 66466964-caa5-cded-20a6-627495521904
* Content: [Service health and continuity - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/service-health-and-continuity)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/service-health-and-continuity.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/service-health-and-continuity.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for your request. I've reached out to the product team, and I'll let you know when I have a response. Thanks again!

**Comment by annferre** [comment]
Hi there, Q1 2022 uptime input is: 99.99%. We'll be updating the page. Please reopen if you have further questions.

**Comment by DataHam** [comment]
Wow, that was fast. You are amazing. Thank you
