### ISSUE TITLE
ErrorQuotaExceeded when requesting Inbox messages via API

### ISSUE THREAD

**Issue by jonfdaily** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#69]
When making a request via the Outlook API, we are getting this response back for one specific user. This is the error returned:

request: `GET https://outlook.office365.com/api/beta/Me/MailFolders/Inbox/messages?%24filter=ReceivedDateTime+ge+2019-02-19`
response: `403 "error :{ "code":"ErrorQuotaExceeded", "message":"Cannot save changes made to an item to store."}`

I cannot find any indication as to what this error means or how to resolve it. It appears to be account specific, but I can't find any limits based on API use in documentation, and the owner of the account has indicated that his account functions normally outside of this API request issue.

Any suggestions on what could be causing this issue?

**Comment by SKjerland** [comment]
@jonfdaily - Please reach out to one of our experts at the [Answer Desk](https://support.microsoft.com/en-us/contactus/), or ask the [Microsoft Community](https://answers.microsoft.com/en-us/msoffice/forum) for help.
