### ISSUE TITLE
Defender for Office 365 feature scoping to licensed users

### ISSUE THREAD

**Issue by Aegrum** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#690]
[Enter feedback here]
The following section about scoping the features of Defender for Office 365 to only users licensed for the service punches out to two links, neither of which discuss how to accomplish this. Both the Safe Links and Safe Attachments pages make no mention of ways to limit the use benefits to only those licensed.

> How can the service be applied only to users in the tenant who are licensed for the service?
To scope Microsoft Defender for Office 365, follow the Safe Links and Safe Attachments deployment policies:
> - For information on configuring Safe Links for licensed users, see [Safe Links in Microsoft Defender for Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/atp-safe-links).
> - For information on configuring Safe Attachments for licensed users, see [Safe Attachments in Microsoft Defender for Office 365](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/atp-safe-attachments).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#how-can-the-service-be-applied-only-to-users-in-the-tenant-who-are-licensed-for-the-service-20)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, I have reached out to the Security & Compliance team regarding your question, and I'll keep you posted on the response. Thank you for your comment.

**Comment by annferre** [comment]
Hi there, I received a response from the product team, and we are in the process of changing the page/section to the below: 
**How can the service be applied only to users in the tenant who are licensed for the service?**
The default selection is to scope Defender for Office 365 policies to all users in the organization. But during or after setup, you can change the policy assignment to specific users, groups, or email domains. For more information regarding Defender for Office 365 please see [Microsoft Defender for Office 365 security documentation | Microsoft Docs](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/?view=o365-worldwide)

**Comment by Aegrum** [comment]
Sorry, but that conflicts with the fact that several of the features within Defender for Office 365 can **only** be enabled at a tenant level. So the statement "you can change the policy assignment to specific users, groups, or email domains" can be either correct or incorrect depending on what feature within Defender for Office 365 you are talking about. Referring to the generic documentation landing page does not yield any answer to this question.

**Comment by annferre** [comment]
Hi there, the product team is reaching out to the BP team to see if they can get assistance with this. The above change has been put on hold, and I'll get back to you as soon as we have more information. If you have any suggestions, we can look into those as well. Thanks again!

**Comment by annferre** [comment]
Hi there, the text has been updated to the below. Please reopen the ticket if you have further questions.
TO: 


How is the service provisioned/deployed?

By default, Microsoft Defender for Office 365 features are enabled at the tenant level for all users within the tenant. For information on configuring Microsoft Defender for Office 365 policies for licensed users, see [Microsoft Defender for Office 365](https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fdocs.microsoft.com%2fen-us%2fmicrosoft-365%2fsecurity%2foffice-365-security%2foffice-365-atp&data=05%7c01%7cTiffany.Gilbert%40microsoft.com%7cdbc8f1aad56941eb47f708da81464bd1%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637964436169931157%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000%7c%7c%7c&sdata=4rQiSmuUgea2XgFt9QMh1NDbGrPcwHX5kzbNIkTionE%3D&reserved=0).

For information on configuring Safe Links for licensed users, see [Safe Links in Microsoft Defender for Office 365](https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fdocs.microsoft.com%2fen-us%2fmicrosoft-365%2fsecurity%2foffice-365-security%2fatp-safe-links&data=05%7c01%7cTiffany.Gilbert%40microsoft.com%7cdbc8f1aad56941eb47f708da81464bd1%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637964436169931157%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000%7c%7c%7c&sdata=9CKYCWdUqwvpOq3aOhWy%2fcg%2B0d53NJV8SNFawQhhWjM%3D&reserved=0).
For information on configuring Safe Attachments for licensed users, see [Safe Attachments in Microsoft Defender for Office 365](https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fdocs.microsoft.com%2fen-us%2fmicrosoft-365%2fsecurity%2foffice-365-security%2fatp-safe-attachments&data=05%7c01%7cTiffany.Gilbert%40microsoft.com%7cdbc8f1aad56941eb47f708da81464bd1%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637964436169931157%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000%7c%7c%7c&sdata=kdgsGWhuFguQDuvEkWLUJ5Gnn1cWpOm%2Bq2q8vp%2fU3gE%3D&reserved=0).
