### ISSUE TITLE
Inconsistencies for Exchange Online Plan 2 including/not including DLP

### ISSUE THREAD

**Issue by brsieff** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#691]
Hello, I've noticed some inconsistencies regarding Exchange Online Plan 2 and DLP. I am seeing conflicting information throughout Microsoft docs articles with some indicating [DLP is offered as long as you have one Exchange Online Plan 2 license in your tenant](https://docs.microsoft.com/en-us/exchange/security-and-compliance/data-loss-prevention/data-loss-prevention#installation-prerequisites) whereas other articles [[1](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#microsoft-purview-information-protection-data-loss-prevention-dlp-for-exchange-online-sharepoint-online-and-onedrive-for-business)] [[2](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description#features-available-to-some-plans)] are showing that DLP is not included as part of Exchange Online Plan 2. Was hoping to get the correct answer for this to determine which is the source of truth. Thanks in advance!

**Comment by annferre** [comment]
Hi there, I received confirmation from the product team that DLP is included in Exchange Online Plan 2. We will be updating the page. Thank you for your comment.
