### ISSUE TITLE
Feature matrix out of date

### ISSUE THREAD

**Issue by GitWesDone** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#692]
many of the features listed as "No" in the GCC column are actually there now.  
This matrix should get updated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3ab3187-c403-8fb1-6ee7-56818777fdad
* Version Independent ID: f6b28482-bf80-436e-cb8f-facb974c24ec
* Content: [Office 365 US Government - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for your comment. I have reached out to all the product teams to get verification. I'll keep you posted on the responses. Since there are quite a few teams involved, it would help to know which ones you specifically saw that were wrong, and we can get those updated first. Thanks again.

**Comment by GitWesDone** [comment]
- There is a form of MyAnalytics in GCC
- "Power Map for Excel" I believe is now called 3D Maps and is in GCC
- 3D models are available in all the core office apps
- PowerPoint Presenter Coach
- possibly others

**Comment by annferre** [comment]
Hi there, we're still working on going through all of the features. For the ones you mentioned, this is the status:
-	waiting for information regarding MyAnalytics and Power Maps.
-	3D models are available in each env for win32 apps (not in Office Online).
-	Also waiting to hear back about Presenter.

**Comment by SeanGit88** [comment]
Hello,  This matrix has been updated and the changes are live.  thank you
