### ISSUE TITLE
Who are "All Users"?

### ISSUE THREAD

**Issue by Kazzan** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#693]
Hi, can you please specify who are the "All Users" there? Are these the internal users and not guests, or the standard licensed objects? Because guests can access Teams or SharePoint for example.

Because for example Shared Mailbox is licensed by access of user with assigned license. To time when no license is assigned to mailbox, it does need it.

Do you want to link this page or update these data also to [Microsoft 365 guidance for security & compliance](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#microsoft-defender-for-office-365) which state only high level enabling for licensed users?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 502796e9-ca73-7123-7719-c7b5b1042b7b
* Version Independent ID: 2929af88-6d56-4de3-2b4e-4e1d0e4d97ef
* Content: [Microsoft Defender for Office 365 service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description)
* Content Source: [Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi Petr, thank you for your comment. I have forwarded your request/question to the product team. I'll keep you posted on it. Thanks again!

**Comment by annferre** [comment]
Hi Kazzan, I received the following response from the product team. Reopen if you have further questions.
Guest requires a user license. Typically Defender products offer flexibility that customers can purchase additional user licenses and assign them to their vendors, suppliers for their business operations purpose.

**Comment by Kazzan** [comment]
Hi, so by this PG mean "physical users" like single person? Every? So, internal "AAD = Member" and external "AAD = Guest". I think this needs to be clarified somewhere, because for example Guest does not need license to get MFA, because AAD Premium for one internal license five external, or I can use Azure licensing. So, for example, Shared Mailbox does not need license for Exchange at all. But does it need Defender for Office 365 license if I license all the people accessing this mailbox?
