### ISSUE TITLE
MDI Documentation - License - Wording causes miss-understanding. 

### ISSUE THREAD

**Issue by tareqmusmar** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#695]
In the following two sections, the wording can be made more clear. Current wording makes the client think that we can limit the MDI license consumption to specific users while that is not true.

```
How is the service provisioned/deployed?
Microsoft Defender for Identity features are enabled at the tenant level for all users within the tenant. For information on configuring Microsoft Defender for Identity, see [Create your Microsoft Defender for Identity instance](https://docs.microsoft.com/en-us/defender-for-identity/install-step1).

How can the service be applied only to users in the tenant who are licensed for the service?
Microsoft Defender for Identity services aren't currently capable of limiting capabilities to specific users. Note that in scenarios where one user may have multiple accounts in Active Directory, for example, different administrative accounts for different domains/forests, the requirement is to only have one license for this one person.

Similarly, there is no requirement to license service accounts, or any account that facilitates automation. Only human users need to be licensed.

```

Original:

```
How is the service provisioned/deployed?
By default, Microsoft Defender for Identity features are enabled at the tenant level for all users within the tenant. For information on configuring Microsoft Defender for Identity, see [Create your Microsoft Defender for Identity instance](https://docs.microsoft.com/en-us/defender-for-identity/install-step1).

How can the service be applied only to users in the tenant who are licensed for the service?
Microsoft Defender for Identity services aren't currently capable of limiting capabilities to specific users. You must license every user you intend to benefit. Note that in scenarios where one user may have multiple accounts in Active Directory, for example, different administrative accounts for different domains/forests, the requirement is to only have one license for this one person.

Similarly, there is no requirement to license service accounts, or any account that facilitates automation. Only human users need to be licensed.

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#microsoft-defender-for-identity)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your comment. I have reached out to the product team regarding your request, and I'll let you know when I receive a response. Thanks!

**Comment by annferre** [comment]
Hi there, I received a response from the product team and for now we will be removing the below, but they will also be looking into the info about the service accounts. Thank you for your comment.
Removing:
Similarly, there is no requirement to license service accounts, or any account that facilitates automation. Only human users need to be licensed.

**Comment by annferre** [comment]
Hi there, the text was removed. I'll keep you updated regarding the answer to the service accounts question.

**Comment by annferre** [comment]
Hi again, we've also updated the text to the below. Thank you for your comment. Please reopen if you have further questions.

 AFTER:

How can the service be applied only to users in the tenant who are licensed for the service?

Microsoft Defender for Identity services are currently not capable of limiting capabilities to specific users. Efforts should be taken to limit the service benefits to licensed users.
