### ISSUE TITLE
Viva is not here - only Viva learning

### ISSUE THREAD

**Issue by emilylait** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#696]
Hi there.
Viva is a bigger conversation in education lately. In the Education SKUs, there seems to be some parts of Viva included (connections, some of insights, none of topics and some of learning). As there are bits and pieces of Viva in EDU SKUs and some not included, it would be great to make that clear in the edu service description. It mentions only Viva learning so far and just says NO, where as that is incorrect i believe, SOME of learning is available in the SKU, some of it is not. Can this be updated correctly with all Viva components and notes made if some are partially included etc.
Thank you
Em

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8328da3-5093-09b6-9b9b-b92d13625219
* Version Independent ID: f2171de5-bfa5-65d1-4615-30db23349b40
* Content: [Microsoft 365 Education - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your comment. I have forwarded the request to the production team, and I'll keep you posted.
