### ISSUE TITLE
Online template availability

### ISSUE THREAD

**Issue by anhage** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#698]
Online template availability is not listed under the [Office application and feature availability](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government#office-application-and-feature-availability-in-government-plans) section. I propose the below additions:

Application/feature | Accessibility   feature | GCC | GCC   High | DOD
-- | -- | -- | -- | --
**Microsoft Excel** |   |   |   |  
In-application   search for online templates |   | No | No | No
**Microsoft PowerPoint** |   |   |   |  
In-application   search for online templates |   | No | No | No
**Microsoft Word** |   |   |   |  
In-application   search for online templates |   | No | No | No

The feature I am referring to is here:
Download free, pre-built templates
https://support.microsoft.com/en-us/office/download-free-pre-built-templates-29f2a18d-29a6-4a07-998b-cfe5ff7ffbbb

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3ab3187-c403-8fb1-6ee7-56818777fdad
* Version Independent ID: f6b28482-bf80-436e-cb8f-facb974c24ec
* Content: [Office 365 US Government - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government?source=docs#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by anhage** [comment]
I also have a Microsoft bug number I can provide privately.

**Comment by annferre** [comment]
Hi there, I have forwarded your request to the pubops team and I'll keep you posted on the change. Thank you for your comment.

**Comment by annferre** [comment]
Fyi. We're still working on the Office for the web rewrite.

**Comment by SeanGit88** [comment]
Hello, this has been updated. thanks for your feedback.
