### ISSUE TITLE
Add FAQ and File Size Limits.

### ISSUE THREAD

**Issue by sp-karl** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#7]
It would be helpful to customers to see the limits of Office Online server for On-Premises and for O365.  There is a 300 MB error message customers receive when trying to open a PowerPoint document that is greater than 300 MB in PowerPoint Online.    I have found this documented in blogs, https://wopi.readthedocs.io/en/latest/faq/file_sizes.html but not in Microsoft Documentation.  Adding that this this article and to the individual PowerPoint Online File for example on the 300 MB level.

I found another request out there for this in GitHub https://github.com/Microsoft/Office-Online-Test-Tools-and-Documentation/commit/8f9b65b16fed6d14af8eba959a228d4b3c8f27c3

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cdf2ace-b564-bb26-303e-4374041610a7
* Version Independent ID: 4ea274ad-8b4f-9f37-e935-49ee485a1a7e
* Content: [Office Online Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-online-service-description/office-online-service-description)
* Content Source: [Office365-ServiceDescriptions/office-online-service-description/office-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-online-service-description/office-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by SKjerland** [comment]
@sp-karl - I passed this information onto the content owner. He updated the [How certain features behave in web-based PowerPoint](https://support.office.com/en-us/article/How-certain-features-behave-in-web-based-PowerPoint-A931F0C8-1305-4428-8F7C-9CFA00EF28C5#OfficeVersion=PowerPoint_Online) article, per feedback from the product team, to say: "PowerPoint Online can open files up to 2 gigabytes (GB) in size."
