### ISSUE TITLE
The feature capabilities of the Office mobile apps to Office 365 E1 and Biz Essentials should be update.

### ISSUE THREAD

**Issue by o365tatsuyan** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#70]
Microsoft is already expanded the editing capabilities of the Office mobile apps to Office 365 Business Essentials and Office 365 Enterprise E1, So the above table should be fix like as below;
-------------------------------
Office Mobile for iPad/iPhone :  Yes for "Office 365 Business Essentials"
Office Mobile for Android :  Yes for "Office 365 Enterprise E1"
-------------------------------

Information source is :   https://support.office.com/en-us/article/what-you-can-do-in-the-office-apps-on-an-android-ios-or-windows-mobile-device-with-an-office-365-subscription-9ef8b63a-05fd-4f9c-bac5-29da046833ea?ui=en-US&rs=en-US&ad=US

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61b8fbc9-7314-1e82-7c85-f0f9d3c3c1fd
* Version Independent ID: 7a5944ad-e785-5711-0954-f2be068e79d1
* Content: [Office Applications Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-applications-service-description/office-applications-service-description#feature-availability-across-office-365-plans)
* Content Source: [Office365-ServiceDescriptions/office-applications-service-description/office-applications-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-applications-service-description/office-applications-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by o365tatsuyan** [comment]
any update on this?

**Comment by prabita** [comment]
@o365tatsuyan  Page updated.
