### ISSUE TITLE
Webinars in GCC is now available.  Please update documentation

### ISSUE THREAD

**Issue by 3017mark** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#700]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9035b5a9-1f84-54be-89ae-c3a0e53891f8
* Version Independent ID: cff57f08-ca51-2266-6189-1ce8181b942e
* Content: [Microsoft Teams service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/teams-service-description)
* Content Source: [Office365-ServiceDescriptions/teams-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/teams-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, the update has been completed in PR 1713: https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/pull/1713. Please reopen if you have further questions.
