### ISSUE TITLE
DLP for SharePoint

### ISSUE THREAD

**Issue by bozenektoja** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#701]
DLP for SharePoint – can this be corrected here? [From the “Microsoft 365 guidance for security & compliance”](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Foffice365%2Fservicedescriptions%2Fmicrosoft-365-service-descriptions%2Fmicrosoft-365-tenantlevel-services-licensing-guidance%2Fmicrosoft-365-security-compliance-licensing-guidance%23microsoft-purview-information-protection-data-loss-prevention-dlp-for-exchange-online-sharepoint-online-and-onedrive-for-business&data=05%7C01%7Cbozenas%40microsoft.com%7C1148e2b784b149279de408da43bba2c6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637896770418404177%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YilkmhKUcvwvUzYyWKOJ3PwYDDcUn2oV6lQ4BeYxkfI%3D&reserved=0) – again, the customer does not necessarily have to have E3, SPO Plan 2 is enough (it creates this confusion that e3 is not only exo plan 2, spo2 etc but that there are also some compliance elements added)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#microsoft-purview-information-protection-data-loss-prevention-dlp-for-exchange-online-sharepoint-online-and-onedrive-for-business)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for your comment. I have reached out to the product team and I'll let you know as soon as I get a response. Thanks again!

**Comment by annferre** [comment]
Hi again, I have confirmed with the product team that you are correct, and we will be making an update to all applicable items on the page. I'll let you know when those are live.

**Comment by bozenektoja** [comment]
hello,

Can you please tell me when this doc will be updated?

Best regards/Pozdrawiam,
Bozena Hutyra
________________________________
Od: Ann Hemmons Ferreira ***@***.***>
Wysłane: wtorek, 7 czerwca 2022 19:01
Do: MicrosoftDocs/OfficeDocs-O365ServiceDescriptions ***@***.***>
DW: bozenektoja ***@***.***>; Author ***@***.***>
Temat: Re: [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions] DLP for SharePoint (Issue #701)


Hi again, I have confirmed with the product team that you are correct, and we will be making an update to all applicable items on the page. I'll let you know when those are live.

**Comment by annferre** [comment]
Hi Bozena, the document has been updated to the below. Please reopen if you still have questions.

Which licenses provide the rights for a user to benefit from the service?

 

Microsoft 365 E5/A5/G5/E3/A3/G3/Business Premium, SharePoint Online Plan 2, Exchange Online Plan 2
Office 365 E5/A5/G5/E3/A3/G3
Microsoft 365 E5/A5/G5/F5 Compliance and F5 Security & Compliance
Microsoft 365 E5/A5/F5/G5 Information Protection and Governance
Microsoft Purview Data Loss Prevention
