### ISSUE TITLE
Need to add M365 A1 for Device Licensing construct to this page

### ISSUE THREAD

**Issue by amitpawar74** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#703]
Need to add M365 A1 for Device Licensing construct to this page.

Similar to https://aka.ms/EDU-Plan-Comparison 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8328da3-5093-09b6-9b9b-b92d13625219
* Version Independent ID: f2171de5-bfa5-65d1-4615-30db23349b40
* Content: [Microsoft 365 Education - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education?source=docs#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, I have forwarded your request to the product team and I'll keep you posted on the response. Thanks!

**Comment by annferre** [comment]
Hi there, I just wanted to let you know the new column is available online: https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education
Please reopen if you have questions.

**Comment by amitpawar74** [comment]
Thank you.
________________________________
