### ISSUE TITLE
Storage quota for Recoverable Items folder in archive mailbox for M365 Business Premium

### ISSUE THREAD

**Issue by AkikoTsukahara** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#704]
Some customers and SEs have been pointing out that "Storage quota for Recoverable Items folder in archive mailbox for M365 Business Premium" should be same as that for E3/E5 because M365 Business Premium includes EOA (Exchange Online Archiving).
Is this understanding correct? if it's correct, it would be appreciated if you correct the following descriptions.

https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#mailbox-folder-limits-1

- Storage quota for Recoverable Items folder in archive mailbox (not on hold) for Microsoft 365 Business Premium

Current: 30 GB
Expected: 1.5 TB?

- Storage quota for Recoverable Items folder in archive mailbox (on hold) for Microsoft 365 Business Premium

Current: 100GB
Expected: 1.5 TB?

![image](https://user-images.githubusercontent.com/44765762/173793038-5c7a59e5-1488-463d-8ff9-2bb7a15f1329.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for your comment, I have sent a request to the product owners and I'll keep you posted on the response.

**Comment by ScottSchnoll** [comment]
Hi @AkikoTsukahara, thanks for your comment.  You are correct that it should say 1.5TB instead of 100GB, as 1.5 TB is the maximum size for the auto-expanding archive.  We'll correct the document to reflect this.

cc: @annferre

**Comment by annferre** [comment]
Hi Akiko, the update is live. Thank you again for your comment.
