### ISSUE TITLE
Update Microsoft Business Voice Documentation To Reflect Recent Service Changes

### ISSUE THREAD

**Issue by arazilsongweaver** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#705]
The Microsoft Business Voice documentation should be updated to reflect the realignment of Microsoft Business Voice licensing per: https://docs.microsoft.com/en-us/microsoftteams/business-voice-to-teams-phone-licenses

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abdc7fbf-1f49-704b-cad5-08f15e811642
* Version Independent ID: 2a9be28e-06a1-bfff-766c-de34214e7fba
* Content: [Microsoft 365 Business Voice service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-business-voice-service-description)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-business-voice-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-business-voice-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for your comment. I have forwarded your request to the product team, and I'll get back to you as soon as I have a confirmation. Thanks again!

**Comment by annferre** [comment]
Hi there, I received a response from the product team, and they were hoping to get more specifics. Can you share a little more as to the changes you suggest need to be made? They did say that the page is valid as is, as the life of Business Voice. has not ended. They also mentioned that existing Business Voice customers will continue to enjoy their subscription till the end of their agreements (the transition to Teams Phone with Calling Plan – is a change in licensing).
