### ISSUE TITLE
Feedback | License Info and incorrect redirect link

### ISSUE THREAD

**Issue by qaehtesh** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#706]
Note - Unable to do this directly from review.docs.microsoft.com so creating feedback request

The [Features available to some plans] needs correction for below points,

1) The hyperlink for [IRM using Azure Information Protection] in the table is incorrect and redirecting to Archive topic instead of IRM
https://docs.microsoft.com/en-us/exchange/policy-and-compliance/in-place-archiving/in-place-archiving
2) The license information for [Microsoft Purview Message Encryption (Basic)] is incorrect, since feature is dependent on AIP (AzureRMS) , E1 etc licenses which does not cover AIP should not be Yes.

<Additonal Reference>
https://docs.microsoft.com/en-us/microsoft-365/compliance/ome-version-comparison?view=o365-worldwide
https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#information-protection
https://docs.microsoft.com/en-us/azure/active-directory/enterprise-users/licensing-service-plan-reference

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2f622a7-32c1-2c35-2df9-ddf1bc74c74d
* Version Independent ID: e37d85d2-8b81-0c64-b7d0-1e8c01b303db
* Content: [Exchange Online service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for your comment. I have forwarded your request to the product team, and I will get back to you as soon as I have confirmation.
