### ISSUE TITLE
Link to the Small and Medium business licensing is missing

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#707]
The first paragraph needs updating to include links to both the Enterprising licencing and the Small and Medium business licensing tables.  Currently, the link is only linking to Enterprise licensing. This link to the Small and Medium business licensing is shown on the lefthand menu but not referred to.
Revised wording

Appropriate subscription licenses are required for customer use of online services. To see the options for licensing your users to benefit from Microsoft 365 compliance features, download the [Microsoft 365 Comparison table for Enterprise and Frontline Workers Plans](https://go.microsoft.com/fwlink/?linkid=2139145) or the [Microsoft 365 Comparison table for Small and Medium Business Plans] (https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWR6bM).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, I just wanted to say thank you for your comment, and let you know that the links are now live. Please reopen if you have questions. Thanks again!
<img width="442" alt="image" src="https://user-images.githubusercontent.com/86699727/178552966-8801907a-62a3-412c-b504-3d0bb3760ca0.png">
