### ISSUE TITLE
Footnote error

### ISSUE THREAD

**Issue by Cyphrz** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#708]
Footnote contradicts

6 Users with a Project Plan 3 or Project Plan 5 subscription can submit resource engagement requests. They cannot review, fulfill, or approve resource engagement requests.
7 Users with a Project Plan 5 subscription can review, fulfill, and approve resource engagement requests.

I believe it should say this

6 Users with a Project Plan 3 or ~~Project Plan 5~~ subscription can submit resource engagement requests. They cannot review, fulfill, or approve resource engagement requests.
7 Users with a Project Plan 5 subscription can review, fulfill, and approve resource engagement requests.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 929f5194-b49a-1d9c-1777-a4d34a720068
* Version Independent ID: 44e5b986-fd93-75de-10e2-b6802f8e3e27
* Content: [Microsoft Project Online service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/project-online-service-description/microsoft-project-online-service-description#notes)
* Content Source: [Office365-ServiceDescriptions/project-online-service-description/microsoft-project-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/project-online-service-description/microsoft-project-online-service-description.md)
* Product: **office-online-server**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, I just wanted to let you know the footnote has been corrected. Thank you for your comment. Please reopen if you have questions. Much appreciated. Thanks!
