### ISSUE TITLE
Upload/Save limits for drag and drop and Upload button on command bar

### ISSUE THREAD

**Issue by jhersko** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#709]
In SharePoint in Microsoft 365, is there a upload limit or max size of content you can upload into a library at a single time? If so, what are the limits? Are they the same as the Moving and copying across sites limits, different, or non-existent? The upload methods I’m referring to are drag and drop and the Upload button the command bar. (Either Files or Folder.)  

Please note that not all large data moves into Microsoft 365 occur using the migration tool or PowerShell.  I believe it would be profoundly useful to know if the limits exist or not.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits?redirectSourcePath=%252fen-us%252farticle%252fSharePoint-Online-software-boundaries-and-limits-8f34ff47-b749-408b-abc0-b605e1f6d498)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by jhersko** [comment]
Good morning!  Is an update available?

Thank you,
J. Hersko

**Comment by annferre** [comment]
Hi there, the product team responded with the below. Please reopen if you still have questions.
Quickly looking from the documented limits - [https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Foffice365%2Fservicedescriptions%2Fsharepoint-online-service-description%2Fsharepoint-online-limits&data=05%7C01%7Cv-annhem%40microsoft.com%7C85d964a5c0884c5c097108da5f707223%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637927233796709414%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RM4o4rKnpeHOa613xR%2FE1yGs4nJca3Gsay2qkp1FFB0%3D&reserved=0)

Seems that the file upload limit is 250GB – but don’t think there’s any other limits as such and even that documented limit could be higher than what’s in docs.
