### ISSUE TITLE
The support team isn't clear on what scripts mean in the statement "The Office 365 team does not support scripts."

### ISSUE THREAD

**Issue by rlbogue** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#71]
They're including calculated columns as a script.  There should be clarity here that "scripts" means JavaScript scripts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4bab1e0-b326-22fd-d1b8-23780e0720d3
* Version Independent ID: bf81479e-1ed7-d465-a72b-bb425c757411
* Content: [Support](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/support)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/support.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/support.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by prabita** [comment]
@rlbogue - Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response.

**Comment by SharS** [comment]
Updated note: "The Office 365 team does not support scripts (e.g. scripting techniques like JavaScript, VBScript etc. or VBA). If you need assistance with scripts, contact Microsoft Support. For Office Apps usage support, see Support options for Microsoft Office application issues for Office 365 subscribers."
