### ISSUE TITLE
Incorrect information about GCC trial

### ISSUE THREAD

**Issue by dkontyko** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#710]
Under the "What trials are available?" header, there is a link to a GCC O365 trial. The link forwards to [a page](https://www.microsoftevents.com/profile/form/index.cfm?PKformID=0x741969fc0) that says the trial is no longer available. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86dc9aff-0190-52d9-2ab0-4f236d862739
* Version Independent ID: f6cbf527-2a7d-edd6-49b9-ca70ba43b9d6
* Content: [Microsoft 365 Government how to buy - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/microsoft-365-government-how-to-buy)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/microsoft-365-government-how-to-buy.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/microsoft-365-government-how-to-buy.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, I have forwarded your request to the product team, and I'll get back to you as soon as I receive a response.

**Comment by annferre** [comment]
HI there, the redirect link should point to the below. Please reopen if you have further concerns.
https://www.microsoft.com/en-us/microsoft-365/government/eligibility-validation
