### ISSUE TITLE
Business Premium Confusion-AGAIN

### ISSUE THREAD

**Issue by beachgrootbreadalto** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#711]
Please explain how to interpret this note with regard to Business Premium and its archive limit.
Exchange Online Plan 1, Office 365 E1/A1/G1, and Microsoft 365 Business Basic/Standard/**Premium** have a size limit on the mailbox and archive. 

I **believe** that Business Premium includes Exchange Online Plan 1 and the Exchange Online Archive add-on (so technically the EXO Plan 1 included in BP does not offer a 1.5TB archive mailbox, its the add-on that's included in BP that offers the larger archive). BUT, please make this crystal clear! I have documentation sent to me from our reseller from several months ago that specifically states BP only offers a 50GB archive mailbox with no mention of the add-on. 

Just asking for you guys to get your stuff together so I don't look like an idiot when I have to keep contradicting myself. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c55dc71-81ed-864b-ac3f-63ce84688070
* Version Independent ID: 578c9a02-045e-4bf9-6384-d70560c332f0
* Content: [Exchange Online Archiving service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description)
* Content Source: [Office365-ServiceDescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for your comment. I have forwarded your request to the product team, and I will get back to you as soon as I receive a response. Thanks again!

**Comment by annferre** [comment]
Hi there, just letting you know the note below is being removed. This no longer applies. I'll let you know when the update is live. Also, the product team is looking into your concern. I'll get back to you as soon as I receive a response. Thanks!
Exchange Online Plan 1, Office 365 E1/A1/G1, and Microsoft 365 Business Basic/Standard/Premium have a size limit on the mailbox and archive.

**Comment by annferre** [comment]
Hi there, I just wanted to let you know the note was removed the edited version is live. Please reopen if you have further concerns. Thanks!
