### ISSUE TITLE
Need clarification on M365 A1 for Devices

### ISSUE THREAD

**Issue by cobirge** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#712]
Per a field request a customer is looking for clarification on the [Microsoft 365 A1 for Devices SKU](https://educationblog.microsoft.com/en-us/2021/09/support-all-learners-with-the-new-microsoft-365-a1-for-devices-license), separate from the other Microsoft 365 A1 SKUs. Can we get that column inserted into the table please?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8328da3-5093-09b6-9b9b-b92d13625219
* Version Independent ID: f2171de5-bfa5-65d1-4615-30db23349b40
* Content: [Microsoft 365 Education - Service Descriptions](https://docs.microsoft.com/en-ca/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, I just wanted to let you know the new column is available online: https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education
Please reopen if you have questions.
