### ISSUE TITLE
No option to turn on Targeted Release

### ISSUE THREAD

**Issue by VShrubowich** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#713]
In the **Platform Features** table under **Service Updates**, it says **Yes** for **Option to turn on Targeted Release** for all plans.  However, under the [Targeted release](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/release-options-in-office-365?view=o365-worldwide#targeted-release) section of the [Set up the Standard or Targeted release options](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/release-options-in-office-365?view=o365-worldwide) document (accessible by clicking on **Service updates**, then the "Microsoft release options" link in the **Targeted release** section under the **Domains, networks, partners, S&C, and SLA tab**), it states, 

> Targeted release is not currently available for customers with either the Office 365 GCC plan or the Office 365 GCC High and DoD plan.

The **Release preferences** option is missing in our GCC Microsoft 365 admin center, leading me to believe that the [Set up the Standard or Targeted release options](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/release-options-in-office-365?view=o365-worldwide) document is correct, not this one.

Also, each **Yes** for **Option to turn on Targeted Release** refers to footnotes 8 and 22.  I can see how footnote 8 applies, but not 22.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3ab3187-c403-8fb1-6ee7-56818777fdad
* Version Independent ID: f6b28482-bf80-436e-cb8f-facb974c24ec
* Content: [Office 365 US Government - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your comment. I have forwarded your request to the product team and will update the article as necessary based on their response.

**Comment by annferre** [comment]
Hi there, I just wanted to let you know the footnotes are being updated to the following:
<html>
<body>
<p style="box-sizing: border-box; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-weight: bold; margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box;"><br class="Apple-interchange-newline">AFTER:</span><br style="box-sizing: border-box;"></p>

Service updates | Office 365 Government G1 | Office 365 Government G3 | Office 365 Government G5 | Office 365 Government F3
-- | -- | -- | -- | --
Regular updates provided to all customers | Yes | Yes | Yes | Yes
Notifications sent to Message Center when action is required | Yes15 | Yes15 | Yes15 | Yes15
Roadmap.office.com for some service updates | No10, 13 | No10, 13 | No10, 13 | No10, 13
Option to turn on Targeted Release | Yes8,11 | Yes8,11 | Yes8,11 | Yes8,11

<p style="box-sizing: border-box; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-weight: bold; margin: 0in 0in 0.0001pt; font-size: 11pt; font-family: Calibri, sans-serif;"> </p><br class="Apple-interchange-newline">
</body>
</html>AFTER:
[Service updates](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/service-updates)

Office 365 Government G1

Office 365 Government G3

Office 365 Government G5

Office 365 Government F3

Regular updates provided to all customers

Yes

Yes

Yes

Yes

Notifications sent to Message Center when action is required

Yes15

Yes15

Yes15

Yes15

Roadmap.office.com for some service updates

No10, 13

No10, 13

No10, 13

No10, 13

Option to turn on Targeted Release

Yes8,11
Yes8,11
Yes8,11
Yes8,11

**Comment by VShrubowich** [comment]
Thank you for the update.  However, since 11 states "Not supported for Office 365 Government offerings." and the entire document is specific to Office 365 Government, shouldn't that then be as follows?

Option to turn on Targeted Release | No | No | No | No

**Comment by annferre** [comment]
Hi Victor, thank you for your comment. The product team responded with the following: The primary intent of these pages is to indicate which capabilities or entitlement are/are not included in the various SKU levels. E.G. there are some things that if you want to get them, you have to pay for the E3/G3 or E5/G5 offering. We base the list of capabilities/entitlements on the corresponding page for WW, so that people can compare what is available in the WW offering with what is available in Govt Cloud. So if it’s a capability/entitlement that we intend to include for that SKU, but we have not released for a particular Govt Cloud yet, we’d put “Yes” in that cell, but add a footnote that it has not been made available for GCC/GCCH/DOD yet, as appropriate. Hopefully that is not too confusing. I’d say that we intend to make Targeted Release available in GCC/GCCH/DOD, So that would mean putting “Yes” in these cells, with a footnote to indicate that Targeted Release is not yet released to GCC/GCCH/DOD. "
Please reopen if you have further questions.
Thanks again for you comment.
