### ISSUE TITLE
This page has poor grammar or its contradictory.  4 This is the storage limit for a single site (previously called "site collection"), not the amount of storage provided for each site. This limit applies to all types of sites, including Office 365 group-connected team sites and OneDrive. SharePoint admins can manually set lower storage limits.

### ISSUE THREAD

**Issue by ftacnik-github** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#714]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your comment. I have forwarded your request to the product team and will update the article as necessary based on their response.

**Comment by annferre** [comment]
Hi there, the product team responded saying: It simply means that a single site collection has a maximum storage limit and admins can use as is or minimize so site collection owners can only utilize some of that total storage per design of how their governance plan gets implemented.

If you have a suggestion on what you would like to see written, I can forward to the product team. Thanks!

**Comment by annferre** [comment]
Hi there, please reopen if you have a suggestion for the verbiage you would like to see. Thanks!
