### ISSUE TITLE
How do we see which licenses are allowed to have view access to project for the web and roadmap?

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#715]
The article says,
> However, users that are assigned certain Office 365 licenses are allowed to have view access to Project for the web and Roadmap. This provision will allow them to have read-only access to projects and roadmaps that are shared with them, without needing to be assigned a Project Plan license.

Where do I see what those certain office 365 licenses are?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b614c3a-5070-9595-2cb2-d2ec4fb68cb7
* Version Independent ID: f73e4cf9-fe59-e6f4-7638-2bddf97a069e
* Content: [Microsoft Project service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/project-online-service-description/project-online-service-description)
* Content Source: [Office365-ServiceDescriptions/project-online-service-description/project-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/project-online-service-description/project-online-service-description.md)
* Product: **office-online-server**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by jonwbstr** [comment]
Disregard, opened for the wrong document and I found the answer I was looking for.
https://docs.microsoft.com/en-us/project-for-the-web/office-365-user-view-access-to-project-and-roadmap#office-365-subscription-with-view-access

**Comment by annferre** [comment]
Thanks!
