### ISSUE TITLE
Please ignore my previous post regarding the recipient rate limit

### ISSUE THREAD

**Issue by martin-heeck** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#718]
[Enter feedback here]
After careful reading I think that I misinterpreted the behavior of Exchange Online. In fact it seems as if the limit for "Messages received from single sender" is applied. This would then equal to 33% of receiving limit of 3600 messages per hour = 1188 messages per hour.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi Martin, can I close out 717? Also, are you requesting a change to the verbiage? If yes, what would the verbiage be?
