### ISSUE TITLE
GCC Using only US Data Centers??

### ISSUE THREAD

**Issue by dfoelker** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#719]
Hello,

This article states that GCC Tenants may be using processing capacity in Commercial Data Centers, but these datacenters reside in the US:
![image](https://user-images.githubusercontent.com/106116570/181625402-599ab946-eecc-4c6d-adee-3f8da76c321d.png)

However, some GCC customers have noted that some Inbound Direct Routing calls to their SBCs are originating from non-US Data Centers:
![image](https://user-images.githubusercontent.com/106116570/181626173-bf2d06cf-f7ba-4b80-9425-82e8dd356601.png)

What is going on here?
Regards,
Daniel

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3ab3187-c403-8fb1-6ee7-56818777fdad
* Version Independent ID: f6b28482-bf80-436e-cb8f-facb974c24ec
* Content: [Office 365 US Government - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi Daniel, I have reached out to the product team and cc'd you on the communication. Thank you bringing this up.

**Comment by dfoelker** [comment]
Great!  Thank you Ann.

Regards,
Daniel Foelker
Teams Voice Technical Specialist
Modern Work, State & Local Government

Office:   414.615.6539
Mobile: 608.422.3225
***@***.******@***.***>

***@***.***

**Comment by annferre** [comment]
Hi Daniel, closing per our email conversation. Thanks for the comment.

**Comment by dfoelker** [comment]
Ok.  Thank you Ann.

Regards,
Daniel Foelker
Teams Voice Technical Specialist
Modern Work, State & Local Government

Office:   414.615.6539
Mobile: 608.422.3225
***@***.******@***.***>

***@***.***
