### ISSUE TITLE
Revert to A1 instead of free trial A5

### ISSUE THREAD

**Issue by TweetingCynical** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#72]
Hi All,

We are a brand new school for educating students in English and Mathematics. I have tried to register our organisation for Office 365, but it has given us an A5 subscription. I tried changing this in billing and support of the Admin to A1, but this package is not available. I do not want to set all of my students up with accounts that we then use to collaborate on for classes, if it is going to removed after the A5 trial ends. Any ideas?

Thanks in advance,

Jon

**Comment by prabita** [comment]
@TweetingCynical - Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response.
