### ISSUE TITLE
Privileged access management in Office 365 - Incorrect Licensing information

### ISSUE THREAD

**Issue by Aldridge-A** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#720]
There seems to be some incorrect information in the Licensing section for Privileged access management in Office 365.

It mentions that Microsoft 365 E5/A5/F5 Information Protection and Governance licenses will allow the user to benefit from the PAM service. This is incorrect as this license does not include PAM. 

This looks to be a mistake as it is meant to be Microsoft 365 E5/A5/F5 Insider Risk Management which does include PAM use rights and is not currently mentioned in this section of the document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#privileged-access-management-in-office-365)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, I just wanted to let you know I reached out to the product team, and I'm waiting for their feedback. I'll let you know as soon as I hear from them. Thanks!

**Comment by annferre** [comment]
Hi there, I just wanted to let you know edits were made to the online page and it now shows as the below. Please reopen if you have further concerns. Thank you again for your comment.
<img width="434" alt="image" src="https://user-images.githubusercontent.com/86699727/186793453-3d17f95c-7cda-4c87-988d-6b1029037c08.png">
