### ISSUE TITLE
Mistake 

### ISSUE THREAD

**Issue by tg1212** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#721]
[Enter feedback here]

The last paragraph of that [section](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#microsoft-purview-data-lifecycle-management--microsoft-purview-records-management) 
says:

"Additionally, shared mailboxes are limited to 50 GB without the need for an Exchange add-on. To increase the size limit to 100 GB, the **inactive mailbox** requires Exchange Online Plan 2 or Exchange Online Archiving + Exchange Online Plan 1."

The bold part shoud be "... shared mailbox..."

Is it correct that I do not need an ExO Plan 1 + Online Archiving license when I use a retention policy with that mailbox? MS Support said last year I need it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#microsoft-purview-data-lifecycle-management--microsoft-purview-records-management)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your comment. I have reached out to the product team for confirmation, and I'll get back to you as soon as I receive a response. Thanks again!

**Comment by annferre** [comment]
Hi there, I received confirmation of the following:
"Additionally, shared mailboxes are limited to 50 GB without the need for an Exchange add-on. To increase the size limit to 100 GB, the **shared** mailbox requires Exchange Online Plan 2 or Exchange Online Archiving + Exchange Online Plan 1."
Let me know if you still have questions.
Thanks again for your comment.

**Comment by annferre** [comment]
Hi there, I just wanted to let you know the new text is live. Please reopen if you still have questions. Thanks!
