### ISSUE TITLE
Power BI Dataset availability for GCCH

### ISSUE THREAD

**Issue by anhage** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#722]
Is this accurate?
https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government#:~:text=3%20Excel/Power%20BI%20cloud%20connected%20features%20are%20only%20supported%20for%20cloud%20environments%20supported%20by%20Power%20BI.

And what does this mean?
https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government#:~:text=3%20Excel/Power%20BI%20cloud%20connected%20features%20are%20only%20supported%20for%20cloud%20environments%20supported%20by%20Power%20BI.

I am internal Microsoft SEE and have a support case related to this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3ab3187-c403-8fb1-6ee7-56818777fdad
* Version Independent ID: f6b28482-bf80-436e-cb8f-facb974c24ec
* Content: [Office 365 US Government - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi Ann, it's unclear what you are referring to because they're both pointing to the same location. The below is what is highlighted when going to the link. Is this what you are referring to?
3 Excel/Power BI cloud connected features are only supported for cloud environments supported by Power BI.

**Comment by anhage** [comment]
I apologize, I made a copy/paste mistake.

Is this accurate? (The "No" availability for GCC/GCCH/DOD) 
https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government#:~:text=Improved%20integration%20with%20Power%20BI%20(Power%20BI%20Data%20Types%2C%20Power%20BI%20Datasets)3

And what does this mean?
https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government#:~:text=3%20Excel/Power%20BI%20cloud%20connected%20features%20are%20only%20supported%20for%20cloud%20environments%20supported%20by%20Power%20BI.

**Comment by annferre** [comment]
Thanks Ann, I sent your request to the product team. I'll keep you posted.

**Comment by annferre** [comment]
Hi there, the update is live. Please reopen if you have further questions. Thanks again for your comment.
