### ISSUE TITLE
F5 Compliance add on license missed?

### ISSUE THREAD

**Issue by EdmondZhangJian** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#723]
For information barrier, Will F5 Compliance addon license provide the rights for a user ? 
Seems it is not inculuded.

~~~
Which licenses provide the rights for a user to benefit from the service?
Microsoft 365 E5/A5/G5, Microsoft 365 E5/A5/G5 Compliance, Microsoft 365 E5/A5/G5 Insider Risk Management, and Office 365 E5/A5/G5, provide the rights for a user to benefit from Information Barriers.
~~~

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance?source=docs#information-barriers)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your comment. I forwarded your request to the product team and I'll get back to you as soon as I have confirmation.

**Comment by annferre** [comment]
Hi there, edits have been made to the [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance?source=docs#information-barriers) page and the below is what is now available online. Please reopen if you have further questions. Thanks again for your comment.
<img width="446" alt="image" src="https://user-images.githubusercontent.com/86699727/186794171-bef38b11-d68b-4c12-9dd5-8cd0ee9c97fa.png">
