### ISSUE TITLE
how many attachments can be supported for a list item?

### ISSUE THREAD

**Issue by frankchen76** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#724]
I see "250 MB - File attached to a list item. Applies to Microsoft Lists and SharePoint lists - both based on same lists platform.", do we have limit how many attachments can be uploaded for one list item?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your post. I have forwarded your question to the product team and I'll get back to you as soon as possible.

**Comment by annferre** [comment]
Hi there, I received a response from the product team: the default lists and libraries won’t be counted and should not impact the total subsites. Having said that, we recommend customers not create too many subsites.  Please reopen if you still have a question.

**Comment by frankchen76** [comment]
> Hi there, I received a response from the product team: the default lists and libraries won’t be counted and should not impact the total subsites. Having said that, we recommend customers not create too many subsites. Please reopen if you still have a question.

@annferre can you please clarify what you mentioned? my original question is if _we have limit how many attachments can be uploaded for one list item_. you mentioned impacting to total subsites. I don't see your answer is related to my question. Am I missing something?
