### ISSUE TITLE
Remove records management section

### ISSUE THREAD

**Issue by EricaToelle** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#725]
We've combined the Data Lifecycle and Records Management sections of this page. Please delete the stand-alone records management section at the bottom.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance?source=docs)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thanks Erica, I have forwarded the request to PubOps. I'll let you know as soon as it's live.

**Comment by annferre** [comment]
Hi Erica, this has been done. Thanks for your comment.

**Comment by dsnyder99** [comment]
Erica, was this change meant purely to make the page more concise, or does it represent a shift in licensing terms? The prior stand-alone Records Management section was more explicit in stating that end users tagging records required higher level licensing. Thank you!

**Comment by EricaToelle** [comment]
Hi @dsnyder99 There was no change in licensing terms. Data Lifecycle Management and Records Management aren't different from a licensing perspective, so it did not make sense to have two separate sections.

The new combined section is much more detailed and still covers what licenses end users need, which depends on the retention label configuration. Technically, we don't have record labels. We have retention labels, and one of the setting options is to configure it as a record, which in our tool means immutability is enabled.

**Comment by dsnyder99** [comment]
Thanks for the quick response, Erica. Just to confirm - if an end user is a member or owner of a site to which a retention label configured to mark items as a record or a regulatory record is published, that user would need E5/A5/F5/G5 level license (in other words, the elevated license requirement would not simply be required of the administrator creating and publishing that label with the "record" configuration)?

Thanks again,
David

Thanks again for the clarification.

**Comment by EricaToelle** [comment]
Correct @dsnyder99
