### ISSUE TITLE
Inconsistent information - automatic sensitivity labeling and O365 A5

### ISSUE THREAD

**Issue by CarolWangMS** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#726]
Hello Team,

In the [document](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#which-licenses-provide-the-rights-for-a-user-to-benefit-from-the-service-19 ) it says, 
_

For both client and service-side automatic sensitivity labeling, the following licenses provide user rights:

- Microsoft 365 E5/A5/G5
- E5 Compliance
- Microsoft 365 E5/A5/G5 Information Protection and Governance
- Office 365 E5

---
However,  when I check "compare Microsoft Education Plans" in this page [https://www.microsoft.com/en-us/education/products/microsoft-365](https://www.microsoft.com/en-us/education/products/microsoft-365)
it shows that the Automatic sensitivity labels (client-side) and Automatic sensitivity labels (service-side) is included in O365 A5. 

Please kindly check it.

_

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your comment. I have forwarded your request to the product team, and I'll let you know the response as soon as it's received.

**Comment by annferre** [comment]
Hi there, edits have been made to the [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance)  page, and online now shows the below. Thank you again for your comment. Please reopen if you have further questions.

<img width="406" alt="image" src="https://user-images.githubusercontent.com/86699727/186795556-b256cad4-07b1-4b17-b923-0da7480ae729.png">
