### ISSUE TITLE
Clarify a limitation for subsites.

### ISSUE THREAD

**Issue by kefujino** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#727]
Hello, 

The limitations of Subsites and Lists/Libraries creation are  2000 within a single site collection.

![image](https://user-images.githubusercontent.com/13634805/184899959-2120d1ae-9926-4107-80b2-731056907f1e.png)

However, each subsite has about 10 automatically created lists and libraries, such as Masterpage Galleries and User Info Lists. So if we create  200 subsites in a site collection, it reaches lists and libraries limitation. **In other words, the number of subsites that can be created should be much smaller than 2000.**

Could you please clarify that the number of subsites that can be created should depend on the maximum number of lists and libraries? Today, subsites creation should be avoided, but the service limits description must be clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your post. I have forwarded your question to the product team and I'll get back to you as soon as possible.

**Comment by annferre** [comment]
Hi there, the product team said that the default lists and libraries won’t be counted and should not impact the total subsites. Having said that, we don’t not recommend customers to create too many subsites. Please reopen if you have further questions.
