### ISSUE TITLE
Small bug in the table at **Features available to some plans** section

### ISSUE THREAD

**Issue by szymonbr** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#728]
The table in **Features available to some plans** section contains improper information related to message encryption.

**Microsoft Purview Message Encryption (Basic)** is not included in **Microsoft 365 Business Basic** and **Business Standard** plans.
It requires additional subscription for **Azure Information Protection** service which is not mentioned there.

It should be mentioned clearly it's ready to enable the feature but requires additional subscription to enable **Microsoft Purview Message Encryption**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2f622a7-32c1-2c35-2df9-ddf1bc74c74d
* Version Independent ID: e37d85d2-8b81-0c64-b7d0-1e8c01b303db
* Content: [Exchange Online service description - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for your comment. I have forwarded your request to the product team, and I'll let you know as soon as I receive a response.

**Comment by ScottSchnoll** [comment]
Hi @szymonbr, you are correct that it is not included by default. You can however add Azure Information Protection Plan 1 to the following plans to receive Microsoft Purview Message Encryption: Exchange Online Plan 1, Exchange Online Plan 2, Office 365 F3, Microsoft 365 Business Basic, Microsoft 365 Business Standard, or Office 365 Enterprise E1. We'll update the doc to make that clear.

cc: @annferre

**Comment by annferre** [comment]
Hi @szymonbr, a footnote has been added to clarify that this has to be added on. Please reopen if you have further concerns. Thanks!
