### ISSUE TITLE
Doesn't include objects/web form controls not supported by Excel on the Web

### ISSUE THREAD

**Issue by tdo365** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#729]
This article says that Excel on the Web doesn't support check box controls Excel for the web. But that is is not in the limitation list. Is there a part of this article the limitations article that says that there may be other limitations not listed? Or does this limitation needed to be added to the list?

https://support.microsoft.com/en-us/office/add-a-check-box-or-option-button-form-controls-9f201e46-8f6b-4a9d-a320-f44b28088cb0#ID0EBBH=Web

Many thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0d13579-5b95-82bd-4083-1919e38c034f
* Version Independent ID: 4bc5df6e-4168-3a3e-f72b-0aa327a492e8
* Content: [Excel for the web - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-online-service-description/excel-online)
* Content Source: [Office365-ServiceDescriptions/office-online-service-description/excel-online.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-online-service-description/excel-online.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, Thank you for your comment. I have forwarded your request to the product team, and I'll let you know as soon as I receive a response.

**Comment by annferre** [comment]
Hi there, we are currently working on adding this feature to the [Office for the web service description - Service Descriptions | Microsoft Learn](https://learn.microsoft.com/en-us/office365/servicedescriptions/office-online-service-description/office-online-service-description)  page as being available for Desktop but not for Web.
I'll let you know one it's live. Thanks!
