### ISSUE TITLE
More than 250 users on a Skype meeting?

### ISSUE THREAD

**Issue by dtdono0** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#73]
Is a higher user limit available with Office 365 Enterprise F1 subscription?  We have meetings where maybe 500+ users are invited.  Not all of them show up obviously, but sometimes for popular subjects we have hit the 250 user meeting limit.  I've been in Discord voice channels with 500+ users before and everything works fine.  Why can't MS actually offer a more scalable Enterprise experience for Skype?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adfbc495-10f9-ae85-6486-6731d5942688
* Version Independent ID: d8d1bcec-612f-633c-e03d-e027972ed337
* Content: [Skype for Business Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/skype-for-business-online-service-description/skype-for-business-online-limits#feedback)
* Content Source: [Office365-ServiceDescriptions/skype-for-business-online-service-description/skype-for-business-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/skype-for-business-online-service-description/skype-for-business-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by prabita** [comment]
@dtdono0 Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response

**Comment by Gizzo** [comment]
I'm also interested in increasing this limit. Our current on-prem SFB infra has a dedicated AV pool and so we have the limit increased to 999.

**Comment by SharS** [comment]
Microsoft has announced that Skype for Business Online will be retired on 7/31/2021. Microsoft recommends that you upgrade to Teams. (For more information, see this [blog post](https://techcommunity.microsoft.com/t5/Microsoft-Teams-Blog/Skype-for-Business-Online-to-Be-Retired-in-2021/ba-p/777833))
