### ISSUE TITLE
Purview Exact Data Match?

### ISSUE THREAD

**Issue by itguysocal** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#730]
Can you please add a section on this page for Purview Exact Data Match? We are unable to find any public documents from Microsoft on what license packages are required, and whether a single license is required or if all users need to be licensed? 

For example this documentation page for Exact Data Match does not include license information either:
https://docs.microsoft.com/en-us/microsoft-365/compliance/sit-get-started-exact-data-match-based-sits-overview?view=o365-worldwide#required-licenses-and-permissions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, Thank you for your comment. I have forwarded your request to the product team, and I'll let you know as soon as I receive a response.

**Comment by annferre** [comment]
Hi there, we will be adding the section, but we don't have a timeline for this. We will get back to you when we'll be working on this.
