### ISSUE TITLE
Clarification on tenant-wide user scoping??  Guests?

### ISSUE THREAD

**Issue by PeteHaigh-MSFT** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#731]
Hi there

Is the documentation correct in saying that while the service is tenant-wide in scope, only activity for licensed users is stored for the 1-year period?? The obvious (glaring!) gap here is retention of external user activity where the risk profile is higher - and it looks like there's no way of keeping these audit logs for longer than 90 days in the tenant? 

Does Audit Premium actually keep Guest users logs for 12 months? .. it should.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for your question/comment. I have forwarded the request to the product team, and I'll get back to you as soon as I receive a response.

**Comment by PeteHaigh-MSFT** [comment]
Hi there - could we please get a response on this?

**Comment by annferre** [comment]
Hi PeteHaigh-MSFT, I received the following response from the product team: 
Regarding Audit (Premium). The links in that section go to pages with more details (ie: [Microsoft Purview Audit (Premium) - Microsoft Purview (compliance) | Microsoft Docs](https://docs.microsoft.com/en-us/microsoft-365/compliance/advanced-audit?view=o365-worldwide)) which includes customization. And there is a note about guest users there:
