### ISSUE TITLE
Add information related to licensing requirements to deploy the AIP Scanner

### ISSUE THREAD

**Issue by flmihai91** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#732]
Currently, there is a lot of confusion in terms of licenses required to configure the AIP Scanner and its different capabilities. While we know that the scanning in discovery mode is E3 and auto-labelling is E5, scenarios like assigning a default label via the scanner creates a lot of confusion.

In a particular scenario with one of my customers, after the CSAM involved someone from the Licensing team, that person confirmed that the Scanner has an E3 minimum requirement.

Could you please update the documentation to avoid this level of confusion?
It might be worth adding a licensing requirements section in the AIP Scanner docs as well:
https://docs.microsoft.com/en-us/azure/information-protection/deploy-aip-scanner-prereqs

Thanks in advance!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#microsoft-purview-information-protection-sensitivity-labeling)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for your comment. I have forwarded your request to the product team, and I'll let you know as soon as I receive a response. Thanks again!

**Comment by annferre** [comment]
Hi there, we updated the AIP Scanner section to the below. Please reopen if you have further questions.
<img width="456" alt="image" src="https://user-images.githubusercontent.com/86699727/189706842-b0306f77-333f-4f90-9e27-a905ed1a8be7.png">
