### ISSUE TITLE
Sovereign Cloud information

### ISSUE THREAD

**Issue by carlova** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#733]
Internal advocates are attempting to determine what on this page is applicable to sovereign clouds, particularly the O365 GCC High and DoD environments. I recognize that some of these features are applicable (for example, PIR), but some are not. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76358610-0b3b-49d9-6e6a-0b334b19d795
* Version Independent ID: 66466964-caa5-cded-20a6-627495521904
* Content: [Service health and continuity - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/service-health-and-continuity)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/service-health-and-continuity.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/service-health-and-continuity.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, I have forwarded your request to the product team. I will let you know as soon as I have a contact person you can reach out to regarding this matter. Thank you for your post.

**Comment by annferre** [comment]
Sorry for the delay. See below answer from the product team. Please reopen if you have further questions:

Everything on this page is relevant to commercial and gov cloud, with the exception of the quarterly uptime data -- the data does not apply to U.S. Government DoD, and GCC High.

For the items that we link to outside of the doc, IE Admin App, Microsoft System Center Management Pack, Service Comms API, etc., Gov cloud eligibility will be dictated by those specific toolsets on their page.
