### ISSUE TITLE
Please note Kaizala is being retired Aug 2023.

### ISSUE THREAD

**Issue by avalport** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#734]
Please note in the document that Kaizala is being retired Aug 2023.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dd954d8-5874-8d25-36eb-0718ef86d585
* Version Independent ID: 001e3018-251d-dc72-c669-a21e303f21d7
* Content: [Microsoft 365 suite features - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-suite-features?source=recommendations)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-suite-features.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-suite-features.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your comment. I have reached out to the product team to see if they want to update the page. Thanks again!

**Comment by annferre** [comment]
Thank you for reaching out regarding Kaizala, I spoke with the Service Description portal owner, and the response was that the service description repository is not for marketing but it is for products that are in Generally Availability status, including products that will sunset. However, the marketing team has added information to the Kaizala page which the service description points to, that shows this product will soon be retired: https://www.microsoft.com/en-us/microsoft-365/business/microsoft-kaizala. Please reopen if you have further questions.
