### ISSUE TITLE
Licence information for EndPoint Data Loss prevention is missing

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#736]
EndPoint Data Loss Prevention (DLP) licencing information is missing from this page. You only cover

- Microsoft Purview Information Protection: Data loss Prevention (DLP) for Exchange Online, SharePoint Online, and OneDrive for Business
- Microsoft Purview Information Protection: Data Loss Prevention (DLP) for Teams

A summary of licence information is shown on the on the Get started with Endpoint data loss prevention page https://docs.microsoft.com/en-us/microsoft-365/compliance/endpoint-dlp-getting-started?view=o365-worldwide. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#information-protection-data-loss-prevention-for-exchange-online-sharepoint-online-and-onedrive-for-business)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi Nikki, I forwarded your request to the product team, and I'll keep you posted on response.

**Comment by annferre** [comment]
Hi there, the document has been updated. Thank you for your comment. Please reopen if you have further questions. https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#microsoft-purview-information-protection-purview-data-loss-protection-dlp
