### ISSUE TITLE
Licencing query on the Licensing for retention policies section

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#737]
I have a licencing query on the Licensing for retention policies section (not the Teams chat part) and the information shown in the [Microsoft 365 Comparison table for Small and Medium Business](https://aka.ms/M365BusinessPlans)

Business Premium includes Exchange Online 1 and SharePoint One 1 licensing. 
The section on Licensing for retention policies section does not include the Business Premium , Exchange Online 1 or SharePoint One 1 licensing.  See quote below.

> > Licensing for retention policies
> For organization-wide, location-wide, or include/exclude retention policies, the following licenses provide user rights:
> 
> Microsoft 365 E5/A5/G5/E3/A3/G3
> Microsoft 365 E5/A5/G5/F5 Compliance and F5 Security & Compliance
> Microsoft 365 E5/A5/F5/G5 Information Protection and Governance
> Office 365 E5/A5/G5/E3/A3/G3
> If the retention policy location is an Exchange mailbox, then the following licenses also provide user rights:
> 
> Exchange Plan 2
> Exchange Online Archiving
> If the retention policy location is SharePoint or OneDrive for Business, the following licenses also provide user rights:
> 
> SharePoint Plan 2

However the link at the top of the page to the Microsoft 365 Comparison table for Small and Medium Business] PDF shows that Business Premium does get a Basic org-wide or location-wide retention policies

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#information-protection-office-365-message-encryption)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi Nikki, thank you for your comment. I have forwarded your request to the product team, and I'll get back to you as soon as possible.
