### ISSUE TITLE
Missing information in the Microsoft Purview Information Protection: Sensitivity labeling section about Authentication contexts 

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#738]
Please can you add in the following information to the Microsoft Purview Information Protection: Sensitivity labeling section for Authentication contexts are used with sensitivity labels which in preview and due to go GA this year.

Manage site access based on sensitivity label
With [Azure Active Directory authentication context (preview)](https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/concept-conditional-access-cloud-apps#configure-authentication-contexts), you can enforce more stringent access conditions when users access SharePoint sites that have a sensitivity label applied.

Authentication contexts are used with sensitivity labels to connect [Azure AD conditional access policies](https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/overview) to labeled sites.

Using authentication context with SharePoint sites requires at least one of the below licenses:

Office 365 E5
Office 365 A5 for faculty
Office 365 A5 for students
Microsoft 365 E5
Microsoft 365 E5 Compliance
Microsoft 365 E5 Information Protection and Governance
Microsoft 365 Security And Compliance For FLW
Microsoft 365 A5 for faculty
Microsoft 365 A5 for students

Full details are here https://docs.microsoft.com/en-gb/sharepoint/authentication-context-example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi Nikki, I forwarded your request to the product team. I'll let you know as soon as I receive a response. Thank you for your comment.
