### ISSUE TITLE
Update needed in section Microsoft Purview Information Protection: Sensitivity labeling for labeling Teams groups and sites

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#739]
The section Microsoft Purview Information Protection: Sensitivity labelling states

> Information Protection helps organizations discover, classify, label, and protect sensitive documents and emails. Admins can define rules and conditions to apply labels automatically, users can apply labels manually, or a combination of the two can be used—where users are given recommendations on applying labels.
> 
> How do users benefit from the service?
> Users benefit by having the ability to manually apply sensitivity labels to their content or by having their content automatically classified.

There is no mention that sensitivity labels can also protect content in Microsoft Teams, Microsoft 365 groups, and SharePoint sites. reference page https://docs.microsoft.com/en-gb/microsoft-365/compliance/sensitivity-labels-teams-groups-sites?view=o365-worldwide.

Please can the first two paragraphs be updated to

> > Information Protection helps organizations discover, classify, label, and protect sensitive documents and emails.  Admins can define rules and conditions to apply labels automatically, users can apply labels manually, or a combination of the two can be used—where users are given recommendations on applying labels.  In addition, information Protection can be used to protect Teams, Groups and sites (containers).
> 
> How do users benefit from the service?
> Users benefit by having the ability to manually apply sensitivity labels to their content and containers or by having their content automatically classified.

Also if the licensing rule should be clarified. Currently, it states 

> For manual sensitivity labelling, the following licenses provide user rights:

I am assuming this is manual labelling for both content and container. If this is correct can the sentence explicitly state content and container labels. However, if there are different licencing conditions for containers labelling this should be detailed in another section

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi Nikki, I forwarded your request to the product team. I'll let you know as soon as I receive a response. Thank you for your comment.
