### ISSUE TITLE
Domain Limits is mssing can you please add and confirm

### ISSUE THREAD

**Issue by Ramonin** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#74]
I bleive we have a limit of 900 SMTP Domains.  Can you add and check

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#receiving-and-sending-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by prabita** [comment]
@Ramonin Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response

**Comment by SharS** [comment]
@Ramonin Article was updated with this information.

**Comment by Ramonin** [comment]
Thanks I don’t see the change yet – should it be there already


Ramon Infante
Principal Program Manager
M365 and Secruity Group

Microsoft
Office: +1 (425)538-0610
Mobile: 201-647-4962
ramonin@microsoft.com<mailto:ramonin@microsoft.com>

For Office 365 Networking
https://aka.ms/O365Networking

For Office 365 ExpressRoute review process  - https://aka.ms/ErGuidance

For O365 network bandwidth meter
https://aka.ms/bandwidth

New Connectivity tool
http://connectivity.office.com<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fconnectivity.office.com&data=04%7C01%7CRamon.Infante%40microsoft.com%7Cbd37225ed6f24d1ae9d308d6b481b354%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636894866485804492%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=hl4ig5q9%2Bh7BsJU2rnFrF3KfrPzI9gRYxx9l3Wp%2Bk9I%3D&reserved=0>



[http://mysignature.azureedge.net/files/L_Microsoft.png]
[CHANGE  PRACTITIONER  Prosci]
