### ISSUE TITLE
Licensing for retention policies does not align with the Microsoft 365 Comparison table for Small and Medium Business Plans.

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#740]
The Business Premium Licensing for retention policies section does not align with the Microsoft 365 Comparison table for Small and Medium Business Plans which is shown at the top of the page and links here https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWR6bM. 

The section shown below for Licensing for retention policies does not include Business Premium licencing so I am assuming they are not entitled to the organization-wide, location-wide, or include/exclude retention policies.

> > Licensing for retention policies
> For organization-wide, location-wide, or include/exclude retention policies, the following licenses provide user rights:
> 
> Microsoft 365 E5/A5/G5/E3/A3/G3
> Microsoft 365 E5/A5/G5/F5 Compliance and F5 Security & Compliance
> Microsoft 365 E5/A5/F5/G5 Information Protection and Governance
> Office 365 E5/A5/G5/E3/A3/G3
> If the retention policy location is an Exchange mailbox, then the following licenses also provide user rights:
> 
> Exchange Plan 2
> Exchange Online Archiving
> If the retention policy location is SharePoint or OneDrive for Business, the following licenses also provide user rights:
> 
> SharePoint Plan 2

Also Business Premium licencing only has Exchange plan 1 and SharePoint plan 1 so is not covered under the other headings.

However when you view the link to the [Microsoft 365 Comparison table for Small and Medium Business](https://aka.ms/M365BusinessPlans) Plans it shows the Business premium licences has the Basic org-wide or location-wide retention policies in addition to retention labelling and Team message retention policies.

![image](https://user-images.githubusercontent.com/69439002/189238102-ff988523-3032-43af-ac77-b66b9393e480.png)

Please can we have clarification of licences as it is very confusing trying to get to the single source of truth when two documents show different functionality in scope

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#microsoft-purview-information-protection-sensitivity-labeling)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi Nikki, I forwarded your request to the product team. I'll let you know as soon as I receive a response. Thank you for your comment.

**Comment by annferre** [comment]
Hi Nikki, Business Premium has been added to the licensing information (see below) . Please reopen if you have further questions or concerns. Thanks again for your comment.

**Licensing for retention policies**
SharePoint Plan 2
If the retention policy location is Microsoft Teams chats, channels, or private channels, then the following licenses also provide user rights. The retention or deletion period must be more than 30 days for the plans that are underlined:

Microsoft 365 E5/G5/A5/E3/G3/A3/F3/F1, Business Basic, Business Standard, and **Business Premium**
Office 365 E5/G5/A5/E3/G3/A3/F3/E1/G1
Microsoft 365 F5 Compliance and Microsoft 365 F5 Security and Compliance add-on plans
If the retention policy uses an adaptive policy scope, then one of the following licenses is required to provide user rights:

For retention label creation, the following licenses provide user rights:

Microsoft 365 E5/A5/G5/E3/A3/G3/F3/F1/**Business Premium**
Microsoft 365 E5/A5/G5/F5 Compliance and F5 Security & Compliance
Microsoft 365 E5/A5/F5/G5 Information Protection and Governance
Office 365 E5/A5/G5/E3/A3/G3/F3/E1/A1/G1

To publish retention labels, the following licenses provide user rights:

Microsoft 365 E5/A5/G5/E3/A3/G3/F3/F1/**Business Premium**
Microsoft 365 E5/A5/G5/F5 Compliance and F5 Security & Compliance
Microsoft 365 E5/A5/F5/G5 Information Protection and Governance
Office 365 E5/A5/G5/E3/A3/G3/F3/E1/A1/G1
