### ISSUE TITLE
Information Barriers Required Licensing Incorrect

### ISSUE THREAD

**Issue by davidfox2** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#741]
I believe the following section on Information Barriers are now available all the way down to A1 licenses based on a change this past year when they left public preview? The current section indicates E5/A5:
https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#which-licenses-provide-the-rights-for-a-user-to-benefit-from-the-service-14

The implementation documentation located here indicates down to A1 
https://docs.microsoft.com/en-us/microsoft-365/compliance/information-barriers-policies?view=o365-worldwide

Unless this was limited to just education offerings?
We had received confirmations from Microsoft reps that it was now A1 eligible. 

Thanks,
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi Nikki, I forwarded your request to the product team. I'll let you know as soon as I receive a response. Thank you for your comment.

**Comment by annferre** [comment]
Thank you for your comment. You are correct in regards to A1. We are in the process of updating the page.
