### ISSUE TITLE
Locale shouldn't be included in link

### ISSUE THREAD

**Issue by ChrisKibble** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#742]
https://www.microsoft.com/en-in/microsoft-365/enterprise/compare-office-365-plans should remove the "en-in" so that language redirection happens naturally.  Other DOC links include en-us that should be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f448a5a2-1307-bf89-c910-9bc03840afde
* Version Independent ID: d99ca5b3-1b4b-6af2-d3c9-dc4cd1afaac3
* Content: [Microsoft 365 and Office 365 service descriptions - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-service-descriptions-technet-library)
* Content Source: [Office365-ServiceDescriptions/office-365-service-descriptions-technet-library.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-service-descriptions-technet-library.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for your comment. I have forwarded your request to pubops to update the page. Thanks again.

**Comment by annferre** [comment]
Hi there, I just wanted to let you know we fixed the links. Thanks again for your comment.
