### ISSUE TITLE
"Power Map" is now "3D Maps"

### ISSUE THREAD

**Issue by anhage** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#743]
In the section "Office application availability and enterprise value", one of the listed items is "Power Map for Excel". This is now called "3D Maps" (https://support.microsoft.com/en-us/office/get-started-with-3d-maps-6b56a50d-3c3e-4a9e-a527-eea62a387030)

I propose that line item should be changed to:
3D Maps (Power Map for Excel)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3ab3187-c403-8fb1-6ee7-56818777fdad
* Version Independent ID: f6b28482-bf80-436e-cb8f-facb974c24ec
* Content: [Office 365 US Government - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government#office-application-and-feature-availability-in-government-plans)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for your comment. I have forwarded your request to the product team. I'll keep you posted on response.

**Comment by annferre** [comment]
Hi Ann, Updates have been completed and confirmed live. Closing. Thanks again for your comment.
