### ISSUE TITLE
Desktop Push Notifications not listed in "Exchange Online Features"

### ISSUE THREAD

**Issue by rvtdadmin** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#744]
Desktop Push Notifications for "Outlook on the Web" do not work in any GCC tenant.
Per [Case #:31181564] we opened with 365 support. 
They said Desktop Email Notifications are not intended to work with GCC.
It is not listed at all as a GCC feature on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ff8bcc8-4789-dc65-c108-ee0641c7c3b7
* Version Independent ID: 20fff9c3-700c-30f1-0714-535957ef40e9
* Content: [Exchange Online for US government environments - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/exchange-online-for-us-government-environments#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/exchange-online-for-us-government-environments.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/exchange-online-for-us-government-environments.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for your comment. I have forwarded your request to the product team and I'll get back to you as soon as I receive a response.

**Comment by annferre** [comment]
Hi there, is this what you are referring to, or is there something else?
<img width="470" alt="image" src="https://user-images.githubusercontent.com/86699727/196750722-0c5d8144-132d-4312-8bc4-c415e503eb3a.png">

**Comment by rvtdadmin** [comment]
Hello, that would not be it as that is in regard to Microsoft To Do.

It is Windows Desktop Push Notifications when a new email is received on Outlook on the Web that does not work.
If it is truly by design that they do not work for GCC as the product team has stated we would expect Push Notifications to be listed in the Exchange Online Features.
It is a pretty significant functionality for Outlook on the Web that you don't get email notifications and is surprising it wouldn't be listed.  
Thanks for your help
