### ISSUE TITLE
Hold limits does not include litigation holds.

### ISSUE THREAD

**Issue by tyamauch1** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#745]
[Enter feedback here]
We verified that you can create litigation holds of more than 10,000 mailboxes, so litigation holds should not be included in the 10,000 per tenant maximum for compliancy policies.
We are aware of no mention of such a restriction being applied, nor has it ever been publicized in the Microsoft 365 message center.
If litigation holds are still included in the 10,000 per tenant maximum for compliancy policies, please describe in Docs how the policy counts when litigation holds are enabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for your comment. I have forwarded your request to the product team, and I"ll get back to you as soon as I get a response. THanks again!

**Comment by annferre** [comment]
Hi there, I did confirm with the product team, and we are removing Litigation hold from the "Holds limits" section. I'll let you know once this is live. Thank you again for your request.

**Comment by tyamauch1** [comment]
Thank you for your support.
As for the following URL, there is the same litigation hold limitation statement, please remove the litigation hold statement at the same time.
https://learn.microsoft.com/en-us/microsoft-365/compliance/retention-limits?view=o365-worldwide#maximum-number-of-policies-per-tenant
-----
 Note

These maximum numbers for Exchange and SharePoint are not exclusive to retention but are shared with other types of hold policies that include eDiscovery holds, **Litigation holds**, and In-Place Holds.
-----

**Comment by annferre** [comment]
Hi there, I just wanted to let you know the page has been updated. The second request for change is on a page I don't own/manage, so I'm closing out the ticket. However, I am emailing the page owner to see if they can assist in updating the page and I'm ccing you. Thanks again for your comment.
