### ISSUE TITLE
Premium eDiscovery license clarification

### ISSUE THREAD

**Issue by bubhat** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#747]
State and Local customers perform a lot of public records requests and want to leverage Premium eDiscovery. They do not add custodians or non custodians because their searches are targeted towards an entire department or tenant. Most of the times, they don't want to put content on hold, but only search keywords through collections & then upload it to review set. This article [here ](https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#how-can-the-service-be-applied-only-to-users-in-the-tenant-who-are-licensed-for-the-service-11)says custodians need to be licenced with G5/G5 compliance etc. My understanding is that all custodians/non custodians or any user or shared mailbox whose content is targeted through collections need to be licensed for Premium eDiscovery. But this is not clearly documented and creates a lot of confusion with our customers. Can you please clarify the license requirements for Premium eDiscovery?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#how-can-the-service-be-applied-only-to-users-in-the-tenant-who-are-licensed-for-the-service-11)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, I checked with the product team, and I have the following update:
You are correct regarding the need for license for each user that accesses/benefits from a service. As stated in the Product Terms [https://www.microsoft.com/licensing/terms/product/ForOnlineServices/EAEAS](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Flicensing%2Fterms%2Fproduct%2FForOnlineServices%2FEAEAS&data=04%7C01%7CTiffany.Gilbert%40microsoft.com%7Ccaa54a5382164d81633408d9f0b26f98%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637805471432942093%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3AQs7GYoQM7Y%2BaYWP1r070muZqvQWw4Q4YHd3AMgSys%3D&reserved=0)

Customers must acquire and assign the appropriate subscription licenses required for its use of each Online Service. Each user that accesses the Online Service must be assigned a User SL…..

This was the intent of the language in the eDiscovery section, and by stating “eDiscovery administrators can select specific users as data custodians….” It was to provide a link on how admins can do this. Not to state that these are the only users that need to be licensed. We will update this section for clarity.
