### ISSUE TITLE
incorrect information

### ISSUE THREAD

**Issue by AKeeler-MSFT** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#748]
[Enter feedback here]
The line for PowerPoint:
"Insert text, sticky notes and images"

is incorrect. There is not a way to insert sticky notes into PPT and Sticky Notes are not supported in GCC, GCC-High or DOD. Guessing maybe it was intended to be slide notes?

It would also be useful to include the unsupported status of Sticky Notes.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b3ab3187-c403-8fb1-6ee7-56818777fdad
* Version Independent ID: f6b28482-bf80-436e-cb8f-facb974c24ec
* Content: [Office 365 US Government - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government?source=docs)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, the feature you are inquiring about is listed under Microsoft Whiteboard. I have reached out to the Whiteboard team to confirm regarding Gov availability. Thank you for your comment.

**Comment by annferre** [comment]
Hi there, I did confirm with the Microsoft Whiteboard team that this is correct, so I won't be making changes to the page. I will, however ask the PowerPoint team about adding "sticky notes" to the PowerPoint section.

**Comment by AKeeler-MSFT** [comment]
What is correct?

I do have Microsoft internal content that specifically states that Sticky Notes is unsupported for GCC/GCC-High/DOD and also tested that I cannot sign into Sticky notes with my GCC or GCC-High test accounts.

I delivered this information to a customer, and they referred me to this article which seems to indicate we would support it which in this scenario would be wrong.

As we seem to know that Sticky Notes is not supported, other than maybe in an unsupported offline capacity, it would be helpful to have this included in this article.

For the Insert Sticky Notes into PPT, I cannot find a way to do that regardless of what account type I use and I am on the team that supports PowerPoint, possibly I am wrong but if I am it would be helpful to have more information on the steps required to do that so we can test further.

Thanks,
Andy
