### ISSUE TITLE
Clarity for Data Lifecylce Management/Records Management

### ISSUE THREAD

**Issue by MichaelRyan87** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#750]
Hi There,

Should the tables also cover Data Lifecycle Management and Records Management?

The general licensing page for compliance products only covers the full licenses not the details for student use benefit versions - https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#microsoft-purview-data-lifecycle-management--microsoft-purview-records-management

From review, your table suggests that for AIP auto-labelling a full A5 license is required, the student use benefit won't cut it. Is this the same for the above-mentioned products?

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f8328da3-5093-09b6-9b9b-b92d13625219
* Version Independent ID: f2171de5-bfa5-65d1-4615-30db23349b40
* Content: [Microsoft 365 Education - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your comment! I have forwarded your request to the product team and I'll keep you posted on the response. Thanks again!
