### ISSUE TITLE
G5 Delve

### ISSUE THREAD

**Issue by carlova** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#751]
Platform features - Delve- Footnote 15 is included on G1, G3, and F3. I believe it should also be included on G5. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b3ab3187-c403-8fb1-6ee7-56818777fdad
* Version Independent ID: f6b28482-bf80-436e-cb8f-facb974c24ec
* Content: [Office 365 US Government - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government?source=docs)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/office-365-us-government.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your comment! I have forwarded your request to the product team and I'll keep you posted on the response. Thanks again!

**Comment by annferre** [comment]
Hi there, I just wanted to let you know that you are correct, and we'll be updating the service description page. I'll let you know when the change is live. Thanks!
