### ISSUE TITLE
contradiction regarding Email archiving

### ISSUE THREAD

**Issue by takeakitake** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#752]
This is written "Email archiving" section in this page.
https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#microsoft-purview-data-lifecycle-management--microsoft-purview-records-management
-------------------------------
・To enable an archive mailbox and auto-expanding archive, the following licenses provide user rights:

    Archive mailbox limited to 50 GB
        ・Exchange Online Archiving
        ・Office 365 E1
        ・Microsoft 365 Business Premium
-------------------------------

There are contradictions in this page for Exchange Online Archiving.
There are written 2 points. It is not restricted to 50 GB.

1. The archiving feature (called auto-expanding archiving) provides additional storage space in archive mailboxes, up to a maximum of 1.5 TB.
2. Each Exchange Online Archiving subscriber initially receives 100 GB of storage in the archive mailbox.

Exchange Online Archiving service description
https://learn.microsoft.com/en-us/office365/servicedescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description
-------------------------------
Archive storage quota
Administrators can't adjust the storage quota. The archiving feature (called auto-expanding archiving) provides additional storage space in archive mailboxes, up to a maximum of 1.5 TB. Each Exchange Online Archiving subscriber initially receives 100 GB of storage in the archive mailbox. When auto-expanding archiving is turned on, additional storage space is automatically added when the 100 GB storage capacity is reached. In Exchange hybrid deployments, auto-expanding archiving is only supported for cloud-based archive mailboxes when the on-premises user's mailbox resides on Exchange Server 2019, Exchange Server 2016, or Exchange Server 2013 SP1 and later.
-------------------------------

And in this pdf file indicates that we can use "userAuto-expanding email archive" in Microsoft 365 Business Premium.

https://aka.ms/M365BusinessPlans

If Archive mailbox limited to 50 GB in Microsoft 365 Business Premium, you should explain in this pdf file too.

This pdf file is linked from left pane of Service Description page like this.
https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-service-descriptions-technet-library

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#microsoft-purview-audit-premium)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your comment. I have reached out to the product team, and I will keep you posted on their response.

**Comment by annferre** [comment]
Hi there, I have confirmed it is 1.5. I'll be sending a request to PubOps to update the page. Thank you for your comment.

**Comment by annferre** [comment]
Hi there, I just wanted to let you know the updated text is live. Thanks again for your comment.
