### ISSUE TITLE
GCC note/date

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#753]
> Attack simulation training is now available in WW and GCC (will be in GCC from June 21).

"is now available in WW and GCC" and "will be in GCC" are contradictory. If it is now available, can the stuff in the parenthesis be removed?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d4178aae-6e59-80d3-606b-23e53ea7865c
* Version Independent ID: dd502084-a5a7-136c-63ed-2b137f873707
* Content: [Microsoft Defender for Office 365 Features service description - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-defender-for-office-365-features#attack-simulation-training)
* Content Source: [Office365-ServiceDescriptions/microsoft-defender-for-office-365-features.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-defender-for-office-365-features.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your comment. I will work with the product team on trying to resolve the issue.

**Comment by annferre** [comment]
Hi there, we're updating the document to the below. Also, I'm looking into the status of Attack Simulation for GCC High. If it's available, we will update the document. Thanks!
Attack simulation training is available in WW and GCC. If your organization has Office 365 G5 GCC or Microsoft Defender for Office 365 (Plan 2) for Government, you can use Attack simulation training in the Microsoft 365 Defender portal to run realistic attack scenarios in your organization as described in [this article](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/attack-simulation-training-get-started?view=o365-worldwide). Attack simulation training is not yet available in GCC High or DoD environments.
