### ISSUE TITLE
Limits to Site Collections under /Sites/

### ISSUE THREAD

**Issue by don-matese** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#755]
Is there a limit to how many site collections can be held within the /Sites/ collection directly? i.e. can we have 100,000 site collections under /sites/ or are they also limited to 2000?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint limits - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits#lists-and-libraries)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, I have sent your question to the product team, and I'll get back to you as soon as I receive a response. Thanks!

**Comment by annferre** [comment]
Hi there, can you clarify a little further. Below is the response from the product team.
_The question is not quite clear. I don’t know what this “/sites/” means. If the customer is asking how many site collections a tenant can contain, then it is not this 2000 limit. Site collection cannot live in any other object._

**Comment by annferre** [comment]
Please reopen if you have further questions. Thanks!
