### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by xhoy** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#756]
in the table [Features available to some plans](https://learn.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description#features-available-to-some-plans) the links to Exchange Online Archiving for Exchange Online and Exchange Online Archiving for Exchange Server 

return a 404 page. I think one of the links should be: https://learn.microsoft.com/en-us/office365/servicedescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c2f622a7-32c1-2c35-2df9-ddf1bc74c74d
* Version Independent ID: e37d85d2-8b81-0c64-b7d0-1e8c01b303db
* Content: [Exchange Online service description - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your comment. I have reached out to the product team for the correct links, and I'll update the document as soon as I have those. Thanks again!

**Comment by SeanGit88** [comment]
Hello, this has been updated. Thanks for your feedback!
