### ISSUE TITLE
Does Online Archiving for Exchange online still include in-place hold and litigation hold?

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#757]
Footnote2 gives me a 404 page not found error - In-Place Hold and Litigation Hold
> 2 For more information, see Exchange Online limits. Exchange Online Archiving for Exchange Online add-on adds auto-expanding archiving and In-Place Hold and Litigation Hold.

This is probably from the Purview rename. [This](https://learn.microsoft.com/en-us/microsoft-365/compliance/ediscovery?view=o365-worldwide) is the new eDiscovery article. The new article does not say Exchange online Archiving includes content search, or either eDiscovery feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5c55dc71-81ed-864b-ac3f-63ce84688070
* Version Independent ID: 578c9a02-045e-4bf9-6384-d70560c332f0
* Content: [Exchange Online Archiving service description - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description)
* Content Source: [Office365-ServiceDescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, I have reached out to the product team, and I'll let you know as soon as I receive a response. Thanks!
