### ISSUE TITLE
Contradiction regarding Email archiving 2 (for EOA)

### ISSUE THREAD

**Issue by takeakitake** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#758]
"Exchange Online Archiving" is remaining in "Archive mailbox limited to 50 GB" part. Is this correct?

There are contradictions in this page for Exchange Online Archiving.

Exchange Online Archiving service description
https://learn.microsoft.com/en-us/office365/servicedescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description
-------------
Archive storage quota
Administrators can't adjust the storage quota. The archiving feature (called auto-expanding archiving) provides additional storage space in archive mailboxes, up to a maximum of 1.5 TB. Each Exchange Online Archiving subscriber initially receives 100 GB of storage in the archive mailbox. When auto-expanding archiving is turned on, additional storage space is automatically added when the 100 GB storage capacity is reached. In Exchange hybrid deployments, auto-expanding archiving is only supported for cloud-based archive mailboxes when the on-premises user's mailbox resides on Exchange Server 2019, Exchange Server 2016, or Exchange Server 2013 SP1 and later.
-------------

There are written 2 points, and both indicate do not restricted size to 50 GB.

1. The archiving feature (called auto-expanding archiving) provides additional storage space in archive mailboxes, up to a maximum of 1.5 TB.
2. Each Exchange Online Archiving subscriber initially receives 100 GB of storage in the archive mailbox.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#microsoft-purview-data-lifecycle-management--microsoft-purview-records-management)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for the comment. We will be updating the service description with the below. I'll let you know as soon as it's updated. Thanks again! 
•	Archive mailbox limited to 50 GB
  o	Exchange Online Plan 1
  o	Office 365 E1
•	Archive mailbox limited to 1.5 TB
  o	Exchange Online Archiving
  o	Exchange Online Plan 2
  o	Microsoft 365 E5/A5/G5/E3/A3/G3
  o	Microsoft 365 E5/A5/G5/F5 Compliance and F5 Security & Compliance
  o	Microsoft 365 E5/A5/F5/G5 Information Protection and Governance
  o	Office 365 E5/A5/G5/E3/A3/G3
  o	Microsoft 365 Business Premium

**Comment by takeakitake** [comment]
Thank you! I relief to know EOA has 1.5 TB storage.
If possible, please add Microsoft 365 Business Basic and Microsoft 365 Business Standard. It will help other customers.
