### ISSUE TITLE
Clarifying Sensitivity labeling on M365 Apps for Enterprise

### ISSUE THREAD

**Issue by LucioBenzor** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#759]
Wanted to ask if the Product team would consider modifying the verbiage around sensitivity labeling to note that Sensitivity labeling is not supported on per-device O365 licensing like M365 Apps for Enterprise even if F3/F5/M365 E3/M365 E5 users are interacting with the application and signed in. 

Looking at the [documentation](https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#microsoft-purview-information-protection-sensitivity-labeling) on licensing guidance, this isn't a limitation mentioned so customers assume it's a supported deployment model.

Here's an example of a user finding this out while interacting with our support, customer engineering, and product team: https://www.yammer.com/askipteam/threads/1560778648174592 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#microsoft-purview-information-protection-sensitivity-labeling)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Thank you for your request. I have reached out to the product team, and I'll get back to you as soon as I receive a response.

**Comment by SeanGit88** [comment]
Hello, this guidance has been updated. thanks again for your feedback.
