### ISSUE TITLE
Transport rule limit

### ISSUE THREAD

**Issue by JeroenDronkers** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#76]
This article says: "The transport rule limits also apply to EOP standalone customers."
However the entire article does not speak about Transport rule limits...
I suggest to add information regarding Transport rules limits in Office 365. For example:
https://blogs.technet.microsoft.com/eopfieldnotes/2014/10/27/transport-rule-limit-increase/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5013ccda-a0c6-ce6c-73e7-c78187008f55
* Version Independent ID: a2233d27-d1b1-23af-776b-b860eb1f79b6
* Content: [Exchange Online Protection Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-protection-service-description/exchange-online-protection-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-protection-service-description/exchange-online-protection-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-protection-service-description/exchange-online-protection-limits.md)
* Service: **o365-administration**
* GitHub Login: @pebaum
* Microsoft Alias: **pebaum**

**Comment by prabita** [comment]
@JeroenDronkers Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response

**Comment by SharS** [comment]
Thank you for your feedback. Transport rule limits are documented in the Exchange Online Limits Service Description (https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits)
