### ISSUE TITLE
Linked content not available

### ISSUE THREAD

**Issue by ferringer** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#761]
This article links to another Microsoft article titled "Reporting and message trace in Exchange Online Protection" but that link appears to be broken or no longer exist... I believe it may need to be updated to target [Monitoring, reporting, and message tracing in Exchange Online](https://learn.microsoft.com/en-us/exchange/monitoring/monitoring).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#reporting-and-message-trace-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by annferre** [comment]
Hi there, thank you for your comment. I have reached out to the product team for an updated link. I'll get back to you as soon as the new link is live. Thanks again!

**Comment by SeanGit88** [comment]
Hello, the link has been updated.   thanks for your feedback.
