### ISSUE TITLE
Inactive Mailboxes available for F5 Compliance or not?

### ISSUE THREAD

**Issue by JonesMikael** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#762]
The article regarding **Inactive Mailboxes** (https://learn.microsoft.com/en-us/microsoft-365/compliance/inactive-mailboxes-in-office-365?view=o365-worldwide) it says:

> But if a hold is applied to the mailbox prior to deleting the Microsoft 365 account, the mailbox will be converted into an inactive mailbox.

**F5 Compliance** enables you to apply a hold on a mailbox using various methods (Retention Policies, Litigation Hold) so that would give you the impression that "_the mailbox will be converted into an inactive mailbox_".

However, if you check the PDF (https://aka.ms/M365EnterprisePlans) and scroll up to the first page regarding, **Inactive Mailboxes** is mentioned as NOT supported for F5 Compliance.

Is this true or a mistake? I think this does not really make sense to exclude that small feature  if you put the mailbox on hold.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by SeanGit88** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by SeanGit88** [comment]
Hello, this has been updated. thanks for your feedback.
