### ISSUE TITLE
Defender for Office licensing terms seem vague, could need clarification or calculation examples

### ISSUE THREAD

**Issue by DMoenks** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#764]
The statements in the [Licensing terms](https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description#licensing-terms) section seem to be the most detailed official licensing information available, as even the Product Terms and Licensing Documents portals refer here at multiple points, although those statements seem to be vague when taking a closer look.

- The second statement in each list seems to be the most concise, as _shared mailbox_ is as indisputable as it gets.
- The third and fourth statements in each list seem to be comparably concise, as _user_ seems well-defined when it comes to Office services other than Exchange Online.
- The first statement in each list seems far less concise though, as _user_ can mean different things in Exchange Online:

  - Does it mean the possible values of _RecipientTypeDetails_ retrieved when calling _Get-User_?
  - Does it mean the possible values of _RecipientTypeDetails_ mentioned in the _User_ section found at [Recipients in Exchange Online](https://learn.microsoft.com/en-us/exchange/recipients-in-exchange-online/recipients-in-exchange-online)?
  - Does it mean the values of _RecipientTypeDetails_ mentioned in the configuration documentation for [anti-phishing](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-mdo-anti-phishing-policies?view=o365-worldwide#use-the-microsoft-365-defender-portal-to-create-anti-phishing-policies), [Safe Attachments](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-safe-attachments-policies?view=o365-worldwide#use-the-microsoft-365-defender-portal-to-create-safe-attachments-policies) and [Safe Links](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-safe-links-policies?view=o365-worldwide#use-the-microsoft-365-defender-portal-to-create-safe-links-policies)?
  - Does it include team members when a team's mailbox is in scope of a protection policy?
  - Does it even include team mailboxes themselves when they're in scope of a protection policy?

Depending on the answers to above questions, the number of necessary licenses might vary by hundreds or thousands even for mid-sized companies.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 502796e9-ca73-7123-7719-c7b5b1042b7b
* Version Independent ID: 2929af88-6d56-4de3-2b4e-4e1d0e4d97ef
* Content: [Microsoft Defender for Office 365 service description - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by SeanGit88** [comment]
Thanks for your comments. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by SeanGit88** [comment]
Thanks for your additional comments.

**Comment by SeanGit88** [comment]
From the team:  "We trust in our customers to determine that they are compliant and we ask that licenses be acquired for any user that intends to benefit from and/or access the service. "
