### ISSUE TITLE
Safe Documents enabled by default

### ISSUE THREAD

**Issue by theonlybrand** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#765]
The "Safe Documents" feature is enabled when creating a new tenant. Tested on two CDX tenants (one Enterprise, one Business Premium). Documentation states "This feature is off by default and will need to be enabled by the Security Administrator."

Should be changed IMO.

https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-defender-for-office-365-features#safe-documents

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by SeanGit88** [comment]
Hello, this has been updated. thanks for your feedback.
