### ISSUE TITLE
[Sentence update] Regarding to applicable device screen size for Office 365.

### ISSUE THREAD

**Issue by saburok** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#766]
[Enter feedback here]
I see screen size description as **10.1** inches at this page.
https://learn.microsoft.com/en-us/office365/servicedescriptions/office-applications-service-description/office-applications-service-description 
===
4 Limited to devices with integrated screens measuring 10.1 inches or less diagonally.
===

But from Product Term, we can see applicable screens size are allowed to **10.9'** for Office 365 A1, E1, F3 and Business Basic.
https://www.microsoft.com/licensing/terms/en-US/productoffering/Office365Suites/EAEAS

====
Smartphone and Tablet Devices
Each Office 365 A1, E1, F3, and Business Basic user to whom Customer assigns a User SL may (i) use Microsoft Office for mobile devices for commercial purposes and (ii) sign into Microsoft Office with their org ID on up to five smartphones and five tablets with integrated screens 10.9” diagonally or less.
====

So would you double check and update for service description page sentence from 10.1 inch to 10.9' ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 128805e7-b1a4-5cdf-1890-8794fa46d5d5
* Version Independent ID: 884c3ae0-9317-d37c-f94f-97aabd0e622d
* Content: [Office applications service description - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/office-applications-service-description/office-applications-service-description)
* Content Source: [Office365-ServiceDescriptions/office-applications-service-description/office-applications-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-applications-service-description/office-applications-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will update the article as necessary based on their response.
