### ISSUE TITLE
Add Microsoft Purview Retention Policy line item

### ISSUE THREAD

**Issue by Smartboss88** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#767]
Need to add a row about Microsoft Purview Retention Policy (Hold) and match the row with the In-place Hold so that it clearly says that F3 does not support it.

![image](https://user-images.githubusercontent.com/48076085/204837766-3f977879-4992-43ec-a8a4-82a6161b2c87.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c2f622a7-32c1-2c35-2df9-ddf1bc74c74d
* Version Independent ID: e37d85d2-8b81-0c64-b7d0-1e8c01b303db
* Content: [Exchange Online service description - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description?source=docs)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by ScottSchnoll** [comment]
Hi @Smartboss88, I'm not sure that change is warranted.  According to https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#licensing-for-retention-labels, F3 is supported.  Can you share why you believe it is not supported?  Thanks!

**Comment by Smartboss88** [comment]
Hi Scott, I’m talking about Retention Policy in Purview not Retention Labels. Microsoft 365 guidance for security & compliance - Service Descriptions | Microsoft Learn The root of the question came from, can F3 licensed assigned mailbox be converted to inactive mailbox.  We say F3 can’t do inplace hold and lit hold but we never said it can’t do Retention Policy in Purview so does that mean F3 licensed mailbox can be converted to inactive?  If not, then we should say so in the table that F3 cannot use Retention Policy in Purview to Retain. Sent from Mail for Windows From: Scott SchnollSent: Friday, December 2, 2022 12:53 PMTo: MicrosoftDocs/OfficeDocs-O365ServiceDescriptionsCc: Smartboss88; MentionSubject: Re: [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions] Add Microsoft Purview Retention Policy line item (Issue #767) Hi @Smartboss88, I'm not sure that change is warranted. According to https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#licensing-for-retention-labels, F3 is supported. Can you share why you believe it is not supported? Thanks!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
