### ISSUE TITLE
Incorrect URL on hyperlink

### ISSUE THREAD

**Issue by csovde** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#768]
The hyperlinks in the following paragraph both link to the 'In-Place Hold and Litigation Hold' page.

'Exchange Online Limits' should link to https://learn.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits

<img width="848" alt="image" src="https://user-images.githubusercontent.com/45495486/205779843-9141589b-b5f1-4cd8-87fa-727286190932.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5c55dc71-81ed-864b-ac3f-63ce84688070
* Version Independent ID: 578c9a02-045e-4bf9-6384-d70560c332f0
* Content: [Exchange Online Archiving service description - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description)
* Content Source: [Office365-ServiceDescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by SeanGit88** [comment]
Hello, this has been updated. thanks for your feedback.
