### ISSUE TITLE
Online archive for on premise mailbox

### ISSUE THREAD

**Issue by kgazar** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#77]
is it possible to enable online archive feature for mailbox that exist on hosted exchange? supposing that exchnage hybrid is configured

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e0ba987-5e52-0e0d-f9f8-d6da3feaa53c
* Version Independent ID: 5763ce54-2c7c-8956-f44e-c946d0c9a5c4
* Content: [Archive Features in Exchange Online Archiving](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-archiving-service-description/archive-features)
* Content Source: [Office365-ServiceDescriptions/exchange-online-archiving-service-description/archive-features.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-archiving-service-description/archive-features.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by markjjo** [comment]
@kgazar Yes. Please see https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description -  If you want to add a cloud-based archive to a primary mailbox that's located on an on-premises Exchange server, you need to configure a hybrid deployment.
