### ISSUE TITLE
Discrepancy in license feature - Litigation Hold

### ISSUE THREAD

**Issue by kumaarrahul** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#770]
Hello Team,

Referring to this article: https://learn.microsoft.com/en-us/microsoft-365/compliance/ediscovery-create-a-litigation-hold?view=o365-worldwide#assign-an-exchange-online-plan-2-license

It states that Office 365 A1 supports Litigation Hold.

_Note:
For Office 365 Education organizations, Litigation hold is supported in Office 365 A1 subscriptions, which include an Exchange Online Plan 2 license with supplemental features. For more information, see the "Exchange Online features" section in the [Office 365 Education service description](https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-education#exchange-online-features)._

However, if we check the Office 365 Education service description: https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-education#exchange-online-features, we see Litigation Hold marked as No for Office 365 A1.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 482f1200-178f-088c-f189-ac129614cdb0
* Version Independent ID: 94ff27f4-966c-f271-1822-515c4e56a1bb
* Content: [Office 365 Education - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-education#exchange-online-features)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-education.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-education.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by SeanGit88** [comment]
A note from the Exchange team:

A1 *by itself* only includes Exchange Online P1, which does not include Litigation Hold capability.

Litigation hold is supported in Office 365 A1 subscriptions, which include an Exchange Online Plan 2 license with supplemental features.
