### ISSUE TITLE
Dictation feaure

### ISSUE THREAD

**Issue by takeakitake** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#771]
Please add dictation feature to the list.
We can use dictation feature on Word for the web using free MS account for consumers.

https://www.microsoft.com/en-us/microsoft-365/word?rtc=1&activetab=tabs:faqheaderregion3
"Dictation and voice commands"

Therefore, dictation feature should be able to use on Word for the web using any Microsoft 365 plans which support Word for the web.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 03c6bd97-32d7-11be-e5ff-52b37aaa638c
* Version Independent ID: 8c688d43-0be9-7e68-4d08-cbb8fa5fba11
* Content: [Word for the web - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/office-online-service-description/word-online)
* Content Source: [Office365-ServiceDescriptions/office-online-service-description/word-online.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-online-service-description/word-online.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by SeanGit88** [comment]
Hello, The product team has elected not to add this to the above referenced service description page. (https://learn.microsoft.com/en-us/office365/servicedescriptions/office-online-service-description/word-online)
