### ISSUE TITLE
Office applications

### ISSUE THREAD

**Issue by si-chan** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#772]
Office applications is mentioned in the table, however this isn't a Product listed in the Microsoft Product Terms.
Should this be listed as Microsoft 365 Apps for Enterprise (or Apps for Business) instead?

The issue here is being able to tie up the Installation and Use Rights for M365 Apps to the Service Description.
The Product Terms document for M365 E3 references this page (indirectly), but this page does not then provide any detail as to whether use rights such as Shared Computer Activation are included.
See: https://learn.microsoft.com/en-us/deployoffice/overview-shared-computer-activation
The link above references something called "Microsoft 365 Apps", rather than "Office Applications".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a3fea44b-ae19-6168-157e-56e36c76b467
* Version Independent ID: 74e1c2f3-c8f7-16cf-0fd2-7d6007b12abb
* Content: [Microsoft 365 and Office 365 plan options - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-plan-options)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-plan-options.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-plan-options.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by si-chan** [comment]
The "Microsoft 365 Enterprise full subscription comparison table" referenced here also mentions Shared Computer Activation for M365 Apps (which also implies that M365 E3 includes M365 Apps: https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-service-descriptions-technet-library

The Shared Computer Activation page also says that "Any plan that includes Microsoft 365 Apps for enterprise. For example, Office 365 E3 or Microsoft 365 E5".

Would be good if the Service Description could also mentioned "Microsoft 365 Apps for enterprise" / "Microsoft 365 Apps for business" as well

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will update the article as necessary based on their response.
