### ISSUE TITLE
What about Shared Mailbox ?

### ISSUE THREAD

**Issue by marcosmcampos** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#774]
I believe this page should include clarification regarding licensing on Defender for Office 365 P2 (MDO P2) tenants.

First, when is a tenant MDO P2?
Second, if the tenant is MDO P2, this page mentions that all shared mailboxes need to be licensed for MDO P2. I believe there should also be a "disclaimer" regarding the MDO P2 license pre-requisite on Exchange Online P1/P2 license, as one should not be able to license a mailbox with MDO P2 without first an Exchange Online P1/P2. Is this assumption correct?
Third, is there any option whatsoever to license only specific shared mailboxes with MDO P2 (and EXO P1/P2 is previous comment is correct)? I ask this as there is a precedent for this on Defender for Identity and Defender for Cloud Apps, where these products, upon activated on the tenant, provide protection for all users but efforts should be taken to scope the deployment and inherent protection only for licensed users.

I believe this clarification on this page would provide a clear understanding for how organization can be compliant on shared mailboxes and what flexibility they have upon choosing how many shared mailboxes - if not all of them - they would like to protect.

Thanks,
MC

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 502796e9-ca73-7123-7719-c7b5b1042b7b
* Version Independent ID: 2929af88-6d56-4de3-2b4e-4e1d0e4d97ef
* Content: [Microsoft Defender for Office 365 service description - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description#licensing-terms)
* Content Source: [Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by marcosmcampos** [comment]
@SeanGit88 is there an update?

**Comment by SeanGit88** [comment]
from the team:  "There is no technical limitation requiring an EXO license on a mailbox in order to enable MDO.  MDO enablement is policy driven, not license driven so a customer can scope an entire domain to MDO.  The mailbox could be EXO, shared, on-prem, even Gmail or some other 3rd party."
