### ISSUE TITLE
Reuse Slide in PPT is not available for GCC Low

### ISSUE THREAD

**Issue by YogeshBarania** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#778]
[Enter feedback here] In the table, for PowerPoint, Reuse slide is not available for GCC low and table is showing Yes for that. Please edit that as No because this feature is not available for GGC customers at all. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a3813c1d-357d-dcc2-e3ba-375c794dfea9
* Version Independent ID: a3813c1d-357d-dcc2-e3ba-375c794dfea9
* Content: [Office application and feature availability in Government plans - Service Descriptions](https://learn.microsoft.com/en-us/office365/ServiceDescriptions/office-applications-service-description/office-application-and-feature-availability-in-government-plans)
* Content Source: [Office365-ServiceDescriptions/office-applications-service-description/office-application-and-feature-availability-in-government-plans.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-applications-service-description/office-application-and-feature-availability-in-government-plans.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by SeanGit88** [comment]
Hello, this has been updated. thanks for your feedback.

**Comment by YogeshBarania** [comment]
Thank you. Closing the issue now.
