### ISSUE TITLE
Limit for journaling rule

### ISSUE THREAD

**Issue by joker226** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#78]
The limit for Journaling rule is 10.

We have more than 10 journaling rules in our tenant (currently 13), so what's the real limit ? what should happen when the limit is reached ? (nothing, in our case) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by markjjo** [comment]
@joker226 The current limit is now 50 journaling rules; the service description has been updated accordingly. https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#journal-transport-and-inbox-rule-limits

**Comment by prabita** [comment]
@joker226 Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response
