### ISSUE TITLE
Standalone no longer supported

### ISSUE THREAD

**Issue by bobbyaterry** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#781]
Under the available plans heading it says this.

"Microsoft Azure Information Protection can be purchased either as a standalone or through one of the following Microsoft licensing suites"

AIP can no longer be purchased as a standalone product.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 235aff98-76e3-1544-7224-4b6624a1de54
* Version Independent ID: 235aff98-76e3-1544-7224-4b6624a1de54
* Content: [Azure Information Protection service description - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/azure-information-protection)
* Content Source: [Office365-ServiceDescriptions/azure-information-protection.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/azure-information-protection.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by SeanGit88** [comment]
Hello, Thanks for your comment.  This has been updated. Thanks again for your feedback!
