### ISSUE TITLE
How many licenses are needed for  "Defender for Identity"

### ISSUE THREAD

**Issue by CoMMyCZ** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#782]
Hi, a question from site> https://learn.microsoft.com/en-us/defender-for-identity/technical-faq
"Does Defender for Identity need only a single license or does it require a license for every user I want to protect?
For information about Defender for Identity licensing requirements, see Defender for Identity licensing guidance."
links to this page.

However, **here is NOT the answer**. Can you please phrase the answer here exactly and straightforward?
Example - you need to license only personal (Administrators) working with the Defender for Identity. Or you need to license all the users including guest users that are in your AzureAD. Or something specific.

Thank you
Libor

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#microsoft-defender-for-identity)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by SeanGit88** [comment]
Hello, this has been updated. Thanks for your feedback!
