### ISSUE TITLE
discripency in maximum size of a transport rule 

### ISSUE THREAD

**Issue by sunilkms** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#783]
[on the page details for the following field has descripency.
Maximum size of an individual transport rule = 8 KB 
Character limit for all regular expressions used in all transport rules = 20 KB (this seems incorrect)
i found the following from my test max size of a TR can be 20 KB, and character limit for regular expressions used in a transport rules could be 8 KB, please validate and fix.
]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits?redirectedfrom=MSDN#journal-transport-and-inbox-rule-limits-across-standalone-options)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by SeanGit88** [comment]
From the product team:  "Our Article is correct.  When we check the character limit, we do not check individual rules, it’s a limit for all rules together and it’s 20KB."
