### ISSUE TITLE
Please update the table to include Viva Engage and Viva Suite

### ISSUE THREAD

**Issue by soyalejolopez** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#786]
Viva Engage is missing from the table. Also, it would be helpful to see Viva Suite at the top as a SKU and corresponding Viva Apps/features included with Viva Suite. Perhaps even add Dynamics license which includes Viva Sales.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d53db8b-8a48-4608-5613-e94e81d61281
* Version Independent ID: 6241e635-edac-9e14-c4b8-47e3db93a124
* Content: [Microsoft Viva service description - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-viva-service-description)
* Content Source: [Office365-ServiceDescriptions/microsoft-viva-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-viva-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by SeanGit88** [comment]
Thanks for your comment. This work is currently in progress.   I will post again when updates are live.

**Comment by SeanGit88** [comment]
Hello, this has been updated. thanks for your feedback.

**Comment by soyalejolopez** [comment]
perfect, thanks @SeanGit88 !
