### ISSUE TITLE
Seeking Clarification: Viva Topics for GCC

### ISSUE THREAD

**Issue by sparkitect** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#787]
Document states:
(US Gov GCC, GCC-High, and DoD are not in scope at this time).

Is this still true?

According to [the Roadmap](https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=GCC&searchterms=72185) it is out since April 2022 but we have not been able to start a trial or actually purchase Viva Topics in any of our customer's GCC tenants.

SO: Is Viva Topics available for GCC and if so, how does one actually go about acquiring it?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d53db8b-8a48-4608-5613-e94e81d61281
* Version Independent ID: 6241e635-edac-9e14-c4b8-47e3db93a124
* Content: [Microsoft Viva service description - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-viva-service-description)
* Content Source: [Office365-ServiceDescriptions/microsoft-viva-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-viva-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by SeanGit88** [comment]
Hello, this has been updated. thanks for your feedback.
