### ISSUE TITLE
Topic availability in GCC

### ISSUE THREAD

**Issue by pratikbhusal18** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#788]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

[Enter feedback here]
VIVA Topics is available in GCC. I am a FastTrack Engineer at Microsoft and one of my customer is a GCC customer who was confused to see this. 
Viva Topics is now generally available as an add-on to Microsoft 365 Commercial and Education plans. Users must be licensed with Microsoft 365 F1/F3/E3/A3/E5/A5/Business Basic/Business Standard/Business Premium, Office 365 F3/E1/A1/E3/A3/E5/A5, or a standalone SharePoint plan (**US Gov GCC,** GCC-High, and DoD are not in scope at this time). 
https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-viva-service-description

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d53db8b-8a48-4608-5613-e94e81d61281
* Version Independent ID: 6241e635-edac-9e14-c4b8-47e3db93a124
* Content: [Microsoft Viva service description - Service Descriptions](https://review.learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-viva-service-description)
* Content Source: [Office365-ServiceDescriptions/microsoft-viva-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/main/Office365-ServiceDescriptions/microsoft-viva-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by SeanGit88** [comment]
Hello, this has been updated. thanks for your feedback.
