### ISSUE TITLE
Update/rephrase: Meeting labels licensing

### ISSUE THREAD

**Issue by ChristianJBergstrom** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#789]
[Sections 1 & 2 to be more specific. I.e. E5 needed for Outlook meetings and E5 and Teams Premium needed for Teams meetings.

1) ”For manual sensitivity labeling for scheduled meetings, the following licenses provide user rights:
Microsoft 365 E5/A5/G5
Office 365 E5/A5

2) ”In addition to manual sensitivity labeling for Teams online meetings, the following additional licenses provide user rights:
Teams Premium”

Best,

/Christian ]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#which-licenses-provide-the-rights-for-a-user-to-benefit-from-the-service-22)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by ChristianJBergstrom** [comment]
Great! Will be well received as I get a lot of questions like ”they (MSFT) first told us it would be enabled for all” and ”I’ve heard it’s coming as default for Outlook only if not using Teams Premium”.

Would you mind updating here when the product team get back to you? Thanks!

**Comment by ChristianJBergstrom** [comment]
@SeanGit88 Update. Just read this in Message center so things are more clear now!

Sensitivity labeling will soon be available for meetings in Outlook.

This message is associated with Microsoft 365 Roadmap ID [98924](https://www.microsoft.com/microsoft-365/roadmap?filters=&searchterms=98924)

When this will happen:

We will begin rolling out in mid-February and expect rollout to be complete by late March. Timeline as below:

Feb-23: Outlook Web
Mar-23 : Outlook Mac
Mar-23: Outlook Win32
How this will affect your organization:

Pre-requisite - E5 subscription
