### ISSUE TITLE
Pro & Premium short list of differences

### ISSUE THREAD

**Issue by Normanof** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#79]
Very good article.

If I get it right, the only thing a Pro licence will not do as opposed to a premium is: 1- manage resource engagements, 2-all features of Project Portfolio management, 3-edit-create new ressources from PWA or MS Project for the matter and 4-see project assignments from PWA-resource center. But be able to modify a resource profile from manage users-server setting. 

Would a user having the proper privileges with an essential licence be able to access ODATA from Excel?

Thanks,

Normand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69451b60-fdc1-4b81-d154-cdd38931a902
* Version Independent ID: f90ef8b6-b8ed-37d8-d5c6-da25f96a0a1d
* Content: [Project Online Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/project-online-service-description/project-online-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/project-online-service-description/project-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/project-online-service-description/project-online-service-description.md)
* Product: **office-online-server**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@Normanof - Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response.

**Comment by SharS** [comment]
@Normanof  Thank you for your question. A user who has a Project Online Essentials license does not have access to OData.
