### ISSUE TITLE
Clarify Multi-Geo capabilities

### ISSUE THREAD

**Issue by andypituch** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#790]
Can this statement (from the page) be clarified:

>  "Multi-geo is not available for all government cloud customers."
 
... Is multi-geo supported in ANY Government Cloud? If so, which ones? I assumed that it's not since up above it states that "Your organization’s customer content is stored within the United States." but the quote above seems to imply that there is some exception.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5408a406-02e7-bf26-e330-be25ea409aa6
* Version Independent ID: 3ed59637-9e20-85a7-83e1-e70cd61f635e
* Content: [SharePoint for US government environments - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/sharepoint)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/sharepoint.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/sharepoint.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by SeanGit88** [comment]
Hello, this has been updated. thanks for your feedback.

**Comment by andypituch** [comment]
> Hello, this has been updated. thanks for your feedback.

Awesome! Thank you!
