### ISSUE TITLE
Licensing clarification is needed

### ISSUE THREAD

**Issue by pagejustin** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#794]
Is P1, P2 synonymous with Plan 1, Plan 2?
Does E3 licensing include components of P1? Many Microsoft pages suggests it might.
Where on the spectrum of licensing does Microsoft 365 Business Premium with Plan 1 land compared to E3 licensing?

**Comment by SeanGit88** [comment]
Hello, Please provide a link to which service description this is referring to.  thank you

**Comment by pagejustin** [comment]
For question 1: https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/microsoft-defender-for-office-365-product-overview?view=o365-worldwide#microsoft-defender-for-office-365-plan-1-vs-plan-2-cheat-sheet

For questions 2 and 3, it's hard to pinpoint an exact page.

**Comment by SeanGit88** [comment]
thank you.  #1 is a docs article and another team handles revisions for these.   My team handles updates to service description pages and without a link, it will be difficult to pinpoint what we need to address to make it clearer.
