### ISSUE TITLE
Missing licensing details for sensitivity label in a meeting

### ISSUE THREAD

**Issue by dipinn26592** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#796]
For manual sensitivity labeling for scheduled meetings, the following licenses provide user rights:

Microsoft 365 E5/A5/G5
Office 365 E5/A5

apart from the above called out in the document customer can have add on with E3 through which customer could be using sensitivity label. on top of which customer can get T-Pre license and take benefits of sensitivity label in a teams meetings

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#microsoft-purview-information-protection-sensitivity-labeling)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by SeanGit88** [comment]
Question:   E3 is called out - does this not include your scenario?

"For manual sensitivity labeling, the following licenses provide user rights:

Microsoft 365 E5/A5/G5/E3/A3/G3/F1/F3/Business Premium
Enterprise Mobility + Security E3/E5
Office 365 E5/A5/E3/A3"

**Comment by dipinn26592** [comment]
The query is specifically for the scheduling meeting part we do not call out E3 here

" For manual sensitivity labeling for scheduled meetings, the following licenses provide user rights:
Microsoft 365 E5/A5/G5
Office 365 E5/A5
apart from the above called out in the document customer can have add on with E3 through which customer could be using sensitivity label. on top of which customer can get T-Pre license and take benefits of sensitivity label in a teams meetings "

so if a customer is looking to enable sensitivity label for meeting they would end think they needs to have an E5 ( even if they have E3 + add-on )

Regards,
Dipin Nair

**Comment by SeanGit88** [comment]
Thank you - I see the issue now.

**Comment by SeanGit88** [comment]
Hello, this has been updated. thanks for your feedback.
