### ISSUE TITLE
Supported browsers for Outlook on the web for business. Page not found

### ISSUE THREAD

**Issue by HBrowne** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#80]
The link for "Supported browsers for Outlook on the web for business." cannot be found.

https://go.microsoft.com/fwlink/p/?LinkId=287032

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4c17dfb-bbbc-51c8-d47e-08a7ab71ccd8
* Version Independent ID: e14e441b-bbab-55e4-dcb2-ccdcdfc48582
* Content: [Clients and Mobile Devices](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/clients-and-mobile-devices#feedback)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/clients-and-mobile-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/clients-and-mobile-devices.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
Hi, 
Thank you for your feedback. The issue is fixed.
