### ISSUE TITLE
Wrong French Translation with "except email open rates"

### ISSUE THREAD

**Issue by chrisbesgh** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#802]
In French : "except email open rates" is wrongly translated in "à l’exception des tarifs d’ouverture des e-mails" instead of "à l'exception du taux d'ouverture de mails"
The current translation is "except email open pricing"?!
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d53db8b-8a48-4608-5613-e94e81d61281
* Version Independent ID: 6241e635-edac-9e14-c4b8-47e3db93a124
* Content: [Microsoft Viva service description - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-viva-service-description#learn-more)
* Content Source: [Office365-ServiceDescriptions/microsoft-viva-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-viva-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will update the article as necessary based on their response.
