### ISSUE TITLE
GCCHigh tenant can share with tenant outside GCChigh. Detailed steps are in the article I wrote

### ISSUE THREAD

**Issue by Inderjeetsinghjaggi** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#803]
[Enter feedback here]

GCCHigh tenant can share with tenant outside GCChigh. Detailed steps are in the article I wrote

https://social.technet.microsoft.com/wiki/contents/articles/54697.onboard-external-gcchigh-or-commercial-user-to-commercial-ad-tenant.aspx

So this line is incorrect
'Users in GCC-High are currently unable to share with users in Non-GCC High organizations'

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c907526-4061-94b4-f2fd-d6fca90344bb
* Version Independent ID: 82e89c18-8d6e-bbb1-f6d0-6ec091d1556e
* Content: [Office 365 GCC High and DoD - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-us-government/gcc-high-and-dod.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by Inderjeetsinghjaggi** [comment]
Still waiting to hear on this.

**Comment by Inderjeetsinghjaggi** [comment]
> Thanks for your comment. I've forwarded your query to the product team and will update the article as necessary based on their response.

@SeanGit88 Did someone from product team looked into this?

**Comment by SeanGit88** [comment]
Hi, sorry for the delay, it sometimes takes a little while for the product team to review and get back to me.

**Comment by SeanGit88** [comment]
Hello, this has been updated. thanks for your feedback.

**Comment by Inderjeetsinghjaggi** [comment]
@SeanGit88, would may name be added to the Contributor list because its currently not there.?
