### ISSUE TITLE
Is include in plan but not listed?

### ISSUE THREAD

**Issue by xhoy** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#804]
Hello!

In the section:  [exchange-online-archiving-plans](exchange-online-archiving-plans) It states that: "Cloud-based archive and in-place hold as an add-on for the following plans:"

It then lists: "Note that the following plans already include archiving and don't require Exchange Online Archiving as an add-on:"

The first list has then entry: "Microsoft 365 Business Premium (Exchange Online Archiving is included in plan) "

If this includes the online archiving plan, it should be listed in the second list "plans that already include online archiving"

Thanks for the great docs!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5c55dc71-81ed-864b-ac3f-63ce84688070
* Version Independent ID: 578c9a02-045e-4bf9-6384-d70560c332f0
* Content: [Exchange Online Archiving service description - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description)
* Content Source: [Office365-ServiceDescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will update the article as necessary based on their response.
