### ISSUE TITLE
Update to section Microsoft Purview Information Protection: Sensitivity labeling for authentication contexts

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#806]
Can you update the section Microsoft Purview Information Protection: Sensitivity labelling to include licencing information for using for authentication context with sensitivity labels.

With the container sensitivity labels for groups, teams and sites you can use authentication context to can enforce more stringent access conditions when users access SharePoint sites by connecting conditional access policies to a sensitivity label.

This functionality is now included in the new add on licence for Microsoft Syntex - SharePoint Advanced Management licence. See refrence link https://learn.microsoft.com/en-us/sharepoint/advanced-management

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by SeanGit88** [comment]
Hello, this has been updated. Thanks for your feedback!
