### ISSUE TITLE
Webinar availability for A1 licenses

### ISSUE THREAD

**Issue by thewrabbit** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#809]
Previously webinars were not available to A1 licenses.  The documentation currently makes no mention of this restriction.

https://learn.microsoft.com/en-gb/microsoftteams/set-up-webinars - mentions that some features are Teams Premium only

Refers you to Read more about the new features available for your end users in [Get started with Teams webinars](https://support.microsoft.com/office/42f3f874-22dc-4289-b53f-bbc1a69013e3)

Again no mention in this article regarding any licensing restriction.

> Who can schedule a webinar
> By default, anyone who can schedule a Teams meeting can schedule a webinar. If you’re unable to schedule one, check with your IT admin.

The first article also links to 

For more information about the differences between meetings, webinars, and live events, see [Meetings, webinars, and live events](https://learn.microsoft.com/en-gb/microsoftteams/quick-start-meetings-live-events).  This page says:

> License requirements for meetings, webinars, and live events
> Anyone can attend a Teams meeting, webinar, or Public Live Event for free—no license is required.
> 
> For the people who organize, schedule, and host meetings, webinars, or live events, they'll need one of the Microsoft 365 licenses listed in the [Microsoft Teams service description](https://learn.microsoft.com/en-us/office365/servicedescriptions/teams-service-description). If you're already using Teams, you probably have the license you need for organizing and hosting meetings, webinars, and live events.

Again no mention of not being available to A1.

The service description page - which this issue is raised under shows the following table
![image](https://user-images.githubusercontent.com/55286035/229443737-b6e18e0e-d9fa-498a-8f05-c9dc7b75d3b7.png)

It states Education Yes for Webinars - previously A1 licenses did not have webinars.  Can this be clarified as no announcement has been made that the previous position has changed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9035b5a9-1f84-54be-89ae-c3a0e53891f8
* Version Independent ID: cff57f08-ca51-2266-6189-1ce8181b942e
* Content: [Microsoft Teams service description - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/teams-service-description)
* Content Source: [Office365-ServiceDescriptions/teams-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/teams-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by thewrabbit** [comment]
@SeanGit88 - I'm sorry I don't see any relevant updates to the licensing information.  The only mention on the service description page is that for A1 Webinars are limited to 300 participants.  That's the limit that applies to Team Meetings.  Webinars are not available at A1 as far as I'm aware.  Can you please re-open.
