### ISSUE TITLE
Autosave feature in Table for Word Online looks inaccurate

### ISSUE THREAD

**Issue by kdcroteau** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#81]
In the Table, Autosave is list as a feature that is NOT available for Word Online (value of No). Yet when you click on the hyperlink for more detail, the documentation then states Autosave IS available for Word Online.  Very confusing and one is inaccurate (believe it to be the table).  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cdf2ace-b564-bb26-303e-4374041610a7
* Version Independent ID: 4ea274ad-8b4f-9f37-e935-49ee485a1a7e
* Content: [Office Online Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-online-service-description/office-online-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/office-online-service-description/office-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-online-service-description/office-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@kdcroteau - Thank you for your feedback. Table is updated and the new page will be live in 24 hrs.
