### ISSUE TITLE
Automatic labeling licensing

### ISSUE THREAD

**Issue by JMCA2** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#812]
According to https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance automatic labeling is not allowed in Office 365 E3 nor M365 Business Premium.

However, I have tried with an O365 E3 tenant as well as a M365 BP tenant and automatic labeling options are working.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by SeanGit88** [comment]
The product team has responded and suggested that support should be contacted about this if it's causing a problem.   https://learn.microsoft.com/en-us/microsoft-365/admin/get-help-support?view=o365-worldwide 

"This is unexpected. The documentation is correct and matches the code. Office does not activate client-side auto/recommended labeling unless there is one or more signed in user who has one of the documented licenses assigned. If there are multiple accounts signed in, e.g. one with M365 Business Premium and another with M365 E5 or AIP Premium P2, then the feature will be enabled (even if the M365 Business Premium tenant is the one with auto-labeling policy defined). "
