### ISSUE TITLE
When is the Graph API available for the Teams in 21V data center?

### ISSUE THREAD

**Issue by longnlp** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#813]
When is the Graph API available for the Teams in 21V data center? Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7cf1b9f8-9adc-c524-4421-39d791e45a92
* Version Independent ID: 7cf1b9f8-9adc-c524-4421-39d791e45a92
* Content: [Teams operated by 21Vianet - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/teams-operated-by-21vianet)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/teams-operated-by-21vianet.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/teams-operated-by-21vianet.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by SeanGit88** [comment]
Hello,  You've reached the service description team, so I don't have any information about this.

**Comment by SeanGit88** [comment]
Please feel free to log a support ticket to 21Vianet and seek clarification on this.
