### ISSUE TITLE
Purview Records Management included in Business Premium?

### ISSUE THREAD

**Issue by JMCA2** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#814]
According to this docs page "Microsoft Purview Records Management" use rights are included in M365 Business Premium.
However, when a Global Admin with this licenses visits https://compliance.microsoft.com/recordsmanagement it says another license is required and access is blocked.

There is no issue when accessing "Microsoft Purview Data Lifecycle Management" at https://compliance.microsoft.com/informationgovernance

Are the docs correct regarding this?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by JMCA2** [comment]
@alejaraz

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by SeanGit88** [comment]
From product team: business premium is licenses for retention policies & basic retention labels which lives under Data Lifecycle Management, no Records Management features are available for anything lower than E5.

**Comment by JMCA2** [comment]
@SeanGit88 Thanks for clarifying. I must say the docs page is confusing and maybe should be clarified since both "Microsoft Purview Data Lifecycle Management & Microsoft Purview Records Management" are on the same section and Business Premium is included in such, and doesn't say anything regarding Records Management requiring licensing different than retention labels
