### ISSUE TITLE
Lack of documentation around Default Column Values

### ISSUE THREAD

**Issue by Linden-Daniels** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#815]
The SharePoint Online support documentation does not provide any guidance for Default Column Values. The last time Microsoft provided that guidance is 10 years ago: https://learn.microsoft.com/en-us/SharePoint/install/software-boundaries-and-limits#managed-metadata-limits.

Whilst testing this in SPO, we found that we could create around 2000 default column values in one library. (We can test more, but this was roughly what the customer needed, so we didnt test more). We did note that dragging and dropping files was fine, but viewing the default column values setting page was very slow to load. The file size limit for client_LocationBasedDefaults.html of 256 Mb seems incorrect and we suspect that it is meant to be 256 KB, which was only a little larger than what we ended up with.

Please add some updated guidelines on default column values.

Regards
Linden Daniels

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint limits - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits?source=docs)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by SeanGit88** [comment]
Hello, this has been updated. Thanks for your feedback!
