### ISSUE TITLE
List and Libraries limit needs correction

### ISSUE THREAD

**Issue by himani-chi** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#816]
[List and Libraries limit is not 2000 per site collection. It is 2000 per site in a site collection. Root site can have maximum 2000 list and libraries. Each subsite can further have max 2000 lists and libraries.]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint limits - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits#lists-and-libraries)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by USCloud-EricWilborn** [comment]
Was there any determination on this update?

**Comment by SeanGit88** [comment]
Thanks for the reminder.   This is the statement I got back:  The public contract is 2000 lists/libraries per site collection and that is what we support; while the enforcement(hard block) was introduced later after the public contract and was done per subsite level to help reduce impact on existing solutions and give customers time to abide by the limit. In addition, the subsite depreciation also makes these two limits the same eventually.

**Comment by USCloud-EricWilborn** [comment]
Thank you!
