### ISSUE TITLE
Microsoft 365

### ISSUE THREAD

**Issue by JamieWilsonOurIT** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#82]
Although Microsoft 365 Business is referenced within this document this page, Microsoft 365 E3 is not. It is not clear if ATP is included in Microsoft 365 E3

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 502796e9-ca73-7123-7719-c7b5b1042b7b
* Version Independent ID: 2929af88-6d56-4de3-2b4e-4e1d0e4d97ef
* Content: [Office 365 Advanced Threat Protection Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-advanced-threat-protection-service-description)
* Content Source: [Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-advanced-threat-protection-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SKjerland** [comment]
@JamieWilsonOurIT - ATP is not included in Microsoft 365 E3, although anti-spam and anti-malware protection features are included. ATP Plan 1 and Plan 2 are included in Microsoft 365 Enterprise E5, and either can be purchases as an add-on to Microsoft 365 Enterprise E3.

**Comment by xhoy** [comment]
If they are included in Microsoft 365 E5 shouldn't it be listed in the docs? Since its still not there?
