### ISSUE TITLE
Need to add Connection Limits

### ISSUE THREAD

**Issue by greatquux** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#820]
This page doesn't include the limits on concurrent connections to mailboxes in EXO.  It really should, and it needs to consider all the cases really.  Is it a UserMailbox or Shared?  If Shared, is it being connected via AutoMapping, or is the user adding it as a secondary account in Outlook (and then using their own credentials to login)? (Adding a secondary account in Outlook is necessary to get around many limitations in searching shared mailboxes, among other issues.)  Is user connecting with Outlook or OWA?  We really need to know what these limits are!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by SeanGit88** [comment]
The response: "We do not have “limits” for shared / delegated mailboxes because limits will vary greatly on size, number of items, network speeds etc. "

**Comment by SeanGit88** [comment]
The product team sent me this link:  https://support.microsoft.com/en-us/office/best-practices-for-organizations-when-using-the-outlook-calendar-d93f72d3-2361-4e0d-8d6a-5c4939c17f39?ui=en-us&rs=en-us&ad=us  section: "Limit the number of delegates"

**Comment by greatquux** [comment]
ok.. nothing in there talks about the connection limits for a user mailbox, it's just talking about shared/delegate scenarios again.  what are in the limits in EXO for connections to one shared mailbox?  I imagine each connection from Outlook desktop, OWA, and mobile devices adds some, but there really should be some public documentation on how an admin can compute that.

**Comment by greatquux** [comment]
Still looking for someone to add documentation about how many simultaneous connections to a mailbox (let's just say a regular user mailbox) can exist - for MAPI/HTTP (desktop Outlook), and/or OWA.
