### ISSUE TITLE
Wrong link to Viva Pricing(404)

### ISSUE THREAD

**Issue by SimonPiquer** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#822]
Link to "Viva Pricing" page is wrong (includes "learn." subdomain) and leads to 404 page.

![image](https://user-images.githubusercontent.com/80743138/236447852-5c41dd75-4fb0-4dbf-aaa6-c9b0b10875e6.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7ed5a163-06d2-e82a-356b-fb7e3676ddaf
* Version Independent ID: 7ed5a163-06d2-e82a-356b-fb7e3676ddaf
* Content: [Microsoft Viva Engage service description - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-viva-engage-features)
* Content Source: [Office365-ServiceDescriptions/microsoft-viva-engage-features.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-viva-engage-features.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by SeanGit88** [comment]
Hello, this has been updated. Thanks for your feedback!
