### ISSUE TITLE
Typo in the following table

### ISSUE THREAD

**Issue by limp15000** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#827]
Hi, 

In the following table: 
![image](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions/assets/23700466/a5f3e2fe-db7d-4062-8ffb-92f714e0985f)
M365 apps for the web refers to point 10 instead of 11 
![image](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions/assets/23700466/fd359732-37b8-4776-87d3-c26a00037f95)

Many thanks for fixing,
Thomas

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a3fea44b-ae19-6168-157e-56e36c76b467
* Version Independent ID: 74e1c2f3-c8f7-16cf-0fd2-7d6007b12abb
* Content: [Microsoft 365 and Office 365 plan options - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-plan-options)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-plan-options.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-plan-options.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by SeanGit88** [comment]
Thanks for pointing this out. We will update this.
