### ISSUE TITLE
Update of sending limits to highlight lower limits when using sensitivity labels or email encryption

### ISSUE THREAD

**Issue by jmountforduk** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#829]
Please explain recipient limits when sensitivity labels or email encryption (Do Not Forward or Encrypt-Only) are used as per [this Purview troubleshooting article](https://learn.microsoft.com/en-us/microsoft-365/troubleshoot/sensitivity-labels/encrypted-email-cannot-send-many-recipients), which confirms the upper limit is less than 200.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online limits - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#sending-limits-1)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by SeanGit88** [comment]
Hello, this has been updated. Thanks for your feedback!
