### ISSUE TITLE
Dead URL To which online services does the Trust Center apply?

### ISSUE THREAD

**Issue by fkaleck** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#83]
The link to "To which online services does the Trust Center apply?" does not work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3f9b0e1-31b0-1497-10fe-cc8284b42d22
* Version Independent ID: 8d5fa25c-b311-b072-8207-532ccc9109af
* Content: [Privacy, Security, and Transparency](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/privacy-security-and-transparency)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/privacy-security-and-transparency.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/privacy-security-and-transparency.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@fkaleck Thank you for your feedback, issue is fixed and will be lie in 24 hrs.
