### ISSUE TITLE
300 user limit is per offer, not "collectively"

### ISSUE THREAD

**Issue by MurphyAWM** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#830]
The document states: "However, existing limitations on the number of seats per plan don't change. For example, you can have up to 300 seats collectively for Microsoft 365 Business Basic, Microsoft 365 Business Standard, and/or Microsoft 365 Business Premium"

The 300 user limit for SMB offers is _enforced per SKU_, not per tenant. The word collectively should be changed to each.

We have repeatedly confirmed with Microsoft that one tenant can have 300 users of Business Premium and also have another 100 users of Business Standard. Up to 300 users "collectively" is not accurate.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a3fea44b-ae19-6168-157e-56e36c76b467
* Version Independent ID: 74e1c2f3-c8f7-16cf-0fd2-7d6007b12abb
* Content: [Microsoft 365 and Office 365 plan options - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-plan-options?source=recommendations)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-plan-options.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-plan-options.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **office365servicedesc**

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by SeanGit88** [comment]
Response:  M365 Business SKUs are intended for businesses with up to 300 employees. The submitter is correct that it is technically enforced at the individual plan level, however technical enforcement does not equate to licensing policy. 

thanks again for your feedback.
