### ISSUE TITLE
Separation of the two tables more

### ISSUE THREAD

**Issue by jamesreedMSFT** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#831]
If I knew how to do the markup and do a fork of it I would offer to do so. 
1. Can we increase font size of Office 365 and Microsoft 365 above each table?
2. Can we add more space between the O365 table and the Microsoft 365 heading?
3. Can we also make them bookmarks/or linkable so we can the exact table to customers? As more customers are moving to M365 licenses, we need them to jump over the O365 section completely. It's so much info on the page users don't know where to scroll to. 

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f8328da3-5093-09b6-9b9b-b92d13625219
* Version Independent ID: f2171de5-bfa5-65d1-4615-30db23349b40
* Content: [Microsoft 365 Education - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/microsoft-365-education)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/microsoft-365-education.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **pamelaar**

**Comment by SeanGit88** [comment]
Hi James, Thanks for your comment. You've followed one of the correct processes for submitting requests for service description updates.  I will research this and see what can be done here.

**Comment by SeanGit88** [comment]
Hi James - this has been updated - hope this helps.

**Comment by jamesreedMSFT** [comment]
This looks great, thank you!
