### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by pm0d** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#834]
Line 93 contains a broken link: `Explorer contains views, such as Malware (for email and content), Submissions, Phish, and All Email. To see how Explorer compares with real-time detections, [download this PDF](https://github.com/MicrosoftDocs/microsoft-365-docs/raw/public/microsoft-365/downloads/office-365-atp-plan-comparison-march-2020.pdf).`

Same link is also present in line 101 : `Real-time detections contain views, such as Malware (for email and content), Submissions, and Phish. To see how real-time detections compare with Explorer, [download this PDF](https://github.com/MicrosoftDocs/microsoft-365-docs/raw/public/microsoft-365/downloads/office-365-atp-plan-comparison-march-2020.pdf).`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d4178aae-6e59-80d3-606b-23e53ea7865c
* Version Independent ID: dd502084-a5a7-136c-63ed-2b137f873707
* Content: [Microsoft Defender for Office 365 Features service description - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-defender-for-office-365-features)
* Content Source: [Office365-ServiceDescriptions/microsoft-defender-for-office-365-features.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-defender-for-office-365-features.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **pamelaar**

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will update the article as soon as I receive their response.

**Comment by SeanGit88** [comment]
Hello, this has been updated. Thanks for your feedback!
