### ISSUE TITLE
Defender for Cloud Apps licensing in M365 Business Premium

### ISSUE THREAD

**Issue by JMCA2** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#835]
It's not very clear what entitlements users with M365 Business Premium have regarding Defender for Cloud Apps. This should be clarified. Even Microsoft Support is confused regarding this because of the docs. There's not a single mention of Business Premium on the Defender for Cloud Apps section.

`Azure AD P1/P2 provide the rights for a user to benefit from the Discovery capabilities that are included as part of Defender for Cloud Apps.`
It should be added that Business Premium includes Discovery capabilities.

`To benefit from the Conditional Access App Control capabilities in Defender for Cloud Apps, users must also be licensed for Azure Active Directory P1, which is included in Enterprise Mobility + Security F1/F3/E3/A3/G3, Enterprise Mobility + Security E5, Microsoft 365 E3/A3/G3, Microsoft 365 E5/A5/G5, and Microsoft 365 E5/A5/G5/F5 Security and Microsoft 365 F5 Security & Compliance.`
Many suites including AD P1 are listed here, but not Business Premium. Does Business Premium (since it includes AD P1) also support Conditional Access App Control in Defender for Clouds Apps? I would guess yes but would need confirmation since it's not on the list.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#microsoft-defender-for-cloud-apps)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **pamelaar**

**Comment by JMCA2** [comment]
@SeanGit88 any news regarding this?

Thanks

**Comment by SeanGit88** [comment]
@JMCA2 Thanks for reaching out - I am still working on getting the answer

**Comment by SeanGit88** [comment]
Hi.  Microsoft Defender for Cloud Apps Discovery is part of Premium, but an add-on for Small and Medium Business.   We are in the process of reformatting these pages to make them easier to consume.  thanks.
