### ISSUE TITLE
Incorrect translation in Japanese

### ISSUE THREAD

**Issue by taisino** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#84]
Incorrect translation in Japanese is found in this document.
https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits

<Original>
(en-us)
Unique security scopes per list or library - 5,000. For large lists, design to have as few unique permissions as possible.

(ja-jp)
リストまたはライブラリごとの固有のセキュリティスコープ-5000。 大規模なリストについては、可能な限り固有のアクセス許可を設定**する**ように設計します。

This Japanese script means as below and this is opposite of original.
"Unique security scopes per list or library - 5,000. For large lists, design to have as many unique permissions as possible."

Suggested translation is as below.
リストまたはライブラリごとの固有のセキュリティスコープ-5000。 大規模なリストについては、可能な限り固有のアクセス許可を設定**しない**ように設計します。

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits#feedback)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SKjerland** [comment]
@MollyMalone, @OfficeGSX - Can you please look into this localization issue? Thanks!

**Comment by MollyMalone** [comment]
@OfficeGlobal please look into this.   @SKjerland FYI, we recently changed the account from @OfficeGSX to @OfficeGlobal for handling international issues.

**Comment by SKjerland** [comment]
@MollyMalone - Thanks for letting me know about the changed account. I'll make a note of it .

**Comment by OfficeGlobal** [comment]
@MollyMalone We're working on a fix (Bug 3226092)

**Comment by OfficeGlobal** [comment]
@taisino , @MollyMalone The article has been HumanTranslated and published live
