### ISSUE TITLE
"full subscription comparison table" link leads to a PDF that does not include the Project Plans.

### ISSUE THREAD

**Issue by LH-DD-MS** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#842]
There is a link to a PDF underneath the "feature availability across applications and subscriptions" heading that states it will be the most up to date, complete list of Microsoft Project features across plans. 

![image](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions/assets/139186932/be866937-4d3d-495a-ae63-ebfd143de238)

The PDF does contains a plan comparison for the 365 enterprise plans. It does NOT provide a list of the details available to the Microsoft Project plans.

Attached is the document.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6b614c3a-5070-9595-2cb2-d2ec4fb68cb7
* Version Independent ID: f73e4cf9-fe59-e6f4-7638-2bddf97a069e
* Content: [Microsoft Project service description - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/project-online-service-description/project-online-service-description)
* Content Source: [Office365-ServiceDescriptions/project-online-service-description/project-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/project-online-service-description/project-online-service-description.md)
* Service: **office-online-server**
* GitHub Login: @pamelaar
* Microsoft Alias: **pamelaar**
[ModernWorkPlanComparisonEnterprise (2).pdf](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions/files/12009600/ModernWorkPlanComparisonEnterprise.2.pdf)

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will update the link based on their response.

**Comment by SeanGit88** [comment]
Hello, this has been updated. Thanks for your feedback!
