### ISSUE TITLE
Documentation about Teams Graph API availability in China Office 365(Office 365 operated by 21vianet)

### ISSUE THREAD

**Issue by leapyear1969** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#843]
I test the teams graph API in China Office 365, it looks redenring well. 

But I saw that the document says it is not supported. Is there a problem with the description in the document here?

![image](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions/assets/18607988/25c39a3e-83c3-4170-9341-5f72f38d4165)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7cf1b9f8-9adc-c524-4421-39d791e45a92
* Version Independent ID: 7cf1b9f8-9adc-c524-4421-39d791e45a92
* Content: [Teams operated by 21Vianet - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/teams-operated-by-21vianet)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/teams-operated-by-21vianet.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/teams-operated-by-21vianet.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **pamelaar**

**Comment by SeanGit88** [comment]
Hello, this has been updated. Thanks for your feedback!
