### ISSUE TITLE
Callout for Service Plans in Sensitivity Labeling License Requirements

### ISSUE THREAD

**Issue by MSFT-SeanG** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#844]
Request to document the Service Plans required Sensitivity Labels to function correctly in any given configuration.

The E3/G3/A3 requirements also require that the "Information Protection for Office 365 - Standard" service plan is enabled for the assigned license.

The same requirement is necessary on most Sensitivity Label implementations for E5/G5/A5 - using the "Information Protection for Office 365 - Premium" Service Plan.

If these service plans are not enabled within the license, mileage may vary in terms of customer experience - different workloads taking advantage of Sensitivity Labels may not have the same Service Plan checks in place. It is recommended that we add this callout so that customers can plan to deploy these Service Plans with their licensing.

https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#microsoft-purview-information-protection-sensitivity-labeling

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#information-protection)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **pamelaar**

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by SeanGit88** [comment]
Hi , Service Plan information is available elsewhere, but is not in scope for the Service Description pages.  thanks
