### ISSUE TITLE
Need info on co-authoring

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#846]
Please add a section on limits for co-authoring in SPO. For example, max file size supported, max number of people in a session

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint limits - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **pamelaar**

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by SeanGit88** [comment]
Hi, this feature has been announced, but not yet released.  After the feature is released, this update will be ready to be published in the service description.  thanks.

**Comment by danmyhre** [comment]
Co-authoring has been released for a long time. Just looking for current limits.

**Comment by SeanGit88** [comment]
Is this regarding Office files stored on SPO?

**Comment by danmyhre** [comment]
Correct, co-authoring on Word, Excel, and PowerPoint

**Comment by SeanGit88** [comment]
Ok thank you.  This information could very well be in another service description specific to the application. According to the SPO experts, it won't reside in the SPO article.  I will ask around.

**Comment by danmyhre** [comment]
Okay, sounds good. I haven't been able to locate it anywhere - except dated articles for SP2013. The feature is specifically provided by SharePoint (which includes SPO, ODfB, and Teams - it's all SharePoint), so I would think at least linking to something from the SPO service description is warranted.

**Comment by SeanGit88** [comment]
Agreed that the SPO service description should contain a link to this info.

**Comment by danmyhre** [comment]
@SeanGit88  why wouldn't Microsoft publish this?
