### ISSUE TITLE
Update on what isn't available for Word for web

### ISSUE THREAD

**Issue by TiJohn0108** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#848]
In section "Collaboration, advanced", I believe "Track Changes" needs to be dropped from 
"such as turning on Track Changes and merge, compare, and combine documents, are only available in the Word desktop app."

Based on testing and as noted here https://support.microsoft.com/en-au/office/track-changes-in-word-197ba630-0f5f-4a8e-9a77-3712475e806a#TrackChanges=Web, Track Changes appears to be available. 

Related, I believe the reference to "Track Changes" in this article https://support.microsoft.com/en-us/office/differences-between-using-a-document-in-the-browser-and-in-word-3e863ce3-e82c-4211-8f97-5b33c36c55f8#__toc304841573; also needs to be updated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 03c6bd97-32d7-11be-e5ff-52b37aaa638c
* Version Independent ID: 8c688d43-0be9-7e68-4d08-cbb8fa5fba11
* Content: [Word for the web - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/office-online-service-description/word-online#collaboration-advanced)
* Content Source: [Office365-ServiceDescriptions/office-online-service-description/word-online.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-online-service-description/word-online.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **pamelaar**

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by SeanGit88** [comment]
Hello, this has been updated. Thanks for your feedback!
