### ISSUE TITLE
The Limitation for unique permissions in a list/library.

### ISSUE THREAD

**Issue by kefujino** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#849]
Hi, team

The below article of SharePoint Online Limitations states that unique permissions in a single list/library should be designed to be less than 5,000.
https://learn.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits#unique-security-scopes-per-list-or-library

<img width="381" alt="image" src="https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions/assets/13634805/0b30e685-e023-4683-8d15-5a8e88e87dbf">

Today I noticed that another article stated that the maximum value supported is 50,000, not 5,000.
https://learn.microsoft.com/en-us/sharepoint/troubleshoot/lists-and-libraries/error-share-break-inheritance#cause

<img width="459" alt="image" src="https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions/assets/13634805/0b69b9b3-0258-4aa4-b664-128bf8d9ef66">

After reading the article, I understand that 50,000 is a hard limit and 5,000 is a recommended value. Shouldn't information about 50,000 also be added to the first article as a hard limit? Perhaps 50,000 is not mentioned because it might mislead users to use more than 5,000, but we would appreciate it if you could confirm this.

Thank you!
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint limits - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits#unique-security-scopes-per-list-or-library)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **pamelaar**

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by SeanGit88** [comment]
Hello, this has been updated. Thanks for your feedback!

**Comment by kefujino** [comment]
Thank you for your prompt work!
