### ISSUE TITLE
REST and Hx limits for Outlook Mobile

### ISSUE THREAD

**Issue by mgeshkov** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#85]
I am FastTrack engineer and we are often asked by our customers about Outlook Mobile message limits. Could we please add REST and Hx limits in the article as well.

Thank you.
Miro Geshkov.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79b5d74a-02c9-6dc8-ed59-e703d9384a0d
* Version Independent ID: f6957a00-003e-64d2-a9c6-6ccaa8006a6f
* Content: [Exchange Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#feedback)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@mgeshkov Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response

**Comment by SharS** [comment]
@mgeshkov Added the limits for iOS and Android.
