### ISSUE TITLE
Broken link for more information

### ISSUE THREAD

**Issue by BR77BE** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#851]
"For more information, see the Core features in [Compare OneDrive cloud storage pricing and plans](https://www.microsoft.com/microsoft-365/onedrive/compare-onedrive-plans?activetab=tab:primaryr2)."

Link does not produce more information.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 99ce1810-18cd-687b-0c8b-bfceb919225a
* Version Independent ID: 705cde78-7e58-c260-bde3-0b393747cdea
* Content: [OneDrive service description - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/onedrive-for-business-service-description)
* Content Source: [Office365-ServiceDescriptions/onedrive-for-business-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/onedrive-for-business-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **pamelaar**

**Comment by SeanGit88** [comment]
Thank you for making contact.   I am seeing this link as working and directing to:  https://www.microsoft.com/en-us/microsoft-365/onedrive/compare-onedrive-plans?activetab=tab:primaryr2&rtc=1

**Comment by BR77BE** [comment]
I still get, "An error (500 Internal Server Error) has occurred in response to this request."

**Comment by SeanGit88** [comment]
Ok - thanks.   I will send this over to team which owns this to investigate.

**Comment by SeanGit88** [comment]
Hi, in which region are you located?

**Comment by BR77BE** [comment]
UK-ish (Guernsey).

**Comment by SeanGit88** [comment]
Thank you - can you send me the exact link from the address bar which is giving you the 500 error?

**Comment by BR77BE** [comment]
https://www.microsoft.com/microsoft-365/onedrive/compare-onedrive-plans?activetab=tab:primaryr2

**Comment by BR77BE** [comment]
But when I click that link today I find it's now working for me,

**Comment by SeanGit88** [comment]
Ok - thank you.  Let me know if you run into this issue again.

**Comment by BR77BE** [comment]
It's broken again:

"An error (500 Internal Server Error) has occurred in response to this request."
