### ISSUE TITLE
Sending limits - recipient rate limit clarification

### ISSUE THREAD

**Issue by kamilzzz** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#852]
https://learn.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#sending-limits-1

Is the 10 000 recipient limit counted as 10 000 unique recipients per day or 10 000 mail recipients?

If I send a message to the same recipient twice is it counted as a single recipient or 2 recipients as 2 different messages were sent?

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will update the article as necessary based on their response.

**Comment by SeanGit88** [comment]
It is not counted based on “unique” recipients.

**Comment by kamilzzz** [comment]
Thanks. 
To be sure, if I send a first email to the following recipients: 

- a@contoso.com, 
- b@contoso.com, 
- c@contoso.com, 

and a second one to the following recipients:

- b@contoso.com,
- c@contoso.com,
- d@contoso.com,

I understand it will be counted as 6 recipients against Exchange limits, even though recipients b & c are present in both e-mails (we have total of 4 unique recipients), right?
Not sure this matters but in my case these e-mails are sent within origanization only - they are not going to be send to external mailboxes.
