### ISSUE TITLE
Authentication Context with SharePoint Sites

### ISSUE THREAD

**Issue by AdamWalker119** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#853]
It looks like the licensing for Authentication Context with SharePoint sites. It lists Microsoft 365 E5/A5 Compliance twice.

According to https://learn.microsoft.com/en-us/sharepoint/authentication-context-example one of those should be Microsoft 365 E5/A5 Compliance.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd11b55e-ddc0-d45c-b45e-375106a831ff
* Version Independent ID: 1ded3d2c-4b12-bf80-2b6c-3e6127cd14d6
* Content: [Microsoft 365 guidance for security & compliance - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance)
* Content Source: [Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **pamelaar**

**Comment by SeanGit88** [comment]
Thanks for your comment. I've forwarded your query to the product team and will have the article updated.

**Comment by SeanGit88** [comment]
Hello, this has been updated. Thanks for your feedback!
