### ISSUE TITLE
What is Next and Next+ in the GCC Search 

### ISSUE THREAD

**Issue by DJHMS** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#857]
[Enter feedback here]
In review of https://learn.microsoft.com/en-us/microsoftsearch/microsoft-search-us-government-environments, the is references in the Table to Next and Next+.   I do not see a definition of what this means.  Can you provide clarification on the page.  My thoughts are Next is the Next release/version and Next+ is further down the road. 

my MS email is dehutc@microsoft.com

Thank you for the clarification.
-dennis

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e1e8c08c-5dfe-fef7-6d44-178bd1b32f28
* Version Independent ID: 23a510e2-4548-0722-89ae-ad3eb317139e
* Content: [Microsoft Project for the web service description - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/project-online-service-description/project-web-service-description#project-for-the-web-and-microsoft-dataverse)
* Content Source: [Office365-ServiceDescriptions/project-online-service-description/project-web-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/project-online-service-description/project-web-service-description.md)
* Service: **office-online-server**
* GitHub Login: @pamelaar
* Microsoft Alias: **pamelaar**

**Comment by SeanGit88** [comment]
Thanks for your question.  These terms appear on a site which is outside of my area of ownership.  I encourage you to click the feedback button on the bottom of this page (https://learn.microsoft.com/en-us/microsoftsearch/microsoft-search-us-government-environments) to reach the correct audience.  thank you.
