### ISSUE TITLE
Typo 1

### ISSUE THREAD

**Issue by a-zaf** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#86]
Section "Sign-in options / Custom domains and identity options"

Paragraph "For organizations using single sign-on, [...]"

"You would use add two domains to Office 365, such as contractors.contoso.com and staff.contoso.com"

&gt;&gt; should be "You would add two domains [...]"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b65730b-7010-60f8-0b50-5a6c8a4970bd
* Version Independent ID: e07b0622-0e4f-1883-b045-ca4097b3c333
* Content: [User Account Management](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/user-account-management#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/user-account-management.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/user-account-management.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@a-zaf - Thanks for your feedback! The typo is fixed.
