### ISSUE TITLE
Link points to wrong doc

### ISSUE THREAD

**Issue by ivanchuuuu** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#860]
Under the "Available Plans" subheader, the link "Microsoft 365 business plan comparison" points to a PDF called "Break down silos in child protection..." instead of the appropriate comparison. 

Someone needs to edit the aka.ms target. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9035b5a9-1f84-54be-89ae-c3a0e53891f8
* Version Independent ID: cff57f08-ca51-2266-6189-1ce8181b942e
* Content: [Microsoft Teams service description - Service Descriptions](https://learn.microsoft.com/en-us/office365/servicedescriptions/teams-service-description#available-plans)
* Content Source: [Office365-ServiceDescriptions/teams-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/teams-service-description.md)
* Service: **o365-administration**
* GitHub Login: @pamelaar
* Microsoft Alias: **pamelaar**

**Comment by SeanGit88** [comment]
Thanks for your comment. We will update the article and I will let you know when it's completed.

**Comment by SeanGit88** [comment]
Hello, this has been updated. Thanks for your feedback!
