### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by a-zaf** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#88]
Section "Delegated administration and support for partners"

The reference link, at the end of the section, does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b65730b-7010-60f8-0b50-5a6c8a4970bd
* Version Independent ID: e07b0622-0e4f-1883-b045-ca4097b3c333
* Content: [User Account Management](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/user-account-management#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/user-account-management.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/user-account-management.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
Removed the broken link. Issue is closed
