### ISSUE TITLE
Limits by plan - table storage confusion

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#89]
what's the difference between "Storage" and "Storage for site collections".. it is very confusing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ec5d810-704a-75dd-2766-b630663d3d91
* Version Independent ID: 4d8294d4-fe22-9770-2d3c-555b8dc9e498
* Content: [SharePoint Online Limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits)
* Content Source: [Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/sharepoint-online-service-description/sharepoint-online-limits.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by saulpreciado** [comment]
Storage is the total storage in the organization (including all site collections and groups). Storage for Site Collections is the total storage for a single site collection or group. I hope that helps.

**Comment by juanoc** [comment]
Hi Saul, no, it doesn't help, as it doesn't make any sense that the storage for a single site is 25x bigger than the storage for the organization (including all site collection)...

**Comment by MadushkaDias** [comment]
i can see 25 TB is the limit for site collection can customer buy or increase if they needed ?

**Comment by hkim83** [comment]
I think it means the plans start at 1 TB for storage, but with each additional license the storage increases by 10 GB. However, no matter what storage size for organization the maximum you can get is 25 TB per site collection storage. That’s why it says “up to 25 TB”. So most likely if you have 1 TB in total storage for the organization your site collection(s) will also have to be under that limit in total. Therefore, if you only have 1 TB in storage you can’t have site collection(s) that will go beyond 1 TB allotment. This is how I interrupted the table. Not sure if anyone else agrees. Microsoft should confirm this.

**Comment by kaarins** [comment]
Thanks for raising this issue. I have rephrased the row labels and added a comment, and I hope this helps clear up the confusion!
