### ISSUE TITLE
A3 format is not supported on Word Online

### ISSUE THREAD

**Issue by AlexHill90** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#90]
Hi all, we just noticed that the A3 layout is unsupported on Word Online - it renders correctly on Word Online when in "preview"/review mode only, but when in editing the format doesn't render correctly and 'breaks' the impagination. 

The documentation should be amended on the format that are actually supported on Word Online or not. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03c6bd97-32d7-11be-e5ff-52b37aaa638c
* Version Independent ID: 8c688d43-0be9-7e68-4d08-cbb8fa5fba11
* Content: [Word Online](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-online-service-description/word-online#page-layout-tools)
* Content Source: [Office365-ServiceDescriptions/office-online-service-description/word-online.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-online-service-description/word-online.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@AlexHill90 Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response

**Comment by prabita** [comment]
Fixed by SME and published
