### ISSUE TITLE
Exchange Archive

### ISSUE THREAD

**Issue by Kweku-Nketsiah** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#91]
is there a possibility where you can configure Exchange Archive with SharePoint ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e0ba987-5e52-0e0d-f9f8-d6da3feaa53c
* Version Independent ID: 5763ce54-2c7c-8956-f44e-c946d0c9a5c4
* Content: [Archive Features in Exchange Online Archiving](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-archiving-service-description/archive-features#feedback)
* Content Source: [Office365-ServiceDescriptions/exchange-online-archiving-service-description/archive-features.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-archiving-service-description/archive-features.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@Kweku-Nketsiah Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response

**Comment by SharS** [comment]
The product team reported that support for this capability is highly unlikely. You might contact Support for more information. For Support options, see [Support](https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/support).
