### ISSUE TITLE
Question: Are there any limitations to folders within folders within folders (folderception)?

### ISSUE THREAD

**Issue by AndySanchezVM** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#92]

**Comment by markjjo** [comment]
@AndySanchezVM Yes. See "Maximum folder hierarchy depth"  in https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#mailbox-folder-limits - The maximum is 300.
