### ISSUE TITLE
Document assimilation / Building security and expertise would benefit from revision index

### ISSUE THREAD

**Issue by grateful4grace** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#94]
I work as a security professional, and was assigned to make controls recommendations for Office 365 / Microsoft 365 implementation.  I downloaded the PDF, and was shocked at the size.  As I got used to it, I would do searches online to find details in features (printed PDF sections facilitate highlighting and flags/bookmarks, but online and search engines do a better job finding connected material.)  What I noticed was how recent some of the articles were.  And some more recent than the PDF that had been dynamically created.  So, what I thought of is an alternative index, or even a scoped "what is new since ___" search, or a cookie that might indicate the last visit to the section.  I did get a chance to see how rapidly the PDF was growing, so it will be at least a part time job to keep up with new features, exploring them in depth.    It would also be useful to have a reason for update, e.g. added feature, clarification, typo. Because usually, I would skip typos.    Just a thought.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 482f1200-178f-088c-f189-ac129614cdb0
* Version Independent ID: 94ff27f4-966c-f271-1822-515c4e56a1bb
* Content: [Office 365 Education](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-education#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-education.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-education.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by SKjerland** [comment]
@grateful4grace - Thanks for your feedback! I will pass your suggestion on to the platform team.
