### ISSUE TITLE
Enterprise Service Family Clarification

### ISSUE THREAD

**Issue by dips23** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#95]
Hello,

Thank you for this information, however I find some confusion around "Enterprise Service Family"

As per the below link, "Office 365 ProPlus" comes under enterprise plan, however it's not listed under "Enterprise Family" on this page.

https://products.office.com/en-in/business/compare-more-office-365-for-business-plans

While, Office 365 F1 comes under "Enterprise Plan", but it is not listed under above link - Can you please clarify ?

Thanks and Regards,
Dipti Chhatrapati

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3fea44b-ae19-6168-157e-56e36c76b467
* Version Independent ID: 74e1c2f3-c8f7-16cf-0fd2-7d6007b12abb
* Content: [Office 365 Plan Options](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-plan-options#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-plan-options.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-plan-options.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@dips23 - Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response.
