### ISSUE TITLE
Licensing for retention policy should be amended to recent retention policy changes

### ISSUE THREAD

**Issue by AlexHill90** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#96]
Hi, this documentation doesn't seem to be extremely in-line with the licensing described on the page below (e.g. retention policies and retired features such as preservation, in-place holds, etc.). 

https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54cc9525-7b54-4151-ac74-acae805a8f69
* Version Independent ID: 3bb6ba9b-b853-430f-6e88-13d5a20cdaea
* Content: [Exchange Online Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description)
* Content Source: [Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/exchange-online-service-description/exchange-online-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
Not clear what is the issue.

**Comment by chrisda** [comment]
@AlexHill90, many of the policy and compliance features you mentioned started out as being only available in Exchange Online for email. Then, Office 365 added the requirement for these same features for other workloads (Skype for Business Online, SharePoint Online, OneDrive, etc.); not just Exchange Online. These "unified" security and compliance features are available in the Office 365 Security & Compliance Center, and operate differently that the "legacy" Exchange Online only security/compliance features with the same name (e.g., MRM-based retention policies in Exchange Online are very different than the retention policies that are available in the Security & Compliance Center). 

This a long way of saying: the older, Exchange Online only security and compliance features mentioned in the [Exchange Online Service Description](https://docs.microsoft.com/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description) are accurate for Exchange Online. The "unified" security and compliance features are documented in the [Office 365 Security & Compliance Center](https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center) topic that you referenced.
