### ISSUE TITLE
Bookings and MyAnalytics

### ISSUE THREAD

**Issue by marklitwin** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#97]
Bookings is available to E3 and E5 as an add-on?  My Analytics available to everyone?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8f41cb0-4ad7-f25c-6586-fe89e8fca92d
* Version Independent ID: 9354cc15-1341-a4e1-4844-83a1f26ee149
* Content: [Office 365 Platform Service Description](https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-platform-service-description#feedback)
* Content Source: [Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md](https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions-pr/blob/live/Office365-ServiceDescriptions/office-365-platform-service-description/office-365-platform-service-description.md)
* Service: **o365-administration**
* GitHub Login: @SKjerland
* Microsoft Alias: **sharik**

**Comment by prabita** [comment]
@marklitwin - Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response.

**Comment by SharS** [comment]
@marklitwin MyAnalytics (Full) and Insights by MyAnalytics is included with E5 plans. To get MyAnalytics (Full) with the E3 plan, you need to purchase the MyAnalytics add-on. For more details, see [MyAnalytics plans and environments](https://docs.microsoft.com/workplace-analytics/myanalytics/overview/plans-environments). Bookings is available as a free add-on for Office 365 E3 and E5 subscriptions. See [Get access to Microsoft Bookings](https://support.office.com/en-us/article/Get-access-to-Microsoft-Bookings-5382dc07-aaa5-45c9-8767-502333b214ce), I've updated the service description with this information.
