### ISSUE TITLE
Data Loss Prevention

### ISSUE THREAD

**Issue by maptan** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#98]
Found out there is this SKU for Data Loss Prevention Add-On.

DLP ADDON OFFICE 365 SKU 4833683a-1e4a-4816-80cf-25238184b8c4

Would it add DLP for other plans, and in this case, which plans?

**Comment by prabita** [comment]
@maptan - Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response.

**Comment by SharS** [comment]
@maptan - Thanks for your feedback. Can you let me know which service description topic you're referring to?

**Comment by SharS** [comment]
@maptan The DLP add-on can be added to any SKU that has Exchange or SharePoint/OneDrive. I've updated the Security & Compliance Service Description to include this information.
