### ISSUE TITLE
concurrent editors per document for SharePoint online

### ISSUE THREAD

**Issue by wrkc** [MicrosoftDocs/OfficeDocs-O365ServiceDescriptions#99]
according to MS community [post](https://answers.microsoft.com/en-us/msoffice/forum/msoffice_sharepoint/how-many-users-can-simultaneously-edit-a-single/) SPO uses same restrictions as SharePoint 2016 server. 

Is this a confirmed information?

It should appear in [SPO limits page](https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-limits)

**Comment by prabita** [comment]
@wrkc Thanks for your feedback! I’ve reached out to the product team and will update this article as needed, pending their response

**Comment by SKjerland** [comment]
Our SharePoint writer worked with the product team to rewrite the article so all info is current. Thanks!
